google/syzkaller

syz-manager/example.cfg

Missing comma makes it so that syz-manager does not properly parse the example
config.

add missing comma in example.cfg

---

AUTHORS
CONTRIBUTORS
tools/create-image.sh

I'm using arch linux and the chroot fails for me because I don't have all of the required directories in my path. This is an issue that others might face who happen to have a distribution that doesn't satisfy debian's requirements.
This patch sets a `PATH` referencing all of the required directories inside the `chroot` to avoid the host `PATH` playing any role in what the `chroot` is doing.
Additionally, as part of the change I've switched out `( yes | apt-get install ...)` into `apt-get install --yes` which, unless I've missed something ought to achieve the same thing.

Fix create image PATH

---

sys/sys.txt

IOPRIO_WHO_PGRP, IOPRIO_WHO_USER, and IOPRIO_WHO_PROCESS are defined in linux/ioprio.h, which previously wasn't included. Invocation of `make generate` resulted in the following error, this patch simply adds an include for ioprio.h which fixes this for 4.4 mainline.
```
[~/cloud/code/syzkaller]$ make generate LINUX="$HOME/linux"
go run sysgen/*.go -linux=/home/lorenzo/linux sys/sys.txt sys/socket.txt sys/tty.txt sys/perf.txt \
sys/key.txt sys/bpf.txt sys/fuse.txt sys/dri.txt sys/kdbus.txt sys/sctp.txt \
sys/kvm.txt sys/sndseq.txt sys/sndtimer.txt sys/sndcontrol.txt sys/input.txt \
sys/netlink.txt sys/tun.txt sys/random.txt
failed to run gcc: exit status 1
<stdin>: In function ‘main’:
<stdin>:462:7912: error: ‘IOPRIO_WHO_PGRP’ undeclared (first use in this function)
<stdin>:462:7912: note: …
```

Add missing linux/ioprio.h include.

---

tools/create-image.sh

An error in the multi-line string results in apt-get install not running in create-image.sh, this fixes that.
Mea culpa, I missed this.

tools: fix multi-line string.

---

vm/qemu/qemu.go

This patch sets the ssh loglevel to error to avoid noisy warnings, specifically known host errors like:
`Warning: Permanently added '[localhost]:1569' (ECDSA) to the list of known hosts.`
Previously this appeared at the top of every crash report.

vm/qemu: strip ssh warnings

---

cover/cover.go
syz-manager/cover.go
tools/syz-execprog/execprog.go

When executors send coverage data to the manager, they clamp the addresses
of covered blocks to 32 bits. Manager uses RestorePC() to restore the original
addresses.
Previously, RestorePC() assumed that the upper 4 bytes of a kernel code
address were 0xffffffff, which is not so on Android.
Instead we now parse `readelf -SW vmlinux` output to obtain the upper bytes of
PROGBITS sections VMAs in the case those VMAs are non-zero. We assume that
the upper 4 bytes are the same for every section.

Use readelf to obtain the upper 32 bits of addresses returned by kcov.

---

Makefile
sys/decl.go
sys/kcm.txt
sys/netrom.txt
sys/sctp.txt
sysgen/sysgen.go

Hi Dmitry, this pull request support more network protocols.
The first commit add getsockopt functions for sctp network protocol. Currently setsockopt is implemented for sctp, but getsockopt is not implemented. The commit make fuzzy sctp protocol more complete.
The second commit supports KCM(Kernel Connection Multiplexor)(supported from Linux 4.6) and netrom. Thank you.

support getsockopt for sctp and also support kcm and netrom

---

prog/prio.go
prog/rand.go
sys/decl.go
sysgen/parser.go
sysgen/sysgen.go

This commit support range int. For instance,   a filed x with int8 [3, 6], means that x could be 3, 4, 5. This is useful for some system calls ,which only accepts a range integer.

support range int

---

extract.sh

To generate Android-specific constants run extract.sh with
ANDROID=/path/to/kernel/checkout instead of LINUX=...
Also remove /usr/bin from `make defconfig` invocations to let the user
supply custom CC.

extract.sh: allow generating constants for Android devices.

---

prog/mutation.go
prog/rand.go
sys/README.md
sys/align.go
sys/decl.go
sysgen/sysgen.go

The syntax is:
```
struct {
field array[int8, 10:16]
}
```

Allow range sized arrays

---

prog/analysis.go
prog/encoding.go
prog/mutation.go
prog/mutation_test.go
prog/prog.go
prog/rand.go
prog/size_test.go
prog/validation.go
sys/README.md
sys/decl.go
sys/fuse.txt
sys/kdbus.txt
sys/kvm.txt
sys/sndcontrol.txt
sys/sndseq.txt
sys/sndtimer.txt
sys/sys.txt
sys/test.txt
sysgen/sysgen.go
sysparser/lexer.go

1. Allow `len` type to be used to denote the size of any other field
2. Update all `len` fields correctly after mutation
These changes invalidate the corpus, since its format is changed. The old corpus should be removed.

Refactor & improve len type handling

---

vm/adb/adb.go

Some devices may not boot up fast enough when battery check
is done as it currently is in adb.go. Therefore,
getBatteryLevel() is modified to take in a parameter to determine
the number of times to retry before giving up.
Tested on slower-to-boot devices and resolved the scenario where
"failed to create instance: adb [shell dumpsys battery | grep level:] failed: exit status 1
Can't find service: battery" error occurs.

Added a retry clause when doing battery check in adb.go

---

csource/common.go
csource/csource.go
executor/common.h
executor/executor.cc
extract.sh
host/host.go
ipc/ipc.go
sys/vnet.txt
sysgen/syscallnr.go

Emit traffic through /dev/net/tun via syz_emit_ethernet.
Requires the following patch to collect coverage from tun:
https://gist.github.com/xairy/11d6ad5eeec6ac3cff961215ca274f43

Emit ethernet traffic

---

Makefile

`make all-tools` won't make `syz-repro` because `repro` isn't PHONY rule

Fix make repro failed

---

executor/executor.cc
vm/adb/adb.go

Using `adb shell syz-executor reboot` to reboot devices has stopped
working with the recent Android update, probably due to the intro
of seccomp. I have reverted the device reboot logic to use `adb
shell reboot` although it can be flaky at times so that we can
continue to fuzz on devices, until a more reliable solution can be
sought out.

adb: executor: Revert to adb reboot

---

config/config.go
csource/common.go
executor/common.h
syz-manager/manager.go
tools/syz-repro/repro.go
vm/adb/adb.go
vm/console.go
vm/odroid/odroid.go
vm/vm.go

This commit adds Odroid C2 support to syzkaller.
It's now possible to specify "type": "odroid" in manager config.
Documentation on how to setup fuzzing with Odroid C2 board is here:
https://github.com/google/syzkaller/wiki/Setup:-Odroid-C2
Note, that after this change libusb-1.0-0-dev package should be
installed to build syzkaller.

vm: add Odroid support

---

ifuzz/decode.go

The intel documentation states, in section:
2.3.6 "Instruction Operand Encoding and VEX.vvvv, ModR/M"
The following:
"VEX.m-mmmm is only available on the 3-byte VEX. The 2-byte VEX implies
a leading 0Fh opcode byte."
This lead the decode function to reject the following as an unknown
instruction:
`c5 f9 6e c1 vmovd  %ecx,%xmm0`
With this fix, it correctly decodes it as a 4 byte instruction.

ifuzz: fix 2-byte vex decoding

---

tools/create-image.sh

mkfs.ext4 is in /sbin/ and this directory is not usually in the PATH of a normal user. Therefore we need to perform sudo in order to reach /sbin/mkfs.*

Add sudo for mkfs.ext4

---

sys/socket.txt
sys/socket_inet.txt
sys/socket_inet6.txt

Also split `ioctl$sock_inet_ifreq` into multple ioctls to make it possible to disable or enable particular ones.

sys: make ifindex a resource

---

syz-gce/syz-gce.go

syz-gce/syz-gce.go:470: attrs.MetaGeneration undefined (type *"cloud.google.com/go/storage".ObjectAttrs has no field or method MetaGeneration, but does have Metageneration

gce: rename MetaGeneration to Metageneration

---

repro/repro.go

By receiving `vm.Shutdown` in a select,  it can return more quickly and graceful. 
Both in `manager` and `sys-repro`.

repro: quick return when user press ctrl^C

---

CONTRIBUTORS
ipc/ipc.go
syz-fuzzer/fuzzer.go
tools/syz-execprog/execprog.go
tools/syz-stress/stress.go

This PR contains two related commits providing additional control over the execution of the executor.
The first adds an 'abort' signal which is used to ask the executor to exit. When wrapping the executor in an external sandbox, providing a graceful shutdown mechanism may allow the sandbox to out additional debugging information. If the executor fails to gracefully shut down it is sent a SIGKILL.
The second allows control over the the executor output buffer. An external sandbox may output many more logs, making 128k insufficient to provide full context for the failure. The current buffering mechanism isn't ideal for a large buffer size, but it is fine for now.

Add controls for executor aborts and output

---

csource/common.go
csource/csource.go
executor/common.h
executor/executor.cc
host/host.go
prog/prog.go
sys/vnet.txt
sysgen/syscallnr.go
syz-fuzzer/fuzzer.go
tools/syz-execprog/execprog.go

This commit adds a new pseudo syscall syz_extract_tcp_res, that reads a packet from /dev/net/tun and extracts tcp sequence numbers to be used in subsequent packets.
As a result this syzkaller program:
```
mmap(&(0x7f0000000000/0x10000)=nil, (0x10000), 0x3, 0x32, 0xffffffffffffffff, 0x0)
r0 = socket$inet_tcp(0x2, 0x1, 0x0)
bind$inet(r0, &(0x7f0000001000)={0x2, 0x0, @empty=0x0, [0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0]}, 0x10)
listen(r0, 0x5)
syz_emit_ethernet(0x36, &(0x7f0000002000)={@local={[0xaa, 0xaa, 0xaa, 0xaa, 0xaa], 0x0}, @random="4c6112cc15d8", [], {{0x800, @ipv4={{0x5, 0x4, 0x0, 0x0, 0x28, 0x0, 0x0, 0x0, 0x6, 0x0, @remote={0xac, 0x14, 0x0, 0xbb}, @local={0xac, 0x14, 0x0, 0xaa}, {[]}}, @tcp={{0x1, 0x0, 0x42424242, 0x42424242, 0x0, 0x0, 0x5, 0x2, 0x0, 0x0, 0x0, {[]}}, {""}}}}}}) …
```

sys, executor: extract tcp sequence numbers from /dev/net/tun

---

prog/mutation_test.go

I added validations that `BufferType` should be `ArgData` in https://github.com/google/syzkaller/commit/209dba01113133ca87a36e9d0b3a52a6cdec67c3

prog: fix buffer type with value 0x0 in tests

---

executor/executor.cc
ipc/ipc.go
tools/syz-stress/stress.go

This is mostly a cleanup change with little functional change.
Most notably, this removes kErrorStatus from the executor, which the
executor never returns anymore. This has the cascading effect of
removing the failed return from ipc.Env.Exec, which was only returned in
the case of kErrorStatus.
In ipc.command.exec, remove the status fallback from the pipe to the
exit status. Once the executor is serving, it always writes the status
over the pipe; anything else is an error.
Remove the panic check in syz-stress, which is no longer needed.

all: cleanup executor/ipc interaction

---

config/config.go
config/config_test.go

use reflect to enumerate all known fields rather than do it manually,
when change `Config`, there is no need to change `checkUnknownFields` at the same time.

config: use reflect to enumerate all known fields

---

Makefile
executor/common.h

Stack usage warning currently breaks our internal build (with 16K frame limit).
Executor uses stacks of limited size, that's another reason to not
allow frames of arbitrary size.
Limit stack frame size to 8K.
Reduce tun packet size. We don't need to read out whole packet.

executor: limit stack frame size

---

Makefile
csource/common.go
csource/csource.go
executor/common.h
executor/syscalls.h
sysgen/syscallnr.go

A single check is enabled for now (misc-definitions-in-headers).
But it's always fixable and found 2 bugs in csource.

executor: fix clang-tidy warnings

---

pkg/kernel/patch.go
pkg/kernel/patch_test.go
syz-dash/handler.go

Patch parsing is not dashboard-specific and can
be reused by other programs.

syz-dash: move patch parsing to pkg/kernel

---

AUTHORS
CONTRIBUTORS
docs/syscall_descriptions_syntax.md
sys/sysparser/lexer.go
sys/syz-extract/extract.go
sys/syz-extract/fetch.go

Add custom include directories with this syntax in syscall description file:
incdir "incdir"
bin/syz-extract read in the content of syscall description, add -IflagLinux/incdir to compile cmd args
This is for modules which have customized include paths
Same target with https://github.com/google/syzkaller/pull/158

Parse incdir "incdir" in syscall description file to add custom include directories.

---

vm/vmimpl/linux.go

Accidentally changed the backing constant, which breaks the console on Linux

Restore TCXETS2

---

prog/rand.go

The inner return value can't be nil, arguments are always created now.
Fixes #249

prog: fix PtrType generation

---

pkg/repro/repro.go
pkg/repro/repro_test.go
syz-manager/html.go
syz-manager/manager.go
vm/vm.go

After this change syzkaller was able to generate a reproducer for [this bug](https://groups.google.com/forum/#!topic/syzkaller/dQ0r_bHOrJk).
The following is not yet implemented:
```
// TODO: Minimize each program before concatenation.
// TODO: Return multiple programs if concatenation fails.
```
Updates #179

Bisect the log to find multiple guilty programs

---

tools/syz-symbolize/symbolize.go

Currently syz-symbolize symbolizes whole input file.
Add a new mode (controlled with -report flag) when
it prints report as would be extracted by syz-manager.

tools/syz-symbolize: add report mode

---

pkg/csource/csource.go

pkg/csourse: don't generate __NR_X defines for old syscalls

---

pkg/repro/repro.go
syz-manager/manager.go

We can start reproducing one crash, but end up reproducing another.
Currently we still attribute the resulting repro to the original crash.
This is wrong.
Save the resulting desc/report for reproducers and use that in manager.

syz-manager: save proper report for reproducers

---

CONTRIBUTORS
docs/setup.md
docs/setup_linux-host_isolated.md
vm/isolated/isolated.go
vm/vm.go
vm/vmimpl/console.go

Add a new isolated VM for machines that you cannot easily manage. It
assumes the machine is only available through SSH and create a reverse
proxy to ensure the machine can connect back to syz-manager.
Signed-off-by: Thomas Garnier <thgarnie@google.com>

Add Isolated VM

---

pkg/repro/repro.go
syz-manager/manager.go

Logs are useful in situations where we mess the report.
Since we try to report crashes with reproducers,
we need logs for reproducers.

pkg/repro: save final crash log

---

pkg/report/report.go
pkg/report/report_test.go

Which has a tab instead of a space at the beginning of each frame in alloc and free stack traces.

pkg/report: fix symbolization of old KASAN stack trace format

---

pkg/repro/repro.go

res can become nil if one of the repro routines fails with an error.

pkg/repro: fix null-ptr-deref when res is nil

---

prog/mutation.go
prog/mutation_test.go
prog/size_test.go

Use removeCall() to update use references.
Also add a test.

prog: properly remove calls when splicing progs

---

prog/encoding.go
prog/prog.go
prog/prog_test.go
sys/kvm.txt

KVM_RUN ioctl must have arg set to 0, otherwise it returns EINVAL.
This can lead to syzkaller not able to generate a C repro.
Since arg value is undefined, it might have different values when
executing a program with syz-exeprog vs executing a compiled C repro.

sys: fix KVM_RUN ioctl

---

dashboard/app/api.go

We see some episodic
"failed to delete old crash texts: Call error 11: Deadline exceeded (timeout)"
errors in logs.
Deleting at most 10 bugs should be enough since we do this check
after adding each new crash.

dashboard/app: purge at most 10 crashes at once

---

prog/mutation.go

Due to https://github.com/google/syzkaller/issues/316 there're too many
mmap() calls in the programs, and syzkaller is spending quite a bit of
time mutating them. Most of the time changing mmap() calls won't give
us new coverage, so let's not do it too often.

prog: don't mutate mmap() calls too often

---

pkg/osutil/osutil.go
pkg/rpctype/rpctype.go
syz-hub/http.go
syz-hub/hub.go
syz-hub/state/state.go
syz-hub/state/state_test.go
syz-manager/html.go
syz-manager/manager.go

Currently hub allows managers to exchange programs from corpus.
But reproducers are not exchanged and we don't know if a crash
happens on other managers as well or not.
Allow hub to exchange reproducers.
Reproducers are stored in a separate db file with own sequence numbers.
This allows to throttle distribution of reproducers to managers,
so that they are not overloaded with reproducers and don't lose them on restarts.
Based on patch by Andrey Konovalov:
https://github.com/google/syzkaller/pull/325
Fixes #282

syz-manager, syz-hub: share repros between managers via hub

---

.travis.yml

.travis.yml: use go1.9rc1 since aliases trip gofmt for vendored code
For https://github.com/golang/go/issues/21337.
Since the introduction of aliases is in Go1.9 but Go1.9 hasn't
yet been officially released, let's use go1.9rc1 which is supported
on Travis CI by their Go version getter gimme
https://github.com/travis-ci/gimme
instead of against go1.8.1. This solves the problem on which
our vendored code is updated using Go1.9* syntax but is running
against Go1.8* in Travis CI tests.

.travis.yml: test against go1.9rc1, tip since aliases trip gofmt

---

prog/prog.go
prog/prog_test.go

Currently fails on:
- pointers
- VMAs
- structs
- fixed-size structs

prog: fix restoration of default arguments

---

prog/prog.go
prog/rand.go

Reuse defaultArg in generateArg. There is code that does the same.
Also, don't generate pointer value for output arguments.

prog: reuse defaultArg

---

tools/syz-benchcmp/benchcmp.go

Exec total is affected by initial triage/minimize phase,
so two experiments can have the same execution speed
in the stable mode, but have constant diff due to the initial phase.
The one that is higher looks better, but that's not very important.
Provide execution speed characteristic that is not affected
by initial phase. It is not displayed by default.

tools/syz-benchcmp: add execution speed

---

docs/headerparser_usage.md

Remove the --device option from the documentation file docs/headerparser_usage.md

docs: fix syz-headerparser documentation

---

docs/syscall_descriptions_syntax.md
sys/key.txt
sys/socket.txt
sys/socket_inet.txt
sys/socket_inet6.txt
sys/socket_unix.txt
sys/syz-sysgen/sysgen.go
sys/vnet.txt

All other types have optional underlying type as the last argument.
Proc have it as first. This creates very irregular syntax and
complicates parsing. Make type the last argument.
Note: this is a breaking change if you have descriptions on the side.

sys: change proc arguments to the format used by const/flags/len

---

docs/syscall_descriptions_syntax.md
pkg/compiler/testdata/errors.txt
pkg/compiler/types.go

ptr64 is like ptr, but always takes 8 bytes of space.
Needed for some APIs. Unfortunately, most of these APIs
use buffer type, so we can't use ptr64 immidiately.

sys: support ptr64 type

---

.travis.yml
Makefile
docs/setup_generic.md
docs/setup_linux-host_android-device_arm64-kernel.md
docs/setup_ubuntu-host_odroid-c2-board_arm64-kernel.md
docs/troubleshooting.md
syz-ci/syzupdater.go
syz-manager/mgrconfig/mgrconfig.go

We currently build binaries for all targets into bin.
This makes mess in bin/ and does not allow testing of different archs.
Build target binaries into bin/OS_ARCH/ subdirs.
Host binaries are still built into bin/.
Update #333
Update #324
Update #191

Makefile: build target binaries into separate dirs

---

executor/common_linux.h
executor/syscalls_linux.h
pkg/csource/common.go
sys/linux/386.go
sys/linux/amd64.go
sys/linux/arm.go
sys/linux/arm64.go
sys/linux/ppc64le.go
sys/linux/vnet.txt

A recent linux commit "tun: enable napi_gro_frags() for TUN/TAP driver"
added support for fragmentation when emitting packets via tun.
Support this feature in syz_emit_ethernet.

executor: support fragmentation in syz_emit_ethernet

---

executor/executor.h

KCOV comparisons support is in the kernel mm tree already, and the
patch contains an additional uint64_t to store PCs of functions calling
__sanitizer_cov_trace_XXX().
Change kcov_comparison_t accordingly.

executor: add PC to kcov_comparison_t

---

sys/syz-extract/fetch.go

commit 3520854be0e7 ("syz-extract: select declaring printf or not")
broke 'make extract' because it introduced invalid syntax in a text
template.  Fix it.

syz-extract: fix printf conditional in template

---

pkg/repro/repro.go
tools/syz-execprog/execprog.go

`syz-execprog` doesn't utilize info about fault injections from a prog log.
Since `syz-execprog` is used by the repro package to reproduce crashes, crashes caused by fault injections might not reproduce.
Fixes #410

execprog: correctly handle fault injections

---

executor/common_linux.h
pkg/csource/linux_common.go

For some racy bugs syzkaller can generate a C reproducer with tun enabled, when it's not actuallly required to trigger the bug. Some kernel developers (that don't have CONFIG_TUN=y on their setups)
complain about such C repros. When tun is not available, instead of exiting, print a message that tun initialization failed and proceed.
Updates #414

executor: proceed even if /dev/net/tun is not available

---

pkg/report/akaros.go
pkg/report/freebsd.go
pkg/report/freebsd_test.go
pkg/report/fuchsia.go
pkg/report/linux.go
pkg/report/linux_test.go
pkg/report/netbsd.go
pkg/report/report.go
pkg/report/report_test.go
pkg/report/windows.go
pkg/repro/repro.go
tools/syz-symbolize/symbolize.go
vm/vm.go

This change makes pkg/report try to detect corrupted reports by using some heuristics.

pkg/report: add corrupted report detection

---

pkg/report/linux.go
pkg/report/linux_test.go

KASAN report might not have Allocated or Freed stack traces at all.
This change doesn't include new regexps for the whole report yet.

pkg/report: fix corrupted KASAN reports detection

---

pkg/report/freebsd.go
pkg/report/linux.go
pkg/report/linux_test.go
pkg/report/report.go

Add another regexp to oopses that should match the whole report.
Report is considered corrupted when it doesn't.

pkg/report: fix corrupted reports detection

---

pkg/report/linux.go
pkg/report/linux_test.go

Look for stack frames in the next 10 lines after 'Call Trace' instead of 3.

pkg/report: fix corrupted stack trace detection

---

executor/syscalls_linux.h
prog/encoding.go
prog/encoding_test.go
prog/prog.go
prog/validation.go
sys/linux/386.go
sys/linux/amd64.go
sys/linux/arm.go
sys/linux/arm64.go
sys/linux/ppc64le.go
sys/linux/test.txt

For string[N] we successfully deserialize a string of any length.
Similarly for a fixed-size array[T, N] we successfully deserialize
an array of any size.
Such programs later crash in foreachSubargOffset because static size
Type.Size() does not match what we've calculated iterating over fields.
The crash happens only in SerializeForExec in syz-fuzzer,
which is especially bad.
Fix this from both sides:
1. Validate sizes of arrays/buffers in Validate.
2. Repair incorrect sizes in Deserialize.

prog: repair arrays/buffers with incorrect size in Deserialize

---

docs/freebsd.md

Building the executor via `gcc executor/executor_freebsd.cc ...`
requires that a GCC package first be installed on the FreeBSD VM image.
The FreeBSD base system comes with Clang already installed, so we can
build via `c++ executor/executor_freebsd.cc ...` and avoid having to
install additional packages.

docs: use 'c++' to build on FreeBSD

---

executor/syscalls_linux.h
prog/mutation_test.go
prog/size.go
prog/size_test.go
sys/linux/386.go
sys/linux/amd64.go
sys/linux/arm.go
sys/linux/arm64.go
sys/linux/ppc64le.go
sys/linux/test.txt

I guess this is currently unused,
but ignoring bytesizeN for vma looks wrong.
If user asks for bytesizeN for vma, divide vma size by N.

prog: support bytesizeN for vma

---

pkg/report/freebsd.go
pkg/report/linux.go
pkg/report/report.go
pkg/repro/repro.go
syz-ci/jobs.go
syz-manager/manager.go
tools/syz-crush/crush.go
vm/vm.go

Whole raw output is indivisble part of Report,
currently we always pass Output separately along with Report.
Make Output a Report field.
Then, put whole Report into manager Crash and repro context and Result.
There is little point in passing Report as aa bunch of separate fields.

pkg/report: add Output to Report

---

pkg/report/akaros.go
pkg/report/freebsd.go
pkg/report/fuchsia.go
pkg/report/linux.go
pkg/report/linux_test.go
pkg/report/netbsd.go
pkg/report/report.go
pkg/report/windows.go
pkg/repro/repro.go
syz-ci/jobs.go
syz-manager/html.go
syz-manager/manager.go
tools/syz-symbolize/symbolize.go
vm/vm.go

Currently getting a complete report requires a complex,
multi-step dance (including getting information that
external users are not interested in -- guilty file).
Simplify interface down to 2 functions: Parse and Symbolize.
Parse does what it did before, Symbolize symbolizes report
and fills in maintainers. This simplifies both implementations
of Reporter interface and all users of the interface.
Potentially we could get this down to 1 function Parse
that does everything. However, (1) Symbolize can fail,
while Parse cannot, (2) usually we want to ignore (log)
Symbolize errors, but otherwise proceed with the report,
(3) repro does not need symbolization for all but the
last report.

pkg/report: include Maintainers into report

---

dashboard/app/api.go
dashboard/app/entities.go
dashboard/app/handler.go
dashboard/app/main.go
dashboard/app/main.html
dashboard/app/reporting.go
dashboard/dashapi/dashapi.go
syz-ci/jobs.go
syz-ci/manager.go
syz-ci/managercmd.go
syz-ci/testing.go
syz-manager/manager.go
vm/vm.go
vm/vmimpl/vmimpl.go

Make it possible to monitor health and operation
of all managers from dashboard.
1. Notify dashboard about internal syz-ci errors
(currently we don't know when/if they happen).
2. Send statistics from managers to dashboard.

dashboard/app: add manager monitoring

---

pkg/report/freebsd.go
pkg/report/linux.go
pkg/report/linux_test.go
pkg/report/report.go
vm/vm.go

Try extracting report from console output only first. If that doesn't work, try extracting it from the whole log.
Add regexp for executor printed BUGs.
Optimize regexps for rcu detected stalls.
Update rep.StartPos and rep.EndPos in vm/vm.go as well as rep.Output.
Fixes #457

pkg/report: fix report extraction

---

pkg/report/linux.go
pkg/report/linux_test.go

`linuxSymbolizeRe` can match `IP: depot_fetch_stack+0x11/0x40`, which is not part of the call stack trace. Add another regexp that only matches frames.

pkg/report: fix corrupted call trace detection

---

pkg/report/linux.go
pkg/report/linux_test.go

Allow stack traces to be intermixed with random kernel messages that don't start with a space char (all frames in a stack trace do).
Also improve report headers for `BUG`s from `mm/usercopy.c`, since we get quite a lot of those.

pkg/report: improve report header extraction

---

executor/common.h
pkg/csource/akaros_common.go
pkg/csource/freebsd_common.go
pkg/csource/linux_common.go
pkg/csource/netbsd_common.go

Bot found a bug when testing #474
```
tmp.c: In function ‘fail’:
tmp.c:39:41: error: ‘kRetryStatus’ undeclared (first use in this function)
doexit((e == ENOMEM || e == EAGAIN) ? kRetryStatus : kFailStatus);
^
tmp.c:39:41: note: each undeclared identifier is reported only once for each function it appears in
tmp.c:39:56: error: ‘kFailStatus’ undeclared (first use in this function)
doexit((e == ENOMEM || e == EAGAIN) ? kRetryStatus : kFailStatus);
```

executor: fix macros in common.h

---

AUTHORS
CONTRIBUTORS
docs/configuration.md
syz-manager/manager.go
syz-manager/mgrconfig/mgrconfig.go

Users can specify an email address to reveive notifications when a
bug is discovered for the first time, without setting up a full fledged
dashboard. The supported mailer is mailx.
Signed-off-by: Tim Tianyang Chen <soapcn@gmail.com>

syz-manager: add simple email support

---

Makefile
docs/linux/setup_linux-host_android-device_arm64-kernel.md
docs/linux/setup_ubuntu-host_android-device_arm32-kernel.md

There are 2 known problems with current Android support:
1. It does not work with newer NDK
(happens on every NDK update).
2. Dynamic Go binaries do not start on Android emulator.
Drop special Android support and just build static linux binaries.
For context see:
https://groups.google.com/forum/#!msg/syzkaller/etg1ZJmTMzg/NYE-yjxxAQAJ
https://groups.google.com/d/msg/syzkaller/8KjCYWslTFY/1oTXn5tTAgAJ
Fixes #478

Makefile: fix Android builds

---

AUTHORS
CONTRIBUTORS
Makefile

I'm not sure if this is due to different versions of gmake or some other
reason, but the Makefile falsely detected a modified git tree when the
first ifeq argument was unquoted. Also switch to the $(shell ... style
for consistency.

Makefile: fix git "modified tree" test on FreeBSD

---

CONTRIBUTORS
Makefile
sys/syz-extract/fuchsia.go

A change in Zircon a while back moved around where sysroots are located
in Fuchsia; this update will allow for proper extraction.

syz/syz-extract: Update Fuchsia extractor with current Fuchsia paths.

---

Makefile

While CGO should be disabled by default, it is necessary when building
FUCHSIA.
Additionally, the Fuchsia Go toolchain expects ZIRCON_BUILD_DIR to be
set (
https://github.com/fuchsia-mirror/third_party-go/blob/master/misc/fuchsia/gccwrap.sh
), so we set it here.

Makefile: Enable CGO and set ZIRCON_BUILD_DIR for Fuchsia targets.

---

.travis.yml

1.9 is available for a long time, no point in testing in 1.9rc1.
1.10 is already released too.

travis: switch to Go 1.9+1.10

---

AUTHORS
CONTRIBUTORS
executor/executor_bsd.cc

This patch makes the changes necessary to support the new kcov interface in FreeBSD; allowing coverage data to be collected when syzkaller is run on this platform. The interface is intentionally very similar to that of the Linux kcov.
The changes to support this feature in FreeBSD have not been merged yet and therefore are not necessarily final. However, it is unlikely that there will be any changes to the interface itself. Those interested can visit the review for this patch [here](https://reviews.freebsd.org/D14599).

executor: add support for FreeBSD's kcov

---

executor/common_linux.h
pkg/csource/linux_common.go

Add a veth pair with name bond/team_slave and set their master
to bond0/team0.
Remove veth from devtypes because the cmd `ip link add veth0 type veth`
will actually failed with "RTNETLINK answers: File exists" and no veth
interface created. When create veth device, kernel will create a
pair of veth, so no need to create them one by one.
Signed-off-by: Hangbin Liu <liuhangbin@gmail.com>

executor: add salve interface for bond0/team0

---

vm/adb/adb.go

Hi,
While getting my syzkaller setup ready, I realized that the auto detection of UART assume that the UART display all the level of printk. Which is not the case on my setup.
Adding the ALERT tag to the echo in kmsg to ensure proper detection
******
The UART output may filter lower level messages.
This ensure proper detection of the unique ID
Signed-off-by: Jean-Baptiste Théou <jb@essential.com>

adb: add debug level to ALERT for UART detector

---

prog/resources.go

In resources.go, haveGettime is False when SyscallMap["clock_gettime"]
is nil.
In this code, there's a branch that's entered only if Gettime is False,
which appends SyscallMap["clock_gettime"] to resourceCtors.  That is, it
appends nil to resourceCtors, then iterates through resourceCtors and
tries to dereference the .Name of each time, in this case, nil.Name.
This was causing a page fault on Fuchsia.
I'm not certain how the "standard" flow is supposed to work, since it
seems like any code that enters the `if cantCreate == "" && !haveGettime`
should fail... but removing that section causes test failures, so let's
just enforce that SyscallMap["clock_gettime"] is non-nil.
If there's a better way to solve this, I'm open to suggestions, I'm not
super-sure how the transitively-enabled syscall …

prog: Fix page fault for syz-stress users.

---

executor/common_linux.h
pkg/csource/linux_common.go

gcc8 is stricter when dealing with strings and strncpy and demands that
the size of the actual string to be copied to be explicitly smaller than
the size of the destination, just to make sure the NULL terminator is
taken into considerantion. This patch fixes the issue.
Signed-off-by: Ioana Ciornei <ciorneiioana@gmail.com>

executor: fix strncpy compile error

---

vm/adb/adb.go

echo 0 to kptr_restrict in /proc/sys/kernel to unhide
kernel pointers when fuzzing for more reliable crash
dedup and easier debugging when analyzing crash.

vm/adb: disable kptr_restrict for Android

---

executor/syscalls_linux.h
sys/linux/cdrom.txt
sys/linux/gen/386.go
sys/linux/gen/arm.go
sys/linux/gen/arm64.go
sys/linux/gen/ppc64le.go

1. Comment with clarification on how to run qemu added.
2.  Description of int type fixed.
Signed-off-by: Denis Efremov <efremov@linux.com>

sys/linux: fix cdrom rules description && clarification on how to run

---

CONTRIBUTORS
sys/linux/init_alg.go

This adds some recently added AEAD algorithms to the Linux kernel AF_ALG fuzzer:
https://www.mail-archive.com/linux-crypto@vger.kernel.org/msg32482.html
https://www.mail-archive.com/linux-crypto@vger.kernel.org/msg32483.html

sys/linux: add MORUS and AEGIS AEAD algorithms

---

executor/syscalls_linux.h
sys/linux/gen/386.go
sys/linux/gen/arm.go
sys/linux/gen/arm64.go
sys/linux/video4linux.txt

The id field in the v4l2_event_subscription structure
currently described as: id len[type, int32].
But all the documentation states is:
"id - ID of the event source. If there is no ID associated
with the event source, then set this to 0. Whether or not
an event needs an ID depends on the event type."
So, the documentation clearly states that:
1. id - is the source of an event
2. type - is the type of an event
3. for some types of events there is no source and id can be 0
According to this 'id int32' is a more accurate description of
the field.
Discussion https://github.com/google/syzkaller/issues/616

sys/linux: id field fix in v4l2_event_subscription

---

sys/midi.txt

Enabling MIDI supported IOCTL descriptors for Syzkaller

Sound Mixer Descriptors for MIDI

---

CONTRIBUTORS
syz-manager/cover.go
syz-manager/html.go

If vmlinux built from different tree from kernelSrc, cover page will failed to
show. So match only the path without prefix.

syz-manager: Support kernelSrc and vmlinux from different tree

---

executor/common.h
executor/executor.h
executor/executor_bsd.cc
prog/types.go

Found while adding support to OpenBSD, reviewing each commit in isolation is recommended.

Various improvements

---

pkg/csource/gen.sh

OpenBSD and probably other BSDs does not ship with /bin/bash. This particular script runs fine with regular /bin/sh.

pkg/csource: remove /bin/bash assumption

---

vm/adb/adb.go

By using UDEV rules, we can create device nodes which exist at
/dev/ttyUSB.{android device serial}
Which makes it easier to determine which console belongs to a device.
While this is non-standard behavior, it's an inexpensive path check
and makes the lookup faster and deterministic.

adb: Add console logic for ttyUSB.serial

---

docs/configuration.md
syz-manager/mgrconfig/mgrconfig.go

The docs and code comments state in several places that 'setuid' is the default sandbox value.  
However, the default is currently 'none'.  
Fix the default to be in-line with what the docs say.

manager: Fix default value for 'sandbox'

---

dashboard/app/main.html
dashboard/app/static/style.css

For easier linkification, this adds clickable anchors for each
BugNamespaces without changing the current appearance of the h2 tag.

dashboard/app: Add anchor links for BugNamespaces

---

vm/vmm/vmm.go

The IP address of a VM is calculated based on the formula 100.64.X.3 where X
being the ID of the VM, starting from 0. After starting 256 VMs 64 will flip
over to 65 and so on. A more robust solution to calculating the IP is to simply
read it from the output during boot.
While here, stop using the VM ID as the identifier since the VM name also works.

vm/vmm: fix IP address detection

---

sys/openbsd/init.go

On OpenBSD, the vnode type for a device node of type S_IFMT is interpreted as
VBAD. Such vnodes often causes assertion failures inside kernel producing noisy
crashes. The goal of the OpenBSD specific SanitizeCall() is to prevent such
device nodes from being created. The S_IFMT constant is a mask covering all
possible device types, thus covering both character and block devices. Therefore
when the fuzzer generates a mknod{,at}() syscall with the S_IFMT type we cannot
known if the intent was to create a block or character device. Therefore
simplify the code to create a character device under such circumstances.
The observed failure is caused by the interaction between the OpenBSD specific
SanitizeCall() and the Unix one. The Unix sanitizer will not modify the mode
argument if it contains …

sys/openbsd: make SanitizeCall() idempotent

---

executor/executor_bsd.h

OpenBSD does not allow write and exec mappings by default.
Since the OpenBSD target does not make use of syz_execute_func yet, just drop
PROT_EXEC for now.
Supporting write and exec would require one to edit /etc/fstab during
installation.

executor: fix regression on OpenBSD

---

docs/openbsd/setup.md
sys/targets/targets.go
syz-manager/cover.go
syz-manager/html.go
syz-manager/manager.go

With this change, I'm able to render the HTML-representation of the coverage on OpenBSD.

pkg/mgrconfig: allow the name of kernel to be configured

---

docs/linux/setup_ubuntu-host_qemu-vm_x86-64-kernel.md

In the context, there is no one file called id_rsa. From [the suggested script](https://github.com/google/syzkaller/blob/master/tools/create-image.sh) to generate wheezy qemu image, we could see the private key is "wheezy.id_rsa". And the path is directly in the root directory of $IMAGE.

Modify name of private key file as id_rsa does not exist in the context

---

docs/linux/setup_ubuntu-host_qemu-vm_x86-64-kernel.md
tools/create-image.sh

This updates the image creation tool to use Debian stretch (current stable)
instead of wheezy, which is very out of date. The only change needed here
was a hint to systemd to make the root filesystem read-write after booting.
Documentation has also been updated.

tools: update to Debian stretch

---

Makefile
docs/fuchsia.md
sys/fuchsia/fidlgen/main.go
sys/fuchsia/init.go

This adds a Go script `sys/fuchsia/fidlgen/main.go`, which invokes `fidlgen` to automatically generate syscall description of all the currently supported FIDL files. `var zirconLibs` can later be extended to support generation of syscall descriptions for more FIDL files. What's blocking other FIDL files from being compiled is references to structs defined in other FIDL libraries.
Once most of the FIDL files can be compiled by the FIDL syzkaller backend, we may want to add a new rule to the Fuchsia build system, which simplifies this script into a single command that invokes that rule.

sys/fuchsia: add Go script that generates fidl descriptions

---

CONTRIBUTORS
docs/linux/setup_ubuntu-host_qemu-vm_x86-64-kernel.md

Recently Debian image was updated to be 'stretch' from 'wheezy'.  The
ssh command got missed.
Update the ssh command to use 'stretch' instead of 'wheezy'.
Signed-off-by: Tobin C. Harding <me@tobin.cc>

docs: Use 'stretch' in ssh command

---

tools/create-openbsd-gce-ci.sh

Added verification of successful package install.
Related to #712 
@mptre

tools/create-openbsd-gce-ci.sh: Add VMM configuration

---

docs/openbsd/setup.md
pkg/build/akaros.go
pkg/build/build.go
pkg/build/fuchsia.go
pkg/build/openbsd.go

First stab at adding support for OpenBSD to `pkg/build`. Currently
limited to building a kernel with KCOV enabled.

pkg/build: add initial OpenBSD support

---

executor/common_linux.h
executor/executor.cc
pkg/csource/generated.go

Compiling the executor on OpenBSD currently fails:
executor/executor.cc:1316:6: error: unused function 'debug_dump_data'
Another approach would be to make the function non-static.

executor: move debug_dump_data() into common_linux.h

---

pkg/symbolizer/nm.go
pkg/symbolizer/nm_test.go

On OpenBSD, nm(1) does not support the `-S` option.
The order of symbols from nm(1) varies between platforms, therefore rework the
test case to cope with that.
Is the ordering of symbols by address of importance?

pkg/symbolizer: favor portable nm(1) format

---

executor/common.h
executor/common_linux.h
executor/executor.cc
pkg/csource/generated.go

Sometimes race conditions are reproduced by syz-execprog and are not
reproduced by the programs generated with syz-prog2c. In such cases
it's very helpful to know when exactly the fuzzing syscalls are executed.
Unfortunately, adding timestamps to the output of the original 'debug'
option doesn't work. This option provides very verbose output, which
slows down executor and breaks the repro.
So let's add the 'racedebug' option for syz-execprog, which provides the
limited debug output with timestamps from executor.
Signed-off-by: Alexander Popov <alex.popov@linux.com> …

executor: add 'racedebug' option for syz-execprog

---

docs/reproducing_crashes.md

This pull request fixes a typo in the *How to reproduce crashes* documentation.

docs: fix typo in reproduction documentation

---

Makefile
docs/fuchsia.md
sys/fuchsia/fidlgen/main.go

Anytime we're running `make extract/generate` with Fuchsia as a target, we
probably want to update FIDL descriptions too, so we don't fall behind
what upstream is up to.
This includes generate_fidl as part of the `make generate` workflow.

Include generate_fidl as part of the `extract` step.

---

docs/linux/setup_ubuntu-host_qemu-vm_x86-64-kernel.md

The package names for perf and qemu are out of date. This updates them.

docs: Update package names for modern Ubuntu

---

prog/target.go
sys/targets/targets.go

This avoids the issue of "android" not having any registered configurations
or syscalls / ioctls / etc, when built with GOOS=android.
This occurs when building in Google3, since --config=android_arm64 selects
the Android toolchain.
This supercedes #758 which was much more complex than it needed to be.
Per the feedback there, I've used `GetTarget` as the main hook point, and removed many of the changes which were only needed due to  unnecessary changes in `targets.go`.

targets: Use OS=linux when GOOS=android

---

executor/common_fuchsia.h
pkg/csource/generated.go

zx_task_resume() is deprecated; switch to using
zx_task_resume_from_exception() instead.

executor: Fuchsia: Use zx_task_resume_from_exception()

---

docs/openbsd/setup.md
vm/vmm/vmm.go

As a result, the boot time is significantly improved since there's no longer any
need to copy the complete disk.
This feature was recently committed to OpenBSD-current. Any existing base image
used must be recreated, this time using the qcow2 disk format.

vm/vmm: use derived disks for VMs

---

executor/common.h
executor/common_linux.h
pkg/csource/generated.go
tools/android/Makefile
tools/android/jni/Android.mk
tools/android/jni/Application.mk
tools/android/jni/sandbox_test.c

Android: Fix sandbox implementation
My test harness for this code performed some steps that are not performed when syz-executor is invoked directy.
Specifcally, we need to operate from a directory under /data/data, and have the correct UID/GID set as the owner of the directory.
I added a simple test harness to demonstrate that it works, and ease the testing process in the future.
Test: make -C tools/android run
Test: make presubmit

Android sandbox fixes

---

vm/gvisor/gvisor.go

As of commit 3f053259, gVisor sentry panics are no longer sent to the
stderr for "runsc run" by default, as that stderr belongs exclusively to
the application.
As a result, syzbot never sees the gVisor panic stack trace, and is only
reporting errors that occur when waiting for a dead sandbox.
Passing the "-debug" flag to runsc will make the sentry panics visible
to syzbot again.

Pass -debug flag to runsc.

---

vm/vmm/vmm.go

The ddb(4) debugger defaults to showing 24 lines at a time, the next chunk of
lines will be displayed only after receiving keyboard input. Setting maxlines to
0 disables pagination completely.

vm/vmm: disable pagination and show panic in Diagnose()

---

pkg/report/openbsd.go
pkg/report/testdata/openbsd/report/7

Sometimes the reorder_kernel error message is truncated causing the current
ignore pattern to fail. Instead, simply reject all lines containing
reorder_kernel in order to reduce noisy crash reports.

pkg/report: do not interpret reorder_kernel lines as a crash on OpenBSD

---

docs/fuchsia.md
pkg/build/fuchsia.go

* Needed to clean out the build on the main host. We switched to a
"petal" layout which required a complete rebuild.
* Update SSH interface.  SSH keys have to be set at buildtime via
--args.
* Update fvm.blk location.

[fuchsia] Fix Fuchsia build.

---

pkg/build/fuchsia.go

Hey--so I *don't* know a particularly efficient way to test syz-ci right
now.
There's no good config I can find for just running it locally, and I
couldn't find any good unit tests for this function in particular, and
running it manually on a ci server isn't super-appealing since I'd have
to clobber the configuration there to point to my repo instead of the
canonical repo, pull from there, etc.
Do you have any good ideas for testing this before it rolls out?  In
particular I want the invocation to look exactly like:
./scripts/fx set x64 --packages garnet/packages/products/sshd --args 'extra_authorized_keys_file="//.ssh/authorized_keys"'
I thought I'd escaped it properly last time, but, since I couldn't test
it, clearly I goofed.  I *think* this does the right thing but I'd love
a sanity …

[fuchsia] Fix typo in Fuchsia build.

---

pkg/build/fuchsia.go
syz-ci/syzupdater.go

SSH keys are now included at the fx clean-build config.
A proper escape sequence looked weird so use a string literal to pass
that config.
Fixed some typos I found while debugging.

[fuchsia] SSH fix and build invocation fix.

---

docs/fuchsia.md

I am adding a note in the fuchsia docs to specify that the caller should also build fuchsia for arm64. This is because the make extract command will call generate_fidl for TARGETARCH amd64 and arm64. If you happen to have an old tree for arm64, your amd64 changes might be overwritten by the arm64 ones.

docs: require arm64 build for fuchsia

---

sys/fuchsia/fidlgen/main.go

This commits adds "zircon-ethernet" to the list of fidl libraries that
fidlgen would look at. This is required because recently, a change in
fuchsia[0] added a new method to the netstack interface, that allows for
adding an EthernetInterface. One of the parameters is a
zircon.ethernet.Device, so we need to import that type for fidlgen to be
able to understand fidl_net-stack.txt.
I tested this by running:
```shell
$ make extract TARGETOS=fuchsia SOURCEDIR=${FUCHSIADIR}
$ make generate
```
[0]: https://fuchsia-review.googlesource.com/c/zircon/+/220580

sys/fuchsia add zircon-ethernet to fidlgen libs.

---

pkg/compiler/check.go
pkg/compiler/compiler.go
pkg/compiler/compiler_test.go
sys/fuchsia/fidlgen/main.go

This commit adds an error handler for the `CollectUnused` function. The
error handler just panics on any error, but is useful for debugging.
The error handler is used any time `comp` finds an error, and if it's
missing, it will panic due to a `nil` pointer dereference. At least now
we get a better understanding of the errors.
The only user of `CollectUnused` is `sys/fuchsia/fidlgen`, which is
failing now and will be fixed in a future commit.
The output message looks like this:
```
panic: could not collect unused nodes. fidl_net-stack.txt:110:15:
unknown type zx_chan_zircon_ethernet_Device_client
```

pkg/compiler: Add error handler in `CollectUnused`.

---

prog/minimization.go
prog/minimization_test.go

This patch changes minimization routines to try assigning a.Res to nil for each pointer arg.

prog: try to nullify pointers when minimizing

---

vm/vmm/vmm.go

openbsd: include process information into crashes

---

pkg/ipc/ipc.go
pkg/ipc/ipc_test.go
pkg/rpctype/rpctype.go
pkg/runtest/run.go
syz-fuzzer/fuzzer.go
syz-fuzzer/proc.go
syz-fuzzer/testing.go
tools/syz-execprog/execprog.go

This patch add a new struct `ProgInfo` that for now holds info about each call in a program `[]CallInfo`, but in the future will be expanded with remote coverage info. Update all the callers to use the new interface as well.

ipc: add ProgInfo struct

---

syz-fuzzer/proc.go
tools/syz-execprog/execprog.go

We used to use `len([]CallInfo)` to check both, whether the slice is `nil` or whether its length is zero. Since `ProgInfo` is not a slice, we need a separate check for nil.

ipc: fix ProgInfo usage

---

executor/common.h
pkg/csource/generated.go

* Fixed endian.h path in executor/common.h. Modified pkg/csource/csource_test.go to skip test for target freebsd.
* Fixed ioctl calls for FreeBSD in executor/executor_bsd.h and replaced corresponding constant definitions by sys/kcov.h include. Modified Makefile to skip executor build for FreeBSD.

FreeBSD executor fix

---

pkg/build/build.go
pkg/build/openbsd.go
t/t.go
tools/create-openbsd-vmm-worker.sh
vm/gce/gce.go
vm/gce/tar_go1.10.go
vm/gce/tar_go1.9.go
vm/vm.go
vm/vmimpl/vmimpl.go
vm/vmm/vmm.go

This is working to the point of uploading a built tar file. The failure at that point is not actionable:
```
2018/11/24 21:18:02 GCE initialized: running on ci-openbsd-1, internal IP 10.128.0.105, project syzkaller, zone us-central1-c, net https://www.googleapis.com/compute/beta/projects/syzkaller/global/networks/default/https://www.googleapis.com/compute/beta/projects/syzkaller/regions/us-central1/subnetworks/default                                         
2018/11/24 21:18:02 uploading image /syzkaller/managers/main/latest.tmp/image to syzkaller/ci-openbsd-main-test-image.tar.gz...                                                 
2018/11/24 21:18:51 creating GCE image ci-openbsd-main-test...
2018/11/24 21:19:02 ci-openbsd-main: failed to create VM pool: failed to create GCE image: …
```

openbsd: run on gce

---

prog/analysis.go
prog/rand.go
prog/rand_test.go

It causes panic later in (*randGen).filename.

prog/analysis: prevent sandbox escaping files from entering s.files

---

tools/create-openbsd-gce-ci.sh

Remove ramdisk which never found any use while here.

tools/create-openbsd-gce-ci.sh: simplification due to workers on GCE

---

vm/qemu/qemu.go

Allow setting qemu_args to "" in the config file. This is needed
when running qemu from the qemu-devel package on FreeBSD, which
does not support the -enable-kvm option.
Without this patch, an entry "" is added to the list of command
line parameters, which breaks the starting of the qemu instances.

vm/qemu: Allow empty qemu-args.

---

AUTHORS
CONTRIBUTORS
vm/gce/gce.go
vm/gvisor/gvisor.go
vm/isolated/isolated.go
vm/kvm/kvm.go
vm/qemu/qemu.go
vm/vmm/vmm.go

When running in debug mode, the number of VMs is reduced to 1.
State this in the debug output.

vm/qemu: Improve debug output.

---

pkg/build/openbsd.go

Previously the config was generated directly, but testing multiple
configurations makes this cumbersome going forward. This makes
kernel_config a mandatory parameter.
@mptre, this changes the UX, let me know if you feel strongly enough that we need to provide a fallback.

pkg/build/openbsd: require kernel config files as configuration data

---

tools/syz-trace2syz/proggen/context.go
tools/syz-trace2syz/proggen/return_cache.go

Adding missing copyright headers to return_cache.go and context.go

tools/syz-trace2syz: adding missing copyright headers

---

pkg/report/akaros.go
pkg/report/freebsd.go
pkg/report/fuchsia.go
pkg/report/fuzz.go
pkg/report/gvisor.go
pkg/report/linux.go
pkg/report/linux_test.go
pkg/report/netbsd.go
pkg/report/openbsd.go
pkg/report/openbsd_test.go
pkg/report/report.go
pkg/report/report_test.go
pkg/report/stub.go
tools/syz-symbolize/symbolize.go

```
$ cat before.txt
ddb{1}> trace
db_enter() at db_enter+0xa
panic() at panic+0x147
__assert(ffffffff81521464,ffff8000211ab3d0,ffff8000210a39e0,ffff800000038e80) at __assert+0x24
_kernel_lock(ffff8000210a39e0,ffff8000211a6000) at _kernel_lock+0x125
pageflttrap() at pageflttrap+0x6c
kerntrap(9) at kerntrap+0x8d
alltraps_kern(6,ffff800000ad6000,ffffffffffffffff,0,9,ffff8000210a39e0) at alltraps_kern+0x7b
ptsignal(2829,ffff8000210a39e0,ffff8000210b7630) at ptsignal+0x115
mi_switch() at mi_switch+0x1fb
sleep_finish(1,ffff8000211ab660) at sleep_finish+0xd3
sleep_finish_all(ffff8000211ab660,32) at sleep_finish_all+0x22
tsleep(ffff8000210a39e0,3,0,ffff8000210b76f8) at tsleep+0x142
single_thread_set(ffff8000210a39e0,ffff8000210a39e0,0) at single_thread_set+0x28b
exit1(ffff8000210a39e0,9,0) at …
```

pkg/report: add initial symbolize suppport to OpenBSD

---

tools/create-openbsd-gce-ci.sh
tools/create-openbsd-vmm-worker.sh

This worked fine for ci machine but gce workers have no packages.

tools/*openbsd*: use nc from base instead of curl from package

---

executor/common_bsd.h
executor/executor_bsd.h
pkg/csource/generated.go
pkg/host/host_openbsd.go

This reverts commit 6565f24da9f4eb36702339ba290213995fcc902f.
Due to this bug:
2018/12/10 09:46:48 program execution failed: executor 0: EOF
dup2(0, kInPipeFd) failed (errno 9)

Revert "executor: add setuid sandbox for openbsd"

---

executor/common_bsd.h
executor/executor.cc
executor/executor_bsd.h
pkg/csource/generated.go
pkg/host/host_openbsd.go

OpenBSD default fd limit of 128 was not enough to run executor uses fd's over 240.

executor/common_bsd: reapply setuid sandbox

---

vm/gvisor/gvisor.go

Diagnose currently sends the panic signal to generate a traceback for
additional context.
However, Diagnose is also called in otherwise successful scenarios
(vm.Instance.MonitorExecution -> vm.monitor.extractError). Triggering a
panic will make this successful scenario look like a failure.
We could simply suppress this panic, but 1) that means we never shutdown
cleanly (not important, but ugly), and 2) we're less likely to detect
delayed crashes since we kill the sandbox immediately (that's what
MonitorExecution is checking for).
Instead, switch from -panic-signal to -trace-signal, which simply logs a
traceback without exiting. This option was added to runsc in
https://github.com/google/gvisor/commit/24c1158b9c21f7f8b7126e810d623a518422052e.
The other uses of Diagnose will always generate …

vm/gvisor: replace signal panic with log

---

vm/gvisor/gvisor.go

Dialing with "tcp" allows use of IPv4 or IPv6, and Listen in instance.inst.testInstance() may do either.
However, by hard-coding "127.0.0.1" here we force v4. Using "localhost" allows whichever is default.

vm/gvisor: support forwarding on IPv6

---

vm/gvisor/gvisor.go

If net.Dial returns an error, conn is nil and closing it will panic.

vm/gvisor: don't close conn on error

---

docs/gvisor.md

This configuration mounts the syzkaller bin/linux_amd64 folder as the
sandbox root, bind mounts a single input log, then runs syz-execprog on
the input.

docs: add instructions for running syz-execprog in gVisor

---

dashboard/config/openbsd-syzkaller.mp
dashboard/config/openbsd-syzkaller.sp
pkg/build/openbsd.go

clean build barely takes 3 minutes end-to-end on our CI machine.
Undo debug options which caused prevented kernels from booting on GCE.
@mptre FYI

pkg/build/openbsd: always make clean to manage config in tree

---

vm/adb/adb.go
vm/gce/gce.go
vm/gvisor/gvisor.go
vm/isolated/isolated.go
vm/kvm/kvm.go
vm/qemu/qemu.go
vm/vm.go
vm/vm_test.go
vm/vmimpl/vmimpl.go
vm/vmm/vmm.go

This requires plumbing the result into the kernel logs, which is actually quite simple.
This replaces #891.

vm/gvisor: use runsc debug --stacks to diagnose

---

tools/syz-trace2syz/parser/parser_test.go
tools/syz-trace2syz/parser/strace.go
tools/syz-trace2syz/parser/strace.y

Strace decodes bitsets like fd_set or sa_mask into the following structure: [a b c d e].
Before we couldn't parse these structures, but now parse them into the Group IR Type

tools/syz-trace2syz/parser: parse strace bitsets

---

executor/executor_bsd.h

Since we no longer cross-compile, there's no need to repeat the defines.

executor: include sys/kcov.h on bsd

---

tools/syz-trace2syz/parser/lex.go
tools/syz-trace2syz/parser/parser_test.go
tools/syz-trace2syz/parser/straceLex.rl

We don't properly parse octal numbers which is an issue because that's how strace decodes file permissions even under -Xraw. We used to do so but we didn't have a test for it so as when we added support for negative numbers we broke how we parse octals. This commit fixes how we parse octals and includes a test to catch future regressions.

tools/syz-trace2syz/parser: parse octal numbers

---

tools/syz-trace2syz/parser/lex.go
tools/syz-trace2syz/parser/straceLex.rl
tools/syz-trace2syz/proggen/proggen.go
tools/syz-trace2syz/proggen/proggen_test.go

trace2syz used to always add a null byte to strings.
This isn't correct behavior since we may end up writing null bytes to files.
The extra byte can affect system calls like ioctl$FS_IOC_ENABLE_VERITY. We now only add the byte for filenames.

tools/syz-trace2syz: only add null-byte for prog.BufferFilename

---

tools/syz-trace2syz/proggen/proggen.go
tools/syz-trace2syz/proggen/proggen_test.go

String buffers get the null byte added during generation. This means we need to add the null byte explicitly in trace2syz.

tools/syz-trace2syz/proggen: append 0 to string buffers

---

syz-manager/cover.go
syz-manager/html.go

On FreeBSD getVMOffset() always returned 0 instead of 0xffffffff.
This breaks the usage of addr2line. For now, just return always
0xffffffff on FreeBSD, since a more sophisticated logic doesn't
seem to be required by now.
Thanks to Dmitry for pointing out that this functions provides
the prefix address.

syz-manager: Improve the computation of getVMOffset() on FreeBSD

---

pkg/host/host.go
pkg/host/host_akaros.go
pkg/host/host_darwin.go
pkg/host/host_freebsd.go
pkg/host/host_fuchsia.go
pkg/host/host_linux.go
pkg/host/host_netbsd.go
pkg/host/host_openbsd.go
pkg/host/host_windows.go
syz-fuzzer/testing.go

Right now syz-fuzzer does a search through /proc/kallsyms for each syscall
to check whether it's supported. Do one search instead and save the results
to a map. This speeds up syscall detection ~60 times when testing arm64 kernel
on x86. Also add another search pattern for arm64 and add some logging.

fuzzer: speed up syscall support detection

---

pkg/host/host_linux.go

As pointed out my Mark Rutland, kallsyms entries have format of
`__ia32_sys_${NAME}` rather than `__ia32_${NAME}`. Fix the regexps.

fuzzer: fix syscall detection

---

executor/executor_bsd.h

Initialize syz data segment with protection allowed by PaX MPROTECT.
PROT_MPROTECT() registers future potential protection that is allowed
to be enabled in future.

Adapt os_init() to NetBSD with PaX MPROTECT

---

executor/gen.go

Disable executor/gen.go for NetBSD

---

tools/syz-trace2syz/proggen/proggen.go
tools/syz-trace2syz/proggen/proggen_test.go

strace incorrectly printed sin6_addr before sin6_flowinfo. To fix this, trace2syz added reorderStructFields() which swapped back the order. Incorrect orderings of structs is either a bug in strace or in our descriptions so we should fix the source rather than work around. We have submitted a [patch](https://lists.strace.io/pipermail/strace-devel/2019-January/008606.html) to fix the sockaddr_in6 decoding in strace (which should get accepted soon) so we can safely delete this function.

tools/syz-trace2syz/proggen.go: delete reorderStructFields()

---

executor/common_bsd.h
pkg/csource/generated.go

Setting the limit caused abnormal failure during early init on NetBSD.

Do not call setrlimit(2) for RLIMIT_AS

---

executor/common_bsd.h
pkg/csource/generated.go

NetBSD uses different uid/gid than FreeBSD/OpenBSD for the user
nobody. Instead of hardcoding the values, retrieve it from the
password entry database.
While there, switch to setuid(2) and setgid(2) calls as they are
good enough and portable. setresgid(2) and setresuid(2) aren't
available on NetBSD.

Adapt switching to user nobody to be more portable on BSDs

---

tools/syz-trace2syz/proggen/generate_unions.go
tools/syz-trace2syz/proggen/proggen_test.go

genSockaddrStorage() determines the correct sockaddr_storage union option when we
cannot identify the system call variant. We used to have custom logic per system
call which was not tested and is actually unnecessary. This patch deletes that
code and adds a test to make sure there are no regressions.

Deleting unnecessary code in genSockaddrStorage()

---

pkg/host/host_linux.go
vm/qemu/qemu.go

Miscellaneous fixes that I needed to get syzkaller working with kcov on ppc64le.
These have been lightly tested on a POWER8 KVM host I have access to. The kernel support for kcov hasn't landed upstream yet but I've sent a patch.

ppc64le fixes

---

tools/syz-trace2syz/proggen/call_selector.go
tools/syz-trace2syz/proggen/call_selector_test.go
tools/syz-trace2syz/proggen/proggen.go
tools/syz-trace2syz/proggen/proggen_test.go

Add support to accurately select variants for open and openat system calls. This is needed because in order to accurately select ioctl variants we need to use device resource types. The device resource types can only be created by syz_open_dev and openat variants.

tools/syz-trace2syz/proggen: add support for open, openat, syz_open_dev variants

---

sys/openbsd/init.go

This reverts commit 77c702cf1a02ef4bb695e9daa9339afb3cbd5d89.
A proper fix has instead been committed to [OpenBSD](https://github.com/openbsd/src/commit/650b9bc3abafbd3178268c3cae5b7a240d7f32b7).
See #932 for further details.

sys/openbsd: revert avoid /dev/fd node creation

---

tools/syz-trace2syz/proggen/proggen.go
tools/syz-trace2syz/proggen/proggen_test.go

trace2syz had trouble generating structs like sockaddr_storage_in6 which are wrappers around other structs like sockaddr_in6 because strace just decodes the wrapped struct (sockaddr_in6). This causes trace2syz to generate the addr field of sockaddr_storage_in6 from the af_family field of sockaddr_in6 which triggers an error. We now try and detect these cases and recursively generate the struct.

tools/syz-trace2syz/proggen: add support to generate structs like sockaddr_storage_in6

---

executor/executor_linux.h
pkg/host/host_linux.go
sys/linux/init.go

Use PC tracing mode when detecting KCOV_REMOTE_ENABLE support in the kernel.
Also fix kcov_remote_handle_usb argument.

kcov: some fixes for extra coverage

---

.travis.yml

14.04 has way too old gcc.
In particular this causes build failures like:
https://travis-ci.org/google/syzkaller/jobs/481342304
Switch to 16.04.

travis: switch to ubuntu 16.04

---

Makefile
pkg/csource/build.go
sys/targets/targets.go

See discussion in PR #942.
Extend support for optional flags in sys/targets
as this flag is not supported by gcc 5.
Make flags consistent across Makefile and pkg/csource.

Makefile: enable -Wunused-const-variable

---

executor/executor_bsd.h
pkg/host/host_openbsd.go

Let's wait until [this commit](https://marc.info/?l=openbsd-cvs&m=154797825521434&w=2) has appeared in openbsd/src this time.

kcov: enable FeatureComparisons on OpenBSD

---

syz-ci/syzupdater.go

This eases debugging when running syz-ci locally.

Have syz-ci print error on failure.

---

dashboard/config/openbsd-syzkaller.mp

Lets give this another try now that larger kernels can boot.

dashboard/config: enable witness on OpenBSD

---

pkg/report/openbsd.go
pkg/report/testdata/openbsd/report/11
pkg/report/testdata/openbsd/report/12

Possible now since the output is consistently [prefixed](https://marc.info/?l=openbsd-cvs&m=154850328128727&w=2)

pkg/report: improved witness handling

---

executor/executor_linux.h

It should be in number of words not in bytes.

executor: fix remote coverage area size

---

sys/targets/targets.go

The latter doesn't work on Raspberry Pi Zero.

sys: use -march=armv6 instead of -march=armv6t2

---

prog/checksum.go
prog/encodingexec_test.go

Make pseudo checksums depend (via csumUses) on the arg it requires for
calculation. Otherwise we fail to assign addrs to those args during encoding
for execution. Also add a test.

prog: fix checksum dependencies

---

dashboard/config/openbsd-syzkaller.mp

This option will print all lock acquisition paths once a lock violation
is identified by [witness](https://marc.info/?l=openbsd-cvs&m=154955230813384&w=2)

dashboard/config: enable WITNESS_LOCKTRACE on OpenBSD

---

pkg/report/openbsd.go
pkg/report/testdata/openbsd/report/6
tools/create-openbsd-vmm-worker.sh
vm/vmimpl/openbsd.go

A line length of 79 in the ddb output does not necessarily imply that the
following line is a continuation of the current line. Since there's no way
to distinguish between ordinary and continuation lines, it could end up
corrupting the report by joining two lines that are [disjoint](https://syzkaller.appspot.com/bug?extid=03f7377a9848d7d008c9)
Instead, disable line wrapping in ddb. If we want some kind of wrapping in
the future it's easier done by pkg/report.

openbsd: remove shorten report logic

---

tools/create-openbsd-gce-ci.sh

Two packages exist now and pkg_add can't choose on its own.

tools/openbsd: disambiguate gcc package name

---

pkg/instance/instance.go

We could probably do this for *bsd, but this change is what I was able to test.

pkg/instance: use gmake on FreeBSD as on OpenBSD

---

executor/common_fuchsia.h
executor/executor_fuchsia.h
pkg/csource/generated.go

expressive.
Fuchsia recently changed such that zx_vmar_map can't be declared
executable and writeable at the same time; use a new syscall for this
purpose.
Also made a few errors more informative.
cc @mvanotti

[fuchsia] Update syntax for making W+X memory regions; make errors more

---

pkg/build/fuchsia.go

We've once again changed the way you define a build via fx; update it in
Syzkaller too.

[fuchsia] Update fx arguments.

---

docs/freebsd/found_bugs.md

When committing the fix the the FreeBSD repo, I missed the line
stating that the issue was found by running syzkaller. So this
entry was missed...

Add missing entry

---

pkg/report/netbsd.go
pkg/report/testdata/netbsd/report/12
pkg/report/testdata/netbsd/report/6
pkg/report/testdata/netbsd/report/7

Now report bugs in the format : 
ASan: Unauthorized (read|write) in (x) syscall

pkg/report: Add better ASan bug parsing for NetBSD 

---

tools/syz-execprog/execprog.go

If the fault injection flags are not provided, but the log contains a
fault injection like this:
2017/08/12 17:16:04 executing program 5 (fault-call:4 fault-nth:5):
we fail to enable fault injection in ipc.Config. Fix it.

execprog: fix executing with fault injection

---

tools/create-image.sh

The list of packages to install is comma-separated, not space. This
fixes the "-f full" argument to actually install the expected packages.

create-image.sh: Fix "full" package list

---

pkg/report/netbsd.go
pkg/report/testdata/netbsd/report/12
pkg/report/testdata/netbsd/report/6

print the last function that executed the bug instead of the syscall that triggered it.

pkg/report: fix the error corrupting reports

---

syz-ci/syzupdater.go

syzupdater fails to report build errors because it is constructing the
dashapi client with the wrong parameters (it is mixing dashboardAddr
with dashboardClient).
This commit swaps the order of those parameters in syzupdater's
uploadBuildError function.
Fixes #1044

syz-ci: fix error reporting for syzupdater.

---

docs/freebsd/README.md
pkg/build/build.go
pkg/build/freebsd.go
pkg/build/netbsd.go
pkg/build/openbsd.go
pkg/report/freebsd.go
pkg/report/testdata/freebsd/report/4
pkg/vcs/freebsd.go
pkg/vcs/vcs.go

This is a minimal set of changes that I've used to get syz-ci to manage FreeBSD targets.
For now the FreeBSD bits in pkg/build only support building on FreeBSD. In the next several months I hope that we will be able to support cross-compilation on Linux.
To run syz-ci, I used the latest 13-current GCE image from freebsd-org-cloud-dev. The gmake, go, git and gcc packages must be installed. To create the base image used for FreeBSD workers, download the latest raw image from [1]. Boot it using qemu:
```
$ sudo pkg install qemu
$ mv FreeBSD-13.0-CURRENT-amd64.raw image
$ qemu-system-x86_64 -hda image
```
When the boot menu pops up, hit "3" to get to the loader prompt, and enter 'set console="comconsole"' and then 'boot' at the prompt. Once booted, add 'console="comconsole"' to …

Add missing bits needed for FreeBSD support in syz-ci.

---

pkg/build/build.go

This CL changes the supported vmType for fuchsia to be QEMU, instead of
GCE.
This was broken by commit b4e5a74e4, which changed the behavior of
getBuilder. It was part of a 6-commit PR trying to add support for
FreeBSD.
That commit has caused syzkaller to stop being able to build the fuchsia
image, getting the following error:
`kernel build failed: unsupported image type fuchsia/amd64/qemu`

pkg/build: fix getBuilder for fuchsia.

---

pkg/build/fuchsia.go

This CL splits the fx commands into two: one that runs `fx set` setting
the same arguments as before, and another one right after, running `fx
clean-build` to build fuchsia.
Recently[0], fuchsia made it impossible to run `fx clean-build`
specifying the arguments. Instead, one should run `fx set` before.
The benefit is that `clean-build` now preserves the build arguments
across runs. For syzkaller, it doesn't change anything though.
[0]: https://fuchsia-review.googlesource.com/c/fuchsia/+/262674

pkg/build: update fuchsia build commands.

---

.travis.yml
Makefile
docs/contributing.md
docs/executing_syzkaller_programs.md
docs/fuchsia/README.md
docs/linux/setup.md
docs/linux/setup_linux-host_android-device_arm64-kernel.md
docs/linux/setup_linux-host_isolated.md
docs/linux/setup_ubuntu-host_android-device_arm32-kernel.md
docs/linux/setup_ubuntu-host_qemu-vm_x86-64-kernel.md
pkg/build/akaros.go
pkg/build/fuchsia.go
pkg/vcs/vcs_test.go
prog/prog_test.go

Differences in code formatting between Go versions cause constant
problems for us (https://github.com/golang/go/issues/25161).
Currently we support 1.9 and 1.10. Switch to newer 1.11 and 1.12.
Fixes #1013

all: switch Go 1.12

---

pkg/build/freebsd.go
sys/targets/targets.go

A couple of minor changes; the main difference is that we now copy kernel.full out of the object tree.
With the FreeBSD diff posted here I get working coverage reports: https://reviews.freebsd.org/D19633
Assuming that lands, syzbot will be able to generate coverage reports once it pulls the update.

Make it possible to generate coverage reports on FreeBSD.

---

executor/common_fuchsia.h
pkg/csource/generated.go

The Fuchsia team is going to remove the `lib/fdio/util.h` library. They
have already moved all the functions to new header files.
I have seen that fuchsia uses `fdio_service_connect`, which has been
moved to the `lib/fdio/directory.h` header file.
This commit just changes the import path in the fuchsia executor, and in
the corresponding generated go file (I made that change by running `make
generate`).

[executor/fuchsia] update fdio import path.

---

pkg/vcs/fuchsia.go

This commit changes the fuchsia git repo to make it point to the main
repo instead of just "zircon".
Previously, zircon had its own git repo, so syzkaller had a wrapper that
would issue jiri commands for the whole fuchsia repo, but would just
report commits in the zircon repo.
Recently, fuchsia merged most of its repositories in just one big git
repo. So now, zircon is part of the fuchsia git repo. I think the code
continued working because the old zircon repo is still part of a git
repository, so git commands worked there.
The new code now doesn't have any special casing for Zircon, and now
(almost) everything is part of the fuchsia repo. The other repos are now
git submodules.

pkg/vcs: fix fuchsia's git repo directory.

---

tools/syz-execprog/execprog.go

handled looks no use in the `createConfig` function.

tools/syz-execprog: remove dead code

---

docs/fuchsia/README.md

This commit updates the documentation for fuchsia, updating both the fx
set commands as well as the syz-manager config example.
The invocation for the fx set command changed recently. The new command
requires the user to specify both the product and board (core.x64 and
core.arm64), as well as the build directory (otherwise everything gets
built into `out/default`).
The changes in the syz-manager config are for it to point to the right
files required to run a fuchsia vm.

docs/fuchsia: update fx set & paths in docs

---

pkg/build/fuchsia.go

This commit adds the "//bundles:tools" packages to the fuchsia build
used for syzkaller. This includes ssh tools, which includes scp.
Recently, Syzkaller broke for fuchsia because it was not able to find 
scp. Apparently, there was no recent change that removed scp from the 
default "core.x64" build: it has been already removed since at least a 
month. It is not clear why it broke right now.
TEST=I have tested this on syz-ci. Fuchsia is now able to pass the image
test.

pkg/build: Add ssh tools for fuchsia.

---

pkg/repro/repro.go

Final reproducers are crafty. Sometimes they just stop working.
In that case the detailed listings of the programs executed by syz-repro
are very helpful. Let's print them at the loglevel 3.

syz-repro: print detailed listings

---

docs/linux/setup.md

svn commit 231296 matches commit d29e939c63b71 ("Add fuzzing coverage support") in the gcc git. The change is part of gcc 6.1.0.
Replace the svn commit number with a gcc version which everyone can easily compare.
Related links: https://github.com/torvalds/linux/commit/58f4df3c1bde999574d3e66b20eb7ee796a2647e#diff-4552954e64a20391a1a3b5fd3e494bc3

Use gcc version number instead svn revision

---

pkg/ipc/ipc.go

We cannot create folders in other directories anymore, for now, we only
have access to create directories in `/data/`. This change is temporary as
we move to a component-based world.

pkg/ipc: use /data for storage in fuchsia.

---

Makefile

Recently[0][1], fuchsia moved some of the tools out of `//scripts`, into the
`//tools` directory. The go script was moved into
`//tools/devshell/contrib/go`.
This commit modifies the Makefile so that it references to the new go
binary.
[0]: https://fuchsia-review.googlesource.com/c/fuchsia/+/267708/
[1]: https://fuchsia-review.googlesource.com/c/fuchsia/+/267908/

Makefile: change go binary path for fuchsia.

---

executor/common_fuchsia.h
pkg/csource/generated.go

This commit modifies the common_fuchsia.h file changing the behavior of
the `syz_future_time function`. Before, the function used to have a switch
case that would fallthrough, making it always set the delta_ms to 10000.
The fix is to add a `break;` statement after each switch case.

executor: don't fallthrough in switches in fuchsia

---

executor/common.h
pkg/csource/generated.go

This commit moves the definition of the `syz_execute_func` after the
block of code that imports all the OS specific common headers.
This is required because after commit
dfd3394d42ddd333c68cf355273b312da8c65a51 `syz_execute_func` started
using the `NONFAILING` macro, which is defined in those header files for
each OS.
I also ran `make generate`.
TEST=I only tested that the executor works for Fuchsia with:
```shell
$ make executor TARGETOS=fuchsia TARGETARCH=amd64 SOURCEDIR=~/fuchsia
```

executor: move syz_execute_func after os imports.

---

AUTHORS
CONTRIBUTORS
sys/targets/targets.go

This fixes issues with targeting a 32 bit armhf machine. 
I notice before a user was testing on their Raspberry Pi Zero. Should armhf be a separate target?
sys/targets/targets.go: Bump armv6 to armv7 in arm target to enable compilation for armhf architecture.
pkg/host/host_linux.go: When running an unsupported architecture for kallsyms parsing, return instead of panic during kallsyms support check.

enable fuzzing on armhf

---

pkg/host/host_linux.go
pkg/host/host_test.go

pkg/host/host_linux.go: Add "arm" to kallsyms support test.
pkg/host/host_test.go: TestKallsymsParse(): Add entry to test arm kallsyms parsing support.

enable kallsyms parsing on arm

---

dashboard/config/openbsd-syzkaller.mp
dashboard/config/openbsd-syzkaller.sp

POOL_DEBUG is disabled during release, but we want it unconditionally
enabled.

dashboard/config: enable POOL_DEBUG on OpenBSD

---

executor/common.h
executor/common_linux.h
executor/executor.cc
pkg/csource/common.go
pkg/csource/generated.go
pkg/csource/options.go
pkg/csource/options_test.go
pkg/ipc/ipc.go
pkg/repro/repro.go
syz-fuzzer/fuzzer.go
tools/syz-execprog/execprog.go
tools/syz-prog2c/prog2c.go
tools/syz-stress/stress.go

Instead of always closing open fds (number 3 to 30) after each program,
add an options called EnableCloseFds. It can be passed to syz-execprog,
syz-prog2c and syz-stress via the -enable and -disable flags. Set the
default value is true. Also minimize C repros over it.

all: add optional close_fds feature to reproducers

---

dashboard/config/openbsd-syzkaller.mp
dashboard/config/openbsd-syzkaller.sp

This reverts commit 2fbd3aa9043e84cdce8328e5084a1fecc6ec5be3.
This unbreaks the build:
```
/syzkaller/managers/main/kernel/sys/arch/amd64/conf/SYZKALLER
/syzkaller/managers/main/kernel/sys/arch/amd64/conf/SYZKALLER:6: already have options `POOL_DEBUG'
```

Revert "dashboard/config: enable POOL_DEBUG on OpenBSD (#1113)"

---

pkg/build/fuchsia.go

Recently, fuchsia changed the build directory for zircon, now instead of
build-zircon, we have arch.zircon, where arch is x64 or arm64.

pkg/build: update zircon build directory.

---

executor/common_usb.h
executor/executor.cc
pkg/csource/generated.go

Allow 2000 ms of waiting time for syz_usb_connect and and the same time for
the whole program is this syzkall is present. Allow 200 ms of waiting time
for syz_usb_disconnect. Remove sleep from syz_usb_control_io.

executor: adjust waiting time for all usb syzcalls

---

executor/common_bsd.h
pkg/csource/generated.go

Improve the handling of packets by:
* setting the local MAC address.
* configuring the local IPv4 address with prefix /24.
* adding an entry in the arp cache for the remote IPv4 address.
* adding an entry in the IPv6 neighbour cache for the remote
IPv6 address.

executor: improve setup for packet handling on *BSD

---

executor/common_bsd.h
pkg/csource/generated.go

Not using `elif GOOS_freebsd` since it could cause breakage on other *BSDs
due to unused variables.
Regression introduced in commit c7c3f772 (executor: improve setup for packet
handling on *BSD).
/cc @tuexen @dvyukov @blackgnezdo

executor: unbreak on OpenBSD at runtime

---

pkg/repro/repro.go
pkg/repro/repro_test.go

Limit the amount of bisection chunks to 8. Going over this value probably
means that we are bisection a flaky crash, and continuing bisection would
just take a lot of time and likely produce no result.

repro: speedup bisection for flaky crashes

---

pkg/build/build.go
pkg/build/linux.go
pkg/build/linux_generated.go
tools/create-gce-image.sh

See #1084.
This currently uses the existing approach of installing a kernel into the disk image. Right now we only use qemu with ppc64le, which means we could load the kernel directly rather than needing to recreate the disk image for each kernel build which would be more efficient. But that's a project for a later time.

Support ppc64le kernel builds

---

pkg/report/linux.go
pkg/report/report.go
pkg/report/testdata/linux/report/379
pkg/report/testdata/linux/report/380

powerpc stack traces are printed a bit differently from x86 stack traces.
Adjust the regexes accordingly to cope with this format.
Signed-off-by: Andrew Donnellan <andrew.donnellan@au1.ibm.com>

pkg/report: Handle powerpc stack traces correctly

---

AUTHORS
CONTRIBUTORS
executor/executor.cc
executor/executor_akaros.h
executor/executor_bsd.h
executor/executor_fuchsia.h
executor/executor_linux.h
executor/executor_test.h
executor/executor_windows.h
pkg/csource/csource.go

In Windows, long is 32-bit data type even in 64-bit architecture.
Therefore, defining arg_t and using size_t in Windows can fix it.
Using size_t since there can be a future work to support 32-bit Windows.

executor: fix type size of syscall args in Windows

---

pkg/report/linux.go
pkg/report/testdata/linux/report/142
pkg/report/testdata/linux/report/22
pkg/report/testdata/linux/report/23
pkg/report/testdata/linux/report/236
pkg/report/testdata/linux/report/239
pkg/report/testdata/linux/report/24
pkg/report/testdata/linux/report/240
pkg/report/testdata/linux/report/249
pkg/report/testdata/linux/report/25
pkg/report/testdata/linux/report/341
pkg/report/testdata/linux/report/342
pkg/report/testdata/linux/report/374

This change makes the reporting code account for the skip patterns when
selecting the frame that is used in a title of a generic warning report.

report: improve warning titles

---

pkg/report/netbsd.go
pkg/report/testdata/netbsd/report/0
pkg/report/testdata/netbsd/report/2
pkg/report/testdata/netbsd/report/3
pkg/report/testdata/netbsd/report/4
pkg/report/testdata/netbsd/report/5

Some reports for page fault in supervisor mode do not go into a trap and hence get corrupted.
example - https://syzkaller.appspot.com/text?tag=CrashReport&x=136887a2c00000 and
https://syzkaller.appspot.com/text?tag=CrashReport&x=10836513200000

pkg/report: fix other NetBSD corrupted reports

---

pkg/host/host_linux.go
pkg/host/host_linux_test.go

On powerpc, the "stat" syscall is implemented by "sys_newstat" entry point.
This causes a test failure as we can't find "sys_stat" in kallsyms.
Add "stat" -> "newstat" to the kallsyms rename map to work around this.
Closes: #1083 ("pkg/host: TestSupportedSyscalls fails on ppc64le")
Signed-off-by: Andrew Donnellan <andrew.donnellan@au1.ibm.com>
----
I've had trouble testing this on arm/arm64, so if someone else could confirm I haven't broken those that would be great.

pkg/host: Add stat to kallsyms rename map

---

dashboard/config/openbsd-syzkaller.mp
dashboard/config/openbsd-syzkaller.sp

Makes interrupt priority level assertions fatal.

dashboard/config: enable SPLASSERT_WATCH on OpenBSD

---

tools/create-openbsd-gce-ci.sh

The previous default must have changed resulting in an apparent
failure to install siteXX.tgz. The observable symptom was:
`Package installation failed. Inspect install_log.`
Diagnosis and suggested fix by @mptre.

tools/create-openbsd-gce-ci.sh: explicitly specify sets location

---

tools/create-openbsd-vmm-worker.sh

Improves consistency (and speed).

tools/create-openbsd-vmm-worker.sh: set location to cd0

---

sys/openbsd/init.go
sys/openbsd/init_test.go

Writing to the raw root disk could lead to all kinds of corruptions[1].
[1] https://flak.tedunangst.com/post/syzkaller-found-a-bug

sys/openbsd: avoid raw root disk node creation

---

pkg/report/linux.go
pkg/report/testdata/linux/report/379
pkg/report/testdata/linux/report/386

Add __switch_to() to the skip list as requested. Also exclude `(unreliable)` stack frames which are often misleading and end up pointing to random symbols that may not even be functions.

PowerPC stack trace skipping

---

executor/executor_bsd.h
pkg/host/host_netbsd.go
tools/kcovtrace/kcovtrace.c

1. I have added the initial support for NetBSD. Patch currently works only if we restrict the number of threads to 1 - due to a slight issue with the kcov implementation.

executor/executor_bsd.h: Added basic Kcov support for NetBSD

---

pkg/csource/csource.go
prog/target.go
sys/openbsd/init.go

Providing additional info, especially regarding syscall arguments, in reproducers
can be helpful. An example is device numbers passed to mknod(2).
This commit introduces an optional annotate function on a per target basis.
Example for the OpenBSD target:
```
$ cat prog.in
mknod(0x0, 0x0, 0x4503)
getpid()
$ syz-prog2c -prog prog.in
int main(void)
{
syscall(SYS_mmap, 0x20000000, 0x1000000, 3, 0x1012, -1, 0, 0);
syscall(SYS_mknod, 0, 0, 0x4503); /* major = 69, minor = 3 */
syscall(SYS_getpid);
return 0;
}
```
Testing would be nice, but I couldn't figure out how-to go from `Prog` to `ExecCall`.

pkg/csource: annotate syscalls using comments in C reproducers

---

pkg/repro/repro.go

For extractProgSingle() lastEntries are already reversed, so no need to
call reverseEntries().
Also for extractProgBisect() there's no point in reversing the entries,
as the idea is to try connecting multiple programs in chronological order.
Fixes #1197

pkg/repro: don't double-reverse log entries

---

pkg/build/akaros.go

* Remove the environment variable: AKAROS_XCC_ROOT
(refer to commit: brho/akaros bdab8c3a)
* Add environment variable AKAROS_TOOLCHAINS which
points to the parent directory of the old AKAROS_XCC_ROOT.
(refer to commit: brho/akaro 62ec5c3c)
* Add "$AKAROS_TOOLCHAINS/x86_64-ucb-akaros-gcc/bin" to PATH.
Signed-off-by: Aditya Basu <mitthu@google.com>

pkg/build: update env variables for akaros

---

CONTRIBUTORS
pkg/host/host_linux.go

A nontrivial number of drivers require specific flags to openat. This pull request updates host_linux.go to first check if the openat has a constant that is specified by the .txt file, then attempts O_RDONLY, O_WRONLY, and O_RDWR.

Adding Support for .txt file openat

---

tools/kcovtrace/kcovtrace.c

It should be uint64_t as a 32 bit tool may be tracing a 64 bit kernel.

tools/kcovtrace: Fix cover type on FreeBSD and NetBSD

---

tools/kcovtrace/kcovtrace.c

Based on the output of clang-format.

tools/kcovtrace: Fix the format of kcovtrace.c

---

sys/openbsd/init.go
sys/openbsd/init_test.go

OpenBSD performs a strict validation of the RLIMIT_DATA soft limit
during memory allocation. Lowering the same limit could cause
syz-executor to run out of memory quickly. Therefore make sure to not go
lower than the default soft limit for the staff group.
This is one of the root causes of the high amount of reported "lost
connection to test machine".

sys/openbsd: sanitize setrlimit(RLIMIT_DATA) syscalls

---

sys/openbsd/init.go
sys/openbsd/init_test.go

Do not allow the stack to grow beyond the initial soft limit chosen by
syz-executor. Otherwise, syz-executor will most likely not be able to
perform any more heap allocations since they majoriy of memory is
reserved for the stack.
This is one of the root causes of the high amount of reported "lost
connection to test machine".

sys/openbsd: sanitize setrlimit(RLIMIT_STACK) syscalls

---

sys/openbsd/init.go
sys/openbsd/init_test.go

Locking down future mappings will most likely cause syz-executor to run
out of memory.
This is one of the root causes of the high amount of reported "lost
connection to test machine".

sys/openbsd: sanitize mlockall syscalls

---

sys/openbsd/init.go
sys/openbsd/init_test.go

The sanitizer fails to sanitize programs like the following:
```
setrlimit(0x10000000000002, &(0x7f0000000080))
```
... due to presence of the most significant bit. Therefore mask of all
bits that cannot form a valid rlimit resource.
This is one of the root causes of the high amount of reported "lost
connection to test machine".

sys/openbsd: correct setrlimit resource detection

---

docs/openbsd/setup.md

The order of arguments passed to vmctl was recently changed: options comes
first followed by positional arguments.

docs/openbsd: correct order of vmctl arguments

---

pkg/report/linux.go

No tests yet to not disclose the bugs.
@ramosian-glider

pkg/report: add KMSAN kernel-usb-infoleak title regex

---

pkg/report/netbsd.go
pkg/report/netbsd_test.go

missed a 'netbsd:' in front of function names for symbolization.

pkg/report: fix error in report symbolization

---

docs/linux/setup_linux-host_qemu-vm_arm64-kernel.md

The sneaky '“' character causes errors when copy-pasting snapshots of the documentation. Solved with s/“/"/g.

docs/linux/qemu-arm64: fix copy/paste with non-ASCII character

---

docs/linux/setup_linux-host_android-device_arm64-kernel.md
docs/linux/setup_linux-host_isolated.md
docs/linux/setup_linux-host_qemu-vm_arm-kernel.md
docs/linux/setup_linux-host_qemu-vm_arm64-kernel.md
docs/linux/setup_ubuntu-host_android-device_arm32-kernel.md
docs/linux/setup_ubuntu-host_odroid-c2-board_arm64-kernel.md
docs/linux/setup_ubuntu-host_qemu-vm_x86-64-kernel.md

In the various linux build instructions, add pointers to the main
doc with instructions for building syzkaller.
These instructions were present before commit d23e90a7b44b ("all:
switch to Go 1.12"). They were duplicated across files. Since the
commit the instructions are in one place. Make it easier to find
them from the platform-specific setup guides.
Also clarify in the x86_64 guide that using a precompiled compiler
from the supplied list is optional if the distribution provided
compiler is recent enough. Before commit d28f4ce ("Update
setup_ubuntu-host_qemu-vm_x86-64-kernel.md") the file had explicit
build instructions. Those are no longer needed.
Before sending a pull request, please review Contribution …

docs/linux: add references to syzkaller build instructions

---

executor/common.h
pkg/csource/generated.go

On OpenBSD, the executor sometimes manages to set the memory resource
limit 0 causing any following memory allocation to fail. Since threads
are potentially created from such a thread which cannot allocate any
memory, the executor will exit non-zero which in turn will cause
false-positive panics to be reported. For more info see the
discussion in PR #1243.
Instead, make any errors during thread creation non-fatal. If the
executor runs of out available threads it will exit zero.

executor: make errors during thread creation non-fatal

---

executor/common_usb.h
pkg/csource/generated.go

The kernel API has changed and now differentiates between IN and OUT control requests.

executor: update USB fuzzing code to use new kernel API

---

executor/common_usb.h
pkg/csource/generated.go

We might not have any string descriptors provided at all, use a hardcoded string in this case.

executor: fix out-of-bounds in USB fuzzing code

---

vm/qemu/qemu.go

Currently the 'image_device' config option in qemu.go doesn't properly
support the modern '-drive' argument for describing qemu hard disks.
In fact the various old ways to define qemu drives all boil down to
the common form '-drive if=TYPE,bus=BUS,unit=UNIT,OPTS...'
For example '-hda img' is equivalent to '-drive index=0,media=disk,file=img'.
Let's make the 'image_device' config option support both forms.
Signed-off-by: Alexander Popov <alex.popov@linux.com>

qemu: support advanced hard drive configurations

---

prog/minimization.go
prog/minimization_test.go

Not sure how to test this though. One option would be to make sure that either `triedPaths` or `p0` has changed when we do `goto again`.

prog: fix updating triedPaths when minimizing resources

---

pkg/cover/report.go
pkg/mgrconfig/config.go
pkg/mgrconfig/load.go
pkg/report/akaros.go
pkg/report/freebsd.go
pkg/report/fuchsia.go
pkg/report/gvisor.go
pkg/report/linux.go
pkg/report/netbsd.go
pkg/report/netbsd_test.go
pkg/report/openbsd.go
pkg/report/openbsd_test.go
pkg/report/report.go
pkg/report/stub.go
syz-manager/cover.go
syz-manager/html.go
tools/syz-cover/syz-cover.go

1. Added a new config parameter - KernelBuildSrc (Defaults to KernelSrc if not added)
2. Now trims prefixes in pkg/cover based on KernelBuildSrc
3. Pass the KernelBuildSrc to all the pkg/report constructors
4. Modify the report shortening to be based on KernelBuildSrc instead of KernelSrc 

pkg/cover: fix prefix computation

---

vm/gvisor/gvisor.go

$ runsc -h
...
-alsologtostderr=false: send log messages to stderr
...
Now gvisor doesn't send log messages on stderr by default,
and if we want to see these messages, we need to specify the
alsologtostderr option.

gvisor: run runsc with the alsologtostderr option

---

dashboard/config/openbsd-syzkaller.mp
dashboard/config/openbsd-syzkaller.sp

In order to assert that vnodes are locked when needed.

dashboard/config: enable VFSLCKDEBUG on OpenBSD

---

dashboard/app/bug.html
dashboard/app/templates.html

* Introduce "bisect_results" inside templates.html to take in a uiJob and shows its contents.
* Modify bug.html to use "bisect_results" to show BisectCause and BisectFix uiJob.

dashboard/app: remove duplicate code inside bug.html template

---

.gitignore
.travis.yml
README.md
fuzzit.sh

The fuzzers now run on every new code that is pushed to master
Regression using the generated corpus from the above step is
run locally in the travis. This should fail the travis if new
or old bugs are introduce and thus help catch bugs earlier.
To reproduce locally you can run
./fuzzit create job --local syzkaller/target-name $PATH_TO_LIBFUZZER_TARGET
@dvyukov

fuzzit.sh: migrate syzkaller to new org and introduce regression

---

dashboard/app/entities.go
dashboard/app/index.yaml
dashboard/app/main.go

As a result all bugs from the ci2-upstream-usb instance can be viewed here:
https://syzkaller.appspot.com/upstream?manager=ci2-upstream-usb

dashboard: allow to view bugs happened on a particular manager

---

sys/targets/targets.go

Recently fuchsia got rid of the buildtools/ folder, and moved some of
the stuff into the prebuilt directory.
See https://fuchsia-review.googlesource.com/c/fuchsia/+/305379 for more
info.

sys/targets: Change CCompiler path for fuchsia.

---

pkg/csource/common.go
pkg/csource/options.go

Running syz-runtest for NetBSD fails due to missing check for NetBSD. This patch seems to fix the issue.

pkg/csource: fix failing syz-runtest for NetBSD

---

pkg/report/linux.go
pkg/report/testdata/linux/report/403
pkg/report/testdata/linux/report/404

MAX_STACK_TRACE_ENTRIES crash reports caused by a particular issues can come
from any part of the kernel, so bucketing them based on the stack trace is
pointless and only creates duplicate bug reports.

pkg/report: revert bucketing MAX_STACK_TRACE_ENTRIES reports

---

pkg/report/gvisor.go

If syzkaller creates >8128 active threads, then we will exceed this goroutine limit.

pkg/report: ignore exceeded race limits

---

pkg/report/openbsd.go
pkg/report/testdata/openbsd/report/16

Reports from witness regarding returning to userspace with locks held is not
unique enough, causing all lock leaks to be grouped under the same bug.
Instead try to extract the name of syscall where the first held lock was
grabbed.
While here, shorten the title a bit.

pkg/report: improve witness extraction for OpenBSD

---

prog/decl_test.go
prog/resources.go
prog/target.go
prog/types.go

When we build a list of resource constructors we over and over iterate through
all types in a syscall to find resource types. Speed it up by iterating only
once to build a list of constructors for each resource and then reuse it.
This significantly speeds up syz-exeprog startup time on Raspberry Pi Zero.

prog: speed up resource ctors detection

---

dashboard/app/bisect_test.go
dashboard/app/jobs.go
dashboard/app/mail_bisect_result.txt
dashboard/app/reporting_email.go
dashboard/dashapi/dashapi.go
pkg/html/html.go

* Modify mail_bisect_result.txt to allow for sending fix bisection results.
* Modify BisectResult to have a Fix field; introduce selectBisect for use within the template for choosing between BisectCause/BisectFix fields.
* Modify bisectFromJob() to return BisectResult with Fix field set if relevant.
* Modify the tests inside bisect_test.go to account for bisect fix related reporting emails.
* Modify incomingMail() to ignore any emails from syzbot itself.

dashboard/app: allow reporting of BisectFix results

---

docs/linux/setup_ubuntu-host_qemu-vm_x86-64-kernel.md

Commands like ```make oldconfig``` will discard configurations like ```CONFIG_KCOV=y``` when the default gcc is out of date.

add CC="$GCC/bin/gcc" to setup_ubuntu-host_qemu-vm_x86-64-kernel.md

---

dashboard/app/bisect_test.go
dashboard/app/mail_bisect_result.txt

* Fix a typo in mail_bisect_result.txt related to the "syz fix:" line.
* Improve the description to make it clearer why sending a "syz fix:" is important.

dashboard/app: fix typo and change reporting description

---

executor/common_fuchsia.h
pkg/csource/generated.go
pkg/ipc/ipc.go

syz_mmap is a pseudo-syscall that can be used by syzkaller in fuzzing
programs, however, it is also used to setup the environment for
syz-executor. syz-executor already checks the return value[0] when it is
used for setting up the environment, so it doesn't make sense for the
function to crash (most probably, in a fuzzing program it will be called
with arguments that would make it fail).
The previous behavior was causing a bunch of "Lost connection to test
machine" syzkaller crashes which were meaningless. An example of a
program in which syz_mmap would crash would be any program in which the
handle to the root vmar is closed before calling syz_mmap.
The other change reuses the logic for sending the output back from
syz-executor to syz-fuzzer that forkserver oses use: reading it …

don't crash on syz_mmap failures in fuchsia + send output of syz-executor for non-forkserver oses.

---

pkg/osutil/osutil_linux.go

pkg/osutil/osutil_linux.go:44:13: cannot use info.Totalram (type uint32) as type uint64 in return argument

pkg/osutil: fix arm build

---

executor/executor.cc
sys/targets/targets.go

Move accessing syscalls array to check for USB syscalls after we validate
the call_num value (it can be e.g. instr_copyin/out).

executor: fix out-of-bounds access to syscalls array

---

sys/targets/targets.go

sys/targets: add ASAN compiler flag to optional

---

Makefile
prog/encoding.go
prog/prog_test.go
tools/syz-expand/expand.go

The syz-expand tools allows to parse a program and print it including all
the default values. This is mainly useful for debugging, like doing manual
program modifications while trying to come up with a reproducer for some
particular kernel behavior.

tools: add syz-expand

---

pkg/vcs/git.go
pkg/vcs/git_repo_test.go

OpenBSD uses cvs and does not enforce the standard Git convention for
commit messages of putting a summary followed by a new line and body.
If such commit[1] contains a `Reported-by` header, it's currently not
detected. Instead, if the body is empty try to extract data from the
commit summary.
[1] https://github.com/openbsd/src/commit/bdbfbec5cea84d24d6a598cf1e63dbdb10e8331a

pkg/vcs: handle git commits without a body

---

pkg/report/linux.go
pkg/report/testdata/linux/report/422

tty_unregister_device looks generic enough, add to ignore list.

pkg/report: improve USB reports

---

pkg/report/openbsd.go
pkg/report/testdata/openbsd/report/18

Some reports[1] does not include a symbol but rather an address in the
"Stopped at" line.
[1] https://syzkaller.appspot.com/bug?id=3e44d0b128fd8d6826e4d0044baadcfc02ba7125

pkg/report: improve uvm_fault reports on OpenBSD

---

executor/common.h
executor/common_linux.h
executor/executor_linux.h
pkg/csource/common.go
pkg/csource/generated.go
pkg/csource/options.go
pkg/host/host.go
pkg/host/host_linux.go
tools/syz-prog2c/prog2c.go

By default, the current KCSAN .config does not enable KCSAN during boot,
since we encounter races during boot which would prevent syzkaller from
ever executing.
This adds support to detect if KCSAN is available, and enables it on the
fuzzer host.
---
Tested and works. Let me know if anything is missing. Thanks!

executor, host, csource: Add support to enable KCSAN

---

dashboard/app/bug.html
dashboard/app/jobs_test.go
dashboard/app/main.go
dashboard/app/reporting.go
dashboard/app/templates.html

When fix bisections fail due to crash on HEAD, the LastTime of the bug is updated so that fix bisection will be retried. However, this change alone might cause confusion to the viewer as there is no information on the UI about what the crash corresponding to LastTime is.
Fix this by listing all fix bisections if the bug.BisectFix is set to BisectNot.
Closes: #1366

dashboard/app: show fix bisections on bug web UI

---

executor/common_linux.h
pkg/csource/generated.go
pkg/host/host_linux.go

The push of this needs to be synchronized with the update of KCSAN.
Once I merge this, I will immediately have to push the new KCSAN (which also includes blacklisting functions from reports).
A follow-up patch will add support for blacklisting functions.

Change KCSAN info file to debugfs

---

pkg/host/host_netbsd.go

There is a problem with the image. Until the problem will be resolved,
disable the feature as it causes premature death of the syzbot setup.

Disable checkFeature[FeatureNetworkInjection] for NetBSD

---

sys/targets/targets.go

Due to issues with ASLR + ASan on ppc64le (see #1446), add the -no-pie
flag to the test target so tests will pass.
-----
@RashmicaG has tested this, it works around our problems for now

sys/targets: Disable PIE/ASLR when building tests

---

pkg/report/linux.go
pkg/report/testdata/linux/report/431

Fix a few regexes so that we handle kernel data access BUGs correctly on ppc64le

pkg/report: ppc64le fixes

---

AUTHORS
CONTRIBUTORS
tools/create-image.sh

The usage of current create-image.sh:
```
./create-image.sh -d=stretch -f=minimal --add-perf
The options are in the following:
-d, --distribution         Set on which debian distribution to create
-f, --feature              Check what packages to install in the image, options are minimal, full
-s, --seek                 Set img size, default 2047(2G)
-p, --add-perf             Add perf support with this option enabled
The default image size may too small(2G) in some debugging scenarios, so change it to configurable.

 tools/create-image.sh: add a new option seek

---

vm/bhyve/bhyve.go
vm/gce/gce.go
vm/vmimpl/freebsd.go

The FreeBSD kernel debugger can provide more information when the
kernel panics. Add support to bhybe and gce to print this information.

vm: Get debug information when FreeBSD on panics

---

pkg/bisect/bisect.go
pkg/bisect/bisect_test.go
pkg/build/build.go
pkg/build/testlinux.go
pkg/instance/instance.go
pkg/vcs/git.go
pkg/vcs/git_repo_test.go
pkg/vcs/linux.go
pkg/vcs/test_util.go
pkg/vcs/testos.go
pkg/vcs/vcs.go
tools/syz-testbuild/testbuild.go

(note: incomplete change)
Refactor existing code as follows:
* Move reusable test utility functions from git_repo_test.go to pkg/vcs/test_util.go and make them exported.
* Split Run() into Run()+runImpl().
* Change type of bisect.go:env.inst to `instance.BuilderTester`. Change usage inside syz-testbuild/testbuild.go accordingly.
* Move most of linux.PreviousReleaseTags() into vcs/git.go as git.previousReleaseTags().
Introduce the following changes:
* instance.BuilderTester is an interface with methods
BuildSyzkaller()
BuildKernel()
Test()
NewEnv() now returns this interface.
* type testEnv implements instance.BuilderTester.
* type testBuilder implements builder interface. Add a entry into table inside pkg/build/build.go:getBuilder() to return testBuilder object.

pkg/bisect: add initial testing support for cause bisection

---

executor/common_linux.h
executor/executor.cc
pkg/csource/generated.go
pkg/report/report.go
pkg/report/report_test.go
pkg/report/testdata/linux/report/427
pkg/report/testdata/linux/report/428
pkg/rpctype/rpctype.go
syz-fuzzer/fuzzer.go
syz-manager/manager.go
syz-manager/rpc.go

This adds support to add frames that have already been in data races, to
the KCSAN report blacklist.

syz-fuzzer, executor: Add support for blacklisting data race frames

---

pkg/ast/ast.go
pkg/ast/walk.go
pkg/compiler/check.go
pkg/compiler/testdata/all.txt

This pull request fixes a bug in typedef checks: the root node was never visited. `Node.Walk()` is also unexported as `ast.Recursive` and `ast.PostRecursive` should be used instead to prevent this error from happening.

Visit root node during typedef checks

---

pkg/report/openbsd.go
pkg/report/testdata/openbsd/report/21

This panic is not to interesting since the intended behavior is to panic and
it requires root due to usage of mknod(2).

pkg/report: suppress fifo_badop reports on OpenBSD

---

pkg/csource/options.go

Remove a check that was mistakenly added with devlink_pci feature and is
duplicate of the existing check.

pkg/csource: remove duplicate check

---

dashboard/app/bisect_test.go
dashboard/app/mail_bisect_result.txt
pkg/bisect/bisect.go
pkg/bisect/bisect_test.go
syz-ci/jobs.go
tools/syz-bisect/bisect.go

When fix bisections fails due to a crash on HEAD, the dashboard needs to keep track of which commit the crash occurred at. In order to do this, send correct commit information to the dashboard.
* Modify Run() to return the commit object when a failure occurs on oldest release (for BisectCause) and latest release (for BisectFix).
* Modify bisect() to set appropriate fields in dashapi.JobDoneReq.Build (KernelCommit, KernelCommitDate, KernelCommitTitle).
* Modify the mail_bisect_result.txt template to be clearer on what BisectResult.KernelCommit represents.  Modify tests in bisect_test.go to accommodate the changes in the templates.
Closes: #1367

syz-ci: send build info for failed bisections

---

pkg/csource/csource.go

Constant 64-bit arguments to the variadic syscall(2) must have their
width specified explicitly.  In practice this is not necessary most of
the time, but on amd64/freebsd with clang the compiler can and does
store the constant 32-bit value to the stack, leaving garbage in the
upper 32 bits.
This makes C reproducers somewhat uglier, but I see no other solution.

pkg/csource: Force promotion of 64-bit constant values

---

pkg/report/netbsd.go
pkg/report/testdata/netbsd/report/12

Handle __asan strings in backtraces.

Correct parsing of Kernel ASan reports

---

tools/syz-usbgen/usb_ids.patch

The patch doesn't properly work on some kernels, some ids might not be printed.

tools/syz-usbgen: update patch to dump usb ids

---

executor/common_linux.h
pkg/csource/generated.go

Fixes the issue caused by PR#1496

executor: consider NLMSG_DONE type in netlink_send_ext()

---

executor/common_linux.h
pkg/csource/generated.go

Fix for #1508
stdbool.h is required by initialize_devlink_ports(): true define.
fcntl.h is required by initialize_devlink_pci(): O_RDONLY define.
Signed-off-by: Denis Efremov <efremov@linux.com>

executor: add missing includes

---

executor/common_linux.h
executor/common_usb.h
pkg/csource/generated.go

When USB_DEBUG is enabled, syzkaller crashes on unknown USB requests.
This helps to find missing descriptions for particular USB classes.

executor: extend USB debug messages

---

executor/common_linux.h
pkg/csource/generated.go

gVisor doesn't support netdevsim and NETLINK_GENERIC.
Without this fix, sys-executor always fails:
E openat(AT_FDCWD, /sys/bus/netdevsim/new_device, ...)
X openat(AT_FDCWD, /sys/bus/netdevsim/new_device, ...) = 0x0 errno=2
E socket(AF_NETLINK, SOCK_RAW|0x0, NETLINK_GENERIC)
X socket(AF_NETLINK, SOCK_RAW|0x0, NETLINK_GENERIC) = 0x0 errno=93
E write(0x2 host:[3], "socket(AF_NETLINK) failed\n", 0x1a)
X write(0x2 host:[3], ..., 0x1a) = 0x1a (2.767µs)
E write(0x2 host:[3], " (errno 93)\n", 0xc)
X write(0x2 host:[3], ..., 0xc) = 0xc (2.729µs)
E exit_group(0x43)
X exit_group(0x43) = 0x0 (900ns)
Cc: @jpirko 
Fixes: f350e2dc1f59 ("executor: rename devlink port netdevices to defined names")

Call initialize_devlink_ports only when a device has been created

---

.gitattributes

This pull request hides all generated files in pull requests, until #1291 is addressed. This feature is documented on [the github-linguist repository](https://github.com/github/linguist#generated-code). You can preview this change on [a small fork I created](https://github.com/pchaigno/syzkaller-tmp/pull/2).

.gitattributes: hide generated files

---

dashboard/config/netbsd-kmsan.config
pkg/build/netbsd.go
pkg/report/netbsd.go

KMSan requires building the kernel with Clang. 
I have made a rough patch which uses the Compiler parameter in the mgrconfig.

pkg/build: Add support to build the NetBSD kernel with KMSan

---

pkg/vcs/git.go
pkg/vcs/git_test_util.go
pkg/vcs/vcs.go

If you try to run git-using tests while the GIT_DIR environment variable
(and GIT_WORK_TREE, etc) happens to be set, the tests are going to do fun
and exciting things on a repository that isn't the test repository it tries
to set up.
As it turns out, if you try to run "make test" using git rebase -x, you'll
end up with GIT_DIR set to the syzkaller tree. Hilarity ensues.
Unset GIT_DIR, GIT_WORK_TREE and a few other environment variables when
invoking git - that way it'll default to looking at the working directory
that we have given it, which is what we expect.

pkg/vcs: Unset various git environment variables when invoking git

---

dashboard/config/openbsd-syzkaller.mp
dashboard/config/openbsd-syzkaller.sp

Recently introduced used to validate correctness of kqueue event lists.

dashboard/config: enable KQUEUE_DEBUG on OpenBSD

---

dashboard/config/kconfiglib-merge-usb-configs.py
dashboard/config/util.sh

Currently the config extraction script can produce an incorrect result, when
one of the configs enables a particular config option, but some other one
doesn't. This change fixes the issue.

dashboard/config: update USB config extraction

---

pkg/cover/report.go

PC from the target is address of "jal __sanitizer_cov_trace_pc" + 8.
E.g. case below has address ffffffff80b4eec4 in PC
ffffffff80b4eebc:       jal     ffffffff80232080 <__sanitizer_cov_trace_pc>
ffffffff80b4eec0:       nop
ffffffff80b4eec4:       move    a1,s0

pkg/cover: Fix PreviousInstructionPC for MIPS64LE

---

vm/isolated/isolated.go

Old isolated.go cannot do hard reset the target device when the target device is stuck,
because it used SSH command to reboot.
New isolated.go can reboot the target device using USB hub,
so it can reboot the device when its kernel is crashed during fuzzing.
It also doesn't require 'CGO' like odroid.go

vm/isolated: update isolated vm

---

executor/common_usb.h
pkg/csource/generated.go

To match the kernel uapi headers.

executor: provide explicit values for usb_raw_event_type

---

.github/workflows/main.yml

Separated build fuzzers and run fuzzers actions. This change needs to be reflected in the workflow file. This should make the bug detected logs clear and not full with useless build information.

Update workflow to reflect new CIFuzz format

---

.github/workflows/main.yml

This change to CIFuzz will notify users when a bug was found in there pull request. It will also upload a directory containing the stack trace and test case that caused to bug. Hopefully will mitigate confusion in situations like https://github.com/google/syzkaller/pull/1590

CIFuzz: Surface error logs and test case on failure

---

.github/workflows/main.yml

This change necessary to keep in sync with the CIFuzz action config. Sorry for the inconvenience, and thanks for dog fooding CIFuzz!

Update CIFuzz .yml file

---

docs/linux/setup_linux-host_isolated.md
vm/isolated/isolated.go
vm/isolated/isolated_test.go

(WIP PR)
Add support for post_repair_script:
* Modify Config{} to contain PostRepairScript.
* Allow repair() to execute a post_repair script after reboot. This script executes on the host and expects ssh arguments(user,addr,port,key,options) to be set the environment variable $SSHARGS.
Add pstore support:
* Modify Config{} to contain Pstore.
* Modify Diagnose() to reboot the DUT and fetch pstore logs, conditional on inst.cfg.Pstore.
* Add readPstoreContents().
* Allow clearing previous pstore logs upon Create() and after use inside readPstoreContents().
* Fetching pstore crashlogs relies on reliably getting lost connection on DUT reboot. Use "ServerAliveInterval=6 ServerAliveCountMax=5" ssh options when running syz-fuzzer with Pstore support enabled.
Allow passing pstore contents into …

vm/isolated: add initial support for fuzzing chromebooks

---

executor/common_linux.h
pkg/csource/generated.go

NETLINK_GENERIC isn't supported in gVisor.
Fixes: c5ed587f4af5 ("wireguard: setup some initial devices in a triangle")

executor: don't exit if NETLINK_GENERIC isnt' supported

---

sys/openbsd/ipc.txt
sys/syz-extract/openbsd.go

While working on something else, I noticed that syz-extract was currently broken on OpenBSD. Best reviewed commit by commit.

sys/syz-extract: broken on OpenBSD

---

pkg/vcs/vcs.go
syz-fuzzer/testing.go

When running with Go 1.14, I'm getting a couple golangci-lint errors which this pull request fixes. See commits for details.

Fix a few golangci-lint errors

---

pkg/report/openbsd.go
pkg/report/testdata/openbsd/report/28

In order to avoid treating the following diagnostic printf as a panic[1]:
vmx_mprotect_ept: uvm_fault returns 14, GPA=0x200000
[1] https://syzkaller.appspot.com/bug?id=25f3ef919bf9f5d8a89e13b1ba5fec8ca56334be

pkg/report: make uvm_fault parsing more strict on OpenBSD

---

pkg/build/netbsd.go

Remove '-u' option for clean builds. Increase the timeout to accommodate this change.

pkg/build: remove '-u' option for NetBSD build and increase timeout

---

vm/vmimpl/openbsd.go

vm/.../openbsd: get back traces of the first two cpus.

---

pkg/compiler/check.go
pkg/compiler/compiler.go
pkg/compiler/gen.go
pkg/compiler/types.go
pkg/host/syscalls_linux.go
prog/analysis.go
prog/any.go
prog/any_test.go
prog/checksum.go
prog/encoding.go
prog/hints_test.go
prog/minimization.go
prog/mutation.go
prog/prog.go
prog/rand.go
prog/size.go
prog/target.go
prog/types.go
prog/validation.go
sys/linux/init.go
sys/linux/init_alg.go
sys/linux/init_vusb.go
sys/targets/common.go
sys/windows/init.go
tools/syz-check/check.go
tools/syz-trace2syz/proggen/call_selector.go
tools/syz-trace2syz/proggen/generate_unions.go
tools/syz-trace2syz/proggen/proggen.go

Remvoe FieldName from Type and add a separate Field type
that holds field name. Use Field for struct fields, union options
and syscalls arguments, only these really have names.
Reduces size of sys/linux/gen/amd64.go from 5665583 to 5201321 (-8.2%).
Allows to not create new type for squashed any pointer.
But main advantages will follow, e.g. removing StructDesc,
using TypeRef in Arg, etc.
Update #1580

prog: introduce Field type

---

pkg/compiler/compiler.go
pkg/compiler/compiler_test.go
pkg/compiler/gen.go
pkg/compiler/types.go
prog/any.go
prog/prio.go
prog/prog_test.go
prog/rand_test.go
prog/resources.go
prog/rotation.go
prog/target.go
prog/types.go
sys/syz-sysgen/sysgen.go
tools/syz-check/check.go

Remove StructDesc, KeyedStruct, StructKey and all associated
logic/complexity in prog and pkg/compiler.
We can now handle recursion more generically with the Ref type,
and Dir/FieldName are not a part of the type anymore.
This makes StructType/UnionType simpler and more natural.
Reduces size of sys/linux/gen/amd64.go from 5201321 to 4180861 (-20%).
Update #1580

prog: remove StructDesc

---

vm/vmimpl/freebsd.go

Right now, kernels are not build with KTR support, so don't
run show ktr. Add showing information about zones like vmstat -z
would show.

vm/vmimpl: Don't show ktr, but uma on FreeBSD

---

sys/targets/targets.go

gmake test is failing on FreeBSD since switching to clang.
To address this:
* use g++ as the C preprocessor for now.
* use a C compiler for compiling C sources and add -lc++ when
compiling executor.cc. Without this, clang warns about
using a C++ compiler for compiling C code.
* some test configs add -no-pie, which is not used by clang.
Add -Wno-unused-command-line-argument to silence a warning
* when test compiling, clang warns about remove_dir() in
executor/common.h. It wants static inline void remove_dir()
instead of static void remove_dir(). Silence this warning
by adding -Wno-unneeded-internal-declaration …

sys/targets: fix tests when building on FreeBSD

---

executor/common_bsd.h
pkg/csource/generated.go

`SYZ_USB` must be for `setup_usb()` only, got it wrong the first time

executor: fix a USB define on NetBSD

---

pkg/build/netbsd.go

`MAKEDEV` may not be up to date in the instances

pkg/build/netbsd: use mknod rather than MAKEDEV

---

pkg/cover/report.go
pkg/cover/report_test.go
sys/targets/targets.go
syz-manager/cover.go
syz-manager/html.go
syz-manager/manager.go
tools/syz-cover/syz-cover.go

Test various combinations of no debug info,
no coverage instrumentation, no PCs, bad PCs, good PCs,
and what errors we produce for these.
Also implement support for cross-arch reports:
prefix objdump with cross-compile prefix
(e.g. aarch64-linux-gnu-objdump instead of objdump).

pkg/cover: add test for report generation

---

pkg/build/fuchsia.go

This commit makes syzkaller build the kasan variant of fuchsia by
default.
Support for kernel address sanitizer has landed in fuchsia since commit
`54c5edfc37afe7294256552cefefca64c6ce7e94`[0].
[0]: https://fxrev.dev/383323

pkg/build/fuchsia: Enable KASAN by default.

---

executor/common_linux.h
pkg/csource/generated.go

The issues is only present with verbose debugging enabled.
```
executor/common_linux.h: In function ‘void netlink_device_change(nlmsg*, int, const char*, bool, const char*, const void*, int, const char*)’:
executor/common_linux.h:380:7: error: ‘%s’ directive argument is null [-Werror=format-overflow=]
380 |  debug("netlink: device %s up master %s: %s\n", name, master, strerror(err));
```

executor: fix printing null master in netlink_device_change

---

CONTRIBUTORS
syz-manager/manager.go
syz-manager/rpc.go
syz-manager/stats.go

Originally, syz-manager confusingly logs corpusSignal as "cover".
Change syz-manager's logging to output corpusSignal, corpusCover and maxSignal.
Add a field in Stats to store maxSignal.

syz-manager: add detailed coverage logging

---

dashboard/app/bisect_test.go
dashboard/app/entities.go
dashboard/dashapi/dashapi.go
syz-ci/jobs.go

Currently only ignores the commit that adds the Raw Gadget interface.
Requested here:
https://groups.google.com/g/syzkaller-bugs/c/sZUeGC3Fh-o/m/t_5cKPrMAQAJ

dashboard, syz-ci: add blacklist for bisection results

---

pkg/runtest/run.go

HostFuzzer targets require that we cross-compile the csource tests and
then copy them to the target system. The code to copy files is
currently missing from syz-runtest; also, at least for Fuchsia (which
uses HostFuzzer mode), cross-compiling is non-trivial.

syz-runtest: disable csource tests for HostFuzzer targets

---

pkg/repro/repro.go
syz-manager/manager.go
tools/syz-repro/repro.go

Manager has already checked what features are present on the target.
But if we detected that, say, USB is missing, we still enabled it
in the starting csource options. This is wrong, increases configuration
minimization time and may lead to some obscure bugs.

pkg/repro: don't enable features missing on the target

---

CONTRIBUTORS
docs/linux/setup_ubuntu-host_qemu-vm_x86-64-kernel.md

Fixes a couple typos that prevent copy-paste.

docs/linux: fix example qemu command

---

executor/common_fuchsia.h
executor/executor_fuchsia.h
pkg/csource/generated.go

Fuchsia has strict controls over who can map memory as executable.
Refactoring syz-executor to be able to do that involves a non trivial
amount of work: it needs to run as a fuchsia component and replace stdin
for some other mechanism to communicate with syz-fuzzer (probably a fidl
service and a thin client that proxies stdin/stdout to syz-fuzzer via
ssh).
Mapping memory as executable doesn't seem to be used or needed in
syz-executor at all. After talking with Dmitry, he mentioned that it was
used in a deprecated feature: `syz_execute_func` which would execute
random code. It also allows more scenarios during fuzzing.
For now, I'm removing that option to allow syzkaller continue fuzzing.
This change also refactors all of the error messages adding a string
representation of the …

executor/fuchsia: Don't map memory as executable.

---

docs/syscall_descriptions.md
docs/syscall_descriptions_syntax.md

- Give some extra clarifications and examples about resources in syscall
descriptions.
- More details about how to use the "enable_syscalls" option.
- Mention pseudo-syscalls in the general syscall description doc file.

docs: more info about resources and the "enable_sysaclls" config option

---

pkg/build/linux_generated.go
tools/create-gce-image.sh
tools/create-image.sh

Add a default udev rule file to the image creation process in
create-gce-image.sh and create-image.sh.
This change creates a default rule to make udev create a custom-named
symlink for the specific vim2m device.

tools: add custom udev rules to generated images

---

sys/targets/targets.go

It seems that the value used on all platforms (512 << 20) does
not work on 32-bit FreeBSD when using the clang tools.
Try (256 << 20) instead.

sys/targets: use a different SYZ_DATA_OFFSET for 32-bit FreeBSD

---

sys/linux/bpf.txt

Extend the syscall definition for BPF_MAP_UPDATE_ELEM to include socket fds, which should make some paths in the sockmap code easier to discover.
Also expand BPF_PROG_ATTACH to include a BPF map fd as the target, since this is used to associate BPF programs with a sockmap.

Increase coverage of BPF sockmap

---

vm/gvisor/gvisor.go

The -alsologtostderr flag is a noop if -panic-log is also set. So before
this change, debug logs were not included in the syzkaller output logs.
By setting -debug-log=/dev/stderr, all debug logs are sent to stderr,
which syzkaller scrapes and includes in the output logs.

vm/gvisor: Send debug logs to stderr so they can be read by syzkaller

---

.github/CODEOWNERS

This should automatically assign reviewers/cc corresponding developers.
Add codeowners for OSes for which we have committers.
For details see:
https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners

.github: add CODEOWNERS

---

executor/common_linux.h
executor/executor.cc
pkg/csource/generated.go

Improve used terminology by using better verbs to express the effect of
the whitelist/blacklist.
This follows TSAN's terminology which uses "suppress" to refer to the effect of its blacklist: https://clang.llvm.org/docs/ThreadSanitizer.html#blacklist
This also changes executor to exclusively show respectful log messages,
and as per recent conversion, converts the last such case.

executor: Improve used terminology

---

AUTHORS
CONTRIBUTORS
Makefile
tools/syz-crush/crush.go

Tool takes syz-manager configuration file and c-source -file as inputs.
It builds the c-program and runs it for 5 minutes.
Possible crashes are saved to <workdir>/crashes.
usage:
syz-reprorunner -config=config.json creprog.c
Produced output is same as syz-manager produces.
New directory called reproduced_with is added that lists all the
reproducers that triggered the crash.
Example:
~/workdir/crashes  $ tree
.
├── 2a8fff76c6267ecfeaf3530a602ed48afbc4a151
│   ├── description
│   ├── log0
│   ├── log1
│   ├── log2
│   ├── report0
│   ├── report1
│   ├── report2
│   └── reproduced_with
│       └── 17a6ed226769660f3e5dad7b22b13466b938e290.c
├── 2b6b921457afe8cebd0a96ca40f8569e6ee95174
│   ├── description
│   ├── log0
│   ├── log1
│   ├── log2
│   ├── log3
│   ├── log4
│   ├── log5
│   ├── …

tools/syz-reprorunner: Add new tool to re-run creprog

---

pkg/report/linux.go
pkg/report/testdata/linux/report/479
pkg/report/testdata/linux/report/480
pkg/report/testdata/linux/report/481
pkg/report/testdata/linux/report/484
pkg/report/testdata/linux/report/485
pkg/report/testdata/linux/report/487
pkg/report/testdata/linux/report/500

Most likely reports without proper stack traces were caused by a bug in the
unwinder and are now fixed in 187b96db5ca7 "x86/unwind/orc: Fix
unwind_get_return_address_ptr() for inactive tasks".
Disable trying to use questionable frames for now.
Fixes #1834

pkg/report: stop using questionable frames

---

CONTRIBUTORS
executor/gen.go

Executor KVM generator works only on amd64 linux machines.

executor: enable KVM generator only on AMD64 arch

---

docs/syzbot.md

Unsure about the compiler, but I suppose it makes sense to keep the latest version up on here. I don't know if we want to accumulate too many prereleases though. Eventually we can "garbage collect" the prereleases.

docs/syzbot: Update KCSAN related information

---

pkg/ipc/ipc.go

If C compiler is installed e.g. in /opt then
we have to import LD_LIBRARY_PATH.

pkg/ipc: support C compiler in non-standard location

---

sys/freebsd/socket_inet_sctp.txt

For implementing sctp_bindx(), FreeBSD uses two IPPROTO_SCTP
level socket options SCTP_BINDX_ADD_ADDR and SCTP_BINDX_REM_ADDR.
The type of the value was changed from struct sctp_getaddresses *
to struct sockaddr_in * or struct sockaddr_in6 * in
https://svnweb.freebsd.org/changeset/base/362451

sys/freebsd: update SCTP related socket options for FreeBSD

---

prog/encodingexec.go

We must pad data arguments with known values when serializing
them into the given destination buffer because it could
be reused and contain random bytes from previous use.

prog/encodingexec: pad data args with zero bytes

---

Makefile
tools/syz-reporter/reporter.go

Goes through crash folder that is stated in the workdir.
Collects the crashes, counts and tags.
usage:
./bin/syz-reporter -config manager.cfg
Ouputs similar html page as syz-manager produces. This tool is very useful to be
used with tools/syz-crush when running testing kernel with existing reproducers.

tools/syz-reporter: Tool to share/visualize crashes

---

executor/executor.cc
executor/executor_linux.h
executor/test.h
pkg/ipc/ipc.go
prog/big_endian.go
prog/decodeexec.go
prog/encodingexec.go
prog/encodingexec_test.go
prog/little_endian.go

Use native byte-order for IPC and program serialization.
This way we will be able to support both little- and big-endian
architectures.

ipc: fix endianness issues

---

prog/prog_test.go
sys/targets/common.go

mknod on netbsd can now also accept a resource for the last arg.
Fix that and add a test that will catch such things more reliably.

sys/targets: fix mknod neutralize for netbsd

---

pkg/kd/kd_test.go
pkg/runtest/run.go
prog/target.go
sys/syz-extract/akaros.go
sys/syz-extract/fetch.go
sys/syz-extract/freebsd.go
sys/syz-extract/fuchsia.go
sys/syz-extract/linux.go
sys/syz-extract/netbsd.go
sys/syz-extract/openbsd.go
sys/syz-extract/trusty.go
sys/syz-extract/windows.go
sys/syz-sysgen/sysgen.go
sys/targets/targets.go
sys/test/test/align0_be
sys/test/test/bf
sys/test/test/bf2
sys/test/test/nla

* Introduce the new target flag 'LittleEndian' which specifies
of which endianness the target is.
* Introduce the new requires flag 'littleendian' for tests to
selectively enable/disable tests on either little-endian architectures
or big-endian ones.
* Disable KD unit test on s390x architecture because the test
works only on little-endian architecture.

target: support of big-endian architectures

---

sys/linux/socket_qipcrtr.txt

The QRTR rpmsg and mhi interfaces are not tested at this time.
The reasoning is documented for future reference in the corresponding
descriptions file.

sys/linux: documented the findings on qrtr rpmsg and mhi drivers

---

prog/little_endian.go

This will allow to run `make TARGETVMARCH=riscv64`.
h/t Munich RISC-V meetup talk by @bjoto

prog: add support for riscv64

---

docs/linux/setup.md
docs/linux/setup_linux-host_qemu-vm_riscv64-kernel.md
vm/qemu/qemu.go

The first commit adds support for running riscv64 qemu VM images. This requires a change in how network device parameters are specified to qemu and thus the introduction of a new `net_device_type` config parameter.
The second commit adds documentation for how to run syzkaller against a linux/riscv64 qemu VM.

Support and docs for running linux/riscv64 qemu VMs

---

executor/common_bsd.h
pkg/csource/generated.go

`2` is the minimum value allowed

executor/netbsd: base nth on 2

---

docs/linux/setup_ubuntu-host_qemu-vm_x86-64-kernel.md

Suggest to checkout linux kernel from kernel.org rather than from github.
github is a mirror and we don't use it ourselves and I think it's
generally not used by kernel developers. The kernel.org repo is
the canonical location.

docs/linux: change suggested kernel git repo

---

docs/linux/setup_linux-host_qemu-vm_riscv64-kernel.md

OpenSBI seems to be the recommended boot method nowadays, see e.g. [1],
[2]
[1] https://riscv.org/2019/01/risc-v-community-releases-opensbi-to-foster-continued-ecosystem-growth/
[2] https://wiki.freebsd.org/riscv#OpenSBI
Signed-off-by: Tobias Klauser <tklauser@distanz.ch>

docs/linux: use OpenSBI instead of BBL to boot linux/riscv64 QEMU VM

---

pkg/bisect/bisect.go
pkg/bisect/bisect_test.go
pkg/vcs/linux.go
pkg/vcs/linux_test.go
pkg/vcs/testdata/linux/config-bisect.pl
pkg/vcs/testdata/linux/merge_config.sh
pkg/vcs/testos.go
pkg/vcs/vcs.go
syz-ci/jobs.go
syz-ci/syz-ci.go
syz-ci/testdata/example.cfg
tools/syz-bisect/bisect.go

First patch is adding new Syzkaller configuration option kernel_baseline_config. This option can be used to provide kernel configuration containing minimalistic set of drivers. It will be used as "good" configuration when configuration bisection is run for crash. To ge good bisection results baseline configuration should contain same debug options as "normal" configuration and have just unneeded drivers disabled.
Second patch is adding kernel configuration bisection as part of normal commit bisection. First original head with original commit is tested as earlier. Then original head is tested with configured baseline configuration (kernel_baseline_config). If crash reproduces with this baseline configuration it's used in commit bisection. If the crash doesn't reproduce then configuration …

[RFC] Implement configuration bisection

---

sys/linux/cgroup.txt

fix: hugetlb.<hugepagesize>.limit_in_bytes can be set.
hugetlb.<hugepagesize>.usage_in_bytes is for reading.
added descriptions for the following resource controllers:
net_cls, net_prio, devices, freezer.
Update #533 , #1115 
@dvyukov @xairy

sys/linux: improved the descriptions for cgroup

---

Makefile

pwd -P works great and is portable.
This fixes OpenBSD ci.

Makefile: avoid non-portable realpath

---

sys/linux/sys.txt
sys/linux/sys_386.const
sys/linux/sys_amd64.const
sys/linux/sys_arm.const
sys/linux/sys_arm64.const
sys/linux/sys_mips64le.const
sys/linux/sys_ppc64le.const
sys/linux/sys_riscv64.const
sys/linux/sys_s390x.const

Added the description for the newly added process_madvise syscall
(https://lkml.org/lkml/2020/5/15/1321).

sys/linux: add process_madvise

---

docs/linux/setup_linux-host_qemu-vm_riscv64-kernel.md

Use the `-bios default` QEMU option (available since QEMU 4.1 [1]). This allows to directly boot the built kernel with QEMU and drops the requirement for wrapping the kernel into an OpenSBI image.
[1] https://www.qemu.org/docs/master/qemu-doc.html#RISC_002dV-_002dbios-_0028since-4_002e1_0029

Use OpenSBI included with QEMU for linux/riscv64

---

docs/linux/setup_linux-host_qemu-vm_riscv64-kernel.md

Follow-up for #1910 which I forgot to push.
Use the OpenSBI "jump" firmware with the QEMU -bios parameter to boot
linux/riscv64. This will allow to boot the kernel directly without
having to recompile OpenSBI every time the kernel is recompiled.

docs/linux: use OpenSBI jump firmware in QEMU for linux/riscv64

---

syz-ci/jobs_test.go
tools/syz-linter/linter.go
tools/syz-reporter/reporter.go

Enable some x/tools linters that are not enabled in vet.
Update #1876

tools/syz-linter: enable some standard linters

---

pkg/compiler/gen.go
pkg/compiler/types.go
prog/alloc.go
prog/alloc_test.go
prog/encoding.go
prog/rand.go
prog/target.go
prog/types.go
tools/syz-trace2syz/proggen/proggen.go

AlignAttr was only used to set padding and not to align to the
given argument. Existing descriptions with [align[X]] don't have
an issue as they align to small blocks and default align is to 64.
This commits adds support for [align[X]] for an X larger than 64.

prog/alloc: align address allocation for aligned[addr]

---

Makefile

Otherwise the versions in go.mod are updated on running `make
install_prerequisites` leading to inconsistent vendoring errors:
```
go: inconsistent vendoring in /go/src/github.com/google/syzkaller:
golang.org/x/net@v0.0.0-20200625001655-4c5254603344: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
golang.org/x/tools@v0.0.0-20200717024301-6ddee64345a6: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
golang.org/x/net@v0.0.0-20200520182314-0ba52f642ac2: is marked as explicit in vendor/modules.txt, but not explicitly required in go.mod
golang.org/x/tools@v0.0.0-20200626171337-aa94e735be7f: is marked as explicit in vendor/modules.txt, but not explicitly required in go.mod
```

Makefile: set GO111MODULE=off for go get in install_prerequisites

---

executor/common_kvm_amd64.h
pkg/csource/generated.go

Fix build errors:
```
gcc -o ./bin/linux_amd64/syz-executor executor/executor.cc \
-m64 -O2 -pthread -Wall -Werror -Wparentheses -Wunused-const-variable -Wframe-larger-than=16384  -DGOOS_linux=1 -DGOARCH_amd64=1 \
-DHOSTGOOS_linux=1 -DGIT_REVISION=\"d88894e6773ab63ac8b3f4b2edbae88290aaf0d6\"
In file included from executor/common_linux.h:1867,
from executor/common.h:394,
from executor/executor.cc:146:
executor/common_kvm_amd64.h: In function ‘void setup_32bit_idt(kvm_sregs*, char*, uintptr_t)’:
executor/common_kvm_amd64.h:143:64: error: ‘gate.kvm_segment::type’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
143 |  uint64 sd = (limit & 0xffff) | (seg->base & 0xffffff) << 16 | (uint64)seg->type<< 40 | (uint64)seg->s << 44 | (uint64)seg->dpl << 45 | …
```

executor: fix build errors in setup_32bit_idt()

---

executor/executor_bsd.h
pkg/host/host_openbsd.go

Recently added[1] to the kcov implementation on OpenBSD.
[1] https://github.com/openbsd/src/commit/8430bc4bce9f93dce843b53971377b7afd96cdb1

executor: enable extra coverage on OpenBSD

---

executor/executor_bsd.h
pkg/host/host_openbsd.go

Forgot that the build machine must be updated to a newer OpenBSD
snapshot first in order to make the new kcov stuff available.
This reverts commit 96dd36234d97bbf6b403f3a7f03cfc0296422879.

Revert "executor: enable extra coverage on OpenBSD"

---

pkg/compiler/check.go
pkg/compiler/testdata/errors2.txt
sys/freebsd/socket_inet_icmp.txt
sys/fuchsia/events.txt
sys/fuchsia/fuchsia_io.syz.txt
sys/fuchsia/objects.txt
sys/fuchsia/posix.txt
sys/fuchsia/streams.txt
sys/linux/bpf.txt
sys/linux/dev_infiniband_rdma.txt
sys/linux/dev_sr.txt
sys/linux/filesystem.txt
sys/linux/sys.txt
sys/netbsd/fs.txt
sys/netbsd/vnet.txt
sys/netbsd/vusb.txt
sys/openbsd/dev_pf.txt
sys/openbsd/dev_speaker.txt
sys/openbsd/wscons.txt
sys/windows/sys.txt

If a resource is never used as an input, it is not useful.
It's effectively the same as using an integer.
Detect such cases, they are quite confusing.
Fix all existing errors in descriptions.
This uncovered some interesting bugs as well,
e.g. use of a completely unrelated fd subtype after copy-paste
(while the resource that was supposed to be used there is completely unused).

pkg/compiler: check for unused resources

---

executor/common.h
executor/common_bsd.h
executor/common_linux.h
executor/common_usb_netbsd.h
pkg/csource/common.go
pkg/csource/csource_test.go
pkg/csource/generated.go

1. We don't generally use /* */ block comments,
few precedents we have are inconsistent with the rest of the code.
2. pkg/csource does not strip them from the resulting code.
Remove the cases we have and add a test to prevent new ones being added.

executor: remove block comments

---

.github/workflows/ci.yml
tools/check-commits.sh
tools/syz-env

We currently check from github.event.pull_request.base.sha
to github.event.pull_request.head.sha, but they may be in
different branches if the PR commits are branched not from
the latest master HEAD (at the time of PR creation).
Then GH will create a merge commit, and the range we try
to check is not valid.
Check github.event.pull_request.commits commits backwards
from github.event.pull_request.head.sha commit.

tools/check-commits.sh: fix commit range detection

---

tools/check-commits.sh

Allow the canonical 'git revert' format.

tools/check-commits: allow canonical 'git revert' format

---

tools/check-commits.sh

Base points to already commetted changes,
we really want to cheack head of the PR.

tools/check-commits.sh: use PR head instead of base

---

pkg/report/openbsd.go
pkg/report/testdata/openbsd/report/32

Regression introduced in commit cb93dc6a ("pkg/report: flag short
uvm_fault reports as corrupted") causing some valid reports to be
flagged as corrupted

pkg/report: fix uvm_fault report detection on OpenBSD

---

pkg/report/linux.go
pkg/report/testdata/linux/report/509

It used to use warningStackFmt, it is wrong, this is not a WARNING.
As the result it previously parsed as:
KMSAN: kernel-usb-infoleak in __kmalloc

pkg/report: fix parsing of kernel-usb-infoleak

---

executor/common_linux.h
pkg/csource/generated.go

We added initialize_vhci to all sandboxes so that we don't have
unused function warnings. We assumed it will fail silently,
but it fails loudly and crashes the whole machine on init,
so no fuzzing can happen with sandboxes other than none.
Initialize vhci earlier while we still have CAP_ADMIN.
As a nice side effect we now don't need to use syz_init_net_socket.

executor: initialize vhci early

---

executor/executor_linux.h

There are many "lost connection to test machine (5)" reports where the
testing terminated due to ENOENT upon open("/sys/kernel/debug/kcov").
Since some testcase might be unintendedly modifying mount information,
let's start from checking whether/how mount is broken.
This commit might be reverted after the cause is identified and fixed.

executor/linux: dump mount information when failed to open kcov file

---

Makefile

Commit 43f1389 ("Makefile: enable clang-tidy in presubmit tests") added clang-tidy to only tools/docker/env/Dockerfile file.
We should try to explicitly install clang-tidy in Makefile for those who don't use docker.

Makefile: try to install clang-tidy package explicitly

---

executor/common_linux.h
executor/executor_bsd.h
executor/style_test.go

The regexp for empty suppressions matches _everything_...
Don't match suppression if it's empty.

executor: fix style checking test

---

executor/executor_linux.h

With commit 50e21c6be6188f42 ("executor/linux: dump mount information when failed to open kcov file"), we got an unexpected result.
/sys/kernel/ does not exist despite /sys/ exists.
/proc/mounts cannot be opened despite /proc/ exists.
If sysfs is not mounted on /sys/ and proc is not mounted on /proc/ , maybe other filesystems (e.g. devtmpfs, cgroup) are not mounted as well.
Let's dump "/", "/proc/" and "/sys/", and then mount /proc/ and dump /proc/mounts .

executor/linux: dump more information when failed to open kcov file

---

executor/common.h
executor/common_bsd.h
executor/common_fuchsia.h
executor/common_kvm_amd64.h
executor/common_kvm_arm64.h
executor/common_linux.h
executor/common_usb.h
executor/common_usb_linux.h
executor/common_usb_netbsd.h
executor/executor.cc
executor/executor_bsd.h
executor/style_test.go
executor/test.h
pkg/csource/generated.go

We generally use the newer C99 var declarations combined with initialization because:
- declarations are more local, reduced scope
- fewer lines of code
- less potential for using uninit vars and other bugs
However, we have some relic code from times when we did not understand
if we need to stick with C89 or not. Also some external contributions
that don't follow style around.
Add a static check for C89-style declarations and fix existing precedents.
There was something about for loops IIRC. But I can't find any details now.
Let's see if there is still something that prevents us from declaring
variables inside of for loops.

executor: warn about C89-style var declarations

---

executor/common_linux.h
pkg/csource/generated.go

"#if not" does not seem to be a thing in C:
$ cpp -undef -fdirectives-only -dDI -E -P -DSYZ_REPEAT -DSYZ_USE_TMP_DIR executor/common_linux.h 1>/dev/null
executor/common_linux.h:3776:9: error: missing binary operator before token "SYZ_SANDBOX_ANDROID"
3776 | #if not SYZ_SANDBOX_ANDROID
|         ^~~~~~~~~~~~~~~~~~~
executor/common_linux.h:3801:9: error: missing binary operator before token "SYZ_SANDBOX_ANDROID"
3801 | #if not SYZ_SANDBOX_ANDROID
|         ^~~~~~~~~~~~~~~~~~~
executor/common_linux.h:3837:9: error: missing binary operator before token "SYZ_SANDBOX_ANDROID"
3837 | #if not SYZ_SANDBOX_ANDROID
|         ^~~~~~~~~~~~~~~~~~~
executor/common_linux.h:3868:9: error: missing binary operator before token "SYZ_SANDBOX_ANDROID"
3868 | #if not SYZ_SANDBOX_ANDROID
| …

executor: fix use of SYZ_SANDBOX_ANDROID define

---

pkg/build/freebsd.go

This is required to unbreak the FreeBSD syzbot instance. :(

pkg/build: add configuration to /boot/loader.conf.local on FreeBSD

---

vm/vmimpl/util.go

This commit adds a new option to SSH options, disallowing the
authentication agent. This is specially useful when you are testing
in a machine that sets the `SSH_AUTH_SOCK` environment variable, as
ssh will try to use that authentication agent on each ssh connection.

Disallow SSH Authentication Agent

---

executor/common_linux.h
pkg/csource/generated.go

I have removed the `#include <linux/fs_fuse.h>` dependency and defined the required structures and constants locally. This should fix the problem reported by syzbot [here](https://groups.google.com/g/syzkaller-lts-bugs/c/Ya6US4zCyzs/m/TwRitPIdBgAJ).
For some reason, using standard fixed size C types (e.g. `uint32_t`) breaks the executor compilation, so I am using the non-standard variant. Is this intended behavior?
---
CC: @balsini

executor/common_linux.h: fix build breakage for Linux 4.14

---

docs/linux/setup_ubuntu-host_qemu-vm_x86-64-kernel.md

There is a missing space on the command at line 131, which when copied causes it not to execute properly.

Missing space at end of line of command

---

docs/usage.md

'...a way connect them' -> '...a way to connect them'
Signed-off-by: Tree Davies <tdavies@darkphysics.net>

docs/usage.md: correct grammatical error

---

docs/linux/kernel_configs.md

Replace `CONFIG_KMEMLEAK` with `CONFIG_DEBUG_KMEMLEAK` in list of recommended kernel configs for `syzkaller`:
https://www.kernel.org/doc/html/latest/dev-tools/kmemleak.html#usage

docs/linux: fix KMEMLEAK variable in suggested kernel configs

---

executor/common_linux.h
pkg/csource/generated.go

unshare(CLONE_NEWNS) might not be sufficient for making all test processes run in separate mount namespace, for "mount --make-rshared /" request issued by systemd causes mount operations issued by test processes visible from outside of test
processes. Issue "mount --make-rprivate /" request after unshare(CLONE_NEWNS). Also, always print error message in order to help finding possible culprit for unexpected mount namespace modification.

executor/linux: change mount propagation type to private

---

executor/common_linux.h
pkg/csource/generated.go

Add the following missing FUSE opcodes to the syz_fuse_handle_req
pseudo-syscall: FUSE_COPY_FILE_RANGE, FUSE_UNLINK, FUSE_DESTROY and
FUSE_BATCH_FORGET.
---
CC: @balsini

executor/common_linux.h: add missing FUSE opcodes

---

dashboard/app/index.yaml

At least on my dashboard setup, the API call 'job_poll' results in a
NEED_INDEX datastore error.
Add the index definition that the development server generates if you make
the job_poll API call.

dashboard: Add missing index for job_poll API call

---

Makefile
docs/contributing.md
tools/docker/README.md
tools/docker/big-env/Dockerfile
tools/docker/env/Dockerfile
tools/docker/old-env/Dockerfile

Some users don't have access to the gcr.io registry.
Mirror images on github as well.

tools/docker: mirror images on github

---

tools/create-image.sh

The help message indicates `--size` to be valid option,
but, in fact `--seek` is being used when parsing the arguments.

tools/create-image.sh: resolve mismatch between help message and opt parsing

---

dashboard/app/access.go
dashboard/app/access_test.go
dashboard/app/api.go
dashboard/app/app_test.go
dashboard/app/entities.go
dashboard/app/jobs.go
dashboard/app/main.go
dashboard/app/reporting.go
dashboard/app/reporting_test.go
dashboard/app/templates.html
dashboard/dashapi/dashapi.go
syz-manager/manager.go

- Change syz-manager so that it will send machine info the first time a crash occurs.
- Add a field in entities.Crash to store machine info.
- Add a field in `dashapi.BugReport` to store machine info.
- Change the HTML template and struct `uiCrash` to display machine info.
This commit does not belong to any branch on this repository.

dashboard/app: send machine information to dashboard

---

pkg/host/machine_info_linux_test.go

TestScanCPUInfo does not build on !linux.
TestMachineInfoLinux builds, but does not do anything useful.

pkg/host: make machine info tests linux-specific

---

executor/common_linux.h
executor/style_test.go
pkg/csource/generated.go

Sone syzbot instances broke with:
<stdin>: In function ‘syz_io_uring_setup’:
<stdin>:476:33: error: ‘__NR_io_uring_setup’ undeclared (first use in this function)
<stdin>:476:33: note: each undeclared identifier is reported only once for each function it appears in
pkg/csource resolves #ifdef's at generation time.

executor: fix definition of __NR_io_uring_setup

---

pkg/host/machine_info_linux_test.go

Use the field 'machine' in /proc/cpuinfo on IBM/Z
to find out the "CPU model".

pkg/host: use 'machine' field as cpu model on IBM/Z

---

CONTRIBUTORS
docs/linux/coverage.md

Expand Linux coverage document. This document explains how binutil tools are utilized to symbolize the kernel image and link the exported program counters to source information for coverage reporting on Linux.

Expand linux coverage docs

---

pkg/host/machine_info_linux_test.go

There is no field 'machine' in /proc/cpuinfo when we run inside
a Docker container but there is a 'processor 0' field which
provides the same information.
Example:
processor 0: version = 00,  identification = 310C57,  machine = 3906

pkg/host: use 'processor 0' as cpu model on s390x inside container

---

sys/targets/targets.go

In ESA/S390 mode, the CPU is able to address only 31bit of
memory address space. GCC on s390x expects the flag -m31 instead
of -m32 for 32bit code.

sys/targets: use -m31 gcc option on s390x arch for 32bit targets

---

tools/create-image.sh

create-image.sh assumes that the qemu name and the Debian name for the
target architecture are the same. This is not always true.
For comedy and/or historical reasons, Debian refers to 64-bit little
endian PowerPC as ppc64el, whereas qemu and most other things use ppc64le.
Debian refers to aarch64 as arm64, and 32-bit little endian arm as armel.
Add special cases to handle this.

tools/create-image.sh: map qemu -> Debian architecture names

---

executor/common.h
pkg/csource/generated.go

Fixes the issue with gcc 10 on Fedora 32 s390x:
In file included from ../../executor/executor.cc:147:
../../executor/common.h: In function ‘void remove_dir(const char*)’:
../../executor/common.h:229:44: error: ‘%s’ directive output may be truncated writing up to 255 bytes into a region of size between 0 and 4095 [-Werror=format-truncation=]
229 | snprintf(filename, sizeof(filename), "%s/%s", dir, ep->d_name);
| ^~
../../executor/common.h:229:11: note: ‘snprintf’ output between 2 and 4352 bytes into a destination of size 4096
229 | snprintf(filename, sizeof(filename), "%s/%s", dir, ep->d_name);
| ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../executor/common.h:229:44: error: ‘%s’ directive output may be truncated writing up to 255 bytes into a region of size between 0 …

executor: forbid inlining of 'remove_dir'

---

Makefile

Since executor/gen.go invokes "gcc kvm_gen.cc kvm.S -o kvm_gen", g++ is needed.
go generate ./pkg/csource ./executor ./pkg/ifuzz ./pkg/build ./pkg/html
gcc: fatal error: cannot execute ‘cc1plus’: execvp: No such file or directory
compilation terminated.
executor/gen.go:6: running "bash": exit status 1

Makefile: try to install g++ package explicitly

---

Makefile

Since some scripts are executed using "python", create a symlink when "python3" exists
and "python" does not exist, by installing python-is-python3 package.
/bin/sh: 1: python: not found
make[2]: *** [Makefile:364: check_links] Error 127

Makefile: try to install python-is-python3 package as needed

---

CONTRIBUTORS
Makefile
pkg/bisect/bisect.go
pkg/bisect/bisect_test.go
pkg/build/build.go
pkg/build/linux.go
pkg/instance/instance.go
pkg/vcs/linux.go
syz-ci/jobs.go
syz-ci/manager.go
syz-ci/syz-ci.go
tools/syz-bisect/bisect.go
tools/syz-testbuild/testbuild.go

Most of the time during bisection is used in building kernels. This patch set is enabling ccache usage for kernel building during bisection.
I did evaluation how using ccache impacts bisection/build times. In this evaluation I used 30 GB cache size. Linux kernel version used in evaluation was v4.19.59 and configuration was upstream-leak.config. HW used in evaluation was Intel core i7 3.2Hz, 32 GB memory and 250GB SSD.
55fc56e39caaf4f597fdbf388108892196d55f3f
with ccache:
revisions tested: 10, total time: 1h2m28.486458285s (build: 52m12.726715465s, test: 7m55.631365309s)
without ccache:
revisions tested: 10, total time: 1h49m56.85679912s (build: 1h39m39.424251006s, test: 7m57.998117335s)
4b61862ab93380cf84d66e09596ff3cbc3bc5341
with ccache:
revisions tested: 79, total time: …

[RFC] Use ccache in bisection

---

CONTRIBUTORS
docs/linux/setup.md
docs/linux/setup_ubuntu-host_vmware-vm_x86-64-kernel.md

Add new page for fuzzing x86-64 Linux kernel on VMware VMs.
It explains how to create a VMDK image and how to run it on Ubuntu host
with Workstation installed. For now only the isolated mode of syzkaller
is supported.

docs/linux: add instructions for fuzzing on VMware hosted hypervisors

---

pkg/build/linux_generated.go
tools/create-gce-image.sh

Add fstab entry to mount the root filesystem read-write after boot. This
has been done with commit 873745 for create-image.sh. Maybe this hint is
not necessary for GCE but it is required when running on other platforms
(e.g. VMware).

tools/create-gce-image.sh: mount the root filesystem read-write

---

Makefile
docs/coverage.md
pkg/cover/report.go
pkg/cover/report_test.go
syz-manager/html.go
tools/syz-cover/syz-cover.go

Add function coverage view into cover page. When percentage of certain source code file is clicked, instead of opening source code view new function coverage view is shown. Source code view is still shown when clicking on source code filename..
also add new option to syz-cover tool to export function coverage to csv file.

[RFC] Function coverage

---

executor/executor_linux.h

Since ENOENT problem was solved by commit 318430cbb3b2ceef ("executor/linux: change mount propagation type to private"), remove the debug code for this problem.

executor/linux: stop dumping mount information when failed to open kcov file

---

dashboard/app/templates.html

We forgot to show the bisection log for one of 4 bisection outcomes.
Consistently show it for all outcomes.

dashboard/app: show log for all bisections

---

pkg/vcs/linux.go

UBSAN is broken in multiple ways before v5.3, see:
https://github.com/google/syzkaller/issues/1523#issuecomment-696514105
Update #1523

pkg/vcs: disable UBSAN before v5.3

---

pkg/ipc/ipc.go
prog/encodingexec.go
syz-fuzzer/proc.go

We started to see lots of "provided buffer is too small" with seeded
syz_mount_image programs. Currently it fails whole VM, which is not good.
Ignoring them is not perfect, but there does not seem to be any better
simple solution.

syz-fuzzer: ignore encodingexec buffer overflow errors

---

dashboard/config/bits-syzbot.config
docs/syzbot.md
pkg/build/linux_generated.go
tools/create-gce-image.sh
vm/qemu/qemu.go

There is suspicion that the random programs corrupt .text segment:
https://groups.google.com/g/syzkaller-bugs/c/d5GC1V8S34k/m/6LTarP8mBAAJ
which leads to a number of assorted confusing crashes:
https://syzkaller.appspot.com/bug?extid=ce179bc99e64377c24bc
Turns out we disable text ro protection with rodata=n.
The comment says that's because it's slow with KASAN,
but most likely what was slow is actually additional
debug checking due to CONFIG_DEBUG_WX.
If we don't enable CONFIG_DEBUG_WX (which we don't),
rodata itself should be fine and desirable.
My experiment with the latest kernel does not show
any noticable slowdown without rodata=n:
[   11.985152][    T1] Freeing unused kernel image (initmem) memory: 3432K
[   11.986129][    T1] Write protecting the kernel read-only data: 147456k
[ …

tools/create-gce-image.sh: drop rodata=n

---

pkg/kcidb/client.go
pkg/kcidb/schema.go
tools/syz-kcidb/kcidb.go

Based on @spbnick comments:
https://groups.google.com/g/syzkaller/c/Gd-hTPH4Two/m/6viE0QLgCQAJ
Normalize git.kernel.org repo addresses.
Send dashboard link in misc rather than in output files.
Don't omit waived.
Also check sent messages with kcidb-validate if it's in PATH.
Update #2144

pkg/kcidb: assorted improvements for the schema

---

docs/fuchsia/README.md
pkg/build/fuchsia.go

This PR fixes a bunch of small issues in syzkaller for fuchsia:
* zbi tool path changed
* multiboot.bin path changed.
* ssh key paths have changed, so now we create new ssh images.
* fvm image needs to be extended before booting.

Fuchsia Fixes

---

pkg/report/akaros.go
pkg/report/bsd.go
pkg/report/freebsd.go
pkg/report/fuzz.go
pkg/report/linux.go
pkg/report/report.go
pkg/report/report_test.go
vm/vmimpl/merger.go
vm/vmimpl/merger_test.go

I have a problem on s390x arch. 
All kernel messages contain a CR at the beginning and this is an attempt to fix it.
I'm open to better solutions :) 
Do we need CRs at all in kernel output ? LFs are not enough ?
Regards
Alex

vm/vmimpl/merger: remove all CRs from output

---

CONTRIBUTORS
executor/common.h
executor/common_fuchsia.h
executor/common_windows.h
executor/executor.cc
executor/executor_windows.h
pkg/csource/generated.go

This PR lets you build the executor using MSVC. The commands to build the executor using MSVC is as follows.
```
cl executor.cc /EHsc /DGOOS_windows /DGOARCH_amd64 /DEBUG:FULL -o syz-executor.exe kernel32.lib user32.lib 
gdi32.lib\winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib winmm.lib 
rpcrt4.lib Crypt32.lib imm32.lib Urlmon.lib Oleaut32.lib Winscard.lib Opengl32.lib Mpr.lib Ws2_32.lib Bcrypt.lib Ncrypt.lib 
Synchronization.lib Shell32.lib Rpcns4.lib Mswsock.lib  Mincore.lib Msimg32.lib RpcRT4.lib Rpcrt4.lib lz32.lib
```
NOTE: This PR is a continuation of the previous PR I'd sent and the changes you asked me to make have been applied in this PR.

executor: msvc support syz-executor

---

pkg/cover/report.go

addr2line on a beefy vmlinux takes up to 1.6GB of RAM,
so don't create more than 4 of them.

pkg/cover: cap number of addr2line processes

---

CONTRIBUTORS
vm/qemu/qemu.go

Changes - vm/qemu/qemu.go: update SCP Timeout for Slower devices/Nested Virtualisation
Problem - Repeated SCP Timeouts in nested virtualized environments
Solution - Increased the timeout for SCP of the initial binaries after boot to 10 minutes to allow more time in a slow environment. This was causing timeouts often in a nested virtualised environment on a slower hardware. This should be a harmless change as it's only related to timeout faults.

vm/qemu : update scp timeout for qemu

---

sys/targets/targets.go

Use as data offset the address 0xfffff000 for s390x arch.
It is better for testing because it crosses the 4GB address space.

sys/targets: use a better DataOffset for linux/s390x

---

tools/create-image.sh

Fix building of riscv64 and x86_64 images, and i386 images on an x86_64 build host.

tools/create-image.sh: misc architecture fixes

---

sys/linux/test/gup_fast

https://lore.kernel.org/linuxppc-dev/20190418100218.0a4afd51@mschwideX1/
The test triggers this bug:
[  224.294341] ==================================================================
[  224.294389] BUG: KASAN: stack-out-of-bounds in gup_pgd_range+0x124a/0x1398
[  224.294405] Read of size 8 at addr 000003e002e8f3d8 by task gup_fast_regr-s/633
[  224.294417]
[  224.294431] CPU: 0 PID: 633 Comm: gup_fast_regr-s Not tainted 5.9.0-rc6 #1
[  224.294443] Hardware name: IBM 8561 T01 701 (KVM/Linux)
[  224.294454] Call Trace:
[  224.294470]  [<0000000047708384>] show_stack+0x174/0x220
[  224.294488]  [<000000004bbcfb9c>] dump_stack+0x274/0x2f8
[  224.294506]  [<0000000047f4e8e6>] print_address_description.constprop.0+0x5e/0x550
[  224.294523]  [<0000000047f4e4ea>] kasan_report+0x11a/0x168
[ …

sys/linux/test: add s390x GUP fast path test

---

pkg/host/machine_info_linux_test.go

Not all architectures have fields in /proc/cpuinfo for vendor, model and
flags, e.g. powerpc doesn't have an equivalent for vendor or flags.
Rather than testing for the presence of at least one field name for each
category, have a separate list per architecture.

pkg/host: test for different cpuinfo fields depending on arch

---

pkg/build/linux.go
pkg/vcs/linux.go

This pull request is fixing kernel signature calculation in pkg/build/linux.go:elfBinarySignature. This issue is discussed here: https://github.com/google/syzkaller/issues/1271. The root cause for signature being a random number is Linux kernel build not being reproducible. Addition to handling MODULE_SIG_ALL case listed in Documentation/kbuild/reproducible-builds.rst BLK_DEV_INITRD was found to cause init.data section to change between builds. These are both fixed in this pull request.

Fix kernel signature calculation

---

executor/common_linux.h
pkg/csource/generated.go

The parent-death signal is set in sandbox_common, but then setresuid and
setresgid clear it and we need to set it again.

executor: set parent-death signal after changing user or group ID-s

---

Makefile
pkg/vcs/git.go
pkg/vcs/git_test.go
pkg/vcs/vcs.go
syz-ci/jobs.go
syz-ci/manager.go
syz-ci/updater.go

The Freshness columns in Instances: table on the dashboard page look outdated, for
these fields are showing when that patch was authored. Showing when that patch was
committed into the tree in question would be more meaningful.

pkg/vcs: use committer date than author date

---

docs/linux/setup_ubuntu-host_vmware-vm_x86-64-kernel.md
vm/vm.go
vm/vmware/vmware.go

Use the "vmrun" utility to manage Workstation VMs. The syzkaller manager
creates temporary VMs (linked clones) from a base image, gets their IP
address and uses ssh to deploy and run programs (similar to the isolated
mode).

vm: Implement the VM interface for VMware Workstation

---

syz-ci/jobs.go
syz-ci/syz-ci.go
syz-ci/testdata/example.cfg

Some users may wish to reduce the frequency at which syz-ci polls for jobs.
Add two new optional settings, job_poll_period and commit_poll_period, that
allow the administrator to set how often syz-ci polls for jobs and commits.
Keep the existing defaults of 10 seconds and 1 hour respectively.

syz-ci: make polling times configurable

---

pkg/cover/report.go
pkg/report/linux.go
pkg/report/testdata/linux/report/522

- pkg/report: support divide_error: crashes
- pkg/cover: support KASLR binaries

dvyukov cover kaslr

---

executor/common_linux.h
pkg/csource/generated.go
pkg/host/syscalls_linux.go
syz-fuzzer/testing.go

- pkg/host: don't log every syscall name twice
- syz-fuzzer: run test program with correct flags
- executor: fix arp netfiler tables alignment for arm

dvyukov arm align

---

CONTRIBUTORS
pkg/build/gvisor.go

Collecting coverage in platform/ring0 code causes the kvm platform to
crash, possibly due torestrictions on the address space that coverage
data is violating.

Omit gVisor platform code from coverage instrumentation

---

pkg/kconfig/minimize.go
pkg/kconfig/minimize_test.go

Always move all non-tristate configs from full because
we don't minimize them.

pkg/kconfig: move all non-tristate configs in minimization

---

docs/linux/setup_linux-host_qemu-vm_riscv64-kernel.md

The patch adding kcov support for riscv64 [1] was merged in the 5.9 merge
window (torvalds/linux@20d38f7c45a4). Adjust the docs accordingly to use
kernel 5.9-rc1.
[1] https://lore.kernel.org/linux-riscv/20200626124056.29708-1-tklauser@distanz.ch/

docs/linux: update recommended kernel to 5.9-rc1

---

dashboard/app/static/common.js
pkg/html/generated.go
tools/syz-reporter/reporter.go

This pull request is adding reproducer information into generated report. "Tags" column is changed as Reproducer column. For syz-crush workdir listed reproducers are read from a tag file and syz-manager workdir repro.(c)prog filename is added into column. Now you get view how many of found crashes do have reproducer when generating report from syz-manager workdir
Also summary is added. I.e. "Crash Count" and "Crash With Reproducers Count"

tools/syz-reporter: add summary and reproducer information

---

vm/qemu/qemu.go

compiler says:
vm/qemu/qemu.go:501:49: conversion from int to string yields a string
of one rune, not a string of digits (did you mean fmt.Sprint(x)?)

vm/qemu: fix {{TCP_PORT}} replacement

---

tools/docker/env/Dockerfile

Go 1.15 is the latest release and it finds new bugs.
Leave old-env on 1.14 so that we test with both.

tools/docker/env: switch to Go 1.15

---

CONTRIBUTORS
executor/common_linux.h
pkg/csource/generated.go

Process group leader is not allowed to call setsid, thus remove setpgrp.

executor, pkg/csource: remove setpgrp() in sandbox_common()

---

pkg/report/openbsd.go
pkg/report/testdata/openbsd/report/10
pkg/report/testdata/openbsd/report/33

These reports are not that helpful and are rarely a problem as each
vnode has a unique lock. Reports from witness regarding lock order
reversal between two vnode locks are already suppressed by the kernel,
see RWL_IS_VNODE in the rwlock(9) manual.
While here, update `testdata/openbsd/report/10` as this report was
generated before I prefixed all output from witness.

pkg/report: suppress witness vnode lock order reversal on OpenBSD

---

.github/workflows/ci.yml
tools/docker/old-env/Dockerfile

Use syz-old-env because it contains Go 1.14.
syz-env contains Go 1.15 and go-fuzz is broken with Go 1.15:
https://github.com/dvyukov/go-fuzz/issues/294

.github/workflows: switch fuzzit to syz-old-env

---

syz-ci/manager.go
syz-ci/syz-ci.go

The syz-ci's configuration parameter *cover_upload_path*
contains a protocol-specific path now. Currently, only two
protocols for uploading of manager's coverage reports are supported:
* Google Cloud Storage (GCS)
* HTTP PUT
- A path which starts with "gs://" shall be interpreted as a GCS path
with gcs:// prefix stripped.
- For a path which starts with http:// or https:// the HTTP PUT method
shall be used for uploading.
- If the given path contains no supported protocol prefix, then syz-ci
shall assume that it is a GCS path. …

syz-ci: support HTTP PUT method to upload coverage reports

---

executor/common_linux.h
pkg/csource/generated.go

write_file() is needed for setup_sysctl() and syz_usbip_server_init().
setup_sysctl() also misses some header includes.

executor: fix linux includes

---

vm/qemu/qemu.go

MSI-X support is mandatory for any PCI device on s390x but
virtio-rng-pci doesn't support it.
Fixes the following error on s390x:
qemu-system-s390x: -device virtio-rng-pci: MSI-X support is mandatory in the S390 architecture
The problem was introduced in commit 36e8b020 ("vm/qemu: enable virtio-rng-pci").

vm/qemu: use virtio-rng-ccw on s390x arch

---

tools/create-image.sh

Current script hard-coded the basename for the path of kernel source,
if the basename of the path to the kernel source code is not "linux",
this script will just abort.
Fix this by using the basename obtained by the basename utility.

tools/create-image.sh: use the basename instead of hard-coded "linux"

---

pkg/compiler/const_file.go

While adding new syscall descriptions to OpenBSD I ran into the following problem:
$ gmake extract SOURCEDIR=/home/src && ./bin/syz-sysgen
fs.txt.const:15: failed to parse int: strconv.ParseUint: parsing "": invalid syntax
$ tail -n +15 sys/openbsd/fs.txt.const | head -1
O_RDONLY =
Note that `O_RDONLY` lacks a value and the same directive is defined as
0 on OpenBSD.
In `ConstFile.Serialize()`, if val is equal to the default value is has
only already been serialized if `max != 0`.

pkg/compiler: fix handling of defines with a 0 value

---

dashboard/app/config.go
dashboard/app/reporting_email.go

* Allows using a mail account provider other than Google App Engine
* Allows changing the app URL that appears in emails sent by syzbot

dashboard/app: add new config parameters for own email(s) and app URL 

---

syz-ci/jobs.go

Display kernel repo's URL and branch if a commit cannot be found
by getCommitInfo().

syz-ci/jobs: improve log message for non-found git commits

---

pkg/bisect/bisect.go
pkg/bisect/bisect_test.go
syz-ci/jobs.go

If during bisection we detect more "good" results than "bad" bisection is marked as flaky and number of tests is doubled.
Number of tests is also doubled if crash is not reproduced on original commit.

[RFC] Add new flag "flaky" for marking bisection result as ignore.

---

pkg/kconfig/kconfig.go
pkg/kconfig/minimize.go
pkg/kconfig/minimize_test.go

Test for case described in:
https://groups.google.com/g/syzkaller/c/c1J1kzzW7Ew/m/CeyEJm04AQAJ
It seems to work as is (mostly).
Fix parsing of the very last kconfig config (currently it's dropped).
s/menuend/endmenu/ in error message.
Sort dependencies so that we can express the test.
But none of this should have affected actual config minimization.

pkg/kconfig: add minimization test with dependent configs

---

pkg/compiler/check.go
pkg/compiler/compiler_test.go

Discovered by go-fuzz/OSS-Fuzz:
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=27599

pkg/compiler: fix crash on invalid templates

---

pkg/vcs/git.go

Fetching a remote branch w/o the corresponding remote with git
disables delta optimization on the server's side and the git
client is forced to download the complete branch even if it
already has got an older version. This leads to several problems as:
* Long fetch time
* Limitless growth of local git repo due to git fetch creating
a new pack file every time
Create a remote before fetching to fix the above issues.
With a remote, only the first fetch will take some time and all the following
ones shall be very fast. Furthermore, git fetch will avoid creating many
pack files in .git/objects/pack.
Before sending a pull request, please review …

pkg/vcs/git: optimize CheckoutBranch

---

pkg/ifuzz/ifuzz.go
pkg/ifuzz/ifuzz_test.go
pkg/ifuzz/ifuzzimpl/ifuzzimpl.go
pkg/ifuzz/iset/iset.go
pkg/ifuzz/powerpc/powerpc.go
pkg/ifuzz/powerpc/pseudo.go
pkg/ifuzz/x86/decode.go
pkg/ifuzz/x86/encode.go
pkg/ifuzz/x86/gen/gen.go
pkg/ifuzz/x86/pseudo.go
pkg/ifuzz/x86/x86.go
prog/rand.go

- pkg/ifuzz: use sub-tests for arches
- pkg/ifuzz: invert ifuzz and ifuzzimpl
- pkg/ifuzz/ifuzzimpl: move ModeInsns into tests
- pkg/ifuzz/ifuzzimpl: simplify Insn interface
- pkg/ifuzz/x86: don't use X86 suffix for types
- pkg/ifuzz/x86: simplify pseudo-instruction intialization
- pkg/ifuzz/x86: deduplicate modeInsns population logic
- pkg/ifuzz/ifuzzimpl: move IsCompatible from x86

dvyukov ifuzz refactoring

---

dashboard/app/api.go
pkg/mgrconfig/load.go
pkg/mgrconfig/mgrconfig_test.go
pkg/report/report.go
vm/adb/adb.go
vm/bhyve/bhyve.go
vm/gce/gce.go
vm/gvisor/gvisor.go
vm/isolated/isolated.go
vm/kvm/kvm.go
vm/qemu/qemu.go
vm/vm.go
vm/vm_test.go
vm/vmimpl/linux.go
vm/vmimpl/vmimpl.go
vm/vmm/vmm.go
vm/vmware/vmware.go

- vm: remove code duplication in MonitorExecution
- vm: pass Report to Diagnose
- vm/qemu: dump LOCKDEP state in Diagnosis

dvyukov vm diagnosis

---

pkg/osutil/osutil.go

Knowning the new wd may help to localize the error.

pkg/osutil: extend error message on wd change

---

docs/linux/setup_linux-host_qemu-vm_arm64-kernel.md

Clarify that the kernel build instructions refer to building the kernel
and not buildroot.

docs: update setup_linux-host_qemu-vm_arm64-kernel.md

---

dashboard/config/linux/stable-4.14.config
dashboard/config/linux/stable-4.19.config

Add CMDLINE we now have upstream to stable 4.14 and 4.19 configs.
This removes the last use of dashboard/config/linux/upstream.cmdline.

dashboard/config/linux: add CMDLINE to stable configs

---

sys/linux/fs_ioctl_fscrypt.txt
sys/linux/key.txt

Make some improvements to the fscrypt descriptions which should make it much more likely that syzkaller will generate programs that both add an encryption key to the kernel (`FS_IOC_ADD_ENCRYPTION_KEY` or `add_key$fscrypt_v1`) *and* create a directory that is encrypted using that key (`mkdir()` + `FS_IOC_SET_ENCRYPTION_POLICY`):
* sys/linux: make some fscrypt ioctls take fd_dir
* sys/linux: describe old way of adding fscrypt keys
* sys/linux: add some sample fscrypt keys
* sys/linux: annotate more field directions in fscrypt structs

sys/linux: improve fscrypt descriptions

---

pkg/report/linux.go
pkg/report/testdata/linux/guilty/45
pkg/report/testdata/linux/guilty/46
pkg/report/testdata/linux/guilty/47
pkg/report/testdata/linux/guilty/48

We are getting lots of WARNINGs in urb.c and all of them seem
to mean a bug in a particular driver. And fixes for these bugs
go into a particular driver code. But we send all of them to
urb.c maintainers. Skip urb.c as a guilty file.
If a bug happens to be in urb.c for real, a driver maintainers
should CC USB core maintainers on it.
Update #2284

pkg/report: skip drivers/usb/core/urb.c as guilty file

---

tools/syz-crush/crush.go

Currently syz-crush saves the results in the syzkaller workdir.
If you run this tool multiple times, you may lose the connection
between your reproducers and the crash reports saved in workdir.
Let's improve storeCrash():
1. print the sequence number of the saved crash,
2. report about the errors during crash saving,
3. copy the reproducer to the workdir as well.
Signed-off-by: Alexander Popov <alex.popov@linux.com>

tools/syz-crush: improve the output

---

syz-ci/syz-ci.go

syz-ci: allow 3-letter manager names

---

pkg/cover/report.go

If coverage contains some PCs that's don't map to coverage callbacks,
we can get file coverage >100% because total PCs are filtered against
all coverage callbacks, while actual coverage is not.
Filter actual coverage as well.

pkg/cover: fix file coverage percent calculation

---

pkg/mgrconfig/config.go
pkg/mgrconfig/load.go
pkg/rpctype/rpctype.go
syz-hub/hub.go
syz-hub/state/state.go
syz-hub/state/state_test.go
syz-manager/hub.go
syz-manager/hub_test.go
syz-manager/manager.go

Hub input domain identifier (optional).
The domain is used to avoid duplicate work (input minimization, smashing)
across multiple managers testing similar kernels and connected to the same hub.
If two managers are in the same domain, they will not do input minimization after each other.
If additionally they are in the same smashing sub-domain, they will also not do smashing
after each other.
By default (empty domain) all managers testing the same OS are placed into the same domain,
this is a reasonable setting if managers test roughly the same kernel. In this case they
will not do minimization nor smashing after each other.
The setting can be either a single identifier (e.g. "foo") which will affect both minimization
and smashing; or two identifiers separated with '/' (e.g. "foo/bar"), in …

syz-hub: support input domains

---

tools/syz-crush/crush.go

Currently syz-crush saves the results in the syzkaller workdir.
That brings a side effect: if you test two different reproducers giving
crashes with the same title, syz-crush saves all your results in
a single crash directory.
Let's make it more flexible. Save syz-crush results in the directory
containing the tested reproducer:
- we have the original workflow, if all tested reproducers reside
in the syzkaller workdir;
- we can get the results separately, if all tested reproducers reside
in separate directories.
Signed-off-by: Alexander Popov <alex.popov@linux.com> …

tools/syz-crush: make the results saving more flexible

---

executor/executor.cc
executor/executor_fuchsia.h
executor/executor_linux.h
sys/freebsd/ipc.txt
sys/linux/ipc.txt
sys/linux/prctl.txt

1. Apply ignore_return to semctl$GETVAL which produces random errno
values on linux and freebsd.
2. Apply ignore_return to prctl and remove the custom code in executor.
3. Remove the custom errno ignoring code in fuchsia executor.
The calls are already marked as ignore_return, so this is just a leftover.
4. Only reset errno for ignore_return.
The syscall can still return a resource (maybe).
We only need to reset errno for fallback coverage.

sys/linux, sys/freebsd: apply more ignore_return attributes

---

syz-manager/hub.go

r.Progs is not filled anymore (for legacy managers).
Use r.Inputs instead of r.Progs everywhere.

syz-manager: fix hub stats calculation

---

pkg/report/openbsd.go
pkg/report/testdata/openbsd/report/34

It looks we got a couple of odd crashes where the syz-executor is
probably hanging but the VM is still responsive[1].
Does the hypervisor try to diagnose the VM under such circumstances?
Since the VM is still responsive, the input written to the console is
echoed back which in turns causes a panic to be detected.
If this theory is true, we can avoid detecting such false positives by
making the oops indicator disjoint from the input written to the
console.
[1] https://syzkaller.appspot.com/bug?id=af604b59c590384e9faa00dfc958ef87a922ae71

pkg/report: make panic oops on openbsd more stringent

---

codecov.yml

Disable codecov annotations on PR.
So far they seem to be more annoying than useful.
We have some files that are not covered by unit tests
and these are just filled with "this line is not covered".
See https://docs.codecov.io/docs/codecovyml-reference

codecov.yml: disable github annotations

---

executor/cov_filter.h
executor/executor.cc
executor/test.h
pkg/cover/report.go
pkg/ipc/ipc.go
pkg/mgrconfig/config.go
pkg/rpctype/rpctype.go
syz-fuzzer/fuzzer.go
syz-manager/covfilter.go
syz-manager/covfilter_test.go
syz-manager/manager.go
syz-manager/rpc.go

syz-manager/manager.go: read coverage filter from the configuration, generate regular expressions from files or functions. Pick out PCs if files or functions match to those regular expressions, and create a bitmap for executor filtering.
executor/executor.cc, executor/bitmap.h: read bitmap and do coverage filter.
pkg/cover/report.go: add method "PCs" to visit the member "pcs" of ReportGenerator. Define arch name as constant because the message from "make presubmit" recommended.

Support coverage filter

---

pkg/report/linux.go
pkg/report/report.go
pkg/report/testdata/linux/guilty/49

LOCKDEP can add "hard/softirs last enabled/disabled at" lines
with more files at the top. These files are generally not related,
or at least out of order. We want to extract the file from stacks,
so ignore these lines.

pkg/report: better guilty file extraction with lockdep header

---

sys/linux/sys.txt

Also flip these:
/proc/sys/net/ipv4/tcp_dsack
/proc/sys/net/ipv4/tcp_recovery
/proc/sys/net/ipv4/tcp_mtu_probing
/proc/sys/net/ipv4/tcp_rfc1337
/proc/sys/net/ipv4/tcp_rmem
/proc/sys/net/ipv4/tcp_wmem

sys/linux: flip more tcp sysctl's

---

executor/common_bsd.h
pkg/csource/generated.go

Lately, I've been looking into why such low amount of syz reproducers on
OpenBSD are turned into C reproducers. One thing I did notice is that
such syz reproducers have one thing in common: they use the
threaded=true and sandbox=none parameters. Such C reproducer always
exits non-zero early on since the call to setsid() fails with EPERM.
Meaning, the calling process is already a process group leader.
Not sure if the preprocessor conditional should be tweaked in order to
avoid unwanted side effects on other BSDs or configurations.

executor: skip setsid() for threaded reproducers

---

docs/linux/setup_ubuntu-host_qemu-vm_x86-64-kernel.md

setup_ubuntu-host_qemu-vm_x86-64-kernel.md recommends using
create_image.sh to create a Debian Stretch VM image.  The script
configures the image assuming that the kernel will be booted with
predictable network device naming disabled, which syz-manager
currently does but the example qemu command in the setup document
does not.
To avoid confusing the user, add "net.ifnames=0" to the example qemu
command to disable predictable device naming.  If not the VM fails to
bring up network interfaces and is then inaccessible via. ssh.
#2329  …

docs/linux: fix up example qemu command for Ubuntu

---

pkg/vcs/git.go

git fetch can fail due to force-recreated tags:
> ! [rejected] ext4_for_linus -> ext4_for_linus
>   (would clobber existing tag)
And due to something related to updating local branches
(see 'git help fetch' for details).
--force should avoid both issues and it seems that
we always want force for our purposes (rather than
fail update/patch testing).

pkg/vcs: use --force with git fetch

---

docs/bisect.md
pkg/bisect/bisect.go
pkg/bisect/bisect_test.go
pkg/debugtracer/debug.go
pkg/kconfig/minimize.go
pkg/kconfig/minimize_test.go
pkg/vcs/git.go
pkg/vcs/git_repo_test.go
pkg/vcs/linux.go
pkg/vcs/testos.go
pkg/vcs/vcs.go
syz-ci/jobs.go
tools/syz-bisect/bisect.go
tools/syz-minconfig/minconfig.go
tools/syz-reporter/reporter.go

This patchset is trying to ease up usage of syz-bisect tool and also implements storing results of bisection into files located in crash directory. This make syz-bisect more usable as standalone tool. Also syz-bisect results are now added into syz-report output. Example report is attached in this pull request.
[syz-reporter.html.gz](https://github.com/google/syzkaller/files/5546178/syz-reporter.html.gz)

Bisect improvement

---

pkg/cover/backend/backend.go
pkg/cover/backend/elf.go
pkg/cover/backend/gvisor.go
pkg/cover/backend/pc.go
pkg/cover/cover.go
pkg/cover/cover_test.go
pkg/cover/html.go
pkg/cover/pc.go
pkg/cover/report.go
pkg/cover/report_test.go
syz-manager/cover.go
syz-manager/covfilter.go
syz-manager/html.go
syz-manager/rpc.go
tools/syz-cover/syz-cover.go

- pkg/cover: split into ELF-dependent/independent parts
- pkg/cover: pass VM type for report generator
- pkg/cover: accept object dir instead of object file
- pkg/cover: provide .text offset
- pkg/cover: provide ReportGenerator.RestorePC
- syz-manager: store mgrconfig.Config in RPCServer
- syz-manager: better encapsulate report generator
- syz-manager: use ReportGenerator.RestorePC in RPCServer.NewInput
- syz-manager: use compile units for file coverage filter
- pkg/cover: don't fail when can't open single source file
- pkg/cover: move cleanPath into backend
- pkg/cover: support compiler frontend coverage
- pkg/cover: don't show programs when we don't have them
- pkg/cover: don't show func coverage if we don't have it
- pkg/cover: add gvisor support

dvyukov cover report refactor

---

pkg/build/gvisor.go
pkg/cover/backend/gvisor.go
syz-manager/covfilter.go

When running under syz-ci gvisor image is called 'image',
but it's not in objDir. pkg/build/gvisor.go doesn't copy
anything into obj/.
Copy runsc into obj/vmlinux (as expected for linux target)
and open it in pkg/cover.

pkg/cover: fix location of gvisor object file

---

executor/executor.cc
executor/executor_bsd.h
executor/executor_linux.h
executor/nocover.h

gvisor coverage is not a trace, so producing edges won't work.

executor: don't use coverage edges for gvisor

---

pkg/cover/backend/backend.go
pkg/cover/backend/elf.go
pkg/cover/backend/gvisor.go
syz-manager/covfilter.go

If coverage filter is enabled, executor filters comparisons based on PCs.
But we don't include comparison callback PCs in the filter,
so most of them will be falsely filtered away.
Add comparison callback PCs to symbols and compile units and use
both when creating coverage filter. But still use only coverage
PCs while generating coverage reports.
Reported-by: Kaipeng Zeng
Link: https://groups.google.com/g/syzkaller/c/mD0wv-A2wno/m/v1ntQbTUAwAJ

pkg/cover: fix comparison filtering

---

executor/executor.cc
pkg/csource/csource.go
pkg/csource/csource_test.go
pkg/csource/options.go
pkg/csource/options_test.go
pkg/instance/instance.go
pkg/instance/instance_test.go
pkg/ipc/ipc.go
pkg/ipc/ipc_test.go
pkg/ipc/ipcconfig/ipcconfig.go
pkg/mgrconfig/load.go
pkg/repro/repro.go
pkg/rpctype/rpc.go
pkg/runtest/run.go
sys/linux/init.go
sys/targets/targets.go
syz-fuzzer/fuzzer.go
syz-fuzzer/testing.go
syz-manager/hub.go
syz-manager/manager.go
tools/syz-crush/crush.go
tools/syz-execprog/execprog.go
tools/syz-hubtool/hubtool.go
tools/syz-runtest/runtest.go
vm/vm.go
vm/vm_test.go

Add sys/targets.Timeouts struct that parametrizes timeouts throughout the system.
The struct allows to control syscall/program/no output timeouts for OS/arch/VM/etc.
See comment on the struct for more details.

all: make timeouts configurable

---

pkg/build/gvisor.go

The instrumentation filter has to match all sub-packges of
//pkg/sentry/platform.
Signed-off-by: Andrei Vagin <avagin@google.com>

build/gvisor: don't instrument the platform code

---

syz-manager/manager.go
syz-manager/rpc.go

We used to print disabled syscalls before failing due to an error.
This helped to debug "all system calls are disabled" error.
After a recent change we fail before printing disabled syscalls,
as the result manager just prints "all system calls are disabled"
and fails. Restore the check sequence.

syz-manager: fix machine check sequence

---

executor/common.h
pkg/csource/generated.go

```
<stdin>:353:4: error: misleading indentation; statement is not part of the previous 'if' [-Werror,-Wmisleading-indentation]
kill_and_wait(pid, &status);
^
<stdin>:351:3: note: previous statement is here
if (current_time_ms() - start < 5000)
^
1 error generated.
```
dashboard link: https://syzkaller.appspot.com/bug?extid=38fe37bc451a42e6c9a4
Reported-by: syzbot+38fe37bc451a42e6c9a4@syzkaller.appspotmail.com

executor/common: repair clang complaint about bad indentation

---

pkg/build/freebsd.go

This option is required for the TCP RACK and TCP BBR stack.

pkg/build: use RATELIMIT kernel option on FreeBSD

---

prog/prio.go
prog/prio_test.go
syz-manager/html.go
tools/syz-showprio/showprio.go

Switch from float32 to int32.
Float32 is super slow in arm emulation.
Plus flats are generally non-deterministic due to order of operations,
so we needed to do additional sorts to deal with that. Now we don't.

prog: make priority calculation faster

---

syz-manager/covfilter_test.go

Support little as well as big endian architectures.
Fixes this on s390x arch:
=== RUN   TestCreateBitmap
2021/01/12 16:42:44 coverage filter from 0x81000000 to 0x81200020, size 0x200020, pcs 2
covfilter_test.go:22: bad region 0x81/0x20002000
--- FAIL: TestCreateBitmap (0.18s)

syz-manager: fix endianess for covfilter test

---

docs/syzbot.md

The official LLVM repo hosts prebuilt binaries for various distributions
and architectures, so let's use that one.
---
syzbot was updated with the official 11.0.1 build for Ubuntu 16.04.

docs: add link to clang 11.0.1 release binaries

---

dashboard/app/app_test.go
dashboard/app/bisect_test.go
dashboard/app/config.go
dashboard/app/email_test.go
dashboard/app/entities.go
dashboard/app/jobs.go
dashboard/app/jobs_test.go
dashboard/app/notifications_test.go
dashboard/app/reporting.go

Currently we can CC specific people for bugs on a particular kernel repo
(always, upstream, for build bugs). Add similar functionality for bugs
on a particular manager. This will be needed to CC people on clang instances.

dashboard/app: allow CCing people for bug on specific manager

---

pkg/build/gvisor.go

Instrumenting this package is too slow--every time the Sentry switches
to the application, task work will iterate through all of the coverage
counters. Instrumenting this code path will add many atomic operations
on race builds, drastically degrading performance.

pkg/build: exclude gvisor pkg/coverage from coverage instrumentation

---

executor/common_linux.h
pkg/csource/generated.go

KVM was removed for arm architecture.
Latest Linux headers don't contain <asm/kvm.h> for arm.
So don't even include them.

executor: don't include kvm on arm

---

tools/docker/syzbot/Dockerfile

A new image required to build i386 executables in bullseye.

tools/docker: add libc6-dev-i386-amd64-cross to syzbot image

---

dashboard/app/app.yaml

With the default f1 setting, the app episodically crashes with:
Exceeded soft memory limit of 256 MB with 264 MB after servicing 25 requests total.
See https://cloud.google.com/appengine/docs/standard/go/config/appref#instance_class

dashboard/app: switch to f2 app class

---

syz-ci/syz-ci.go

Relative paths generally work except for few cases
where we e.g. start a subprocess in another dir and
pass a path from config to it (e.g. kernel build make).
Explicitly turn all paths into absolute to support
relative paths everywhere.

syz-ci: allow to use relative paths in config

---

pkg/build/linux_linux.go
syz-ci/syz-ci.go

- pkg/build: extend error message
- syz-ci: don't make compiler/ccache paths absolute

dvyukov syz ci abs paths

---

tools/docker/syzbot/Dockerfile

It's used by kernel/gen_kheaders.sh.
Update #2096

tools/docker/syzbot: add cpio

---

dashboard/app/main.go
dashboard/app/templates.html

Show crash title for each crash, since they can be different now.
More fancy solutions are possible, but let's start with just
exposing it.
Remove Maintainers instead, I am not sure who/how uses them.
Nobody uses them now to the best of my knowledge, but they
take lots of page space.
Update #1575

dashboard/app: show crash titles

---

sys/linux/filesystem.txt
sys/linux/sys.txt
sys/linux/sys.txt.const

Hi,
This commits add a new syscall and new variants for Linux. It may be useful to fuzz features like Landlock #2380 .
I'm not sure how to handle the `fork()` syscall because of its return value (cf. `breaks_return` for `clone3()`).
I'm also not sure how to write tests with `fork()` or `clone()` because they create two flows of execution. Is there a way to have conditions in such tests?

Add Linux syscall variants

---

pkg/build/gvisor.go

$ bazel build --features=race  //runsc:runsc-race
...
WARNING: --features=race is no longer supported. Use
--@io_bazel_rules_go//go/config:race instead.

build/gvisor: fix compile time warning

---

sys/targets/targets.go

syzbot fails with:
error: use of undeclared identifier 'SYS___realpathat'
error: use of undeclared identifier 'SYS___realpathat'

sys/targets: enable more syscall defines for freebsd

---

sys/linux/filesystem.txt

Simplify and align `mount$tmpfs()` with other mount variants.
The current `mount$tmpfs()` works but uselessly use an input string. Align it with `mount$bpf`, `mount$overlay` and `mount$binder`.

sys/linux: simplify mount$tmpfs

---

pkg/host/features_linux.go
pkg/host/features_linux_test.go

syscall.Utsname is hard to use portably, see:
https://github.com/google/syzkaller/pull/2418#issuecomment-774858512
Switch to unix.Utsname which does not have this problem.

pkg/host: use unix.Utsname instead of syscall.Utsname

---

pkg/csource/csource_test.go
pkg/csource/options.go
pkg/runtest/run.go
pkg/runtest/run_test.go

Need to check arch requirement early as some programs
may fail to deserialize on some arches due to missing syscalls.
See discussion on #2380.
Also support negative arch requirements (-arch=amd64).

pkg/runtest: check arch requirement early

---

docs/syscall_descriptions.md

Synchronize with commit 2bd9619f7621 ("pkg/runtest: check arch
requirement early"), which removes TestSysTests.

docs: update test for syntax

---

pkg/build/gvisor.go

It was a part of the pkg/sentry/platform, but recently it was moved out.

pkg/build: exclude gvisor pkg/ring0 from coverage instrumentation

---

pkg/vcs/linux.go

All bisections started failing with:
Compiler lacks asm-goto support.
Use gcc 10 for v5.9+.

pkg/vcs: use gcc 10 for linux v5.9+

---

sys/linux/sys.txt
sys/targets/common.go

Enable creation of a safe character device: /dev/null .
Also add mknodat$null and mknodat$loop .

Mknod variants

---

executor/common_linux.h
executor/executor.cc
pkg/csource/generated.go
sys/linux/test/syz_genetlink_get_family_id

We used to use our own netlink socket and then fail
on any errors. But commit "sys/linux: add ieee802154 descriptions"
made it possible to use fuzzer-provided socket,
and fuzzer can pass any invalid fd.
So don't fail on errors now.
Fixes #2444

executor: don't fail in syz_genetlink_get_family_id

---

dashboard/app/jobs.go
dashboard/app/reporting.go

This restriction was meant or emails.
But now we don't embed log in emails, they are provided as dashboard links.
Now this only affects external reporting, which can handle large logs itself.
On the other hand, external reporting does not have a way to "restore" full log.
Remove the restriction.

dashboard/app: remove restriction on max log size

---

sys/targets/targets.go

copy_file_range is also not defined in the syzbot host image.

sys/targets: emit syscall numbers for more syscalls on freebsd

---

executor/executor.cc

Print details and errno after SYZFAIL line.
pkg/report captures output after SYZFAIL line,
so it's better to have details after that line
so that they are captured in report.

executor: improve SYZFAIL message

---

pkg/report/openbsd.go
pkg/report/testdata/openbsd/report/35

The witness output was recently changed in order to aid tracking down
scenarios in which lock ordering data is missing. This is probably a bug
and turning them into unique reports should hopefully help syzkaller
being able to find a reproducer.
The existing inode suppression must be tweaked a bit order to not flag
the relevant reports as suppressed.

pkg/report: improve witness reports on OpenBSD

---

AUTHORS
CONTRIBUTORS
pkg/mgrconfig/config.go
pkg/mgrconfig/load.go
syz-manager/manager.go

This doesn't change any current behaviour, but makes it possible to keep arbitrarily many crash logs.

Make the maximum number of crash logs to store configurable

---

AUTHORS
CONTRIBUTORS
sys/linux/prctl.txt

This fixes 9 prctl variants because of a non-zero fifth syscall argument.

Fix prctl variants

---

pkg/cover/backend/backend.go
pkg/cover/backend/elf.go
pkg/cover/report.go
pkg/cover/report_test.go
pkg/mgrconfig/config.go
pkg/symbolizer/symbolizer.go
pkg/symbolizer/symbolizer_test.go
syz-manager/cover.go
syz-manager/manager.go
tools/syz-cover/syz-cover.go
vm/qemu/qemu.go

PC returned for dynamic loaded module (DLKM) is not
parsed in coverage page.
So the commit is to use DLKM modules' load address
to restore the PC and show coverage data of DLKM.
As the load address is written in cfg file, so kaslr
needs to be disabled.
And for linux target, load address is getting from
/proc/modules during instance setup.
For either manual or auto address setting case,
name and path are needed in config kernel_modules, where
name is module name on target.
path is module unstripped object path on host.
addr is decimal value of module load address on target.
Example of config:
"kernel_modules": [
{
"name": "nf_nat",
"path": "/usr/src/linux-source/net/netfilter/nf_nat.ko",
"addr": 18446744072637911040
}
]
*********************************************************************** …

all: add KernelModule cfg to show DLKM coverage

---

syz-manager/manager.go

We rotate crash log/report files so that we don't fill the whole disk.
But we only save report file if it's not empty. As the result
during rotation it's possible to save a new log, but leave an old
report in place. Which leads to a confusing combination.
Remove report file is the report is empty.

syz-manager: remove stale report files

---

executor/common_linux.h
pkg/csource/generated.go

/sys/kernel/debug/x86/nmi_longest_ns is x86 specific,
don't set it on non-x86 arches.

executor: don't setup x86-specific sysctl on non-x86

---

pkg/host/machine_info.go
pkg/host/machine_info_linux_test.go

- pkg/host: fix nil deref on non-linux
- pkg/host: add TestCollectMachineInfo
- pkg/host: don't include empty machine info sections

dvyukov modules info fix

---

executor/cov_filter.h
executor/executor.cc
syz-fuzzer/fuzzer.go

Some target device has ro rootfs, when cover filter enabled,
syz-fuzzer will crash.
So use TMPDIR to store syz-cover-bitmap file.

executor, syz-fuzzer: fix readonly root

---

vm/qemu/qemu.go

Don't pass cmdline arguments that are not needed for basic operation.
We used to enforce too many cmdline args that are really up to user.
Users may not want panic_on_warn, or KVM configuration is really up to user
(should be setup the way it's setup in real targets of interest).
Leave all these args to user. CONFIG_CMDLINE is the right way for user
to configure default args.

vm/qemu: remove panic_on_warn/kvm/etc cmdline args

---

AUTHORS
docs/executing_syzkaller_programs.md

'scp' command needs 10022 port number specified to establish connection
over which vm is listening. If it isn't specified, scp tries to connect
over port 22 and connection fails.
The other docs write machine as 'root@localhost'. Replace it here to
avoid confusion.
Collon is necessary at the end for the command to work.

docs: fix scp command in instructions

---

executor/cov_filter.h
syz-manager/covfilter.go
syz-manager/covfilter_test.go

There is an out-of-bound array access when cov filter enabled.
1 byte less is allocated

syz-manager, executor: fix out-of-bound access

---

.github/workflows/oss-fuzz.yml

It's claimed to be fixed:
https://github.com/google/oss-fuzz/issues/3670

.github/workflows: re-enable oss-fuzz

---

Makefile
executor/common_fuchsia.h
pkg/build/fuchsia.go
pkg/csource/generated.go
pkg/mgrconfig/load.go
syz-ci/updater.go

Multiple small commits to fix various issues in building syzkaller for fuchsia.
* `driver.h` file moved. This breaks syz-executor build.
* There's no need to build syz-executor if we are building targetting fuchsia: that binary gets built as part of the fuchsia build.
* `zircon.elf` file moved. This breaks syz-ci.
* `goma` is deprecated. Disable for now.

Fix fuchsia build

---

docs/linux/setup_linux-host_android-device_arm-kernel.md

Sandbox value needs quotes,
but we can simply drop sandbox as "none" is the default value.
Fixes #2526

docs/linux: fix config syntax

---

pkg/cover/backend/pc.go
syz-manager/covfilter.go

Hi @dvyukov ,
It seems we made a mistake in the cover filter.
The PCs of compileunits or symbols is the address of "call __sanitizer_*".
But, what the cover filter of the executor needs is the return address of it.
Although we drop the lowest 4-bit of address, it would cause a little PC were filtered.

syz-manager: fix createCoverageBitmap

---

docs/contributing.md

Paths like SOURCEDIR must be absolute as they're being used as volume
paths given to Docker and will be interpreted as Docker volume names if
not absolute paths.

docs/contributing.md: Fix syz-env invocation

---

executor/common_linux.h
pkg/csource/generated.go

This blocks some of the ways the fuzzer can trigger a reboot.
ctrl-alt-del=0 tells kernel to signal cad_pid instead of rebooting
and setting cad_pid to the current pid (transient "syz-executor setup") makes it a no-op.
For context see: https://groups.google.com/g/syzkaller-bugs/c/WqOY4TiRnFg/m/6P9u8lWZAQAJ

executor: set ctrl-alt-del sysctl to 0

---

sys/linux/perf.txt

Updates perf_event_attr (perf events subsystem) to be in sync with
latest linux-next.
This includes all the changes I used to test the perf+SIGTRAP series: https://lkml.kernel.org/r/20210408103605.1676875-1-elver@google.com

sys/linux: update perf_event_attr based on latest linux-next

---

sys/freebsd/socket_inet.txt
sys/freebsd/socket_inet_sctp.txt

The size of struct sockaddr_storage is always 128 bytes.
So the padding after struct sockaddr_in, which is of size 16,
needs to be an array of 14 uint64s.
This allows to describe the structures used in the SCTP socket
options as unpacked

sys/freebsd: fix struct sockaddr_storage usage

---

CONTRIBUTORS
docs/contributing.md
pkg/cover/backend/backend.go
pkg/cover/backend/dwarf.go
pkg/cover/backend/elf.go
pkg/cover/backend/mach-o.go
pkg/cover/backend/modules.go
pkg/cover/report_test.go
pkg/host/syscalls.go
tools/check-commits.sh

This is my first patch set in my ongoing effort to implement XNU/Darwin support in syzkaller: google/syzkaller#2553
I've tested this set as part of my more complete XNU syzkaller POC and can confirm this at least enables me to visit the `/cover` endpoint, after some coverage has been collected, and see some pretty red lines and sometimes even numbers next to those lines. ;)
Let me know what you think.

pkg/cover/backend: add mach-o object support in coverage machinery

---

tools/syz-symbolize/symbolize.go

Signed-off-by: Dongliang Mu <mudongliangabcd@gmail.com>
Align "}`))"

tools/syz-symbolize: fix a code format issue

---

syz-fuzzer/fuzzer.go

We build choice table only after we received the initial corpus,
so we don't check the initial corpus in deserializeInput,
we check it later in BuildChoiceTable.

syz-fuzzer: fix nil deref in deserializeInput
