google/syzkaller

AUTHORS, CONTRIBUTORS, Makefile, sys/decl.go, sys/random.txt, sys/socket.txt, sys/tun.txt, sysgen/sysgen.go
This commit adds  "/dev/random, /dev/urandom and /dev/net/tun" support.
=> sys: support /dev/random and /dev/net/tun

README.md
I thought this may be a valuable addition, as this method may be unknown to some
users.
=> added note for email based subsciption for the mailinglist

vm/adb/adb.go
The code to detect the ttyUSB number that a Suzy-Q connected device was
exposing wasn't handling the case when the devices were plugged in via a
USB hub (which extends the port numbering scheme). This CL changes the
regexp to detect the serial correctly in these cases as well.
=> Improve Case Closed Debugging Port Detection.

CONTRIBUTORS
Add Billy Lau as new collaborator so that he can add changes to syzkaller.
=> Add new collaborator to CONTRIBUTORS

prog/encodingexec_test.go, prog/mutation.go, prog/prio.go, prog/rand.go, sys/align.go, sys/decl.go, sys/test.txt, sysgen/sysgen.go
=> Emit BufferBlob for array[int8]

tools/create-image.sh, vm/qemu/qemu.go
Fix startup of a fresh debian-wheezy virtual machine.
=> VM startup fixes

prog/validation.go
Also update validation code to use arg.Type instead of passing typ recusively.
=> prog: fix cheking nonoptional nil pointers in validation

sysgen/sysgen.go
=> sysgen: always check dir when generating an argument

CONTRIBUTORS, syz-manager/manager.go, vm/adb/adb.go, vm/kvm/kvm.go, vm/qemu/qemu.go
check if `cfg.Bin` in `$PATH`
fix Detect missing ADB #93
=> vm:  check if `cfg.Bin` in $PATH, fix issue #93

report/report.go, syz-manager/cover.go, syz-manager/manager.go, tools/syz-report/syz-report.go, tools/syz-symbolize/symbolize.go
save and reuse  values  which are used more than once
=> symbolizer, manager: save and reuse value

pkg/git/git.go, syz-gce/syz-gce.go
Move few helper git-related functions from syz-gce
to a separate pkg/git package.
=> pkg/git: add new package

csource/common.go, executor/common.h
=> executor: add sys/sysmacros.h include for makedev in newer gcc

report/guilty.go, report/guilty_test.go, syz-manager/html.go
A simple prototype of extracting the guilty file from a report.
Need to run this on bots and see in which cases it extracts the file incorrectly.
=> report: extract guilty file

pkg/repro/repro.go
A work in progress.
- try all programs from log with short duration
- execute programs from last to first
- simplified logic
Updates #179
=> Minor reproducing improvements

tools/create-image.sh
install gcc and glibc because useful compile reproduce testing C program in current kernel version on QEMU!
=> Added GCC and glibc

Makefile, docs/setup_linux-host_android-device_arm64-kernel.md
This is a bit hacky but hides some of the ugly cruft from the instructions.
=> Add 'make android' target and document it

pkg/git/git.go, pkg/report/guilty.go
Tested locally. Requires path to the linux kernel checkout directory, no sure if adding this config into manager makes sense now.
Fixes #242
=> report: add get maintainers function

pkg/repro/repro.go
=> pkg/repro: return crash report

syz-manager/manager.go
We now take reports from repro and they are not symbolized.
Symbolize them.
=> syz-manager: symbolize repro reports

executor/common.h, pkg/csource/common.go, pkg/csource/csource.go, pkg/repro/repro.go
- try extracting C repro before simplifying generic prog options
- make all usleeps random to increase the chance of guessing the right timings
Updates #179
=> Improve C repros

docs/setup.md, docs/setup_linux-host_android-device_arm64-kernel.md, docs/setup_linux-host_isolated.md, docs/setup_linux-host_qemu-vm_arm64-kernel.md, docs/setup_ubuntu-host_odroid-c2-board_arm64-kernel.md, docs/setup_ubuntu-host_qemu-vm_x86-64-kernel.md, docs/syscall_descriptions_syntax.md, docs/troubleshooting.md, docs/usage.md
=> docs: small fixes

vm/gce/gce.go
Sometimes we get truncated console output during repro.
The problem is that we start the console reading ssh command,
but do not wait for it to actually connect and start piping console.
Wait while the command actually starts piping console before
starting the target command.
=> vm/gce: fix truncated console output

.clang-format, .travis.yml, Makefile
=> Initial travis-ci integration

pkg/git/git.go, syz-ci/manager.go
Dashboard needs to know when bug fixing commits reach
builders in order to fully close bugs.
Send commits that dashboard is interested in to dashboard.
=> syz-ci: send commits to dashboard

vendor/golang.org/x/net/context/go19.go, vendor/golang.org/x/net/context/pre_go19.go
See https://github.com/golang/go/issues/21337
=> vendor/golang.org/x/net/context: fix fmt with Go 1.8

pkg/csource/csource.go, prog/analysis.go, prog/checksum.go, prog/encoding.go, prog/encodingexec.go, prog/mutation.go, prog/prog.go, prog/prog_test.go, prog/rand.go, prog/size.go, prog/validation.go, sys/align.go, sys/decl.go, sys/syz-sysgen/sysgen.go
We currently use uintptr for all values.
This won't work for 32-bit archs.
Moreover in some cases we use uintptr but assume
that it is always 64-bits (e.g. in encodingexec).
Switch everything to uint64.
Update #324
=> sys, prog: switch values to to uint64

docs/headerparser_usage.md, docs/syscall_descriptions.md, tools/syz-headerparser/headerlib/container.py, tools/syz-headerparser/headerlib/header_preprocessor.py, tools/syz-headerparser/headerlib/struct_walker.py, tools/syz-headerparser/headerparser.py, tools/syz-headerparser/test_headers/th_a.h, tools/syz-headerparser/test_headers/th_b.h
This is an initial import of headerparser, a tool that assists in writing syzkaller device descriptions.
=> tools: Add syz-headerparser to assist in writing system call descriptions

pkg/ast/ast.go, pkg/ast/format.go, pkg/ast/parser.go, pkg/ast/parser_test.go, pkg/ast/scanner.go, pkg/ast/test_util.go, pkg/ast/walk.go, pkg/compiler/compiler.go, pkg/compiler/compiler_test.go, pkg/compiler/consts.go, pkg/compiler/consts_test.go, pkg/compiler/testdata/consts.txt, pkg/compiler/testdata/consts_errors.txt, pkg/compiler/testdata/errors.txt, sys/sys.txt, sys/syz-extract/extract.go, sys/syz-sysgen/sysgen.go, tools/syz-fmt/syz-fmt.go
=> pkg/compiler: more static error checking

vm/isolated/isolated.go
Do not fail a reboot if the reboot command returns an error. Reduces the
wait time per ssh commands to 30 seconds.
Signed-off-by: Thomas Garnier <thgarnie@google.com>
=> Fix reboot support for VM isolated

executor/common_linux.h
Executor process does not have any env, including PATH.
On some distributions, system/shell adds a minimal PATH, on some it does not.
Set own standard PATH to make it work across distributions.
=> executor: set own PATH when starting subprocesses

syz-manager/html.go
This adds /rawcover handler which returns a file with all covered so far PCs, e.g.:
0xffffffff8100763e
0xffffffff81007667
...
0xffffffff8100767d
Useful for offline coverage processing, diffing coverage, etc.
In particular allows to do:
curl http://localhost:1234/rawcover | addr2line -e vmlinux
=> syz-manager: expose raw cover in http handler

docs/configuration.md
docs: fix configuration documentation
Fix the relative link.
=> docs: fix configuration documentation

AUTHORS, CONTRIBUTORS, docs/netbsd.md
- Added a new file that documents the image preparation and running instructions for NetBSD.
=> Added documentation for NetBSD.

dashboard/app/reporting.go, dashboard/app/reporting_email.go, pkg/email/parser.go, pkg/email/parser_test.go
1. Allows sending emails upstream.
2. Filter out duplicate emails coming from our mailing lists.
3. Increase retry attempts for email commands
(don't want them to fail due to concurrent crash reports from managers).
=> dashboard/app: email fixes

README.md, docs/akaros/README.md, docs/akaros/found_bugs.md, docs/found_bugs.md, docs/setup.md
=> docs: add found_bugs for akaros

pkg/git/git.go, pkg/kernel/kernel.go, pkg/osutil/osutil_akaros.go, pkg/osutil/osutil_appengine.go, pkg/osutil/osutil_bsd.go, pkg/osutil/osutil_darwin.go, pkg/osutil/osutil_fuchsia.go, pkg/osutil/osutil_linux.go, pkg/osutil/osutil_windows.go
=> pkg/kernel: sandbox make invocation

.travis.yml, Makefile
=> makefile: move diff check to makefile from travis script

executor/syscalls_freebsd.h, executor/syscalls_linux.h, executor/syscalls_netbsd.h, pkg/compiler/check.go, pkg/compiler/testdata/errors2.txt, sys/freebsd/amd64.go, sys/freebsd/socket.txt, sys/freebsd/socket_unix.txt, sys/linux/386.go, sys/linux/amd64.go, sys/linux/arm.go, sys/linux/arm64.go, sys/linux/kvm.txt, sys/linux/ppc64le.go, sys/linux/socket_bluetooth.txt, sys/linux/socket_inet_sctp.txt, sys/netbsd/amd64.go, sys/netbsd/socket.txt, sys/netbsd/socket_unix.txt
This [almost] always means a bug in descriptions.
Fix all bugs identified by the check.
=> pkg/compiler: add check that len does not refer to array with varlen elems

pkg/repro/repro.go
=> pkg/repro: rerun repro when report is corrupted

pkg/report/linux.go, pkg/report/linux_test.go
=> pkg/report: add sl*b.c to guilty blacklist

pkg/report/linux.go, pkg/report/linux_test.go
Fix for: https://groups.google.com/forum/#!msg/syzkaller-bugs/wUNFqXiscyk/ywEAZ283AgAJ
=> pkg/report: detect suspicious RCU usage report corruption

pkg/report/linux.go, pkg/report/linux_test.go
=> pkg/report: improve bad unlock balance corruption detection

pkg/report/linux.go
pkg/repro expects pkg/report to return CrashStart index in the whole report, not only in the kernel output.
=> pkg/report, pkg/repro: fix report parsing

pkg/report/linux.go, pkg/report/report.go
=> pkg/report: return raw log in Report.Output

pkg/report/linux.go, pkg/report/linux_test.go
=> pkg/report: various improvements

pkg/report/linux.go, pkg/report/report_test.go, pkg/report/testdata/linux/report/135
=> pkg/report: fix __this_cpu_* report header call trace capture

docs/configuration.md, syz-manager/manager.go, syz-manager/mgrconfig/mgrconfig.go
This patch-set fixes duplicated emails, and enables group emails.
=> syz-manager: improve email handling

prog/mutation.go, prog/rand.go, prog/size.go, prog/size_test.go
=> prog: mutate len arguments

dashboard/app/access.go, dashboard/app/access_test.go, dashboard/app/api.go, dashboard/app/app.yaml, dashboard/app/app_test.go, dashboard/app/bug.html, dashboard/app/config.go, dashboard/app/fix_test.go, dashboard/app/forbidden.html, dashboard/app/handler.go, dashboard/app/jobs.go, dashboard/app/main.go, dashboard/app/main.html, dashboard/app/reporting.go, dashboard/app/static/style.css, dashboard/app/templates.html, dashboard/app/util_test.go
This is the bulk of work for opening dashboard.
Implement finer-grained access control (admin/user/public).
Show only info designated to the current user access level.
Rework UIs for more clarity re bug statuses.
Show fixed bugs.
=> dashboard/app: finer-grained access control

docs/linux/troubleshooting.md
It took me a bit to figure out this kernel configuration quirk, so
thought it may be helpful to add to the troubleshooting section!
=> [docs] Add Linux network troubleshooting guidance.

.travis.yml
Need to see if build of this pull request succeeds.
=> buildbot: fix broken deb package link

AUTHORS, CONTRIBUTORS, docs/netbsd.md
When I was installing syzkaller I faced a lot of issues and needed more information on how exactly to go about in the installation. So to make this process easier, I have included what I found missing. Might add more to this later on too.
=> netbsd.md: Changes made in file about missing clarity

.travis.yml, Makefile
=> Makefile: enable gometalinter on travis

dashboard/app/email_test.go, dashboard/app/mail_bug.txt, dashboard/app/reporting_email.go, docs/syzbot.md, pkg/ipc/ipc_test.go
=> dashboard links

docs/linux/setup_linux-host_android-device_arm64-kernel.md
Signed-off-by: Jean-Baptiste Theou <jb@essential.com>
=> docs: add link for PH-1 kernel

docs/linux/setup_linux-host_isolated.md
Fixed typo for JSON config file. It has a comma after "false". If this comma exist, it always gives issue about object thing.
=> Updated file and fixed typo.

executor/syscalls_linux.h, sys/linux/gen/386.go, sys/linux/gen/arm.go, sys/linux/gen/arm64.go, sys/linux/video4linux.txt
Signed-off-by: Denis Efremov <efremov@linux.com>
=> sys/linux: video4linux v4l2_jpegcompression APP_len fix

.travis.yml, executor/common.h, pkg/csource/csource_test.go, pkg/csource/generated.go
=> .travis.yml: use clang-format 6.0.1

docs/contributing.md
Details how to run tests and how to work around gofmt bug.
=> [doc] Update contributing instructions.

AUTHORS, CONTRIBUTORS, vm/vm.go, vm/vmimpl/console_openbsd.go, vm/vmm/vmm.go
My ambition is to upstream support for OpenBSD in somewhat atomic PRs.
This is a first step adding support for the Virtual Machine Monitor
(VMM) found on OpenBSD.
If wanted, I could squash it into a single commit.
=> vm/vmm: support for vmm found on OpenBSD

Makefile
=> Makefile: Enable working with symlinked directories

sys/targets/targets.go
Location of some sysroot includes changed; ergo, Fuchsia cross-compile
flags need an update.
=> Fix executor build for Fuchsia.

tools/create-openbsd-gce-ci.sh, tools/create-openbsd-vmm-worker.sh
* Fixed pkg_add status checking
* Switched to qcow2 test image (enables #766)
* Minor GC
=> tools/create-openbsd*: Support post-version flip snapshots

docs/linux/setup_ubuntu-host_qemu-vm_x86-64-kernel.md
=> Added kernel config options for debian stretch

docs/openbsd/setup.md, pkg/csource/common.go, pkg/csource/csource_test.go, sys/targets/targets.go, tools/create-openbsd-gce-ci.sh
First stab at adding support for reproducers on OpenBSD, as discussed in #790.
=> Add support for creating reproducers on OpenBSD

sys/targets/common.go
Now that we can create reproducers on OpenBSD, I ran into a different problem.
Some targets (NetBSD and OpenBSD) have a mmap() padding argument between the
file descriptor and offset. Make sure to omit such argument in MakePosixMmap().
Otherwise, reproduce programs will crash at runtime since the expected mapping
at 0x20000000 is not established.
=> sys: conditionally add padding argument in MakePosixMmap()

executor/common_bsd.h, pkg/host/host.go, pkg/host/host_openbsd.go
For the curious: https://blackgnezdo.github.io/syz-execprog
=> openbsd: enable packet injection

docs/syscall_descriptions_syntax.md
=> Fixed a tiny typo

tools/syz-execprog/execprog.go
Fix a bad fix for `ProgInfo` usage.
=> ipc: fix ProgInfo usage better

executor/common_bsd.h, pkg/csource/generated.go
Fix the compilation on FreeBSD when not supporting the tun
interface.
=> executor: Fix compilation on FreeBSD

executor/common_bsd.h, executor/executor_bsd.h, pkg/csource/csource_test.go, pkg/csource/generated.go
=> openbsd: repair pkg/csource_test

tools/create-openbsd-vmm-worker.sh
@mptre - this theoretically obviates set $lines, but I know that not everybody uses my script :)
=> tools/create-openbsd-vmm-worker.sh: shut off pagination in ddb

pkg/report/gvisor.go, pkg/report/testdata/gvisor/report/2
https://github.com/google/gvisor/commit/99d595869332f817de8f570fae184658c513a43c
changed the format of these to include the registers.
=> pkg/report: update gvisor ptrace regs suppressions

pkg/build/build.go
Before:
--- PASS: TestCompilerIdentity/bazel (1.16s)
build_test.go:33: id: 'WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".'
After:
--- PASS: TestCompilerIdentity/bazel (1.15s)
build_test.go:33: id: '[bazel release 0.20.0]'
=> pkg/build: fix bazel version parsing

executor/common.h, executor/common_bsd.h, pkg/csource/csource.go, pkg/csource/generated.go, pkg/csource/options.go
* expose procid on BSD for tun
* deal with terrible bsd includes
* replicate loop() declaration
@tuexen, could you run regression in pkg/csource on FreeBSD?
=> pkg/csource: support tun and setuid repros on {free,open}bsd

executor/executor_bsd.h
Get ioctl() definitions and usage in sync with the upcoming support
reviewed in https://reviews.freebsd.org/D14599.
=> executor: improve kcov compatibility with upcoming support

executor/executor_bsd.h
=> Kcov freebsd

sys/targets/targets.go
=> sys/targets: use appropriate name for KernelObject on FreeBSD

CONTRIBUTORS, prog/hints_test.go
I believe I fixed some typo in comment in hints_test.go that confused me.
=> prog/hints_test.go: fix something wrong in commented out code 

sys/openbsd/init.go
Prevents corpus explosion with corrupted coverage data.
The two parallel runs of:
`doas ./syz-execprog -cover -coverfile /tmp/{fixed,unfixed} r.syz`
show markedly different coverage pictures:
unfixed:
```
2019/01/12 13:55:38 parsed 1 programs
2019/01/12 13:55:38 executed programs: 0
2019/01/12 13:55:38 call #0: signal 821, coverage 2438
2019/01/12 13:55:38 call #1: signal 243, coverage 1363
2019/01/12 13:55:38 call #2: signal 502, coverage 1993
2019/01/12 13:55:38 call #3: signal 15, coverage 44
2019/01/12 13:55:38 call #4: signal 335, coverage 8196
```
fixed:
```
2019/01/12 13:51:57 parsed 1 programs
2019/01/12 13:51:57 executed programs: 0
2019/01/12 13:51:57 call #0: signal 837, coverage 2491
2019/01/12 13:51:57 call #1: signal 241, coverage 1341
2019/01/12 13:51:57 call #2: signal 27, …
```
=> sys/openbsd: avoid /dev/fd node creation

executor/executor_bsd.h, tools/kcovtrace/kcovtrace.c
KCOV support for FreeBSD support has been committed in [342962](https://svnweb.freebsd.org/changeset/base/342962). Update the usage to latest API changes and make use of the header.
=> FreeBSD KCOV support

AUTHORS, CONTRIBUTORS, docs/netbsd.md
Refactored the document and updated the changes. 
=> docs/netbsd.md: updated documentation for NetBSD

syz-manager/html.go
=> Add repo version and config link on stats page

docs/syscall_descriptions_syntax.md
update syntax about unions,union can have "size" attribute like struct,too.
=> docs/syscall_descriptions_syntax.md: update syntax about union

syz-manager/html.go
=> syz-manager: provide config name in Stats

pkg/vcs/netbsd.go, pkg/vcs/vcs.go
=> pkg/vcs : Added vcs support for netbsd

pkg/build/build.go, pkg/build/netbsd.go, sys/targets/targets.go
This adds support to build a NetBSD kernel with kASan Enabled.
=> pkg/build: Add basic support for NetBSD

pkg/build/build.go, pkg/build/build_test.go, pkg/build/linux.go, pkg/build/openbsd.go
This should get kernel build errors reported in syz-ci console.
@mptre FYI
=> pkg/build: share extractRootCause with openbsd

pkg/build/build.go, pkg/build/build_test.go, pkg/build/linux.go, pkg/build/netbsd.go, pkg/build/openbsd.go
=> pkb/build: extractRootCause for NetBSD too

docs/linux/setup_ubuntu-host_qemu-vm_x86-64-kernel.md
If possible, could you move "git vim make" into the script and install them by default?
=> correct image name and remove packages already installed in the script

docs/netbsd/README.md
Added documentation on how to cross compile on Linux since it should be easier.
=> docs/netbsd: Minor changes to the documentation

docs/linux/found_bugs.md
=> remove redundant entry in found_bugs list

pkg/build/build.go, pkg/build/netbsd.go, vm/qemu/qemu.go
1. Made kernel build incremental
2. Added code to copy kernel to disk image
=> pkg/build: Added feature to copy kernel image

docs/netbsd/found_bugs.md
Added a file to hold details of the bugs that we have found and fixed
Currently the format of the file is as below
Short summary of the bug - link to gnats bug report - link to GitHub commit fixing the bug
=> docs/netbsd: Added found_bugs.md

pkg/build/fuchsia.go, pkg/vcs/fuchsia.go
Fuchsia and its repos now live in a new spot!
=> [fuchsia] Update Syzkaller to pull from Fuchsia monorepo.

docs/linux/setup_ubuntu-host_qemu-vm_x86-64-kernel.md, tools/create-image.sh
=> tweak create-image.sh script and modify document about its deployment

docs/freebsd/README.md
=> Add description for setting up a FreeBSD host

docs/found_bugs.md
=> Add missing entries for FreeBSD and NetBSD

docs/linux/setup_ubuntu-host_qemu-vm_x86-64-kernel.md
=> tools/create-image.sh: correct usage examples

docs/netbsd/found_bugs.md
=> docs/netbsd: add the recent bugs

tools/create-image.sh
I finished the following two fixes mentioned in previous PR:
=> Beta Version of create-image.sh

pkg/build/freebsd.go
A couple of small commits that have made syz-ci+FreeBSD a bit easier to use.
=> Fixups for FreeBSD's build code.

pkg/report/openbsd.go, pkg/report/testdata/openbsd/report/14, pkg/report/testdata/openbsd/report/3
=> pkg/report: improve page fault detection on OpenBSD

pkg/report/freebsd.go, pkg/report/testdata/freebsd/report/5, pkg/report/testdata/freebsd/report/6, pkg/report/testdata/freebsd/report/7, pkg/report/testdata/freebsd/report/8
=> Fix matching for traps in kernel mode

syz-manager/manager.go
Signed-off-by: Andrew Donnellan <andrew.donnellan@au1.ibm.com>
=> syz-manager: Fix typo in dashboard stats upload error

docs/openbsd/found_bugs.md
=> docs/openbsd: update found_bugs.md

pkg/host/host_linux.go, pkg/host/host_test.go
Start with a few simple tests that can be extended when needed.
=> host: add kallsyms parsing tests

dashboard/config/upstream-usb.config
=> dashboard/config: update usb config

pkg/email/parser_test.go, pkg/email/patch.go, pkg/email/patch_test.go
Quilt uses a slightly different patch format to traditional git diff/format-patch. Support it.
=> email: support quilt patch format

executor/common_usb.h, pkg/csource/generated.go
Also move some code to helper functions.
=> executor: use NONFAILING in common_usb.h

executor/common_usb.h, pkg/csource/generated.go
=> executor: fix compiler warning

executor/common_usb.h, pkg/csource/generated.go
=> executor: fix another compiler warning

docs/freebsd/found_bugs.md
Thanks to Greg for making me aware of it.
=> docs/freebsd: fix typo

vm/bhyve/bhyve.go
=> vm/bhyve: ensure the VM is destroyed after closing

README.md
=> doc/linux: add one link for linux in the README.md

pkg/build/netbsd.go
Kcov build option added to syzkaller kernel config. Also added the node creation command.
=> pkg/build: Add the KCOV build commands

pkg/report/linux.go, pkg/report/testdata/linux/report/387, pkg/report/testdata/linux/report/388
=> pkg/report: improve usb_submit_urb report titles

docs/netbsd/README.md
=> docs/netbsd: added link to image script

prog/mutation.go
Adds some high-level comments for my understanding what is happening. Work-in-progress: will add more comments.
=> prog/mutation: Add internal comments

pkg/build/netbsd.go
1. Add MKCTF option
2. Remove the command to make the kcov node. Since we do it in the script.
=> pkg/build: fix the failing NetBSD build

executor/executor.cc
Always call write_extra_output() only if the current program or call
can produce extra coverage (== is a syz_usb* syzcall).
=> executor: improve usb coverage attribution

executor/executor_bsd.h
=> pkg/report: use cover protect on NetBSD also

pkg/report/netbsd.go, pkg/report/netbsd_test.go
Ported the existing tests from OpenBSD.
=> pkg/report: Add initial support for report symbolisation

pkg/build/netbsd.go
=> pkg/build: add LOCKDEBUG and KASAN_PANIC

.travis.yml, Makefile
=> travis: use cache

docs/netbsd/README.md
=> docs/netbsd: remove TODO tasks that have been completed

tools/syz-execprog/execprog.go
=> tools/syz-execprog: remove unused parameter

dashboard/app/bisect_test.go, dashboard/app/jobs.go, dashboard/app/jobs_test.go
* createBisectJob() retrieves bugs that are potential candidates for both
BisectCause and BisectFix.
* Modify TestBisectCause() to account for BisectFix jobs that are
returned when polling.
* Add TestBisectFixJob() to check that BisectFix jobs are returned only
after 30 days of reporting.
=> dashboard/app: Allow the dashboard to create BisectFix jobs

dashboard/app/jobs.go
dashboard/app: clean up query inside findBugsForBisection
=> dashboard/app: clean up query inside findBugsForBisection

dashboard/app/bisect_test.go, dashboard/app/bug.html, dashboard/app/main.go, dashboard/app/reporting.go
* Modify the dashboard/app/bug.html template to show fix bisection results.
* Modify handleBug() to fetch and create a uiJob for fix bisection results.
* Modify loadBisectJob() to fetch jobs based on a specified jobType. Change all callers to pass in jobType info into loadBisectJob().
* Add TestBugBisectionResults() to ensure bisection results show up as expected.
=> dashboard/app: allow fix bisection results to be visible on web UI

pkg/build/freebsd.go
=> pkg/build: Enable additional invariants-checking in FreeBSD kernels

executor/common_usb.h, executor/executor.cc, pkg/csource/generated.go
Also simplify timeout related code a bit.
=> executor: add some USB related TODOs

executor/common_bsd.h, pkg/csource/generated.go
=> executer/common_bsd.h: increase the number of tap/tun devices for NetBSD

dashboard/app/bisect_test.go, dashboard/app/main.go, dashboard/app/static/common.js, dashboard/app/static/style.css, dashboard/app/templates.html, pkg/html/generated.go
* Modify uiBug type. Rename BisectCause to BisectCauseDone. Introduce BisectFixDone.
* Modify createUIBug() and MergeUIBug() to set the above fields appropriately.
* Modify bug_list to display the bisection status; remove yesSort() as it is not used anymore. Adjust ".list_table .stat" to appropriate width.
* Add TestBugBisectionStatus() to check bisection status on main page.
* Add file from running "make generate": pkg/html/generated.go
=> dashboard/app: allow main UI to show bisect results

dashboard/app/templates.html
There is a typo and a formatting bug that can be viewed at bugs such as
https://syzkaller.appspot.com/bug?id=f007ef1d7a31a469e3be7aeb0fde0769b18585db
Also cleanup the formatting in surrounding areas so that it is much clearer.
=> dashboard/app: fix UI typo and formatting error

pkg/report/linux.go, pkg/report/testdata/linux/report/409
=> pkg/report: improve ODEBUG titles

pkg/build/fuchsia.go
We have noticed that the build process was being invoked as root. This
change modifies the calls to use osutil.Sandbox before invoking cmds to
build fuchsia.
This is required for the process to use goma, as goma is running under
the syzkaller user.
=> pkg/build: use sandbox to build fuchsia.

executor/common.h, pkg/csource/generated.go
=> executor: fix procid not declared properly for netbsd

dashboard/app/jobs.go, dashboard/app/jobs_test.go
When BisectFix job results in a crash on ToT, the job needs to be retried in the future(30 days from the BisectFix job).
* Modify doneJob() to save the latest crash information corresponding to the bug, and set bug.Bisectfix to BisectNot.
* Add TestBisectFixRetry() to test this functionality.
=> dashboard/app: retry BisectFix if crash still occurs on ToT

prog/analysis.go, prog/any_test.go, prog/encoding.go, prog/generation.go, prog/mutation.go, prog/prog_test.go, prog/rand.go, tools/syz-mutate/mutate.go
=> prog: resource-centric generation/mutation

prog/mutation.go, prog/rand.go
This makes it a bit easier to understand.
Also fix an issue with using flag value as bit number.
=> prog: move all flag mutation logic into flags()

fuzzit.sh
updated fuzzit to v2.4.46. discovered here 
https://github.com/google/syzkaller/pull/1393#issuecomment-530705086
=> updated fuzzit to v2.4.46

.travis.yml, fuzzit.sh
@dvyukov this should fix this https://github.com/google/syzkaller/pull/1397#issuecomment-531229318 
I'll ping again once the travis is finished so you can merge.
Thanks!
=> WIP: fix fuzzit script to work with latest CLI syntax

.golangci.yml
=> updated golangci.yml to exclude new errors

dashboard/config/bits-syzbot.config
=> dashboard/config: add debian stretch options

dashboard/config/netbsd-kasan.config, dashboard/config/netbsd-kubsan.config, pkg/build/netbsd.go
=> pkg/build: build NetBSD kernel from provided config file

docs/syzbot.md
Add in some information about fix bisection in the documentation.
=> docs: update syzbot.md

prog/hints_test.go, prog/mutation.go, prog/mutation_test.go, prog/rand.go, prog/rand_test.go, prog/size.go, prog/types.go
=> prog: use type size when generating/mutating ints

pkg/db/db.go, prog/generation.go, prog/mutation.go, prog/prio.go, prog/prio_test.go, prog/rand.go, tools/syz-mutate/mutate.go, tools/syz-showprio/showprio.go, tools/syz-stress/stress.go
=> prog: better call-to-call priority calculation

pkg/report/freebsd.go, pkg/report/testdata/freebsd/report/10, pkg/report/testdata/freebsd/report/11
=> pkg/report: deduplicate some common FreeBSD panics

dashboard/app/jobs.go, dashboard/app/jobs_test.go
* Modify pollCompletedJobs(); for bugs that are already marked as fixed, invalid or duplicate do not report bisection results.
* Add TestNotReportingAlreadyFixed() to test that reporting does not occur for already fixed bugs.
=> dashboard/app: no reporting fix bisection results for already fixed bugs

syz-fuzzer/fuzzer.go, syz-fuzzer/fuzzer_test.go, syz-fuzzer/proc.go
=> syz-fuzzer: add program priority in corpus

prog/rand.go, prog/rand_test.go
=> syz-manager: fix unwanted syscalls that were enabled

prog/mutation.go
=> prog: fix plain priority for integers

prog/hints.go, prog/hints_test.go
=> prog: add size check during hints mutation

pkg/report/linux.go, pkg/report/testdata/linux/report/427, pkg/report/testdata/linux/report/428
=> pkt/report: Shorten KCSAN report titles

pkg/report/openbsd.go, pkg/report/testdata/openbsd/report/20
=> pkg/report: normalize pool cpu free list modified reports on OpenBSD

executor/executor_linux.h
The kcov extension is being upstreamed and the interfaces has been changed.
=> executor: update kcov remote coverage

pkg/bisect/bisect_test.go
Add tests for the following cases(1 each for cause and fix):
- bisection returns the correct commit
- bisection failed due to crash not occurring on the original commit
- bisection failed as crash occurs on oldest/latest commit
- bisection is inconclusive
=> pkg/bisect: add more tests for various possible bisection results

dashboard/app/app_test.go, dashboard/app/config.go, dashboard/app/jobs.go, dashboard/app/jobs_test.go
* Allow fix bisection to be disabled on kernel repos to which force-pushes occur.
* Pending fix bisection jobs for KernelRepo with FixBisectionDisabled will have to be deleted manually.
* Add TestFixBisectionsDisabled.
=> No bisect next repos

executor/common_usb.h, pkg/csource/generated.go, tools/syz-usbgen/keyboard.c
The number of reported event types changed.
=> executor: update the list of raw usb events

executor/common_usb.h, pkg/csource/generated.go, pkg/host/host_linux.go, tools/syz-usbgen/keyboard.c
The interface is being upstreamed and the interface has changed.
=> executor, pkg/host: update usb raw-gadget interface

docs/syscall_descriptions.md
Clarify that 'make generate' should update syscall description
revision.
=> docs: update syscall_descriptions.md

docs/syscall_descriptions.md
Add detailed instructions to run syz-extract
=> docs:update syscall_descriptions.md

executor/common_linux.h, pkg/csource/generated.go
Contains one simple fix and one debug message addition.
=> Devlink pci fix

pkg/report/linux.go, pkg/report/testdata/linux/report/459
Ignore kobject_put in stack frames.
=> pkg/report: improve reports titles

vm/gvisor/gvisor.go
=> gvisor: show a list of processes in case of any failures

pkg/build/netbsd.go
=> pkg/build: Fix failing NetBSD KMSan build

tools/create-image.sh
It's quite useful for debugging network related stuff.
=> tools/create-image.sh: install tcpdump

pkg/report/freebsd.go, pkg/report/testdata/freebsd/report/12
These can fail in many functions, include the calling function in
the report
=> pkg/report: Add the calling function to sx reports

.github/workflows/main.yml
Chrome bugs-- was wondering if syzkaller would dogfood CIFuzz,
a new feature being rolled out in OSS-Fuzz. It allows for pull 
requests to be fuzzed in CI using fuzz targets enabled in OSS-Fuzz.
=> CIFuzz Dogfood

.travis.yml, docs/linux/external_fuzzing_usb.md, pkg/ipc/ipc.go, prog/mutation.go, prog/mutation_test.go
=> .travis.yml: add go1.14rc1

executor/common_linux.h, pkg/csource/generated.go
The fuzzer will wind up undoing some of this, which is fine, but at
least it now has the chance of hitting some other paths it wasn't
before.
Closes: #1599
=> wireguard: setup some initial devices in a triangle

executor/executor.cc
One observation is that checking for extra cover is very fast
(effectively a memory load), so we can simplify code by removing
th->extra_cover and just check for it always. Additionally, we may
grab some coverage that we would miss otherwise.
Don't sleep for 500 ms at the end if colliding,
we are not going to use the extra coverage in that case anyway.
Check for extra coverage at the end every 100ms to avoid
being killed on timeout before we write any.
Make the 500ms sleep at the end parametrizable.
Enable it for syz_usb syscalls, so we get the same behavior for usb.
But this also allows to get extra coverage for other subsystems.
Some subsystems don't have a good way to detect if we will get any
extra coverage or not. Sleeping for 500ms for all programs slows down
fuzzing too much. So we …
=> executor: refactor extra cover handling

pkg/report/openbsd.go, pkg/report/testdata/openbsd/report/26, pkg/report/testdata/openbsd/report/27
=> pkg/report: normalize soreceive report on OpenBSD

vm/gvisor/gvisor.go
GO's runtime calls the write system call twice to print "panic:"
and "the reason of this panic", so here is a race window when
other threads can print something to the log and we will see
something like this:
panic: log messages from another thread
The reason of the panic.
This confuses the syzkaller blacklist and dedup detection.
=> vm/gvisor: allocate a separate stream of GO's runtime messges

syz-manager/manager.go, vm/gvisor/gvisor.go
This PR addresses Dmiry's comments from #1626.
=> gvisor: code cleanups

executor/common_linux.h, executor/executor.cc, pkg/csource/generated.go, prog/encoding.go, prog/encoding_test.go, prog/generation.go, prog/mutation.go, prog/mutation_test.go, prog/rand.go, prog/rand_test.go, syz-fuzzer/fuzzer.go, syz-fuzzer/proc.go, syz-hub/state/state.go, syz-manager/hub.go, syz-manager/manager.go, syz-manager/rpc.go, tools/syz-mutate/mutate.go, tools/syz-stress/stress.go
=> Dvyukov prog len

pkg/report/linux.go, pkg/report/testdata/linux/report/473, pkg/report/testdata/linux/report/474, pkg/report/testdata/linux/report/475, pkg/report/testdata/linux/report/476, pkg/report/testdata/linux/report/477, pkg/report/testdata/linux/report/478
=> pkg/report: improve report titles

dashboard/config/android/cmdline-5.4, tools/create-gce-image.sh
Looks like it affects not only android-5.4.
=> tools, dashboard: move net.ifnames=0 to create-gce-image.sh

tools/syz-symbolize/symbolize.go
If we want to check if the original crash reproducer was generated is
reproduced we need to generate syzkaller style crash report on
reproducer log and check if hash matches with the original hash. To help
this I created new tool syz-report which takes in the log and generates
report if it contains crash.
=> tools/syz-report: New tool to generate syzkaller report on given log

pkg/build/freebsd.go
Build alternate TCP stacks and ensure that they get loaded.
=> Improve FreeBSD TCP coverage

tools/create-openbsd-gce-ci.sh, tools/create-openbsd-vmm-worker.sh
=> tools/create-openbsd*: update to 6.7

dashboard/config/netbsd-kasan.config, dashboard/config/netbsd-kmsan.config, dashboard/config/netbsd-kubsan.config
Update the NetBSD configs:
- Use tabs instead of whitespaces
- On KMSAN, switch POOL_QUARANTINE to POOL_NOCACHE
- On KASAN, disable modules
- Enable vHCI on all configs
=> dashboard/config: update NetBSD configs

pkg/build/netbsd.go
=> pkg/build: remove all the build dirs for NetBSD

Makefile
Used the recipe from https://github.com/golangci/golangci-lint
Fix #1693
=> Makefile: pin golangci-lint version

pkg/instance/instance.go, tools/syz-bisect/bisect.go
Currenlty only syz file is taken into account when testing.
Use also c source file if available. Still use syz as a "main"
reproducer.
=> pkg/instance: Use syz or c source file when testing

Makefile, dashboard/app/handler.go, dashboard/app/reporting.go, pkg/csource/build.go, pkg/csource/csource_test.go, sys/targets/targets.go, tools/syz-env/env.go
=> sys/targets: better detection for missing/broken cross-compilers

.travis.yml, Makefile
=> Dyvukov travis

sys/targets/targets.go
=> Use clang on freebsd

pkg/csource/build.go, pkg/csource/csource_test.go, sys/syz-extract/linux.go, sys/targets/targets.go, tools/syz-env/env.go
According to
https://github.com/google/syzkaller/pull/1732#issuecomment-627809865,
they have been unused since 3aa3800.
Signed-off-by: Alexander Potapenko <glider@google.com>
=> targets: delete CFlags

executor/common.h, pkg/csource/generated.go
=> executor: fix #ifdef condition for remove_dir()

executor/common.h, pkg/csource/generated.go
=> executor: fix typo

executor/gen.go
=> Improve build

Makefile, sys/syz-extract/linux.go, sys/targets/targets.go
=> Clang support: take 2

pkg/vcs/git.go, pkg/vcs/git_repo_test.go
=> pkg/vcs: always extract tags from subject

.github/workflows/ci.yml, docs/headerparser_usage.md, docs/linux/setup_ubuntu-host_odroid-c2-board_arm64-kernel.md, docs/syscall_descriptions.md, docs/syzbot.md, tools/check_links.py
=> Dvyukov ci dont notify pr

docs/reproducing_crashes.md
Use the relative link `/pkg/mgrconfig/testdata/qemu.cfg`.
=> docs: add the link of manager config file used in the syz-repro

dashboard/config/netbsd-kasan.config, dashboard/config/netbsd-kubsan.config
reduce the diff between the configs, remove duplicate options in the KUBSAN config
=> dashboard/config: improve the NetBSD configs

CONTRIBUTORS, vm/isolated/isolated.go
=> Fix/issue 1750: syz-manager hangs with "target_reboot:" false in isolated VM mode

prog/prio.go, prog/prio_test.go, prog/rand.go
=> Dvyukov prog determinism

prog/prio.go, prog/prio_test.go, sys/syz-sysgen/sysgen.go
=> Dvyukov ci faster

executor/common_usb_netbsd.h, pkg/csource/generated.go
=> executor: fix a cast in common_usb_netbsd.h

sys/syz-sysgen/sysgen.go
This is useful for integrating into Fuchsia's build system, where we
need to be able to run syz-sysgen with a read-only source directory,
and emit the output files elsewhere.
=> sys/syz-sysgen: add -src and -out flags

sys/freebsd/vnet.txt
=> sys/freebsd: mark some fields as big endian

docs/freebsd/README.md
This is required for gmake presubmit.
=> docs/freebsd: install golangci-lint on FreeBSD

.golangci.yml, pkg/ast/ast.go, pkg/ast/format.go, pkg/compiler/check.go, pkg/compiler/consts.go, pkg/csource/options.go, pkg/host/syscalls_linux.go, pkg/report/bsd.go, pkg/report/bsd_test.go, pkg/report/linux.go, pkg/report/netbsd.go, pkg/report/netbsd_test.go, pkg/report/openbsd.go, pkg/report/openbsd_test.go, prog/rand.go, prog/target.go, sys/linux/init.go, syz-manager/manager.go, tools/syz-check/check.go
=> more linter checks

docs/pseudo_syscalls.md
Add a brief description about pseudo-syscalls and how to create new
ones.
=> docs: new file pseudo_syscalls.md

sys/targets/targets.go
We should not skip the second check as well.
=> sys/targets: always fail if SOURCEDIR_GOOS is set but compiler is broken

Makefile, dashboard/app/app_test.go, dashboard/app/bisect_test.go, dashboard/app/config.go, dashboard/app/entities.go, dashboard/app/jobs.go, dashboard/app/jobs_test.go, dashboard/config/kconfiglib-merge-usb-configs.py, dashboard/dashapi/dashapi.go, docs/linux/setup.md, docs/linux/setup_ubuntu-host_odroid-c2-board_arm64-kernel.md, executor/common_linux.h, executor/executor.cc, pkg/csource/generated.go, pkg/email/patch_test.go, pkg/report/linux.go, syz-ci/jobs.go, syz-fuzzer/fuzzer.go, tools/check-language.sh, tools/fops_probe/fops_probe.cc, vm/odroid/odroid.go
=> check language

docs/syzbot.md
=> docs/syzbot.md: update notes on USB

executor/common_bsd.h, executor/common_usb_netbsd.h, executor/executor_bsd.h, pkg/csource/generated.go, pkg/host/host_netbsd.go
`procid` becomes the bus number, and we use port 1 on each bus
=> sys/netbsd: support multiple vHCI buses

sys/linux/l2cap.txt
=> sys/linux/l2cap.txt: fix structs

pkg/build/build.go, pkg/build/build_test.go, syz-ci/manager.go
=> Dvyukov build error fix

tools/syz-crush/crush.go
=> Dvyukov syz crush refactor 2

pkg/cover/report.go, pkg/cover/report_test.go, pkg/report/akaros.go, pkg/report/bsd.go, pkg/report/fuchsia.go, pkg/report/linux.go, pkg/symbolizer/nm.go, pkg/symbolizer/nm_test.go, pkg/symbolizer/symbolizer.go, tools/syz-check/check.go
In preparation to support big-endian architectures.
=> pkg: support compiler triple for 'nm' and 'addr2line'

Makefile, sys/syz-sysgen/sysgen.go, tools/syz-make/make.go
=> Dvyukov make jobs

dashboard/app/app_test.go, dashboard/app/config.go, dashboard/app/entities.go, dashboard/app/reporting.go, dashboard/app/reporting_test.go
=> Dvyukov cycle dups

executor/executor.cc
The output pointer was not updated after writing.
=> executor: fix write_output_64

executor/common_linux.h, pkg/csource/csource.go, pkg/csource/generated.go
=> pkg/csource: fix casting of parameters for trampolines

pkg/bisect/bisect.go, pkg/bisect/bisect_test.go, pkg/osutil/osutil.go, pkg/vcs/linux.go, pkg/vcs/linux_test.go, pkg/vcs/testdata/linux/config-bisect.pl, pkg/vcs/testos.go, syz-ci/jobs.go
=> config bisection

dashboard/app/reporting_email.go, pkg/bisect/bisect_test.go, pkg/build/openbsd.go, syz-manager/manager.go, tools/syz-linter/linter.go, tools/syz-linter/testdata/src/lintertest/lintertest.go
=> syz-linter: check log/error text

pkg/report/linux.go, pkg/report/testdata/linux/report/297, pkg/report/testdata/linux/report/300, pkg/report/testdata/linux/report/350, pkg/report/testdata/linux/report/502, pkg/report/testdata/linux/report/503, pkg/report/testdata/linux/report/504, pkg/report/testdata/linux/report/505, pkg/report/testdata/linux/report/65, pkg/vcs/linux.go, pkg/vcs/linux_test.go, pkg/vcs/testdata/linux/config-bisect.pl
=> pkg/vcs: log trace in tests before failing

docs/pseudo_syscalls.md
=> docs: add note that pseudo-syscalls are discouraged

docs/syscall_descriptions.md
=> docs: add tips on writing descriptions

docs/pseudo_syscalls.md
=> docs: explain pseudo-syscall argument type

executor/executor.cc
=> executor: prohibit malloc

executor/executor.cc
=> executor: clarify debug/debug_verbose use

docs/syscall_descriptions.md, docs/syscall_descriptions_syntax.md
=> docs: add explanation of flags type

pkg/osutil/osutil_linux.go, pkg/report/fuchsia.go, prog/hints_test.go, prog/mutation_test.go, tools/syz-check/dwarf.go, tools/syz-linter/linter.go, tools/syz-linter/testdata/src/lintertest/lintertest.go
=> linter comments

pkg/build/freebsd.go
=> Load additional protocol stacks on FreeBSD

pkg/bisect/bisect.go, pkg/vcs/git.go, pkg/vcs/vcs.go, syz-ci/jobs.go
=> fix patch testing and bisection

docs/pseudo_syscalls.md, docs/syscall_descriptions.md
=> some docs clarifications

Makefile
=> test executor build with clang

prog/prio_test.go, sys/linux/dev_snapshot.txt, sys/linux/init.go
=> sys/linux: disable SNAPSHOT_POWER_OFF

sys/linux/socket_netlink_route.txt
Fix for pull request https://github.com/google/syzkaller/pull/1953 not passing tests.
=> syz/linux: fix formating

sys/linux/sys.txt, sys/linux/sys_386.const, sys/linux/sys_amd64.const, sys/linux/sys_arm.const, sys/linux/sys_arm64.const, sys/linux/sys_mips64le.const, sys/linux/sys_ppc64le.const, sys/linux/sys_riscv64.const, sys/linux/sys_s390x.const
=> sys/linux: add description for copy_file_range

docs/pseudo_syscalls.md, docs/syscall_descriptions.md
The sys/OS/test/* tests are currently mostly undocumented.
Add initial documentation for these tests.
=> docs: add section on descriptions testing

.github/workflows/ci.yml, Makefile, docs/contributing.md, tools/check-commits.sh, tools/syz-env
=> .github/workflows: check commit description format

CONTRIBUTORS, pkg/host/syscalls_linux.go
Related to [https://github.com/google/syzkaller/pull/2001#issuecomment-668390600](https://github.com/google/syzkaller/pull/2001#issuecomment-668390600), @dvyukov What do you think about this?
---
CC: @balsini
=> Refactor isSupportedSyzkall

dashboard/config/upstream-apparmor.cmdline, dashboard/config/upstream-selinux.cmdline, dashboard/config/upstream-smack.cmdline
See https://bugzilla.kernel.org/show_bug.cgi?id=208299
and https://groups.google.com/forum/#!topic/kasan-dev/si9jMcgTr74
for context.
=> dashboard/config: enable rcupdate.rcu_expedited

tools/syz-hubtool/hubtool.go
syz-hubtool uploads local reproducers to syz-hub.
=> tools/syz-hubtool: add initial version

syz-manager/cover.go
=> syz-manager/cover: support compiler triple for readelf

docs/freebsd/README.md
=> Minor FreeBSD documentation updates

prog/mutation.go, sys/test/test.txt
prog/TestMutateRandom used to fail due to this.
@dvyukov @xairy
=> prog: fix UnionType mutation for when per-field dir is specified

pkg/csource/common.go
Historically we checked output length. It's unclear why now.
The Android sandbox error (#2048) was unnoticed because of this.
Check the error in addition to output len.
=> pkg/csource: check cpp error

syz-manager/html.go
I periodically see:
2020/08/23 13:33:21 http: superfluous response.WriteHeader
call from main.(*Manager).httpSummary (html.go:72)
which suggest that there are some erros during template execution.
But currently we don't seem to show them properly.
Show them properly and also log.
=> syz-manager: better handle errors in HTML templates

tools/create-openbsd-gce-ci.sh, tools/create-openbsd-vmm-worker.sh
Removed some never-used knobs as syzkaller always uses snapshots.
Resolved some ShellCheck'd lint.
TESTED=by installing Aug31 6.8 beta.
=> tools/create-openbsd: auto-detect snapshot version

pkg/build/build.go, pkg/build/linux.go
In preparation for s390x support in syz-ci.
=> pkg/build: support Linux s390x

executor/common.h, executor/common_test.h, executor/executor.cc, pkg/csource/generated.go, pkg/repro/repro.go, pkg/runtest/run.go, sys/test/exec.txt, sys/test/test/sleep, tools/syz-prog2c/prog2c.go
- tools/syz-prog2c: add -repro flag
- sys/test/test: add a hanging test
- pkg/repro: fix execution of non-repeatig C programs
=> dvyukov runtest repro

executor/executor_linux.h
gvisor coverage is not in the range of linux kernel coverage.
So the coverage filter does not work. Detect if running under gvisor
and skip the coverage filter.
=> executor: detect gvisor

executor/common.h, pkg/csource/generated.go
While investigating an OpenBSD reproducer[1][2] I discovered the
following:
* All threads are stuck on the last `sleep(1000000)` syscall in main(),
hence no output for the test machine.
* Each executor process created in loop() performs one iteration but
exits abnormally during the call to remove_dir().
* Calling remove_dir() will eventually invoke itself recursively since
one of the executed syscall is `mkdir("./file0", 0)` meaning that it
will try to remove the directory created by execute_one(). However,
`opendir(3)` fails with `EACCES` due to the permissions passed to
`mkdir(2)` is zero.
Instead of exiting, trying to remove the problematic directory in a best
effort manner makes the reproducer continue executing the generated
syscalls. This work around might be considered to narrow. …
=> executor: improve opendir(3) error handling

pkg/rpctype/rpctype.go, syz-fuzzer/fuzzer.go, syz-fuzzer/machine_info.go, syz-fuzzer/machine_info_test.go, syz-manager/manager.go, syz-manager/rpc.go
I will be working on the issue: syz-manager: collect machine info with crashes #466
@jedav @morehouse @dvyukov
=> syz-manager: collect machine information

pkg/host/machine_info.go, pkg/host/machine_info_linux.go, pkg/host/machine_info_test.go, syz-fuzzer/fuzzer.go, syz-manager/manager.go, syz-manager/rpc.go
- pkg/host: move machine info functionality from syz-fuzzer
- syz-manager: cosmetic refactoring
=> dvyukov machine info

tools/create-image.sh, tools/docker/big-env/Dockerfile
=> tools/create-image.sh: support for foreign architectures

docs/linux/setup.md, docs/linux/setup_linux-host_qemu-vm_s390x-kernel.md
=> docs/linux: describe how to setup s390x test environment

pkg/db/db.go, pkg/osutil/osutil.go, syz-ci/manager.go, syz-ci/syz-ci.go, syz-manager/manager.go
This seems to work but I'm not sure what is the best way to test it. I'm also wondering if the interface makes sense.
@dvyukov @ebiggers @morehouse
=> syz-manager: add test file as corpus

pkg/db/db.go, pkg/osutil/osutil.go, pkg/osutil/osutil_test.go, syz-ci/manager.go, syz-ci/syz-ci.go, syz-ci/updater.go, syz-manager/manager.go
- pkg/osutil: support glob patterns in CopyFiles
- syz-ci: fix seeds copying
- syz-manager: load test programs as candidates
=> dvyukov seeds

pkg/build/linux_generated.go, tools/create-gce-image.sh
=> tools/create-gce-image.sh: support s390x

AUTHORS, CONTRIBUTORS, docs/coverage.md
=> docs: clarify coverage point in different compliers

syz-ci/jobs.go
This is a hack as noted in the comment.
A proper support would require touching lots of files,
and we only need this temporary until #2096 is resolved.
One recent example of failed patch testing:
https://groups.google.com/g/syzkaller-bugs/c/O8CkScAt9ck/m/E3CYKSGSAgAJ
=> syz-ci: disable CONFIG_DEBUG_INFO_BTF during patch testing

pkg/cover/report.go, pkg/cover/report_test.go, prog/mutation_test.go, syz-manager/html.go, tools/syz-cover/syz-cover.go
- tools/syz-cover: add cmdprof profiling
- pkg/cover: speed up report generation
=> pkg/cover: speed up report generation

vm/qemu/qemu.go
Switch to the new qemu format for setting up network for all arches.
Add "network_device" configuration parameter to specify the network device type.
For some architectures we did not have a network device type specified before,
some default was used, but it's unclear what it was. Use virtio-net-pci
for these arches as newer/faster thing, e1000 is Intel so probably wasn't
used/supported for non-Intel arches.
=> vm/qemu: allow to specify network device type

syz-ci/manager.go, syz-ci/syz-ci.go
=> syz-ci: add flag to enable debug mode for testing

syz-manager/rpc.go
Let's give it another chance since the previous coverage drop wasn't
completely conclusive.
Few changes that may help:
- do rotation at 1/5 instead of 1/3 rate
- don't send triage candidates to rotated VMs,
since they may not have required syscalls enabled
- don't send new inputs/coverage to rotated VMs,
let them run in complete isolation
Update #1348
=> syz-manager: re-enable corpus rotation

dashboard/app/email_test.go, dashboard/app/reporting.go, dashboard/app/reporting_email.go, dashboard/dashapi/dashapi.go, docs/syzbot.md, pkg/email/parser.go, prog/export_test.go, prog/mutation_test.go, prog/prog_test.go
Add "#syz unfix" command that undoes "#syz fix" effects
and resets any existing fixing commits.
=> dashboard/app: add unfix command

vm/qemu/qemu.go
Replace {{INDEX}} string in qemu_args with 0-based VM index.
Useful to create unique file/device/port/unix socket/etc per-VM.
=> vm/qemu: support {{INDEX}} in qemu_args

pkg/vcs/vcs.go, pkg/vcs/vcs_test.go
For use inside a Docker container e.g.
=> pkg/vcs: support git URL starting with file:///

dashboard/app/admin.go, dashboard/app/entities.go, dashboard/app/kcidb.go
- dashboard/app: refactor updateBugReportingBatch
- dashboard/app: export all open bugs to Kcidb
=> dvyukov kcidb3

docs/linux/external_fuzzing_usbip.md
=> docs/linux: add USB/IP Documentation

docs/maintaining.md
Document some existing rules we have in the project.
=> docs: add maintainer's guide

pkg/host/machine_info_linux_test.go
- pkg/host: refactor machine info tests
- pkg/host: add canned test for cpu info
=> dvyukov machine info tests

pkg/build/gvisor.go
=> gvisor: add build option for collecting code coverage

pkg/build/linux.go
Kernel build runs under sandboxed user, while the rest of the code
runs under root. Sandboxed user does not have access to root files.
Chown all new created files for sandboxed user.
Currently builds fail with:
unable to write 'random state'
writing new private key to 'certs/signing_key.pem'
certs/signing_key.pem: Permission denied
22979106625176:error:0200100D:system library:fopen:Permission
denied:bss_file.c:398:fopen('certs/signing_key.pem','w')
22979106625176:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:400:
certs/Makefile:55: recipe for target 'certs/signing_key.pem' failed
make[1]: *** [certs/signing_key.pem] Error 1
Makefile:1053: recipe for target 'certs' failed
make: *** [certs] Error 2
=> pkg/build: consistently chown new files

dashboard/app/admin.go, dashboard/app/bisect_test.go, dashboard/app/entities.go, dashboard/app/jobs.go, dashboard/app/main.go, dashboard/app/reporting.go, dashboard/app/static/common.js, dashboard/app/static/style.css, dashboard/app/templates.html, pkg/html/generated.go, pkg/kconfig/kconfig.go
- pkg/kconfig: fix for Go 1.11
- dashboard/app: show more detailed info about bisections
=> dvyukov dashboard bisect

CONTRIBUTORS, docs/freebsd/README.md
Miscellaneous hints on growing disk, kernel src, and network configs.
=> docs/freebsd/: add more details

Makefile, executor/test_linux.h, prog/meta.go, vm/qemu/qemu.go, vm/qemu/qmp.go
Here are some improvements for QEMU VMs. Hopefully (again) this time I got all prerequisites right. Please comment. Thanks.
=> QEMU improvements

tools/syz-headerparser/headerlib/container.py, tools/syz-headerparser/headerlib/struct_walker.py, tools/syz-headerparser/headerparser.py
Updating scripts to use python3 using 2to3 as python2 is EOL
=> tools/headerparser: update to python3

syz-ci/manager.go
filesystem.Join converts 'http://' to 'http:/'.
Fixes ea2666e0 ("syz-ci: support HTTP PUT method to upload coverage reports")
=> syz-ci: fix problem with slashes in cover upload url construction

pkg/build/gvisor.go
Right now, we use a hard-coded path, but Dmirty found that it is wrong
for the current versions of bazel and gvisor.
=> build/gvisor: get a path to the runsc binary from bazel

pkg/csource/options.go, prog/prio.go, syz-fuzzer/fuzzer.go, syz-fuzzer/proc.go, tools/syz-expand/expand.go, tools/syz-linter/linter.go, tools/syz-linter/testdata/src/lintertest/lintertest.go, tools/syz-mutate/mutate.go, tools/syz-prog2c/prog2c.go, tools/syz-repro/repro.go, tools/syz-showprio/showprio.go, tools/syz-symbolize/symbolize.go
- all: fix format of fmt.Printf/Fprintf calls
- tools/syz-linter: add a check for fmt.Printf/Fprintf messages
=> dvyukov linter printf

pkg/bisect/bisect.go, pkg/bisect/bisect_test.go, pkg/build/netbsd.go, pkg/instance/instance.go, pkg/ipc/ipc.go, pkg/ipc/ipc_test.go, pkg/ipc/ipcconfig/ipcconfig.go, pkg/mgrconfig/config.go, pkg/mgrconfig/load.go, pkg/report/fuzz.go, pkg/report/linux_test.go, pkg/report/report.go, pkg/report/report_test.go, pkg/repro/repro.go, sys/targets/targets.go, syz-ci/jobs.go, syz-manager/manager.go, syz-manager/rpc.go, tools/syz-bisect/bisect.go, tools/syz-crush/crush.go, tools/syz-repro/repro.go, tools/syz-runtest/runtest.go, tools/syz-symbolize/symbolize.go, tools/syz-testbuild/testbuild.go, vm/vm_test.go
- pkg/mgrconfig: move derived fields into separate struct
- pkg/mgrconfig: add prog&sys.targets targets to Config
- pkg/mgrconfig: remove Syz prefix from fields
- pkg/ipc: remove Config.Timeout
=> dvyukov timeouts preparation

docs/research.md
=> docs: add Healer reference to research.md

tools/kcovfuzzer/kcovfuzzer.c, tools/syz-symbolize/symbolize.go
- tools/kcovfuzzer: refactor for easier addition of new fuzzers
- tools/kcovfuzzer: add binfmt_misc fuzzer
- tools/syz-symbolize: fix config loading
- tools/kcovfuzzer: write input to dmesg
=> dvyukov kcovfuzzer

executor/common_linux.h, pkg/csource/generated.go, sys/linux/sys.txt
- executor: tune few more sysctl's
- sys/linux: flip some sysctl's
=> dvyukov sysctls

syz-hub/http.go, syz-hub/state/state.go
=> syz-hub: show domain on web page

syz-hub/hub.go, syz-manager/hub.go
Actually send domain to the hub...
Update #2095
=> syz-manager: send domain to hub

pkg/build/gvisor.go
These cannot be instrumented with regular atomic operations (e.g.,
sync/atomic.AddInt32), which will happen if -race is enabled. We may be
able to re-enable coverage on them when https://golang.org/issue/43007 is
resolved.
=> pkg/build: skip coverage instrumentation on gVisor norace files

dashboard/app/reporting.go
We started getting lots of the following errors:
Dec 07 07:40: Exceeded soft memory limit of 256 MB with 340 MB after servicing 57 requests total.
Consider setting a larger instance class in app.yaml. (/api)
Dec 07 07:45: Exceeded soft memory limit of 256 MB with 395 MB after servicing 113 requests total.
Consider setting a larger instance class in app.yaml. (/api)
Dec 07 07:46: Exceeded soft memory limit of 256 MB with 270 MB after servicing 51 requests total.
Consider setting a larger instance class in app.yaml. (/api)
Dec 07 07:47: Exceeded soft memory limit of 256 MB with 420 MB after servicing 43 requests total.
Consider setting a larger instance class in app.yaml. (/api)
See https://cloud.google.com/appengine/docs/standard/#instance_classes
for the reference on instance classes.
=> dashboard/app: bump instance class to F2

pkg/build/gvisor.go
=> pkg/build: fix gvisor instrumentation filters

executor/cov_filter.h, executor/executor.cc, executor/test.h, pkg/cover/cover.go, pkg/cover/cover_test.go, pkg/cover/report.go, pkg/ipc/ipc_test.go, syz-manager/covfilter.go, syz-manager/covfilter_test.go, syz-manager/html.go, syz-manager/manager.go, syz-manager/rpc.go, syz-manager/stats.go
- executor: minor coverage filter cleanup
- syz-manager: minor coverage filter cleanup
=> dvyukov covfilter minor cleanups

sys/targets/targets.go
=> sys/targets: define NeedSyscallDefine for FreeBSD

syz-manager/html.go
Support filtered coverage report from this [discussion](https://github.com/google/syzkaller/pull/2017#issuecomment-741616136).
=> syz-manager: support filtered coverage report

docs/linux/external_fuzzing_usb.md
Minor updates and readability improvements.
=> docs: update USB documentation

pkg/ipc/ipc.go, vm/qemu/qemu.go, vm/vm.go, vm/vmimpl/vmimpl.go
- vm/qemu: scale ssh timeout
- pkg/ipc: scale sandbox timeout
=> dvyukov qemu timeouts

syz-manager/html.go
This adds /filterpcs handler which is similar to /rawcover.
It returns a file with all covered so far filtered PCs.
Useful for offline filtered coverage processing, diffing coverage, etc.
In particular allows to do:
curl http://localhost:1234/filterpcs | addr2line -e vmlinux
=> syz-manager: expose filtered raw cover in http handler

pkg/host/features_linux.go, pkg/report/linux.go, pkg/report/testdata/linux/guilty/50, pkg/report/testdata/linux/report/237, pkg/report/testdata/linux/report/241, pkg/report/testdata/linux/report/243, pkg/report/testdata/linux/report/45, pkg/report/testdata/linux/report/46, pkg/report/testdata/linux/report/546, pkg/report/testdata/linux/report/547, pkg/report/testdata/linux/report/548, pkg/report/testdata/linux/report/549, pkg/report/testdata/linux/report/550, pkg/report/testdata/linux/report/551, pkg/report/testdata/linux/report/552, pkg/report/testdata/linux/report/553, vm/qemu/qemu.go
- vm/qemu: fix arm qemu args
- pkg/report: implement arm oops parsing
=> dvyukov qemu arm

docs/syzbot.md
=> docs: clarify how syzbot identifies bugs

prog/rotation.go, prog/rotation_test.go
Reported-by: ManhNDd
Fixes #2372
=> prog: fix oob panic in rotatorState.Select

docs/research.md
=> docs: add reference to HFL paper

dashboard/app/api.go
We need to search old bugs by all alternative titles
rather than only the current main title.
If a bug is renamed its old title becomes one of alternatives titles.
It's hard to test because this code is invoked only
during migration from old schema.
Update #1575
=> dashboard/app: fix merging of renamed bugs

docs/linux/external_fuzzing_usb.md
=> Update external_fuzzing_usb.md to match the latest code

pkg/build/openbsd.go
Reported-by: syzbot+badc83af4aac6e58c236@syzkaller.appspotmail.com
=> pkg/build/openbsd: sync before umount

tools/docker/syzbot/Dockerfile
=> tools/docker/syzbot: include ccache

syz-ci/syz-ci.go
- syz-ci: allow moving managers between ci instances
- syz-ci: reduce cyclomatic complexity of loadConfig
=> dvyukov syz ci manager name

pkg/build/gvisor.go
Build options can affect a path where runsc will be saved.
=> build/gvisor: run aquery with all build options

vm/isolated/isolated.go, vm/qemu/qemu.go, vm/vmimpl/util.go
Restrict access to the external network from within the VM
and access to VM SSH to local interface only.
Fixes #332
=> vm/qemu: restrict network access

syz-ci/manager.go
Report generation can consume lots of memory.
Generate one at a time. Otherwise we see OOMs.
=> syz-ci: serialize coverage report generation

.golangci.yml, tools/docker/env/Dockerfile
- .golangci.yml: disable staticcheck nil pointer deref check
- tools/docker/env: switch to Go 1.16
=> dvyukov go1.16

dashboard/app/api.go, dashboard/app/repro_test.go, dashboard/dashapi/dashapi.go, syz-manager/manager.go
=> syz-manager: don't reproduce leaks again and again

pkg/bisect/bisect.go
=> pkg/bisect: fix number of tests for flaky repros

dashboard/app/api.go, dashboard/dashapi/dashapi.go, executor/android/android_seccomp.h, executor/common_bsd.h, executor/common_fuchsia.h, executor/common_linux.h, executor/common_usb_netbsd.h, executor/cov_filter.h, executor/executor.cc, executor/executor_bsd.h, executor/executor_fuchsia.h, executor/executor_linux.h, executor/style_test.go, pkg/csource/csource.go, pkg/csource/generated.go, pkg/report/report.go, pkg/report/testdata/linux/report/601, syz-manager/manager.go
- dashboard/app: save suppressed reports
- pkg/report: detect executor failures
=> dvyukov save suppressed

pkg/report/linux.go, pkg/report/testdata/linux/report/602
=> pkg/report: ignore kcsan_setup_watchpoint in reports

CONTRIBUTORS, pkg/report/linux.go, pkg/report/testdata/linux/report/605
Added extra cases to ignore that occured on Android 11 Pixel3XL
=> pkg/report: ignore cases for Android

dashboard/app/admin.go, dashboard/app/main.go
- dashboard/app: add helper function to update bug titles
- dashboard/app: show similar bugs based on alt titles
=> dvyukov dashboard show similar

dashboard/app/api.go, dashboard/app/app_test.go, dashboard/app/bisect_test.go, dashboard/app/email_test.go, dashboard/app/jobs_test.go, dashboard/app/notifications_test.go, dashboard/app/reporting.go, dashboard/app/reporting_email.go, dashboard/app/util_test.go
=> dashboard/app: add prefix to email subjects

vm/qemu/qemu.go
For context see:
https://groups.google.com/g/syzkaller/c/NBCGPtkMTWs/m/jVZnTnWcAgAJ
=> vm/qemu: improve parameter descriptions

pkg/cover/backend/backend.go, pkg/cover/backend/elf.go, pkg/cover/report.go, pkg/cover/report_test.go, pkg/mgrconfig/config.go, pkg/symbolizer/symbolizer.go, pkg/symbolizer/symbolizer_test.go, syz-manager/cover.go, syz-manager/manager.go, tools/syz-cover/syz-cover.go, vm/qemu/qemu.go
This reverts commit 69a06ca2b532ff4021a43fdead4e2ac1452a44c0.
=> Revert "all: add KernelModule cfg to show DLKM coverage"

dashboard/app/main.go
Don't show all managers in manager filter mode, e.g.:
https://syzkaller.appspot.com/upstream?manager=ci-qemu2-arm64-mte
Other managers only add clutter in this mode.
=> dashboard/app: show only single manager in filter mode

pkg/cover/backend/elf.go
arm64 has different opcode and instruction bytes' order.
Example:
ffffffd0100a2a60:       9407e172        bl      ffffffd01029b028 <__sanitizer_cov_trace_const_cmp4>
ffffffd0100a2a6c:       9407e09f        bl      ffffffd01029ace8 <__sanitizer_cov_trace_pc>
ffffffd01029c42c:       97fffa2f        bl      ffffffd01029ace8 <__sanitizer_cov_trace_pc>
Above ffffffd0100a2a60 is address of 0x72 in 9407e172, so position
of 0x94 needs to minus 3 to get address of 0x72.
Also elf has .init.text and .exit.text sections which have those
__sanitizer_cov_trace_* code which were missing. …
=> pkg/cover: support opcode search for arm64

vm/adb/adb.go
The flag is for test purpose, especially useful
during kernel development.
=> vm/adb: add flag to avoid adb reboot at 1st time

dashboard/config/freebsd/syz-ci-service.sh
For context see:
https://groups.google.com/g/syzkaller/c/mpypAGJF0hc/m/6LREl1tDAwAJ
=> dashboard/config/freebsd: enable fsck_y_enable

pkg/cover/backend/elf.go
1. Move len check after opcode check.
This should make things faster, because opcode check
will be false most of the time.
2. Don't compare strings in the loop.
3. Rewind position to the beginning of the instruction for arm64.
This simplifies subsequent checks and calculations.
=> pkg/cover/backend: refactor readCoverPoints

sys/linux/init.go
Add VSYSCALL_ADDR, PAGE_OFFSET, VMEMMAP addresses.
=> sys/linux: add more amd64/riscv64 special addresses

dashboard/app/app.yaml, dashboard/app/cache.go, dashboard/app/cron.yaml, dashboard/app/index.yaml, dashboard/app/main.go
Building the memcache object with bug stats takes
significant time and periodically slows down user requests.
Update it with cron ahead of time.
=> dashboard/app: update memcache with cron

vm/adb/adb.go, vm/isolated/isolated.go, vm/isolated/isolated_test.go, vm/vmimpl/vmimpl.go
Add repair_script and startup_script config to
1. execute repair script before adb available in case device stay in crash mode
2. execute startup script after adb available before fuzzing
=> vm/adb: add startup_script config

dashboard/config/linux/bits/base.yml, dashboard/config/linux/bits/debug.yml, dashboard/config/linux/bits/kasan.yml, dashboard/config/linux/bits/x86_64.yml, dashboard/config/linux/main.yml, pkg/kconfig/kconfig.go, tools/syz-kconf/kconf.go, tools/syz-kconf/kconf_test.go, tools/syz-kconf/parser.go
- pkg/kconfig: relax parsing for older kernels
- tools/syz-kconf: improve support for third-party config files
- tools/syz-kconf: faster kernel release detection
- dashboard/config/linux: support for v4.15 kernels
=> dvyukov kconf update

docs/contributing.md
Add some general contribution guidelines.
=> docs: extend contributing.md

syz-fuzzer/fuzzer.go, syz-fuzzer/proc.go, syz-fuzzer/testing.go, syz-manager/html.go
For debugging of:
https://groups.google.com/g/syzkaller/c/fBDU5arcOTE/m/-XCcN0HxAQAJ
=> syz-fuzzer: extend diagnostics for execution of disabled syscalls

dashboard/app/reporting.go, syz-fuzzer/fuzzer.go, syz-fuzzer/testing.go
- syz-fuzzer: fix revision check
- dashboard/app: remove HasReport check during crash reporting
=> dvyukov revision check fix

pkg/cover/html.go
=> pkg/cover: show stat of PCs in covered function

pkg/report/linux.go, pkg/report/testdata/linux/report/609
Suggested-by: Vegard Nossum
Link: https://groups.google.com/g/syzkaller/c/aHHCG_ZHOZA/m/M6aiIuzkAQAJ
=> pkg/report: add format for new 0-size vmalloc warnings

prog/rand_test.go, syz-fuzzer/fuzzer.go, syz-fuzzer/proc.go
- prog: extend TestEnabledCalls test
- syz-fuzzer: check incoming programs for disabled syscalls
=> dvyukov disabled calls

pkg/build/freebsd.go
=> pkg/build: enable RedZone on FreeBSD

syz-manager/rpc.go
- dashboard/config/linux: update to v5.13
- executor: move vm.nr_overcommit_hugepages into config
- syz-manager: explicitly mark rotated fuzzers
=> dvyukov rotated fix

pkg/host/syscalls_linux.go, pkg/mgrconfig/config.go, syz-manager/html.go
- pkg/mgrconfig: give instance default name
- pkg/host: better error message for missing syscalls
=> dvyukov config default name

pkg/cover/backend/dwarf.go, pkg/cover/backend/elf.go, pkg/cover/backend/mach-o.go
=> pkg/cover: fix mismatch frame and progs PC for arm64

docs/syscall_descriptions_syntax.md, pkg/host/machine_info_linux.go, pkg/host/machine_info_linux_test.go, sys/linux/sys.txt
=> all: support exclude globs in descriptor

syz-manager/html.go
=> syz-manager: add link to download corpus.db

dashboard/config/linux/bits/kmsan.yml, dashboard/config/linux/upstream-kmsan-base.config, dashboard/config/linux/upstream-kmsan.config
Signed-off-by: Alexander Potapenko <glider@google.com>
=> kmsan: enable panic_on_kmsan=1

vm/gvisor/gvisor.go
Let's stop instances with "runsc kill" instead of killing sandbox
processes. This will guarantee that ongoing rpc calls will not fail with
unexpected errors.
Reported-by: syzbot+084fca334720887441e7@syzkaller.appspotmail.com
=> vm/gvisor: stop instances properly

dashboard/app/api.go, dashboard/app/app_test.go, dashboard/app/config.go, dashboard/app/repro_test.go, dashboard/app/util_test.go
The previous names confused a couple of unrelated concepts.
=> dashboard/app: document the values in maps and rename local vars

pkg/cover/html.go
=> pkg/cover: add line number in cover page

pkg/cover/html.go, pkg/cover/report.go, syz-manager/html.go
=> all: add /rawcoverfiles to help debug PC symbolize

pkg/cover/backend/dwarf.go, pkg/cover/backend/elf.go, pkg/cover/html.go, pkg/cover/report_test.go, syz-manager/html.go, tools/syz-cover/syz-cover.go
=> all: fix arm64 runtime pc not align with elf

pkg/build/freebsd.go
=> pkg/build: disable DEBUG_REDZONE for FreeBSD

pkg/report/freebsd.go, pkg/report/testdata/freebsd/report/14, pkg/report/testdata/freebsd/report/15
=> pkg/report: match FreeBSD KASAN reports

docs/executing_syzkaller_programs.md
=> docs/executing_syzkaller_programs.md: fix typo

syz-verifier/main.go, syz-verifier/main_test.go
Contributes to #692
* added several test cases to syz-verifier primary functions
* accounted for corner cases related to VMs crashing in the `syz-verifier` logic and documented them in-depth
=> syz-verifier: account for corner cases and improve test coverage

dashboard/app/bisect_test.go, dashboard/app/email_test.go, dashboard/app/mail_bisect_result.txt, dashboard/app/mail_bug.txt, dashboard/app/static/style.css, dashboard/app/templates.html, pkg/html/generated.go, pkg/html/html.go, syz-manager/html.go
Closes https://github.com/google/syzkaller/issues/2184
=> Use 12 byte long hashes for kernel commits

dashboard/app/api.go, dashboard/app/app_test.go, dashboard/app/auth.go, dashboard/app/auth_test.go, dashboard/dashapi/dashapi.go, dashboard/dashapi/jwt.go
Just to get some early feedback...
=> dashboard: auth by bearer token

pkg/cover/backend/backend.go, pkg/cover/backend/dwarf.go, pkg/cover/html.go, pkg/cover/report.go, syz-manager/html.go
=> all: add /modulecover page

syz-verifier/main.go, syz-verifier/main_test.go
Contributes to #692, depends on #2676
The results are now ordered by pool index (from 0 to N-1 for N pools)
=> syz-verifier: ensure results are ordered by pool index

dashboard/config/openbsd/config.ci, dashboard/config/openbsd/recreate.sh
This repository now contains the complete configuration of ci-openbsd.
=> dashboard/config/openbsd: scripts and configs for ci-openbsd

pkg/rpctype/rpctype.go, syz-runner/runner.go, syz-verifier/main.go, syz-verifier/main_test.go, syz-verifier/stats.go, syz-verifier/stats_test.go, syz-verifier/test_utils.go, syz-verifier/verifier.go, syz-verifier/verifier_test.go
=>  syz-verfier: add reruns to the architecture

pkg/instance/instance.go, pkg/report/akaros.go, pkg/report/bsd.go, pkg/report/darwin.go, pkg/report/freebsd.go, pkg/report/fuchsia.go, pkg/report/fuzz.go, pkg/report/gvisor.go, pkg/report/linux.go, pkg/report/netbsd.go, pkg/report/openbsd.go, pkg/report/report.go, pkg/report/report_test.go, pkg/report/stub.go, pkg/repro/repro.go, syz-manager/manager.go, syz-verifier/main.go, tools/syz-crush/crush.go, tools/syz-runtest/runtest.go, vm/vm.go
Closes https://github.com/google/syzkaller/issues/2685
=> Pass whole log to the `Report.Parse` method

pkg/cover/backend/elf.go
=> pkg/cover: fix func range drop into variable range

docs/darwin/0001-fuzzing.patch, docs/darwin/README.md, docs/darwin/found_bugs.md
This patch is part of my ongoing effort to implement XNU/Darwin support in syzkaller: #2553
Finally add documentation on how to use darwin+syzkaller :^)
=> docs: document how to fuzz macOS

pkg/cover/report_test.go, sys/targets/targets.go
The -static-pie flag enables us to build static binaries with ASLR
support. Local testing demonstrated that enabling ASLR on syz-executor
eliminates (almost all?) memory corruptions and significantly reduces
the number of "no output from test machine" errors.
Enable ASLR by default for Linux and *BSD targets.
Replace -static-pie by -static when -static-pie is not supported.
Update cover report_test to properly handle ASLR binaries.
=> all: enable ASLR for syzkaller executables

Makefile, prog/encoding.go, tools/docker/big-env/Dockerfile, tools/docker/env/Dockerfile, tools/docker/old-env/Dockerfile, tools/docker/syzbot/Dockerfile
- tools/docker: use apt-get update --allow-releaseinfo-change
- tools/docker/big-env: install Go 1.12
- Makefile: test appengine app build locally
- prog: don't use reflect.Value.IsZero
=> dvyukov reflect is zero

pkg/report/openbsd.go, pkg/report/testdata/openbsd/report/21
This routine was recently renamed.
=> pkg/report: sync openbsd badop suppression

Makefile, executor/common.h, pkg/cover/report_test.go, pkg/csource/generated.go, tools/docker/big-env/Dockerfile
- pkg/cover: fix tests with clang
- executor: work around clang-format issue
- tools/docker/big-env: install clang-14
- Makefile: run more test with clang
=> dvyukov clang ci

docs/syz_testbed.md
=> docs: rename syz-testbench to syz-testbed

syz-verifier/main.go, syz-verifier/main_test.go, syz-verifier/monitoring_api.go, syz-verifier/rpcserver.go, syz-verifier/stats.go
To track the impact of the upcoming changes, some monitoring API is needed.
In future, want to make some dashboard that will get the required data using http/json.
As of now, the plain json is enough to move forward.
=> syz-verifier: add monitoring api

docs/research.md
=> docs: Add SyzGen (CCS'21)

dashboard/config/linux/bits/kmsan.yml, dashboard/config/linux/upstream-kmsan-base.config, dashboard/config/linux/upstream-kmsan.config
This is how the boot-time parameter is called now.
Signed-off-by: Alexander Potapenko <glider@google.com>
=> kmsan: change panic_on_kmsan=1 to kmsan.panic=1

pkg/cover/backend/dwarf.go
GCC11 uses DWARF 5 format by default, which is not supported by go1.14 -
the Go version recommended by our documentation. This was fixed in
go1.16, but that version is not yet in the official stable Debian
packages.
Recover from such panic and return a meaningful error. This should help
the users to resolve the problem themselves.
Update #2878
=> pkg/cover/backend: recover from DWARF parsing panic

dashboard/app/config.go, dashboard/app/entities.go, dashboard/app/graph_bugs.html, dashboard/app/graph_fuzzing.html, dashboard/app/graph_lifetimes.html, dashboard/app/graphs.go, dashboard/app/graphs_test.go, dashboard/app/main.go, dashboard/app/static/style.css, dashboard/app/templates.html, pkg/html/generated.go
=> dashboard/app: add page with manager stats graphs

dashboard/app/graphs.go
Show also the "executions per second" graph on the dashboard.
We have differing amouns of fuzzing time each day, so it is very hard
to analyze the dynamics of "exec total" otherwise.
=> dashboard: add an exec speed graph

tools/syz-symbolize/symbolize.go
The tool package simplifies failing. Use it.
=> tools/syz-symbolize: use tool package

executor/common_bsd.h, pkg/csource/generated.go
=> executor: support larger maximum number of tun devices on *BSD

tools/syz-repro/repro.go
tools/syz-repro/repro.go: save syz-repro output to files
This PR saves syz-repro output program file and C file. By default, files are saved in a directory where syz-repro is executed. Fixes #2951.
=> tools/syz-repro/repro.go: save syz-repro output to files

pkg/report/linux.go, pkg/report/testdata/linux/report/638
=> pkg/report: ignore atomic_dec_and_lock frames

docs/linux/reporting_kernel_bugs.md
=> docs: update reporting_kernel_bugs.md

sys/openbsd/init.go
The executor uses more file descriptors by now.
=> sys/openbsd: sync fd range

pkg/report/gvisor.go, pkg/report/testdata/gvisor/report/28
Reported-by: syzbot+8a8330333cd20c039a1b@syzkaller.appspotmail.com
=> pkg/report: ignore ThreadSanitizer clock allocator overflow errors

tools/syz-kconf/kconf.go, tools/syz-kconf/parser.go
- tools/syz-kconf: allow to specify custom compiler
- dashboard/config/linux: use custom compiler for kmsan
=> dvyukov kconf compiler

tools/docker/env/Dockerfile, tools/docker/syzbot/Dockerfile
The existing build lacked some headers, which prevented us from being
able to configure newer kernels.
=> docker: make clang-kmsan hermetic

dashboard/app/entities.go, dashboard/app/graph_crashes.html, dashboard/app/graphs.go, dashboard/app/graphs_test.go, dashboard/app/main.go, dashboard/app/static/common.js, dashboard/app/static/style.css, dashboard/app/templates.html, pkg/html/generated.go
- Show top crashes for X last days.
- Show daily share of crashes that satisfy user-entered regexps.
=> dashboard: add crash stats

pkg/gce/gce.go, vm/gce/gce.go
Now we always enable it, make this configurable for GCE instances.
=> vm/gce: enable display device configuration

syz-verifier/monitoring_api.go, syz-verifier/stats.go, syz-verifier/stats_test.go, syz-verifier/verifier.go, syz-verifier/verifier_test.go
s/TotalMismatches/TotalCallMismatches/ for readability.
Add ExecErrorProgs to count failures.
=> syz-verifier: improve statistics

syz-verifier/verifier.go
Reused config parameter "config.vm.count".
Local fuzzing speed test result:
1 vm/pool => 380 programs/minute
2 vm/pool => 1050 programs/minute
4 vm/pool => 1600 programs/minute
8 vm/pool => 800 programs/minute
=> syz-verifier: support multiple VMs

syz-verifier/exectask.go, syz-verifier/exectask_test.go
Added tests.
Fixed some concurrency issues.
=> syz-verifier/exectask.go: add tests

syz-verifier/stats.go, syz-verifier/verifier.go
Encapsulate Stats aggregation logic.
=> syz-verifier: simplify Stats API

vm/cuttlefish/cuttlefish.go
To copy files onto the virutal device, we first copy them to the host
GCE instance using the 'gce.Copy()' function and then push it to the
device using 'adb push <src> <dst>'.
Running commands on the device is also simple and merely prepends "adb
shell" to the command run on the GCE instance. This results in an
overall command along the lines of "ssh adb shell <command>".
=> vm/cuttlefish: implement copy and run functions

pkg/build/linux_linux.go
Now it's assumed to always be ext4, which is actually not always the
case. Try to mount ext4, then try vfat.
=> pkg/build: detect fs type automatically in embedLinuxKernel()

pkg/build/linux_linux.go
Assume that /etc can be on a partition different from the one, where the
kernel resides.
=> pkg/build: mount /etc before copying the sysctl file

tools/docker/env/Dockerfile, tools/docker/syzbot/Dockerfile
It's required by the NetBSD-KMSAN instance.
=> tools/docker: configure an alias for clang++

Makefile
The build target is kind of inconsistent, but `make build` would be even more confusing..
=> make: add syz-build target

docs/adding_new_os_support.md
=> docs: update the documentation of new OS support

tools/syz-kconf/kconf.go, tools/syz-kconf/parser.go
- tools/syz-kconf: apply replacement vars to Compiler as well
- tools/syz-kconf: add SOURCEDIR replacement var
- tools/syz-kconf: allow to specify linker
=> dvyukov syz conf compiler

dashboard/app/access_test.go, dashboard/app/graphs.go, dashboard/app/templates.html
Show graph pages to users who have access to the bugs themselves.
=> dashboard/app: open graph pages

dashboard/app/main.go, dashboard/app/templates.html
Very handy to assess if it's the right/wrong commit.
=> dashboard/app: linkify bisection commits

dashboard/app/handler.go
Guess, the intention here was to report templates.ExecuteTemplate() issue.
=> dashboard/app: fix reported error depth

tools/syz-reprolist/reprolist.go
Support the new GCE auth which does not require client key.
And support multiple clients at the same time.
=> tools/syz-reprolist: support gce auth and multiple clients

docs/syzbot.md
- docs: update link to stretch image
- docs: add how to use syzbot image for kernel builds
=> dvyukov docs update

dashboard/app/app_test.go, dashboard/app/bug.html, dashboard/app/main.go, dashboard/app/static/style.css, pkg/html/generated.go, pkg/vcs/vcs.go, pkg/vcs/vcs_test.go
- pkg/vcs: add FileLink
- dashboard/app: linkify source files in sample reports
=> dvyukov dashboard links

pkg/cover/html.go, pkg/cover/report_test.go
pkg/cover: show module in /funccover and /filecover
pkg/cover: show percent of covered pcs in funcs
=> Improve coverage by adding module name

pkg/report/linux.go, pkg/report/testdata/linux/report/649
=> pkg/report: ignore syz-executor's general protection fault

executor/common.h, pkg/csource/generated.go
There is a BSD syscall, chflags(2), which lets one set various flags on
a file, including several that prevent unlinking.  The use of this flag
can cause the executor to fail to clean up tmpdirs, which can lead to
spurious reports.
Thus, when unlinking fails, try again after clearing relevant flags.  I
suspect this would be useful on other BSDs but I can't easily verify
that this change works there.  It may eventually be worth having a
BSD-specific remove_dir() implementation.
=> executor: try harder to unlink files on FreeBSD

pkg/build/android.go, pkg/build/build.go, pkg/build/linux.go, pkg/build/linux_test.go, tools/syz-build/build.go
- pkg/build: return error on error
- pkg/build: support debug tracing
- tools/syz-build: add tracing mode
=> dvyukov tools syz sign

vm/adb/adb.go
Instead of looping 300 times (and spamming logs) we should just use the
tooling built in to ADB to wait for the device to come up.
=> vm/adb: use adb wait-for-device for inst.waitForSSH()

pkg/bisect/bisect.go, pkg/bisect/bisect_test.go, pkg/instance/instance.go, syz-ci/jobs.go
This might help get more insight into patch testing failures, especially for old bugs.
In particular, I need this PR to figure out what's going wrong with https://syzkaller.appspot.com/bug?extid=a95f67b348a557728ff8
=> syz-ci: remember syzkaller builds logs

pkg/report/linux.go, pkg/report/linux_test.go, pkg/report/testdata/linux/decompile/amd64/2.out
=> pkg/report: don't decompile opcodes for hanged reports

executor/common_linux.h, pkg/csource/generated.go
Remove /syzcgroup/* if cgroup mount fails. See #3241 for context.
Fixes #3241
=> executor: prevent ENOSPC if cgroup mount fails

pkg/mgrconfig/config.go
Slightly clarify what exactly each sandbox means.
=> pkg/mgrconfig: extend sandbox docs
