google/syzkaller

pkg/report/linux.go, pkg/report/testdata/linux/report/610, pkg/report/testdata/linux/report/611, pkg/report/testdata/linux/report/612
We are getting some duplicate reports where the stall actually happens
in some syscall, but the syscall triggers a page fault repeatedly.
As the result we can attribute some of the stalls to the next frame
after handle_mm_fault.
So don't consider handle_mm_fault as an anchor frame.
We need to be careful to not skip entry into page fault
from user space, because that's a completly different case.
In that case the stall is indeed in the page fault handler.
It's also unclear if this is the right thing to do.
If the stall actually happens in the fault handler
and the root cause in the fault handler, then after this change
we will produce duplicate stalls for every place in the kernel
that can trigger a page fault (we will be skipping the handler
itself and attribute it to the innocent …
=> pkg/report: don't consider handle_mm_fault as anchor frame

pkg/build/freebsd.go
OOM kills are a source of "lost connection to test machine" and "no
output from test machine reports".  At the point where we start getting
OOM kills, we might as well give up, and turning them into a panic gives
us some extra debugging info as well as a way to distinguish OOM kills
from other causes of these reports.
=> pkg/build: configure vm.panic_on_oom on FreeBSD

docs/linux/setup_ubuntu-host_qemu-vm_x86-64-kernel.md
Fixed deprecated command for generating default configuration and clarified that distro's GCC can be used if it's up-to date.
=> Updated documentation for fuzzing x86-64 kernel in a QEMU with Ubuntu host

pkg/build/netbsd.go
netbsd.go uses a hacky way to construct manager config
that skips of all of our verification/completion logic.
As the result the manager config has 0 timeouts and qemu
immidiately timeouts. Fill in timeouts.
=> pkg/build: fix qemu timeouts for netbsd

tools/docker/syzbot/Dockerfile
Not really GRTE, but it's enough to run some
scripts that hardcode the path.
=> tools/docker/syzbot: add fake GRTE python

vm/qemu/qemu.go
This is my fourth patch set in my ongoing effort to implement XNU/Darwin support in syzkaller: #2553
With this change running XNU in syzkaller should be possible, without requiring further syzkaller patches. Doing so still requires hand crafting a VM, bootloader and messing around with the qemu_args in your syzkaller config though. It's not yet trivial, which is what I'll hopefully tackle next.
Let me know what you think.
=> vm/qemu: initial darwin support

pkg/host/machine_info_linux_test.go, sys/sys.go, sys/trusty/gen/empty.go
It was missing and we forgot to import it in sys.
=> sys/trusty/gen: add empty.go

CONTRIBUTORS, dashboard/app/main.go, dashboard/app/templates.html
This information allows users to quickly scan the bug list to identify
bugs that are receiving attention and those that are neglected.
=> dashboard/app: add last activity info to bug list

Makefile
The existing "make clean" removes all directories with generated files,
even "empty.go" which are tracked by git.
This relaxes the clean rule to keep empty.go to stop these warnings:
|| package github.com/google/syzkaller/tools/syz-stress
||      imports github.com/google/syzkaller/pkg/csource
||      imports github.com/google/syzkaller/pkg/mgrconfig
||      imports github.com/google/syzkaller/sys
||      imports github.com/google/syzkaller/sys/windows/gen: \
build constraints exclude all Go files in \
/home/aik/p/go/src/github.com/google/syzkaller/sys/windows/gen
Fixes: 95777977ade5 ("sys: commit empty source files")
Signed-off-by: Alexey Kardashevskiy <aik@linux.ibm.com>
Before sending a pull request, please …
=> Makefile: do not remove empty files from sys/*/gen

pkg/symbolizer/symbolizer.go
As the --help message is localised, this check will fail on systems with
non english locales otherwise.
=> pkg/symbolizer: set LC_ALL to C when launching addr2line check

Makefile, pkg/instance/instance.go, pkg/instance/instance_test.go, pkg/rpctype/rpctype.go, pkg/tool/flags.go, pkg/tool/flags_test.go, syz-runner/runner.go, syz-verifier/main.go, syz-verifier/main_test.go, syz-verifier/verf/verifier.go, syz-verifier/verf/verifier_test.go
Created initial prototype for syz-verifier. This includes functionality for:
- parsing multiple configuration files
- creating VM instances from different VM pools
- establishing RPC communication between server on the host and clients on the guests
- sending an infinite stream of program to clients from the host
- sending an infinite stream of execution trace back to the host (for now, just in ipc.ProgInfo)
-  verifying the returned errnos match between different executions of the same program
=> syz-verifier: initial prototype

pkg/tool/flags.go
Fixes line alignment in comments in `pkg/tool` for `cfgsFlag`
=> syz-verifier: comment fix

AUTHORS, CONTRIBUTORS, executor/common_bsd.h, pkg/csource/generated.go
The "scope" field of struct fault_ioc_info is an input to the ioctl,
so initialize it to FAULT_SCOPE_LWP to match other fault_ioc_* usage.
=> executor: initialize scope in fault_ioc_info

syz-verifier/main.go, syz-verifier/main_test.go, syz-verifier/verf/verifier.go, syz-verifier/verf/verifier_test.go
Refactored the `verf.Verify` function so that it creates `ResultReport` in case mismatches between returned errno are found and added functionality to store this reports in files for further inspection.
=> syz-verifier: Initial functionality for persistent storage of mismatching results

pkg/instance/instance.go, pkg/instance/instance_test.go, syz-runner/runner.go, syz-verifier/main.go
The initial experiments we ran using `syz-verifier` consisted of generating programs with only `open`, `read`, `pipe`, `write` and `close` and executing them on two instances of the same version of Linux kernel. One main source of false positives was due to timeouts caused by threaded execution. 
Example program:
```
pipe(r1,r2)
write(r2, ...)
```
With threaded mode enabled, `pipe` and `write` might run in parallel. If on `vm-1` the `pipe` call blocks while on `vm-2` it doesn't, `syz-verifier` will report an errno mismatch at `write` because  on `vm-1` the `write` will finish with errno 9 (bad file descriptor). With threaded execution disabled, the `write` will have to wait until `pipe` completes so it can't operate on a file descriptor that hasn't been properly …
=> syz-verifier: added flags to disable collide and threaded mode in Runner

docs/linux/kernel_configs.md, docs/linux/setup_ubuntu-host_qemu-vm_x86-64-kernel.md, docs/linux/troubleshooting.md
Two adjustments:
1. Remove the notion of Debian Wheezy, as this is already obsolete. This is already impossible to create a Debian Wheezy image via the `create-image.sh`.
2. Add the recommendation to disable `net.ifnames`. Without it, following the instructions results in a non-functioning syzkaller setup.
=> Update the Linux documentation

syz-verifier/main.go, syz-verifier/main_test.go, syz-verifier/verf/verifier.go, syz-verifier/verf/verifier_test.go
The result reports for errno mismatches now outputs results under each system call in increasing order (from kernel `0` to kernel `N` for all kernels that returned results).
Example output  from a program ran on two kernels:
```
ERRNO mismatches found for program:
[✓] newfstatat(0xffffffffffffff9c, &(0x7f0000000100)='./file0\x00', &(0x7f0000000140)={0x0, 0x0, 0x0, 0x0, <r0=>0x0}, 0x0)
↳ Pool: 0, Errno: 2, Flag: 3
↳ Pool: 1, Errno: 2, Flag: 3
[✓] fstat(0xffffffffffffffff, &(0x7f00000001c0)={0x0, 0x0, 0x0, 0x0, <r1=>0x0})
↳ Pool: 0, Errno: 9, Flag: 3
↳ Pool: 1, Errno: 9, Flag: 3
[✗] syz_mount_image$hfsplus(&(0x7f0000000000), &(0x7f0000000040)='./file0\x00', 0x3, 0x1, &(0x7f00000000c0)=[{&(0x7f0000000080)="2fb0463911bbab13d96006a1e91c8e02f8ae5ff7bfe5660de0d90d", 0x1b, 0xffffffff}], 0x80000, …
```
=> syz-verifier: improved readability of result reports

dashboard/app/util_test.go, dashboard/dashapi/dashapi.go, syz-ci/jobs.go, syz-ci/manager.go, syz-ci/syz-ci.go, syz-ci/updater.go, syz-manager/manager.go, tools/syz-kcidb/kcidb.go, tools/syz-reprolist/reprolist.go
This will allow to make a call to meta-server and abort early when
authentication by bearer token is impossible.
=> dashboard/dashapi: return error from dashapi.New

pkg/report/linux.go, pkg/report/testdata/linux/report/344, pkg/report/testdata/linux/report/614, pkg/report/testdata/linux/report/615
Now that we increased CONFIG_PRINTK_SAFE_LOG_BUF_SHIFT to 16
we started getting full parsable "stack guard page was hit" crashes.
Extract the anchor frame as we do for stalls.
This makes reports deterministic rather than point to a random top frame.
=> pkg/report: parse "stack guard page was hit" better

pkg/rpctype/rpctype.go, syz-runner/runner.go, syz-verifier/main.go, syz-verifier/main_test.go
Contributes to #692
Implemented functionality that:
* removes the system calls with missing transitive dependencies from the set of enabled system calls, reporting the reason to the user
* finds the intersection of enabled system calls supported by all kernels and builds the choice table only using those
=> syz-verifier: use only system calls supported by all kernels and with no transitive dependencies when building the `prog.ChoiceTable`

dashboard/app/static/style.css, pkg/html/generated.go
After 12 digit kernel commit hashes were introduced, it turned out that there remains one HTML table that cannot accommodate such values.
Fix this by removing the max-width property from .list_table .stat. This class is not used for data that needs to be truncated anyway.
=> Adjust Kernel Build Commit column width

tools/syz-make/make.go
We previously observed syz-bot hanging OpenBSD machines. We made the problem
less acute by throwing resources at it. Go builds are good at
exploiting the machines themselves, so limiting make concurrency is a
clear benefit on OpenBSD.
=> tools/syz-make: limit make concurrency on OpenBSD

syz-verifier/main.go, syz-verifier/main_test.go, syz-verifier/stats/stats.go, syz-verifier/stats/stats_test.go, syz-verifier/verf/verifier.go, syz-verifier/verf/verifier_test.go
Contributes to #692
Created a `stats` package, used to compute statistics about `syz-verifier` runs. Statistics for the calls that produced mismatches in the program will be added to the result reports while general statistics will be shown when the program exits
=> syz-verifier: add utility for gathering statistics

syz-verifier/main.go, syz-verifier/main_test.go, syz-verifier/stats/stats.go, syz-verifier/stats/stats_test.go
Make use of the `syscall` package to add the errno descriptions in the result reports and global stats in order to have a more detailed output.
=> syz-verifier: add errno descriptions to reports

pkg/instance/instance.go, pkg/instance/instance_test.go, syz-runner/runner.go, syz-verifier/main.go
The Runner can now create an `ipc.Env` for every program about to be executed. Experiments have shown that this approach significantly reduced the rate of (supposedly false positive) mismatches:
* if creating an `ipc.Env` *once* per `Runner`, the percentage of `# syscall mismatches / syscall occurences` can be up to 30% for some system calls (e.g. some System V IPC-related system calls, most of them for semaphore operations)
* if creating an `ipc.Env` *every time* a program is executed by the Runner, the rate of `programs executed / minute` drops by ~10%, however the rate of `# syscall mismatches / # syscall occurences` stays below 4.5% for all system calls enabled (i.e. all except those that are causing concurrency, `perf_event_open*`, `prctl*`, `syz-_mount*`, …
=> syz-verifier: add option to create a new execution environment for each program

pkg/bisect/bisect.go, pkg/bisect/bisect_test.go, pkg/build/akaros.go, pkg/build/build.go, pkg/build/build_test.go, pkg/build/darwin.go, pkg/build/freebsd.go, pkg/build/fuchsia.go, pkg/build/gvisor.go, pkg/build/linux.go, pkg/build/linux_linux.go, pkg/build/linux_nolinux.go, pkg/build/linux_test.go, pkg/build/netbsd.go, pkg/build/openbsd.go, pkg/build/test.go, pkg/build/testdata/linux_compiler_ok/include/generated/compile.h, pkg/instance/instance.go, syz-ci/jobs.go, syz-ci/manager.go, tools/check-copyright.sh, tools/syz-build/build.go
Closes https://github.com/google/syzkaller/issues/2498
This PR makes it possible for syzkaller to extract information about compiler identity in those cases, when no exact compiler is specified in the syz-ci config file. It affects only those platforms where it is possible to specify a custom compiler.
This PR also contains a number of refactorings that let implement this changes in a more straightforward way. See details in the corresponding commit descriptions.
=> Detect default compiler versions

syz-verifier/stats/stats_test.go
Ensure `TestReportCallStats` and `TestReportGlobalStats` pass on OpenBSD as well. This was not the case before as `errno 11` is `resource deadlock avoided` on OpenBSD and `resource temporarily unavailable` on Linux.
=> syz-verifier/stats: ensure stats tests pass on OpenBSD

syz-verifier/main.go, syz-verifier/main_test.go, syz-verifier/stats.go, syz-verifier/stats_test.go, syz-verifier/test_utils.go, syz-verifier/verf/verifier.go, syz-verifier/verf/verifier_test.go, syz-verifier/verifier.go, syz-verifier/verifier_test.go
The `ReturnState` structure will store return values and other information resulted from executing a system call. The `Verify` function now checks that the `ReturnState`s of the same system call executed on different kernels are the same.
=> syz-verifier: create a ReturnState structure

syz-verifier/verifier.go
Modify the `Verify` function to only increase the number of mismatches (both total and per system call) when a new different state is found.
=> syz-verifier: modify mismatch calculation in the Verify function

prog/analysis.go, prog/target.go
Currently fallback coverage imposes an implicit 8K limit
on the max number of syscalls. 8K is quite close to the
current number of syscalls we have on Linux.
1. Bump this limit to 2M.
2. Detect limit violation during startup rather than later,
with an obscure error message and only if fallback coverage is used.
=> prog: increase max number of syscalls

syz-verifier/main.go, syz-verifier/main_test.go, syz-verifier/stats.go, syz-verifier/stats_test.go, syz-verifier/test_utils.go, syz-verifier/verifier.go, syz-verifier/verifier_test.go
Updates #692, depends on #2677
Added VM crashes as a possible `ReturnState` and included them in the logic of the `Verify` function. 
* Having a kernel crashing and the other ones producing results for a program  is considered a mismatch
*  Having all kernels crashing is a match
=> syz-verifier: include crashes in the verification process

sys/linux/dev_random.txt
Syscall `openat$random` should open /dev/random device.
=> sys/linux: minor fix of random dev syscall description

pkg/report/linux.go, pkg/report/testdata/linux/report/616
We ignored some el1_* arm64 frames, but not a new el1h_64_sync
frame appeared in HWASAN reports. Ignore it as well.
=> pkg/report: ignore el1h_64_sync frame

pkg/csource/csource_test.go
HandleSegv can radically increase compilation time/memory consumption on large programs.
For example, for one program captured from this test enabling HandleSegv increases
compilation time from 1.94s to 104.73s and memory consumption from 136MB to 8116MB.
This leads to CI failures on #2688.
Don't enable HandleSegv in short tests.
=> pkg/csource: don't enable HandleSegv in short tests

CONTRIBUTORS, sys/linux/socket_unix.txt
Noticed that descriptions for recvmsg and recvmmsg were missing from socket_unix.txt so added them.
Also fixed the type for sendmmsg$unix and the flag field for send_msghdr_un.
=> unix socket syscall updates

dashboard/config/openbsd/recreate.sh
Correct the path to the openbsd config file.
=> dashboard/config/openbsd: fix recreate script

pkg/auth/auth.go, pkg/auth/auth_test.go
Previously the reported failure was a nondescript
strconv.ParseInt: parsing "": invalid syntax
=> pkg/auth: check HTTP status from the server

pkg/report/linux_test.go
Restrict TestDisassemblyInReports from running on OSes other than
Linux, as the exact resulting disassembly is dependent on that.
=> pkg/report: run objdump-related tests only under Linux

tools/docker/syzbot/Dockerfile
The debian repo contains an old version and it can't build gVisor:
external/rules_pkg/private/pkg_files.bzl:315:12: name 'json' is not defined
=> tools/docker: Install bazel from the official bazel repo

sys/linux/dev_bifrost.txt
Mali GPU is at /dev/mali0 on Android.
=> ARM Mali GPU different dev node on Android

syz-manager/html.go
Extra coverage is attributed to a fake ".extra" syscall, which is not present in `SyscallMap`. As `syz-manager` is not aware of this, it fails to render the /syscalls page, when remote coverage is present.
Handle fake syscalls gracefully during /syscalls page rendering.
Closes #2725.
=> syz-manager: handle extra coverage in /syscalls

vm/adb/adb.go
On Android 12+ debugfs gets unmounted after boot.  This remounts it as
part of reset.
=> vm/adb: Mount debugfs on Android if it is not mounted.

dashboard/config/openbsd/recreate.sh
Once this is submitted, the changed line should be run to update ci-openbsd.
=> dashboard: switch recreate.sh to the new openbsd overlay location

pkg/csource/common.go, sys/targets/targets.go
This patch is part of my ongoing effort to implement XNU/Darwin support in syzkaller: #2553
Reproducers never worked with Darwin before, as we tried to create them using clang++, as well as with -static. Both is not possible as described in the change.
=> sys/targets: fix darwin reproducers

executor/common_bsd.h, pkg/csource/generated.go
At least on OpenBSD this is the behavior:
% doas ifconfig tun5 create
% doas ifconfig tun5 destroy
% doas ifconfig tun5 create
% doas ifconfig /dev/tun5 destroy
ifconfig: SIOCIFDESTROY: Invalid argument
=> executor: ifconfig destroy wants the interface (not device) name

docs/darwin/README.md, vm/qemu/qemu.go
This patch is part of my ongoing effort to implement XNU/Darwin support in syzkaller: #2553
This way users don't have to overwrite qemu_args in their configs.
=> vm/qemu: add apple_smc_osk and efi_{code,vars}_device options

CONTRIBUTORS, tools/syz-usbgen/usb_ids.patch
Previous patch causes build error on top of v5.14:
error: ‘usb_bus_type’ undeclared (first use in this function); did you mean ‘hid_bus_type’?
2299 |         bus_for_each_drv(&usb_bus_type, NULL, NULL, usb_device_id_dump_driver);
|                           ^~~~~~~~~~~~
|                           hid_bus_type
Fix it by including drivers/usb/core/usb.h where usb_bus_type declaration
is. Also, removed duplicate is_usb_device_driver definition, since it's
already in drivers/usb/core/usb.h.
Tested localy on qemu
Signed-off-by: Pavel Skripkin <paskripkin@gmail.com>
=> tools/syz-usbgen: fix usb_ids.patch

tools/syz-usbgen/usbgen.go
I wanted to fuzz only one driver, so I've slightly changed
usb_ids.patch to print ids only for needed driver:
So, I got following vm log:
```
syzkaller login: [   34.303492] hid: USBID: 0300da0b79810000000000000000000000
[   34.303969] hid: USBID: 0300da0b79010000000000000000000000
[   34.304454] hid: USBID: 0300da0b79f10000000000000000000000
[   34.304988] hid: USBID: 0300b80779810000000000000000000000
[   34.305455] hid: USBID: 0300f60d76000000000000000000000000
[   34.305941] hid: USBID: 030001200f330000000000000000000000
[   34.306406] hid: USBID: 0300012010330000000000000000000000
[   34.306893] hid: USBID: 0300012011330000000000000000000000
[   34.307364] hid: USBID: 030001201b330000000000000000000000
[   34.307865] hid: USBID: 03006e0508400000000000000000000000
[   34.308349] hid: …
```
=> tools/usbgen: handle zero ids count case

vm/adb/adb.go, vm/vmimpl/console.go
1. Add console string to the device struct in Adb Config
2. Add console implementation of Cuttlefish, using ssh when it's in remote instance
I've test it locally but not when Cuttlefish is remote, please instruct if this solution makes sense or there is better way to handle it.
=> vm/adb: add console impl for remote Android virtual device

docs/syz_verifier.md
Update the introduction of syz-verifier to better define the problem it
is attempting to solve: "semantic bugs" is the correct terminology for
the type of bugs that syz-verifier attempts to find.
Reflow the rest of the document to make it readable in plain-text.
Co-developed-by: @maramihali
=> docs/syz_verifier: update introduction

executor/common_kvm_amd64.h, executor/common_kvm_arm64.h, executor/common_kvm_ppc64.h, executor/common_linux.h, pkg/csource/generated.go, sys/syz-extract/linux.go, sys/syz-sysgen/sysgen.go
It is impossible to compile a number of definitions in `include/uapi/linux/kvm.h` for other platforms, which leads to `syz-extract` not being able to update constants.
Skip processing of this file for all arches except i386 and amd64.
This is a hacky and (hopefully) temporary solution until #2754 is implemented.
=> sys: skip kvm const extraction for non i386/amd64

pkg/host/syscalls_linux.go
Since commit 4f7e1d0f5e1c ("sys/linux: use openat for /dev/cdrom")
changed syz_open_dev to openat syzkaller tries to open /dev/cdrom
with r,w,rw flags. However, if there is no media in a cdrom
device these attempts will fail resulting in:
> disabling openat$sr: open(/dev/sr0) failed: no medium found
Add O_RDONLY|O_NONBLOCK mode to successfully open cdrom devices
with no media.
=> pkg/host: add O_NONBLOCK to isSupportedOpenFile

pkg/build/build.go
We've just got a timeout failure for TestCompilerIdentity test:
--- FAIL: TestCompilerIdentity (0.00s)
--- FAIL: TestCompilerIdentity/bazel (60.19s)
build_test.go:24: failed: timedout ["bazel" ""]
FAIL
=> pkg/build: increse timeout for bazel

vm/gce/gce.go
These messages are of relevance to debugging problems on syz-ci's side,
but due to log level 1 they are not saved to the logs by default. Set their
log level to 0.
=> vm/gce: adjust log level for timeout-related errors

vm/qemu/qmp.go
A user has reported the following crash:
panic: runtime error: invalid memory address or nil pointer dereference
goroutine 1021 [running]:
github.com/google/syzkaller/vm/qemu.(*instance).qmp()
vm/qemu/qmp.go:96 +0x1c9
github.com/google/syzkaller/vm/qemu.(*instance).hmp()
vm/qemu/qmp.go:115 +0xbd
github.com/google/syzkaller/vm/qemu.(*instance).Diagnose()
vm/qemu/qemu.go:662 +0x18d
qmp function accesses resp even if doQmp returns an error
and doQmp can return a nil resp in this case if inst.monEnc.Encode fails.
Don't access resp if error is returned. The only caller hmp
does not use the returned object is an error is returned.
=> vm/qemu: fix nil deref in qmp

docs/linux/setup_ubuntu-host_qemu-vm_x86-64-kernel.md
After this changes into the setup_ubuntu-host_qemu-vm_x86-64-kernel.md we'll:
1. Have prerequisites section.
2. Have smaller steps for a newcomer (used ### for 3 level subcategories).
3. Have the Ubuntu 20.04 LTS manually verified command chain.
4. Reduce the bar for Kernel unaware newcomers (v5.14 is proposed to be base).
5. Use optimized make -j\`nproc\`.
6. Have a simplified copy-paste procedure.
Live preview is available [here](https://github.com/tarasmadan/syzkaller/blob/update-ubuntu-doc/docs/linux/setup_ubuntu-host_qemu-vm_x86-64-kernel.md) .
=> docs/linux: extend and reformat Ubuntu documentation

docs/executing_syzkaller_programs.md
I've tested the command chain with Go v1.13, v1.14, v.1.15, v1.16 and v1.17.
Without the GO111MODULE=off documentation works for v1.13, v1.14 and v1.15. It doesn't work for v1.16+.
With the GO111MODULE=off it works for v1.13 - v1.17. No backward compatibility issues were found.
If we want to continuously support new Go versions and maintain the documentation consistency - it is a good place for the automation.
* as a small bonus - removed the $ to improve the copy-paste experience
=> docs/executing_syzkaller_programs.md: fixes the incompatibility with Go 1.16+

executor/executor.cc, pkg/ipc/ipc.go
We have seen cases when a test program re-execed the current binary:
11:53:29 executing program 0:
openat$zero(0xffffffffffffff9c, &(0x7f0000000040), 0x0, 0x0)
r0 = openat(0xffffffffffffff9c, &(0x7f0000000080)='/proc/self/exe\x00', 0x0, 0x0)
lseek(r0, 0x4000000000000000, 0x4)
execveat(r0, &(0x7f0000000080)='\x00', 0x0, 0x0, 0x1000)
In such cases, we have to be sure that executor will not print SYZFAIL
log messages and will not exit with kFailStatus.
Since a659b3f, syzkaller reports bugs in all these cases.
Fixes: a659b3f ("pkg/report: detect executor failures")
=> executor: fail if the first argument isn't a known command

vm/gce/gce.go
OpenSSH 8.8 release disables RSA signatures using the SHA-1 hash
algorithm by default.
Sadly, the ssh-serialport.googleapis.com:9600 uses the deprecated
algorithm for host-key. The end-point identifies itself as:
debug1: Remote protocol version 2.0, remote software version Go
debug1: no match: Go
...
debug1: kex: algorithm: curve25519-sha256@libssh.org
debug1: kex: host key algorithm: ssh-rsa
This should be fixed on the server side, but for now I added a
workaround of enabling this deprecated algorithm.
=> vm/gce: avoid ssh-rsa for user, for now allow it as host-key

executor/common.h, executor/common_kvm_ppc64.h, executor/common_linux.h, executor/common_usb.h, executor/common_usb_netbsd.h, executor/executor.cc, executor/style_test.go, pkg/csource/generated.go
Historically the code base does not use single-line compound statements
({} around single-line blocks). But there are few precedents creeped into
already. Add a check to keep the code base consistent.
=> executor: check for single-line compound statements

pkg/csource/csource.go, pkg/csource/csource_test.go, prog/generation.go, prog/minimization.go, prog/mutation.go, prog/prog.go, prog/rand.go
Currently csource skips calls at the very last moment, which has an
unpleasant consequence - if we make choice of enabled defines depend on
the individual calls or call properties, we may end up with defined yet
unused functions.
The perfect solution would be to untie
syz_emit_ethernet/syz_extract_tcp_res and NetInjection, and also to
untie VhciInjection and syz_emit_vhci.
For the time being, move these checks to the very beginning of csource
processing, so that these calls could be removed before we construct our
defines.
Adjust pkg/csource/csource_test.go to better cover fault injection
generation problems.
=> pkg/csource: remove calls instead of skipping them

docs/syz_verifier.md
Because of the line break, internal link didn't work.
=> docs/syz-verifier: fix internal link

docs/research.md
Hi, Snowboard is a testing tool that targets kernel concurrency bugs. It generates concurrent test inputs by analyzing the executions of sequential test inputs (generated by Syzkaller).
=> docs: add the reference to Snowboard paper

syz-verifier/test_utils.go
The current dir is not necessary writable and is generally a bad place for temp files.
Use a temp dir as scratch dir.
=> syz-verifier: fix use of the current dir in test

CONTRIBUTORS, pkg/cover/html.go
When we click on PC value in coverage page with the source code opened,
there was no option to go back to file src code.
Added a close button to hide (display:none) the syz description,
and bring back the last file source code view.
Fixes #2867
=> pkg/cover: added close btn to hide syz description

docs/syz_testbed.md, tools/syz-testbed/checkout.go, tools/syz-testbed/html.go, tools/syz-testbed/instance.go, tools/syz-testbed/stats.go, tools/syz-testbed/testbed.go
Creation of instances only at the start of the tool limits the scale of
the experiments.
Instead of setting up instances at the beginning, create, start and
stop them dynamically. This allows to conduct much larger experiments
while keeping the maximal resource consumption under control. When an
instance has been executing for the specified time, it is stopped and
replaced by another one.
Introduce two new parameters that control it:
- `max_instance` - the maximal number of simultaneously running instances.
- `run_hours` - the lifetime (in hours) of a single instance.
Now the longer the tool runs, the more test results will be accumulated
for each checkout specified in the configuration file.
Also, add a simple web interface, which is controlled by two optional
parameters:
- `http` - host …
=> tools/syz-testbed: produce results indefinitely

pkg/report/linux.go, pkg/report/report.go, pkg/report/testdata/linux/report/626
Currently KMSAN does not include the "Call Trace" line into its reports.
As syzkaller still expects it, most of those reports end up being
classified as corruped and do not get published by syzbot.
Adjust the parsing rules to support these new reports.
Add a test to validate the new behavior.
Closes #2733.
=> pkg/report: parse new-style KMSAN reports

pkg/config/merge.go, pkg/config/merge_test.go, tools/syz-testbed/checkout.go, tools/syz-testbed/instance.go, tools/syz-testbed/testbed.go
Let the user of the tool specify individual syz-manager configs for
checkouts. A base config is specified as previously and then individual
parts of jsons are applied to that base config, e.g.
```
<...>
"checkouts": [
{
"name": "first",
"repo": "https://github.com/google/syzkaller.git",
},
{
"name": "second",
"repo": "https://github.com/google/syzkaller.git",
"manager_config": {
"kernel_obj": "/tmp/linux-stable2"
}
}
],
"manager_config": {
"target": "linux/amd64",
"kernel_obj": "/tmp/linux-stable",
<...>
}
<...>
```
=> tools/syz-testbed: support per-checkout syz-manager configs

dashboard/app/reporting_test.go
Lets check that first response with ReportingUpdate("dashapi.BugStatusUpstream") from external system works well.
=> dashboard/app: check the reporting detach logic

Makefile
Allow the user to override host/target build flags (such as debug info
generation flags). This is useful for example when syzkaller is compiled
by the Yocto build system, as it always generates packages with debug info.
Signed-off-by: Ovidiu Panait <ovpanait@gmail.com>
=> Makefile: Allow GOHOSTFLAGS and GOTARGETFLAGS to be overridden

executor/style_test.go
SYZ_* constants are always defined and one must not check them via
ifdef. Add a check to prevent such problems during development (inspired
by the discussion in #2882).
=> executor: add an ifdef SYZ_* style check

tools/syz-env
To see you stopped containers, call "docker ps -a | grep Exit".
To clean your system, use "docker container prune". In my case ~9GB.
=> tools/syz-env: automatically remove the container on exit

dashboard/app/handler.go
Currently we show the decommissioned namespaces.
Lets hide this information to let users focus on more actionable things.
=> dashboard/app: hide decommissioned items

executor/executor.cc, executor/executor_bsd.h, executor/executor_darwin.h, executor/executor_linux.h, executor/nocover.h, pkg/osutil/osutil_unix.go, pkg/osutil/sharedmem_file.go, pkg/osutil/sharedmem_memfd.go
This PR includes a set of patches that increate the performance of syz-executor. Experiments with `syz-testbed` have demonstrated a 20-25% increase of the number of executions per second on CGE and a 25-30% speedup when running syzkaller under nested virtualisation. 
Commit descriptions contain more details on the specific changes.
=> syz-executor: increase the execution rate

executor/executor.cc, executor/executor_bsd.h, executor/executor_darwin.h, executor/executor_linux.h, executor/nocover.h
The previous strategy (delay kcov instance creation) seems not to work
very well in good sandboxed environments. Let's see if this approach is
more versatile.
Open a kcov handle for each thread at syz-executor's initialization, but
don't mmap it right away.
=> executor: delay kcov mmap until it is needed

executor/common_bsd.h, executor/common_linux.h, executor/executor.cc, pkg/csource/generated.go
```
executor: set fixed fd for extra coverage kcov instance
Currently it is dup2'd to 0, which is quite likely to be closed by the
fuzzer. Dup2 it to a safer fd instead.
```
```
executor: spread overlapping fds
There's a chance that the methods from common_bsd.h and common_linux.h
could dup2 (and thus close) an fd belonging to a kcov instance.
Prevent this by adjusting fd consts.
```
=> executor: bring some order to fd distribution

pkg/db/db.go, pkg/db/db_test.go, tools/syz-execprog/execprog.go
- pkg/db: properly handle errors when loading a DB
- tools/syz-execprog: don't store prog.LogEntry's
- tools/syz-execprog: support loading from corpus.db
- tools/syz-execprog: default -procs to 2*NumCPU
=> tools/syz-execprog: make suitable for regression testing

syz-ci/manager.go, syz-ci/syz-ci.go
Just as we upload coverage reports, it's useful to snapshot
corpus.db for sharing/regression testing.
=> syz-ci: support uploading corpus.db

executor/executor.cc, pkg/host/features.go, pkg/host/features_linux.go, pkg/host/host_freebsd.go, pkg/host/host_netbsd.go, pkg/host/host_openbsd.go, pkg/ipc/ipc.go, pkg/runtest/run.go, syz-fuzzer/fuzzer.go, tools/syz-execprog/execprog.go
It turns out that the current Linux implementation of KCOV does not
properly handle multiple mmap invocations on the same instance. The
first one succeedes, but the subsequent ones do not actually mmap
anything, yet returning no error at all.
The ability to mmap that memory multiple times allows us to increase
syz-executor performance and it would be a pity to completely lose it
(especially given that mmapping kcov works fine on *BSD).
In some time a patch will be prepared, but still we will have to support
both versions at the same time - the buggy one and the correct one.
Detect whether the bug is present by writing a value at the pointer
returned by mmap. If it is present, disable dynamic kcov mmapping and
pre-mmap 6 instances in the main() function - it should be enough for
all …
=> all: adapt to how mmapping a kcov instance works on Linux

executor/executor.cc
Otherwise, machine checks can fail.
=> executor: fix kcov mmaping in the non-optimized mode 

docs/freebsd/README.md
The instructions for compiling the executor files on the guest machine
referenced executor_freebsd.cc which no longer exists and is now
executor.cc. The DGOOS=freebsd flag is changed to DGOOS_freebsd=1 and
DGOARCH_amd64=1 added to compile syz-executor successfully
=> docs/freebsd: update README.md executor compile command on guest

executor/executor.cc
Set new kcov count limits: 6 for the default mode and 16 for the
optimized mode (when the instances are mmapped a needed). Don't generate
SYZFAIL when these limits are exhausted.
Just increasing those limits won't help as syzkaller will anyway come up
with programs that overcome them.
=> executor: do exitf instead of fail on kcov shortage

pkg/build/gvisor.go, pkg/osutil/osutil.go
We've got a timeout of "bazel aquery". It's currently set to 1 minute.
On an overloaded machine it can fire falsely, I guess bazel can start
only for 1 minute. Increase to 10 minutes.
=> pkg/build: increase bazel aquery timeout

executor/executor.cc, pkg/ipc/ipc_test.go
pkg/repro tries to clear the Threaded flag during repro simplification,
so it's easier just to ignore the remaining async flags in that case -
they won't be in the C repro either.
=> executor: ignore async flag in a non-threaded mode

syz-runner/runner.go, vm/vm.go
Current state: every 5 minutes VM reboots.
Fix: signal "executing program" to monitor to prevent this reboot.
=> syz-verifier: fix VM reboot every 5 minutes

syz-verifier/monitoring_api.go, syz-verifier/stats.go, syz-verifier/utils_test.go
Currently we use int to aggregate statistics.
Counters update require the lock() operation.
Lets relax it and move to int64 + atomic.AddInt64().
=> syz-verifier: use int64 instead of int for statistics

pkg/mgrconfig/config.go, pkg/report/report.go, pkg/repro/repro.go, syz-manager/manager.go
We have "suppressions" parameter to suppress non-interesting reports.
Add "interests" parameter which is an opposite of "suppressions" --
everything that's not in "interests" is suppressed.
It's matched against bug title, guilty file an maintainer emails.
=> pkg/mgrconfig: add "interests"

tools/create-openbsd-vmm-worker.sh
Must happen before cranking securelevel. This makes it possible to fuzz btrace
if we ever want that but more importantly: I have a pending request of running
btrace on the workers in order to investigate a recent performance regression.
=> tools/create-openbsd-vmm-worker: allow dt

tools/create-buildroot-image.sh
Currently the following errors happen during boot:
mount: mounting mqueue on /dev/mqueue failed: No such file or directory
mount: mounting hugetlbfs on /dev/hugepages failed: No such file or directory
mount: mounting fuse.lxcfs on /var/lib/lxcfs failed: No such file or directory
Remove these mounts.
Mounting of /dev/mqueue and /dev/hugepages fails because these dirs don't exist
and the buildroot init does not create them for some reason. We can't pre-create
them because /dev is itself mounted as devtmpfs.
But we also don't need these mounts. Both mqueue and hugetlbfs are trivial to mount
and the fuzzer does not have problems mounting them locally and using (we have good
coverage anyway).
fuse.lxcfs is simply a fuse filesystem (".lxcfs" is ignored). We don't need to mount
an empty global …
=> tools/create-buildroot-image.sh: remove bogus mounts

vm/qemu/qemu.go
Invoking qemu with the nowait option produces a warning that the
short-form boolean options are deprecated and that wait=off is
preferred.
=> vm/qemu/qemu.go: changed deprecated nowait option to preferred wait=off

pkg/report/report.go, syz-manager/manager.go
The recent commit 'pkg/mgrconfig: add "interests"' made pkg/repro
symbolize returned reports. But syz-manager symbolizes them as well.
This leads to double symbolization. Don't symbolize second time.
Fixes #2934
=> syz-manager: don't symbolize reproducer twice

tools/docker/syzbot/Dockerfile
Currently we use the default distro Go, which is 1.15 in Bullseye.
Switch to 1.17 which has register-based calling convention and is
significantly faster.
=> tools/docker/syzbot: switch to Go 1.17

dashboard/config/linux/bits/subsystems.yml
Currently, "syz-env make configs..." command generate errors because:
1. DAMON config options doesn't exist in Linux kernel versions < 5.15.
2. "-" was used instead of the "_" in the description.
=> dashboard/config: fix sybsystems.yml, DAMON support

dashboard/config/openbsd/config.ci, executor/common_bsd.h, pkg/csource/generated.go, tools/create-openbsd-vmm-worker.sh
Currently OpenBSD instances are underutilized because of using only 2
syz-executor processes per VM. Change it to 6 to match the number of
procs on other syzbot instances.
=> dashboard/config/openbsd: increase the number of procs

sys/targets/targets.go
Disable GCC warnings:
* stringop-overflow
* array-bounds
* format-overflow
These warnings generate false positives for C reproducers which cause
GCC to fail if -Werror is given.
This commit fixes the following false positives:
/root/test.c: In function ‘main’:
/root/test.c:88:50: error: writing 1 byte into a region of size 0 [-Werror=stringop-overflow=]
88 | NONFAILING(*(uint8_t*)0x20000088 = 3);
/root/test.c:85:28: error: ‘memcpy’ offset [0, 23] is out of the bounds [0, 0] [-Werror=array-bounds]
85 | NONFAILING(memcpy((void*)0x20000040, "\001\000\000\000\002\000\000\000\003\000\004\000\000\000\000\000\005\000\000\000\000\000\000\000", 24));
<stdin>:86:40: error: ‘%023llo’ directive writing 23 bytes into a region of size 0 [-Werror=format-overflow=]
<stdin>:43:123: note: in definition of …
=> sys/targets: Disable some GCC warnings reported for C reproducers

CONTRIBUTORS, docs/contributing.md, docs/darwin/README.md, docs/executing_syzkaller_programs.md, docs/freebsd/README.md, docs/linux/external_fuzzing_usb.md, docs/linux/setup.md, docs/netbsd/README.md, docs/openbsd/setup.md
Updated documentation regarding source code checkout from the legacy gopath
mode 'go get' to 'git clone'.
Fixes #2828
=> /docs: update instructions for source checkout

executor/common.h, executor/common_ext.h, pkg/csource/gen.go, pkg/csource/generated.go, pkg/host/syscalls_linux.go, syz-ci/updater.go
Add an empty common_ext.h which is included into executor and C reproducers
and can be used to add non-mainline pseudo-syscalls w/o changing any other files
(by replacing common_ext.h file).
It would be good to finish #2274 which allows to add pseudo-syscalls
along with *.txt descriptions, but #2274 is large and there are several
open design questions. So add this simple extension point for now.
=> executor: add extension point for adding non-mainline pseudo-syscalls

Makefile, docs/linux/setup.md, go.mod, go.sum, tools/docker/big-env/Dockerfile, tools/docker/old-env/Dockerfile
- go.sum: run go mod tidy
- Makefile: don't test dashboard/app build with Go 1.12
- tools/docker/old-env: don't use --allow-releaseinfo-change
- tools/docker: update clang to version 12
- tools/docker/old-env: update to Go 1.16
- docs: update Go versions
=> dvyukov go1.16

tools/create-openbsd-vmm-worker.sh
Although it's signified in macros as TUN, in fact common_bsd.h opens
/dev/tap* devices. So create 8 TAP devices instead of 8 TUN devices.
=> tools: create /dev/tap* instead of /dev/tun* in OpenBSD

executor/common.h, executor/common_linux.h, executor/executor.cc, executor/executor_linux.h, pkg/csource/csource.go, pkg/csource/generated.go
As was found out in #2921, fork bombs are still possible in Linux-based
instances. One of the possible reasons is described below.
An invalid stack can be passed to the clone() call, thus causing it to stumble
on an invalid memory access right during returning from the clone() call. This
is in turn catched by the NONFAILING() macro and the control actually jumps
over it and eventually both the child and the parent continue executing the
same code.
Prevent it by handling SIGSEGV and SIGBUS differently during the clone process.
Co-authored-by: Andrei Vagin <avagin@google.com>
I'm currently testing if this patch works as intended.
=> RFC: executor: fail on SEGV during clone()

pkg/db/db.go, pkg/db/db_test.go, syz-manager/manager.go
corpus.db may get corrupted on an unexpected reset, etc.
Commit a254b0f5 ("pkg/db: properly handle errors when loading a DB")
made these errors fatal and manager never recovers on its own.
If we got a corrupted db, delete it and try again.
=> syz-manager: recover if corpus.db is corrupted

pkg/db/db_test.go
Opening inaccessible file won't fail under root.
Skip the test.
=> pkg/db: fix test under root

tools/docker/env/Dockerfile, tools/docker/syzbot/Dockerfile
Until KMSAN compiler API is finalized, we often need to use ToT Clang to
build the kernel. Download the latest compiler build from GS, and put it
under /syzkaller/clang-kmsan.
=> tools/docker: download custom clang to build KMSAN

pkg/db/db.go, pkg/db/db_test.go, syz-hub/state/state.go, syz-manager/manager.go, tools/syz-db/syz-db.go, tools/syz-execprog/execprog.go
It was too radical to repair and overwrite db file unconditionally.
syz-execprog probes if a given file is a database. Usually it's a crash log
or a single program, but db.Open started to overwrite it.
And an explicit repair flag in db.Open and enable it only in
syz-manager and syz-hub.
Fixes #2997
=> pkg/db: make repair of the db file optional

dashboard/app/api.go, dashboard/app/app_test.go, dashboard/app/entities.go
Remember how many crashes are caused by each particular bug each day.
We need this statistics to evaluate the results of our changes to
descriptions and fuzzing engine. For now, let them just be in the DB,
some time later the support on the UI side will also follow.
=> dashboard/app: store daily stats for individual bugs

pkg/mgrconfig/config.go, pkg/mgrconfig/load.go, syz-ci/manager.go, syz-manager/manager.go
Right now we have two inconveniences:
- If a call is disabled, all progs which contain it are ignored. Even if they might still give some coverage.
- If a program is disabled as indicated above, it remains in the corpus forever. Even if we don't need it anymore.
This PR tries to addresses both of them in such a way that should be beneficial both for local syzkaller execution and for syzbot.
=> RFC: syz-manager: facilitate the removal of unneeded calls from the corpus

CONTRIBUTORS, docs/fuchsia/README.md
The links to get started and install fuchsia are broken.
This commit updates the links with valid ones.
=> docs: update fuchsia README.md

AUTHORS, CONTRIBUTORS, executor/executor_darwin.h
Hey everyone, I fixed a bug.
The bug causes the following error.
```
...
mkdir -p ./bin/darwin_arm64
clang -o ./bin/darwin_arm64/syz-executor executor/executor.cc \
-arch arm64 -I /Volumes/NewAPFS/kernel/xnu-7195.81.3/san -Wno-deprecated-declarations -O2 -pthread -Wall -Werror -Wparentheses -Wunused-const-variable -Wframe-larger-than=16384 -Wno-array-bounds -lc++  -DGOOS_darwin=1 -DGOARCH_arm64=1 \
-DHOSTGOOS_darwin=1 -DGIT_REVISION=\"52e8932e8dedd6eae5817814c84c07948141e86e+\"
In file included from executor/executor.cc:401:
executor/executor_darwin.h:83:6: error: use of undeclared identifier 'mmap_alloc_size'
if (mmap_alloc_size > kCoverSize)
^
1 error generated.
make: *** [executor] Error 1
make: *** Waiting for unfinished jobs....
...
```
=> fix: "mmap_alloc_size"->"cov->mmap_alloc_size"

prog/rand.go
Add more special Ints to the array as it supports integers of 64
bytes length.
=> prog: add more integers for generator

executor/common_linux.h, pkg/csource/generated.go
We cannot expect syscalls to always succeed during fuzzing, especially
when the situation involves a complex interaction with the system.
For the syz_genetlink_get_family_id case, it leads to numerous SYZFAIL
crashes every day.
Don't print a SYZFAIL error for this pseudo syscall.
=> executor: tolerate syz_genetlink_get_family_id failures

docs/syz_testbed.md, pkg/config/merge.go, pkg/config/merge_test.go, pkg/html/html.go, tools/syz-linter/linter.go, tools/syz-testbed/checkout.go, tools/syz-testbed/html.go, tools/syz-testbed/instance.go, tools/syz-testbed/stats.go, tools/syz-testbed/table.go, tools/syz-testbed/targets.go, tools/syz-testbed/templates/table.html, tools/syz-testbed/templates/testbed.html, tools/syz-testbed/testbed.go
This PR introduces the following changes:
- Table footers that further automatise data aggregation.
- Configurations are not plain JSONs (at least for normal runs with syzkaller), otherwise it was problematic when branches with new options were tested.
- The tool now supports different modes of operation - for now these are `syzkaller` (check out and run syzkaller instances for the specified time, then again and again) and `syz-repro` (check out and run `syz-repro` on crash logs from the specified directory).
- Numerous minor enhancements.
=> tools/syz-testbed: support syz-repro and other enhancements

pkg/host/host_test.go, pkg/host/syscalls.go, pkg/host/syscalls_linux_test.go, pkg/runtest/run_test.go, syz-fuzzer/testing.go, syz-runner/runner.go, tools/syz-stress/stress.go
When syz-fuzzer starts, it tries all syscalls to filter out any that are
not supported. This process should include only the syscalls that are
enabled using the 'enable_syscalls' and 'disable_syscalls' fields in
syz-manager's config.
This is useful for fuzzing Cuttlefish devices, for example, where the
'vhost_vsock' syscall needs to be excluded from fuzzing and from this
test.
=> Run only enabled syscalls as part of syz-fuzzer startup

pkg/instance/instance.go, pkg/instance/instance_test.go, syz-verifier/verifier.go
syz-runner doesn't use the -collide mode. Lets remove it.
=> syz-verifier: don't use -collide in the runner

syz-verifier/verifier_test.go
=> syz-verifier: fix syscalls API mapping in test

.github/workflows/ci.yml
- Pinned actions by SHA https://github.com/ossf/scorecard/blob/main/docs/checks.md#pinned-dependencies
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
>Pin actions to a full length commit SHA
>Pinning an action to a full length commit SHA is currently the only way to use an action as an immutable release. Pinning to a particular SHA helps mitigate the risk of a bad actor adding a backdoor to the action's repository, as they would need to generate a SHA-1 collision for a valid Git object payload.
https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions
Also, dependabot supports upgrades based on SHA.
Signed-off-by: naveensrinivasan …
=> Pin actions to a full length commit SHA

.github/dependabot.yml
**What changes were proposed in this pull request?**
Enable dependabot to get security updates and if needed version updates on dependencies.
**Why are the changes needed?**
https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically
Having knowledge about vulnerabilities of the dependencies helps the project owners decide on their dependency's security posture to make decisions.
If the project decides to get updates only on security updates and not on any version updates then setting these options would not open any PR's open-pull-requests-limit: 0
This option has to be enabled in the security section of the project.
https://docs.github.com/en/code-security/supply-chain-security/managing-vulnerabilities-in-your-projects-dependencies/confi …
=> Included Dependabot

pkg/bisect/bisect_test.go, pkg/compiler/const_file_test.go, pkg/cover/report_test.go, pkg/host/machine_info_linux_test.go, pkg/osutil/fileutil_test.go, pkg/osutil/osutil_test.go, pkg/vcs/git_repo_test.go, syz-hub/state/state_test.go, syz-verifier/utils_test.go, vm/vm_test.go
A testing cleanup. This PR replaces `ioutil.TempDir` with `t.TempDir` in tests.
We can use the `T.TempDir` function from the `testing` package to create temporary directory. The directory created by `T.TempDir` is automatically removed when the test and all its subtests complete.
Reference: https://pkg.go.dev/testing#T.TempDir
=> all: use `t.TempDir` to create temporary test directory

pkg/cover/html.go, pkg/cover/report.go, pkg/cover/report_test.go, pkg/instance/instance.go, pkg/ipc/ipc.go, pkg/mgrconfig/config.go, pkg/rpctype/rpctype.go, syz-fuzzer/fuzzer.go, syz-fuzzer/proc.go, syz-manager/cover.go, syz-manager/html.go, syz-manager/manager.go, syz-manager/rpc.go, tools/syz-cover/syz-cover.go, tools/syz-runtest/runtest.go
Raw coverage might be important when e.g. analysing the origins of
out-of-place coverage in coverage reports or understanding why the
fuzzer could not reach deeper code.
If "raw_cover" in syz-manager config is set to `true`, syzkaller will
remember unsorted and unduplicated coverage (PCs) for each its
corpus program.
```
<...>
"raw_cover": true,
<...>
```
Raw coverage can be accessed by following HTML links from `/corpus` and `/cover`.
The resulting sequences of PCs can be symbolized e.g. via
`cat cover.txt | addr2line -i -afe ./vmlinux`
Also, this PR includes some minor refactoring.
=> all: add raw coverage collection option

pkg/report/linux.go, pkg/report/testdata/linux/report/646
It popped up in a new KASAN report after recent KASAN changes.
=> pkg/report: ignore print_report function

vm/cuttlefish/cuttlefish.go, vm/gce/gce.go, vm/vm.go
This new VM type embeds the existing 'gce' type to start an instance and
then run a Cuttlefish Android VM on it using the 'launch_cvd' binary
installed on it.
This requires us to make a few fields on the 'gce' type visible so that
'cuttlefish' can set them when starting the instance.
The remaining functionality (SSH forwarding, file copying, and running
commands on the nested Android VM) will be in following changes.
For more information on Cuttlefish, see:
https://source.android.com/setup/create/cuttlefish
https://android.googlesource.com/device/google/cuttlefish/
=> vm/cuttlefish: add vm type for cuttlefish on gce

pkg/instance/instance.go, pkg/instance/instance_test.go, syz-manager/manager.go, tools/syz-runtest/runtest.go
Otherwise we get problems while testing patches for older syzkaller
versions, which didn't support optional arguments.
Adjust tests so that problems with how OldFuzzerCmd handles such
arguments could be seen.
=> pkg/instance: consider the optional flags argument

pkg/build/build.go
With very few exceptions, the building code remains essentially the
same, so there's no need to explicity specify all possible combinations.
Refactor the code.
=> pkg/build: simplify the code

pkg/report/linux.go, pkg/report/testdata/linux/report/647
These are not normal warnings, but they look like real warnings for syzkaller.
=> pkg/report: ignore eibrs mitigation warnings

tools/syz-build/build.go
Let the user specify a custom compiler for building the kernel, just
like it can be done in syz-ci's configs.
=> tool/syz-build: add compiler option

dashboard/app/jobs.go, dashboard/app/jobs_test.go, syz-ci/manager.go
Such bugs don't have an explicit repro, but in fact we can easily test them, even without any changes to the testing code.
Adjust #syz test request validation.
=> dashboard: test patches for boot error bugs

pkg/gce/gce.go, syz-manager/manager.go, vm/gce/gce.go
Now syzkaller can only use the zone where it's running. Make it a
configurable option instead (with the old behavior as a fallback).
=> vm/gce: make zone_id configurable

vm/cuttlefish/cuttlefish.go
We need to tunnel ports from the Manager instance all the way through to the virtual device. We do
this by tunneling from the Manager to the worker GCE instance using 'socat' on the worker instance
and 'adb reverse' to forward the port on the device.
We need the 'socat' process to keep running for the tunnel to stay open. We can check for an error
on launch, but to check if the process is still running we send it a zero signal after waiting an
appropriate amount of time.
The 'adb reverse' command, by comparison returns immediately after the connection is established and
keeps the tunnel open. We loop until we find a valid/available port, similar to what is done in
vm/adb/adb.go. In practice, this nearly always finds a valid port on the first attempt.
=> vm/cuttlefish: implement forward function

syz-ci/jobs.go
For boot-time bugs there may be no repro, yet we can test it. Only leave
a sanity check (if syz repro is present, then repro options must also
be, and vice versa).
=> syz-ci: don't require a repro for JobTestPatch

executor/common_linux.h, pkg/csource/generated.go
executor: overriden implementations of _mkdir_, _rmdir_, _symlink_ when compiled for x86/x64 with Android sandboxing enabled
**The issue**
Syz-executor is linked against glibc when fuzzing runs on Cuttlefish x86-x64. However Android blocks calls into _mkdir_, _rmdir_, _symlink_ which causes syz-executor to crash. When fuzzing runs on Android device this issue is not observed, because syz-executor is linked against Bionic. Under the hood Bionic invokes _mkdirat_, _inlinkat_ and _symlinkat_, which are allowed by _seccomp-bpf_.
_seccomp-bpf_ is a system component on Android (based on seccomp from Linux) that allows filtering of system calls. This approach reduces attack surface on kernel space. When a process in a "secure" state attempts to invoke a syscall outside allowed set it crashes. …
=> Fix divergence between Bionic and glibc for syz-executor

docs/linux/setup_linux-host_qemu-vm_arm64-kernel.md
=> docs/linux: fix trivial typing typo ida_rsa -> id_rsa

pkg/instance/instance.go, tools/syz-execprog/execprog.go
Syzbot tests patches with -collide=true in order to trigger more bugs,
but now that -collide flag is deprecated, this no longer makes sense.
Moreover, it actually prevents the testing of bugs with syz repro now -
syz-execprog immediately exits due to -collide=true and env.Test()
accepts it as a normal outcome.
Set -collide=true only for those bugs, where collide was set to true by
the reproducer (and therefore syzkaller at that revision supported it).
Don't exit from syz-execprog immediately if -collide is set to true.
This will prevent such bugs from happening later and make the problem
more visible.
This was initially part of #3083, but seems to be more urgent to merge,
so pushing it as a separate PR.
Before …
=> all: fix patch testing for bugs witout C repro

docs/coverage.md
Based on https://github.com/google/syzkaller/blob/master/pkg/cover/html.go#L823 the color for "both" is actually "rgb(200, 100, 0)" which is #c86400 (and not #ff6400 which is currently in the documentation).
=> docs: fix coverage color for "both"

vm/vmimpl/vmimpl.go
Selecting the monitor port for qemu using an unseeded pseudo-random generator can lead to failed VM startups,
as the code contains race conditions. This happens frequently if multiple instances are started with a script.
Using real random ports provided by crypto/rand reduces the risk of failing VM starts.
=> vm/vmimpl: improve port selection

pkg/vcs/git.go
Android kernel source uses Git submodules to separate vendor- or
device-specific kernel modules from the main kernel source.
This calls 'git submodules update --init' after calls to 'git checkout',
which is the equivalent of adding the '--recurse-submodules' flag to
'git clone'.
For cases where submodules aren't used (all other Syzkaller targets)
this additional command is a no-op.
=> pkg/vcs: recursively clone git submodules

pkg/log/log.go, pkg/report/report.go, pkg/report/testdata/all/report/5, syz-fuzzer/proc.go
Right now, all fuzzer fatal errors are hidden in "lost connection to test machine"  or "no output from test machine" reports.
=> report: report fuzzer fatal errors

tools/syz-trace2syz/proggen/call_selector.go
The openat filename argument is not necessary a pointer to a string.
It can be a pointer to a struct that builds a string by pieces.
=> tools/syz-trace2syz: fix a panic in tests

syz-manager/manager.go
Now it mistakingly runs only if there was an error during repro
generation.
=> syz-manager: fix strace run condition

pkg/report/gvisor.go
Ensure that the dash char '-' is treated as a literal instead of as a range in regular expression.
=> vm/gvisor: fix regex typo

dashboard/app/main.go, dashboard/app/templates.html
- dashboard/app: don't show Uptime is manager is inactive
- dashboard/app: remove dead code
- dashboard/app: rename Active to Last active
- dashboard/app: show kernel config for the current manager build
=> dvyukov dashboard show uptime

pkg/instance/instance.go
Fix these crashes:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xd430ae]
goroutine 875 [running]:
github.com/google/syzkaller/pkg/instance.(*inst).testRepro.func1(...)
pkg/instance/instance.go:371
github.com/google/syzkaller/pkg/instance.(*inst).testRepro(0xc0005a2c80)
pkg/instance/instance.go:396 +0x26e
github.com/google/syzkaller/pkg/instance.(*inst).test(0xc0005a2c80)
pkg/instance/instance.go:293 +0xf2
github.com/google/syzkaller/pkg/instance.(*env).Test.func1()
pkg/instance/instance.go:237 +0x26
created by github.com/google/syzkaller/pkg/instance.(*env).Test
pkg/instance/instance.go:237 +0x1d7
syz-ci.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
=> pkg/instance: fix nil derefs in patch testing and bisections

pkg/build/linux_generated.go, tools/create-gce-image.sh
If we don't enable SFTP in SSH daemon, then scp will not work w/o -O option.
Fixes:
syz-ci-devel    | 2022/05/10 09:01:23 syz-ci-devel-kasan: VM testing failed with: failed to copy test binary to VM: failed to run ["scp" "-P" "55610" "-F" "/dev/null" "-o" "UserKnownHostsFile=/dev/null" "-o" "BatchMode=yes" "-o" "IdentitiesOnly=yes" "-o" "StrictHostKeyChecking=no" "-o" "ConnectTimeout=10" "/workdir/syzkaller/current/bin/linux_s390x/syz-fuzzer" "root@localhost:/syz-fuzzer"]: exit status 255
syz-ci-devel    | Warning: Permanently added '[localhost]:55610' (ED25519) to the list of known hosts.
syz-ci-devel    | subsystem request failed on channel 0
syz-ci-devel    | scp: Connection closed
Signed-off-by: Alexander Egorenkov <eaibmz@gmail.com> …
=> tools/create-gce-image.sh: enable sftp in ssh daemon

dashboard/app/api.go, dashboard/app/repro_test.go
This has two objectives:
1) Make repros better over time (as we update descriptions / improve
syzlang / repro- and fuzzing algorithms), even for old bugs.
2) Constrain the impact of backward compatibility bugs in syzkaller.
The fewer old repros we have, the less likely it is to stumble on some
problem during patch testing / bug or fix bisection.
Also closes https://github.com/google/syzkaller/issues/3122
=> dashboard: improve the needRepro logic

dashboard/app/access.go, dashboard/app/app_test.go, dashboard/app/handler.go, dashboard/app/main.go
5xx category signals the Internal Server Errors and require server developers attention.
4xx category means client side problem and doesn't require server developers attention.
The tests are needed for PR.
=> dashboard/app: return 404 instead of 500 for user requests

pkg/ifuzz/powerpc/gen/powerisa31_tex_to_syz, pkg/ifuzz/powerpc/generated/insns.go
The source PowerISA latex files have updated:
- changed files layout;
- "cntlzw." got corrected.
The fixed are not used by syzkaller in macros so there should be
no huge change in behaviour, if any.
Signed-off-by: Alexey Kardashevskiy <aik@linux.ibm.com>
=> pkg/ifuzz/powerpc: update cntlzw instruction

executor/executor.cc, pkg/ipc/ipc.go
When a shared memory is used, the executor can corrupt reply messages,
so let's add magic to detect such cases.
It is an attempt to debug issues like this one:
https://syzkaller.appspot.com/bug?id=faca64c3182e9f130ca94b7931dd771be390ef67
=> ipc: add magic in a call reply

executor/executor.cc
Fixes: fcfad4ffcf3a ("ipc: add magic in a call reply")
=> executor: write magic in write_extra_output

tools/docker/env/Dockerfile, tools/docker/syzbot/Dockerfile
Switch to a custom Clang version built from LLVM trunk 9ffb5944a699
with a patch on top of it implementing the -msan-pass-caller-to-runtime
flag. This flag is needed to detect noinstr->instr transitions in the
kernel. Once it is tested on syzbot, it will be added to upstream Clang.
=> tools/docker: update Clang for KMSAN

pkg/osutil/sharedmem_memfd.go
Go-runtime opens all files with CLOEXEC by default.
exec.Cmd doesn't close file descriptors in a child process and so memfd without
CLOEXEC can leak to an executor process where its content can be corrupted by
one of test system calls.
=> osutil: create memfd with the MFD_CLOEXEC flag

executor/common_linux.h, pkg/csource/generated.go
syzkaller reports the following error when it tries to create a C reproducer:
<stdin>: In function ‘syz_clone’:
<stdin>:289:48: error: ‘CLONE_VM’ undeclared (first use in this
function)
<stdin>:289:48: note: each undeclared identifier is reported only once
for each function it appears in
compiler invocation: gcc [-o /tmp/syz-executor3459695007 -DGOOS_linux=1
-DGOARCH_amd64=1 -DHOSTGOOS_linux=1 -x c - -m64 -O2 -pthread -Wall
-Werror -Wparentheses -Wunused-const-variable -Wframe-larger-than=16384
-Wno-stringop-overflow -Wno-array-bounds -Wno-format-overflow
-static-pie -fpermissive -w]
=> executor: include sched.h for syz_clone

vm/cuttlefish/cuttlefish.go
The artifacts are copied in by the build() function in pkg/build/android.go. If we don't pass these flags, Cuttlefish will start with the normal kernel, not the KASan-instrumented one we've built.
=> vm/cuttlefish: pass -kernel_path and -initramfs_path flags

dashboard/app/bug.html, dashboard/app/index.yaml, dashboard/app/main.go, dashboard/app/templates.html
This PR addresses to some degree the complaints that we received on our [mailing list](https://groups.google.com/g/syzkaller/c/-7hzkbArE6k/m/yjM_z9ejEgAJ).
- Let the user choose only one bug group and see it.
- Highlight the fixing commit on the bug info page.
- Highlight the presence of a fixing commit on the bug table.
Ideally we should implement a normal [bug search](https://github.com/google/syzkaller/issues/647) or, even better, somehow classify bugs into subsystems. But it seems that we don't have the necessary bandwidth to do it right now.
=> dashboard: minor UX improvements

tools/docker/syzbot/Dockerfile
We need it to build Cuttlefish images.
=> tools/docker: add rsync to the syzbot docker

prog/any.go, prog/any_test.go, prog/export_test.go, sys/test/exec.txt
Currently reproducing crashed with a particular seed requires
changing sources and rebuilding the test.
Make it possible to provide seed via env var.
=> prog: allow to use fixed test seed w/o rebuilding tests

executor/common_linux.h, pkg/csource/generated.go
executor: _setup_binderfs_ rearranged to be called before seccomp filters installation 
**The issue:** when syzkaller starts with sandbox mode 'android' it doesn't work because syz-executor crashes during invocation of 'mount(...)' syscall. This causes sys-manager to reboot the phone and the process repeats itself. The issue is not observed in sandbox mode 'setuid'. 
**The solution:** The crash happens because seccomp filters created for sandbox mode 'android' block mount(...) syscall. To fix the issue I moved a call of the failing function (_setup_binderfs_) prior to seccomp filters installation in _do_sandbox_android_.
Bugs:  233650668, 233755379
=> executor: fixed sandbox mode 'android'

Makefile
Go test runs vet tool on source files.
Vet tool takes insane amount of time on our auto-generated files.
We run go test in 3 presubmit stages, disable vet with -vet=off
in all but one presubmit stage. It should give the same coverage,
but save some latency and maybe reduce OOMs in race stage.
syzkaller$ TIME="%e %M" taskset -c 0 time go test -run=nothing ./prog
ok  	github.com/google/syzkaller/prog	0.162s [no tests to run]
88.59 6766736
syzkaller$ TIME="%e %M" taskset -c 0 time go test -run=nothing -vet=off ./prog
ok  	github.com/google/syzkaller/prog	0.159s [no tests to run]
40.22 5256900
=> Makefile: run vet only once during presubmit

executor/common_usb.h, executor/common_usb_linux.h, executor/common_usb_netbsd.h, pkg/csource/generated.go
gcc 12.1 reports the following -Werror=array-bounds error:
///
In function 'bool lookup_connect_response_in(...)'
executor/common_usb.h:632:66:
error: array subscript 'usb_qualifier_descriptor[0]' is partly outside array
bounds of 'char [8]' [-Werror=array-bounds]
|
632 |        qual->bNumConfigurations = index->dev->bNumConfigurations;
|        ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In function 'volatile long int syz_usb_connect_impl(...)':
executor/common_usb_linux.h:332:23: note: object 'response_data' of size 8
|
332 |        char* response_data = NULL;
|              ^~~~~~~~~~~~~
...
In function 'bool lookup_connect_response_in(...)',
executor/common_usb.h:633:57:
error: array subscript 'usb_qualifier_descriptor[0]' is partly outside array
bounds of 'char [8]' …
=> executor: fix out of bounds write in lookup_connect_response_in()

prog/any.go, prog/any_test.go, prog/mutation.go, prog/test/fuzz_test.go
If we grow any blob during mutation, we allocate a new address for it
(so that it does not overlap with other data).
To do this we call analyze after the mutation.
However, after mutation the blob can grow out of bounds of the data area
and analyze will cause out-of-bounds access during marking of existing
allocations.
Fix this by calling analyze before we mutate the blob.
Also while we are here use the proper call for analyze.
Currently we always analyze only the first call,
which is wrong (probably a latent TODO from initial implementation).
Fixes #3206
=> prog: fix out-of-bounds access in any blob mutation

dashboard/app/app_test.go, dashboard/app/main.go
In some cases Linux build system generates source file names
that contain dots, e.g.:
arch/x86/kvm/../../../virt/kvm/kvm_main.c
Support this in the regexp.
=> dashboard/app: support . in source file names

pkg/compiler/types.go, prog/any.go, prog/any_test.go, sys/test/any.txt
We've got the following panic:
--- FAIL: TestMutateRandom (7.77s)
export_test.go:37: seed=1655724857302243235
--- FAIL: TestMutateRandom/test/32_shmem (0.00s)
panic: bad size [recovered]
panic: bad size
goroutine 562 [running]:
panic({0x5ea5a0, 0x8dade8})
/usr/local/go/src/runtime/panic.go:1038 +0x215
github.com/google/syzkaller/prog.(*Target).squashResult(0xc0002a9ba0, 0xc026faa7b0, 0xc026ad1bc8)
/syzkaller/gopath/src/github.com/google/syzkaller/prog/any.go:236 +0x2d1
This happens because we try to squash resource of size 1.
While we still don't have such resources in real descriptions,
we've got one in test descriptions (added in out_overlay change).
Support int8 resources in squashing procedure.
=> prog: support int8 resources in any squashing

pkg/instance/execprog.go
That method was not assumed to take ownership of the instance. This
can lead to double-closing of it during bisection/patch testing, and
therefore to panic().
Closes #3210.
=> pkg/instance: don't close vmInst in SetupExecProg

dashboard/app/templates.html
Right now it's sent by email, but still not displayed on the web page.
=> dashboard: show console output for successful patch tests

.gitignore, docs/fuchsia/README.md, executor/common.h, executor/common_fuchsia.h, executor/executor.cc, pkg/csource/generated.go, sys/fuchsia/hypervisor_guests.txt, sys/fuchsia/sockets.txt, sys/fuchsia/time.txt
Hello,
Syzkaller is broken on fuchsia because of the latest updates to fuchsia (check this [discussion](https://groups.google.com/a/fuchsia.dev/g/discuss/c/AcUyILZ4ouQ)).
I am trying to fix it. 
I made the current changes to syzkaller and also made a change in fuchsia.
In fuchsia checkout I modified this file `src/testing/fuzzing/syzkaller/BUILD.gnsrc/testing/fuzzing/syzkaller/BUILD.gn`
by simply replacing one line. 
This is the output of `git diff src/testing/fuzzing/syzkaller/BUILD.gnsrc/testing/fuzzing/syzkaller/BUILD.gn`
```bash
diff --git a/src/testing/fuzzing/syzkaller/BUILD.gn b/src/testing/fuzzing/syzkaller/BUILD.gn
index 9cb2a1866b5..df1c652b30a 100644
--- a/src/testing/fuzzing/syzkaller/BUILD.gn
+++ b/src/testing/fuzzing/syzkaller/BUILD.gn
@@ -64,7 +64,7 @@ …
```
=> executor, sys/fuchsia, pkg/csource: fix fuchsia support 

executor/cov_filter.h, syz-manager/covfilter.go
After introducing NextInstructionPC (fcdb12ba70875c410749932abf39160d19c753d9), in the function `createCoverageBitmap`, if the last  pc is equal to `start+size`, then `NextInstructionPC` will make this out-of-bound.
This bug really occurs in my usage.
=> syz-manager, executor: fix out-of-bound access due to NextInstructionPC

tools/docker/syzbot/Dockerfile
The fetch_cvd tool used for fetching Cuttlefish expects /usr/bin/bsdtar
to be available.
=> tools/docker: add libarchive-tools to Dockerfile

docs/linux/kernel_configs.md
'make kvmconfig' was replaced with 'make kvm_guest.config' after linux 5.10.
=> docs/linux: updated kvm config command

pkg/report/fuzz.go
This is important when opcode decompilation is involved.
Closes #3229.
=> pkg/report: set SysTarget before fuzzing

dashboard/app/index.yaml
We currently fail in fetchFixPendingBugs() when the manager filter is used.
Closes https://github.com/google/syzkaller/issues/3225
=> dashboard: add a missing index

pkg/bisect/bisect.go
Log bisection date and hostname of the bisecting machine for
the debugging purposes. It makes more easy to check bisection
problems on the bisecting host if something goes wrong.
Signed-off-by: Denis Efremov <denis.e.efremov@oracle.com>
=> tools/syz-bisect: print hostname and bisection date

executor/common_linux.h, pkg/csource/generated.go
If root fs is read-only, mkdir(/syzcgroup) will fail and a later
rmdir(/syzcgroup/unified) will fail with ENOENT which we don't expect and fail.
Return early if mkdir(/syzcgroup) fails.
Fixes #3255
=> executor: fix mounting of cgroups on read-only fs

executor/common_linux.h, pkg/csource/generated.go, vm/adb/adb.go
vm/adb: wait for Android boot to finish
executor: removed condition around 'initialize_tun'
Often after reboot Android devices experience a race condition. When a phone is still on the screen with 'G' logo and a progress bar syz-fuzzer already starts execution. Sometimes the phone doesn't go past this screen and can't start all services and processes. In this case fuzzing continues however it doesn't produce results. I can assume that due to dozens per second syscalls Android can't finalize initialization in time. I do not know what exactly causes this race condition however it doesn't happen if I comment out 'initialize_tun'.
This change determines whether a system initialized by monitoring whether a systemui process has started. Adb waits for 3 minutes and if the process is not found …
=> vm/adb: wait for Android boot to finish

pkg/cover/backend/gvisor.go
If code stops reading from process pipe (on error etc.) we get blocked cmd.Wait().
Killing the subprocess guarantees safe cmd.Wait() and prevents unstable subprocess side-effects.
=> pkg/cover/backend/gvisor: kill process to 100% unlock resources

.github/workflows/ci.yml
=> .github/workflows/ci.yml: run dashboard step on the self-hosted instance

.github/workflows/ci.yml
Race step takes ~8 minutes and is the 3rd longest after "build" and "dashboard".
=> .github/workflows/ci.yml: run race step on the self-hosted instance

.github/workflows/ci.yml
New self-hosted runners looks stable enough.
Lets remove old ones. We can always switch back changing "self-hosted" to "ubuntu-latest".
=> .github/workflows/ci.yml: stop to use github instances for heavy tests

executor/common_linux.h, pkg/csource/generated.go
When Android fuzzing ran under system account it was unable to access some dev nodes because it still had restricted app capabilities.
=> executor: fixed fuzzing with System account in Android sandbox

syz-ci/manager.go
We've got some cases when manager hanged generating coverage report.
This in turned hanged whole syz-ci.
Prevent such hangs with a request timeout.
=> syz-ci: add timeout for coverage report requests

vm/adb/adb.go
vm/adb: added a new condition to determine localhost
When fuzzing via remote device proxy syzkaller identified all crashes as 'lost connection'. It happened because a connected device was treated by syz-manager as a remote Cuttlefish. That means a serial console provide by the actual device wasn't used. When a crash happened ADB was disconnected and a stream from serial console was empty. This was treated as lost connection.
I fixed this issue by adding a new condition into isRemoteCuttlefish which tries to identify local connections. Besides 127.0.0.1 and 0.0.0.0 it also checks for 'localhost'
=> vm/adb: added a new condition to determine localhost

.github/workflows/ci.yml, Makefile
presubmit_arch_other is now the slowest presubmit step taking 7-8 mins.
Split it per OS.
=> Makefile: split presubmit_arch_other target

CONTRIBUTORS, pkg/vcs/git.go
Submodule init defaults to remote/origin to initialize upstream modules, but origin was not set in the CheckoutBranch() and SwitchCommit() functions.
Setting remote name to origin instead of a hash of the repo URL.
=> pkg/vcs/git.go: fixed error in initializing submodules

executor/executor_fuchsia.h
Commit 4ce69996ec362f8dd9762dcc1643d13cebaab44a changed the logic
for processing results for fuchsia system calls. That change seems
to be fault, as it sets syscalls that return with ZX_OK to return -1
instead. I am reverting that commit for now.
=> executor: revert errno logic for fuchsia.

pkg/build/android.go
Since the worker instances don't have network access, they won't be able
to download the Cuttlefish packages using this. Instead, we'll have to
pre-install the Cuttlefish tools in the GCE image.
=> pkg/build: don't call fetch_cvd for Android instances

pkg/gce/gce.go, vm/gce/gce.go
This is needed for Cuttlefish-on-GCE. It adds the field 'nested_virt' to
the config file and then passes it through to the relevant field in the
call to gce.CreateInstance().
=> pkg/gce, vm/gce: add param to enable nested virtualization

docs/freebsd/README.md
The git link and branch of freebsd in the documentation are outdated, so update this to the main branch of [freebsd-src](https://github.com/freebsd/freebsd-src.git).
=> docs/freebsd: update the default branch of freebsd-src

pkg/report/openbsd.go, pkg/report/testdata/openbsd/report/37, pkg/report/testdata/openbsd/report/38
The original panic: is printed without logging and is often garbled
by concurrent printing by another core. OTOH, `show panic` is printed
exclusively so we prefer to use that.
=> pkg/report: use `show panic` output for unscrambled panic message

docs/fuchsia/setup.sh
Preventing Fuchsia to be forcibly rebuilt
even if changes only happened on the syzkaller side.
=> docs/fuchsia: building without cleaning

pkg/bisect/bisect.go, pkg/vcs/linux.go, pkg/vcs/testos.go, pkg/vcs/vcs.go, syz-ci/jobs.go, syz-ci/syz-ci.go, tools/syz-bisect/bisect.go, tools/syz-testbuild/testbuild.go
Some outstanding improvements not included in this PR:
- use default compiler, instead of one from the bin_dir, if an old compiler isn't required for the commit under test
- handle vanishing breaking commit (due to rebases) in the fixing commit bisection
- save time while bisecting subtree merges by skipping ahead to subtree merge commit, instead of skipping each subtree commit individually
=> Support clang in linux bisection jobs

vm/cuttlefish/cuttlefish.go
Mounting debugfs to sys/kernel/debug.
Fixing error that /sys/kernel/debug/kcov
does not exist for Cuttlefish.
=> vm/cuttlefish: mount debugfs

pkg/gce/gce.go, vm/gce/gce.go
This can be enabled for all GCE instances which means we can remove the
CreateArgs struct introduced in https://github.com/google/syzkaller/pull/3328.
Created in response to https://github.com/google/syzkaller/pull/3328#issuecomment-1232608941
=> pkg/gce, vm/gce: leave nested virt support up to images

vm/cuttlefish/cuttlefish.go
Create the the deviceRoot directory, then
run adb commands from deviceRoot (data/fuzz).
Additionally, added quotes in adb shell mounting
command; commands should be run inside shell.
=> vm/cuttlefish: run commands from deviceRoot

dashboard/app/entities.go, dashboard/app/jobs.go, dashboard/app/jobs_test.go
Over time, new kernel options might have become necessary to
successfully build/run a kernel. The current approach ignores this
possibility.
Take not only the repro/branch from the latest build, but also the
kernel config.
Close #3352.
=> dashboard: retest repros on latest config

vm/cuttlefish/cuttlefish.go
The Cuttlefish sandbox uses SecComp to filter crosvm signals,
resulting in crosvm being killed during running.
Disabling this option allows Cuttlefish to run successfully.
Additionally, the report_anonymous_usage_stats flag is disabled to
prevent hanging when Cuttlefish is run from the daemon
=> vm/cuttlefish: disable cuttlefish sandbox

.github/workflows/oss-fuzz.yml
10 minutes looks like a too big number, especially given that other CI
actions finish much faster.
=> .github: decrease the OSS fuzzing time

docs/syz_testbed.md
The right target name is "syz-manager", not "syzkaller".
Please merge after reviewing.
=> docs: fix a typo in syz_testbed.md

executor/common_fuchsia.h, executor/common_linux.h, pkg/csource/csource.go, pkg/csource/generated.go
This reverts commit 922294abb4c0bc72b24d8526d625110d73fa1b5a.
The commit reported to cause old warnings on s390x:
https://github.com/google/syzkaller/commit/922294abb4c0bc72b24d8526d625110d73fa1b5a#commitcomment-83096994
=> Revert "pkg/csource: inline void* cast into generated code"

tools/create-buildroot-image.sh
create-buildroot-image.sh creates a minimal sshd_config, which does not
configure sftp.  Thus, if the initial scp to setup syz-fuzzer uses sftp,
it fails with the error below, and syz-manager never starts fuzzing.
2022/09/06 16:03:44 failed to copy binary: failed to run ["scp" "-P" "14125" ... "/home/ec2-user/syzkaller/bin/linux_amd64/syz-fuzzer" "root@localhost:/syz-fuzzer"]: exit status 255
Warning: Permanently added '[localhost]:14125' (ED25519) to the list of known hosts.
subsystem request failed on channel 0
Connection closed
We can see sftp throws the same sequences by manually running scp in
verbose mode.
$ scp -v -P 14125 /home/ec2-user/syzkaller/bin/linux_amd64/syz-fuzzer root@localhost:/syz-fuzzer
Executing: program /usr/bin/ssh host localhost, user root, command sftp
... …
=> tools/create-buildroot-image.sh: Configure sftp subsystem.

tools/docker/syzbot/Dockerfile
Fuchsia build fails inside of syzbot container
b/c syzkaller user does not have home dir:
$ out/x64/host_x64/fpublish --help
Could not initialize SDK mkdir /home/syzkaller
Create syzkaller home.
=> tools/docker: create syzkaller home

vm/qemu/qemu.go
Running with nested virtualization, this was causing many false positives, so we relax it to a similar level as used for Linux targets.
=> vm/qemu: relax Fuchsia lockup detector thresholds

dashboard/app/main.go, dashboard/app/reporting.go
Do not query crashes from inside needReport, because it's not really needed there and because we query it for each opened bug on the main page.
This should noticeably speed up our main page.
=> dashboard: solve the N+1 query problem

vm/qemu/qemu.go
PR #3387 inadvertently set the heartbeat period to the same value as the heartbeat age threshold, which is incorrect. This removes that configuration line, allowing the period to revert to its default of 1sec.
=> vm/qemu: return Fuchsia heartbeat period to default

dashboard/config/openbsd/config.ci
syz-ci doesn't support both ways at the same time.
=> config/openbsd: upload coverage only via asset storage

syz-fuzzer/fuzzer.go
The problem gets triggered on our arm32 instances. Fix this by using a dynamically allocated slice instead of an array.
=> syz-fuzzer: fix "unaligned 64-bit atomic operation"

pkg/asset/backend_gcs.go
From the upload method, always return the path without the bucket. Always prepend the bucket name in the downloadURL().
=> pkg/asset: fix download URLs formation for duplicate assets

syz-ci/manager.go, syz-ci/syz-ci.go
Otherwise it leads to `failed to create manager config: bad manager config: asset storage also requires dashboard client` errors.
Don't set the config. It's not necessary anyway.
=> syz-ci: don't set asset storage for image testing

pkg/report/linux.go, pkg/report/testdata/linux/report/662
Crashes are much more likely to be caused by their callers.
=> pkg/report: ignore klist_ frames

pkg/cover/html.go
The result is not updated because it modifies the deep copy variable prog.
Fix this by using array indexing.
Fixes #3422
=> pkg/cover: fix coverage PC filter

pkg/report/linux.go, pkg/report/testdata/linux/report/113, pkg/report/testdata/linux/report/352, pkg/report/testdata/linux/report/43, pkg/report/testdata/linux/report/44, pkg/report/testdata/linux/report/448, pkg/report/testdata/linux/report/540, pkg/report/testdata/linux/report/576, pkg/report/testdata/linux/report/577, pkg/report/testdata/linux/report/578, pkg/report/testdata/linux/report/579, pkg/report/testdata/linux/report/580, pkg/report/testdata/linux/report/581, pkg/report/testdata/linux/report/582, pkg/report/testdata/linux/report/583, pkg/report/testdata/linux/report/584, pkg/report/testdata/linux/report/585, pkg/report/testdata/linux/report/586, pkg/report/testdata/linux/report/587, pkg/report/testdata/linux/report/656
We used to use "kernel BUG at source:line" for BUGs.
Later we switch to "kernel BUG in function" as a better title,
but kept the old title as alt title so that the new titles are
merged with existing bugs.
Now it's causing issues: the following 2 reports got merged together:
kernel BUG at lib/string_helpers.c:983
Call Trace:
__fortify_strlen include/linux/fortify-string.h:144 [inline]
strlcpy include/linux/fortify-string.h:159 [inline]
init_names fs/gfs2/ops_fstype.c:385 [inline]
gfs2_fill_super+0x1226/0x27f0 fs/gfs2/ops_fstype.c:1187
kernel BUG at lib/string_helpers.c:980!
Call Trace:
__fortify_strlen include/linux/fortify-string.h:128 [inline]
strlcpy include/linux/fortify-string.h:143 [inline]
__set_page_owner_handle+0x2b1/0x3e0 mm/page_owner.c:171
__set_page_owner+0x3e/0x50 …
=> pkg/report: remove alt title for BUGs

pkg/symbolizer/nm.go, pkg/symbolizer/nm_test.go
Function sizes reported by the Linux kernel do not match symbol tables.
The kernel computes size of a symbol based on the start of the next symbol.
We need to do the same to match kernel sizes to be able to find the right
symbol across multiple symbols with the same name.
=> pkg/symbolizer: match kernel symbol size calculation

pkg/bisect/bisect.go, pkg/bisect/bisect_test.go, pkg/vcs/git_test.go, pkg/vcs/vcs.go, syz-ci/jobs.go, tools/syz-bisect/bisect.go
When bisecting a breaking commit, syzkaller starts the bisection from
the commit recorded in the last crash for the given bug. Previously the
bisection was aborted should the commit no longer exist in the repo.
Now we try to reidentify the breaking commit. For git pretty much the
best we can do is to search a commit reachable from HEAD with the same
title. Other VCS systems might have something better.
Syzkaller will still first validate that the start commit is indeed
broken in the way it expects. This prevents syzkaller from getting
confused should we accidentally pick a completely unrelated commit.
=> pkg/bisect: try to reidentify commit rebased after crash

pkg/bisect/bisect.go, pkg/vcs/linux.go, pkg/vcs/linux_test.go, pkg/vcs/testos.go, pkg/vcs/vcs.go, syz-ci/jobs.go, syz-ci/syz-ci.go, tools/syz-bisect/bisect.go, tools/syz-testbuild/testbuild.go
This allows us to bisect at least recently introduced bugs, where the manager that found the bug uses a non standard compiler. This is usefull during development of a new sanitizer for which a compiler with non-upstreamed patches is required.
=> pkg/bisect: use default compiler during bisection where possible

Makefile, tools/syz-env
- This prints a warning for users calling make without `syz-env`, as we can't guarantee they have a compatible environment and go version.
- We got a report where `make generate` fails with recent go versions with the following error: `internal error: package "context" without types was imported from "github.com/google/syzkaller/vm/proxyapp"`
- We are currently blocked from upgrading to the most recent go version by our GAE deployment.
=> make: print warning when make is executed without syz-env

tools/docker/README.md
We don't maintain github packages. Let's deprecate them.
=> tools/docker/README.md: deprecate github packages

tools/syz-env
Let's allow read/write operations for the mounted folders in SELinux environment by default.
https://docs.docker.com/storage/bind-mounts/#configure-the-selinux-label
=> tools/syz-env: fix volume labels in SELinux environment

executor/executor.cc
Pages residing in the BSS section are by now flagged as immutable on OpenBSD. Meaning that their corresponding permissions cannot change. The input_data therefore needs to be explicitly marked as mutable. Should hopefully bring syzbot on OpenBSD back.
=> cope with mimmutable(2) on OpenBSD

pkg/log/log.go, vm/proxyapp/mocks/ProxyAppInterface.go, vm/proxyapp/proxyappclient.go, vm/proxyapp/proxyappclient_mocks_test.go, vm/proxyapp/proxyappclient_test.go, vm/proxyapp/proxyrpc/proxyrpc.go
To be #3395 prepared, we need logs over rpc.
Disconnect case will be tested in #3395.
=> vm/proxyapp: enable logging over rpc

pkg/build/linux.go, syz-ci/manager.go
This will let the `kernel` file be uploaded to the asset storage.
Unfortunately we don't keep its proper name in targets, so we have to do a workaround -- determine the name right in the `syz-ci`.
Also, previously the existence of a kernel image was used as an indication of whether the disk image is bootable. Now that we upload it always, make a decision from the VM type.
=> all: assorted kernel image-related fixes

executor/executor.cc
mmap'ing over bss is asking for trouble and openbsd delivered them with mimmutable changes.
=> executor: always mmap input_data

pkg/build/linux.go
The call has quite a lot of fixed arguments, which makes it prone to errors that do not manifest themselves during compilation (see #3441).
=> pkg/build: don't take trailing arguments in runMakeImpl

syz-fuzzer/fuzzer.go
Experiences this error and it looks confusing. Let's change a little.
=> syz-fuzzer/fuzzer.go: use different prefixes for errors

dashboard/app/templates.html
Commit 2f3b44ea4 ("dashboard: visualize stale repros") inadvertently added a single space in the "<td class=repro>" tag.  This will break tooling which relies on HTML scraping and pattern matching.  This patch ensures the formatting is kept consistent whilst honouring the author's true intentions.
Fixes: 2f3b44ea4 ("dashboard: visualize stale repros")
Signed-off-by: Lee Jones <joneslee@google.com>
=> dashboard: remove accidental whitespace from C Repro cell

sys/targets/targets.go
On s390x, position independent code needs to be built with -fPIC or -fPIE for pie executables.
How to reproduce on s390x
-------------------------
$ git clone https://github.com/google/syzkaller.git $ cd syzkaller
$ make executor
Makefile:32: run command via tools/syz-env for best compatibility, see: Makefile:33: https://github.com/google/syzkaller/blob/master/docs/contributing.md#using-syz-env go list -f '{{.Stale}}' ./sys/syz-sysgen | grep -q false || go install ./sys/syz-sysgen make .descriptions
make[1]: '.descriptions' is up to date.
mkdir -p ./bin/linux_s390x
gcc -o ./bin/linux_s390x/syz-executor executor/executor.cc \
-O2 -pthread -Wall -Werror -Wparentheses -Wunused-const-variable -Wframe-larger-than=16384 -Wno-stringop-overflow -Wno-array-bounds -Wno-format-overflow -static-pie …
=> sys/targets: fix -static-pie for s390x arch

pkg/build/build.go
When Bazel is released with https://github.com/bazelbuild/bazel/commit/c9f9b0b84c4863b5b19220679e610efa17e972f0 the message on build failures changes. In general, we advise not to read the output but use the build protocol instead.
=> Be more lenient when parsing Bazel's build log.

docs/syscall_descriptions.md
Added a link to a Visual Studio code (vscode) syz-lang syntax extension.
=> docs: added info about vscode extension for syz-lang

tools/syz-cover/syz-cover.go
Add a new html flag to the syz-cover tool that allows saving the coverage HTML report to a particular file.
=> tools/syz-cover: allow saving coverage HTML report to a particular file

docs/fuchsia/README.md, docs/fuchsia/setup.sh, pkg/build/fuchsia.go
Fuchsia's //bundles:tools target was renamed to
//bundles/tools.
=> pkg/build: update fuchsia tools target name

dashboard/app/app_test.go, dashboard/app/email_test.go, dashboard/app/jobs.go, dashboard/app/reporting_email.go, dashboard/app/util_test.go, pkg/email/parser.go, pkg/email/parser_test.go
Currently we only determine the bug by looking at the hash encoded after
'+' in syzbot's email address. Users tend to forget to Cc the right
email address while interacting with the bot. Also, it turns out that if
the bug was only sent to Google Groups, any reply to the email thread
does not include the topic starter email address.
Instead of only relying on the right address, try to infer the bug that
was meant by looking more closely at the incoming email.
* Parse the mail subject to extract thee title and the sequence number of the bug.
* Extract the mailing list through which the bug was routed to syzbot.
* Fetch and filter matching bugs.
* If only one matches, handle the command as if it the bug were explicitly specified.
Closes #2614
=> dashboard: infer bug info from subject and mailing list

executor/common_linux.h, pkg/csource/generated.go
Problem: the BT initialization logic (`initialize_vhci()` in `common_linux.h`) expected `HCI_VENDOR_PKT` to be sent first, but this is not always the case as the kernel sends these two packets almost at the same time (both are sent as the result of the `open("/dev/vhci", …)` call):
* syscall thread: `HCI_VENDOR_PKT` (in `__vhci_create_device`)
* `power_on` queue thread: `HCI_OP_RESET` (from `hci_reset_sync` <- `hci_init1_sync` <- `hci_init_sync` <- `hci_dev_open_sync` <- `hci_dev_do_open` <- `hci_power_on` <- `hdev->power_on` <- (worker queue) <- `hci_register_dev` <- `__vhci_create_device`)
Solution: handle both `HCI_OP_RESET` and `HCI_VENDOR_PKT` packets in `initialize_vhci`.
Also instead of waiting for the kernel to send `HCI_VENDOR_PKT` after 1 second, we initiate the setup by sending …
=> executor: fix "wrong response packet" in BT fuzzing (#3493)

sys/fuchsia/vmar.txt
This was a new file created in the rename https://github.com/google/syzkaller/commit/b5cdb36a1de3bc4cacdc296b5348fc00e4766a85; just forgot to update the date.
=> sys/fuchsia: fix date in vmar copyright header

pkg/report/linux.go, pkg/report/testdata/linux/report/670, pkg/report/testdata/linux/report/671, pkg/report/testdata/linux/report/672, pkg/report/testdata/linux/report/673, pkg/report/testdata/linux/report/674
Turns out a lot of KMSAN bugs get merged because of some insignificant origin like "allocate_slab".
Ensure we skip all allocation-related frames when parsing KMSAN reports.
=> pkg/report: skip allocation frames in KMSAN origin stacks

docs/syzbot.md
Built by https://github.com/tarasmadan/gcc-10.2/blob/8a0c67cd9474ab3bf02bf236467f4e01396e342a/build_scripts/build_gcc_10.sh
=> docs/syzbot.md: add gcc 10.2

vm/qemu/qemu.go
Failing to do so might cause a failure to establish a SSH connection when syz-ci tests a built image.
syz-ci output:
--------------
building kernel...
testing image...
VM boot failed with: can't ssh into the instance
failure log:
------------
failed to run ["ssh" "-p" "34490" ... "root@localhost" "pwd"]: exit status 255 Connection timed out during banner exchange
Connection to 127.0.0.1 port 34490 timed out
qemu dmesg
----------
[    6.646475] virtio_net virtio0 eno1: renamed from eth0
Signed-off-by: Alexander Egorenov <eaibmz@gmail.com> …
=> vm/qemu: prevent network device renaming on s390x arch

pkg/runtest/run.go, sys/fuchsia/job.txt, sys/fuchsia/test/job
This change also makes a couple of small updates to job.txt:
- Express the documented limit of 1 policy struct when using the TIMER_SLACK option to set policy
- Include padding in policy struct definition
=> sys/fuchsia: add test for job syscalls

pkg/runtest/run.go, sys/fuchsia/test/vmar, sys/fuchsia/vmar.txt
Also made some small updates to the vmar descriptions:
- In a few places, a `len` arg was incorrectly tagged as the length of another arg when it actually represents a region size; fixed.
- The `buffer` and `buffer_size` args to `zx_vmar_op_range` must be null; replaced with constants.
- Added a `zx_vaddr` resource type wrapping `intptr` and used it in place of `vma`, since it's not clear how to use `vma` as the pointee type of an outptr in a program.
=> sys/fuchsia: add test for vmar syscall descriptions

dashboard/app/email_test.go, dashboard/app/jobs.go, dashboard/app/reporting_email.go, dashboard/app/util_test.go, pkg/email/parser.go, pkg/email/parser_test.go
* Use `From: ` to detect the actual mailing list.
* Use `Reply-To: ` to determine the actual author of the message.
* Relax the email duplicate detection mechanism -- if syzbot was not one of the direct recipients, still handle the command.
* Use canonical email to filter out emails from syzbot itself. Don't ignore such emails completely (otherwise we cannot remember the email we sent).
Closes https://github.com/google/syzkaller/issues/2614
=> dashboard: incoming mail processing improvements

dashboard/app/app_test.go, dashboard/app/email_test.go, dashboard/app/util_test.go
The test config changes needed for the recent incoming email handling changes testing accidentally broke bug access testing.
Fix this by introducing a separate test namespace.
=> dashboard: fix the broken AccessTest

sys/linux/init_images_test.go
It is an external test. It uses only exported "linux" package functions.
=> sys/linux/init_alg_test.go: change package name to linux_test

docs/linux/setup_ubuntu-host_qemu-vm_x86-64-kernel.md
Corrected typos:
- lastest->latest
- exatra->extra
Add languages to fenced code blocks in line with MD040 linting.
=> docs/linux: fix trivial typos in ubuntu-host_qemu-vm.

docs/troubleshooting.md, tools/create-buildroot-image.sh
There are two reasons:
- The 2022.02 version does not longer build with the latest versions of the build tools.
- The latest version was tested to work fine with the scp changes that came with OpenSSH 9.0 (the use of the SFTP protocol).
Document the problem with scp in the troubleshooting guide.
=> tools: upgrade Buildroot image version

prog/compression.go, prog/encoding.go, sys/linux/init_images.go
Currently we uncompress all images in Deserialize to check that the data is valid.
As the result deserializing all seeds we have takes ~40 seconds of real time
and ~125 seconds of CPU time. And we do this during every syz-manager start.
Don't materialize the uncompressed image.
This reduces real time to ~15 seconds and CPU time to 18 seconds (no garbage collections).
In syz-manager the benefit is even larger since garbage collections take longer (larger heap).
=> prog: don't materialize uncompressed image in Deserialize

tools/syz-repro/repro.go, tools/syz-testbed/instance.go, tools/syz-testbed/stats.go
It's more correct to evaluate whether we managed to reproduce the
original bug rather than just any bug.
Retrieve the title information from syz-repro and pretent that the
reproduction failed if the title does not match.
=> tools/syz-testbed: only score repros with the same title

pkg/email/parser.go, pkg/email/parser_test.go
It look like email clients can insert newlines there if the line is too long.
=> pkg/email: tolerate newline characters after #syz

tools/create-openbsd-gce-ci.sh
This should hopefully make `/` filesystem mostly empty again and avoid the regular occurrence of running out of space in syzkaller builds.
=> tools: set GOCACHE on OpenBSD to the big persistent partition

vm/proxyapp/init.go, vm/proxyapp/init_test.go, vm/proxyapp/proxyappclient.go, vm/proxyapp/proxyappclient_tcp_test.go, vm/proxyapp/proxyappclient_test.go
Currently we communicate with plugin by stdin, stdout and stderr pipes.
Stdin and stdout are used to support RPC server. Stderr is used to route logs.
Kris asked to support TCP endpoints. Let's enable it.
1. TCP channel instead of stdin+stdout will be used for RPC calls.
2. Second optional TCP channel will be used for errors.
Minimal valid config specifies cmd OR RPC server host:port then.
=> support TCP proxyapp plugin endpoint

dashboard/app/admin.html, dashboard/app/index.yaml, dashboard/app/main.go, dashboard/app/templates.html
This reflects the situation more adequately than just displaying the recent jobs.
There are times when failed jobs are retried or manually restarted and the current page just does not show such jobs.
=> dashboard: display running and pending jobs on the admin page

dashboard/app/api.go, dashboard/app/app_test.go, dashboard/app/email_test.go, dashboard/app/jobs.go, dashboard/app/jobs_test.go, dashboard/app/reporting_email.go, dashboard/app/reporting_external.go, dashboard/app/util_test.go, dashboard/dashapi/dashapi.go
Accept patch testing requests not only via email, but also by a direct
dashboard API request.
Introduce a new /add_test_job API call.
Add tests that verify the expected flow and some side cases.
=> dashboard: post patch testing jobs externally

pkg/build/freebsd.go
syzbot has been failing to build FreeBSD for the past few weeks with what looks like a toolchain problem.  Let's try a clean build of the bundled compiler to see if that fixes it.
=> pkg/build: try a clean toolchain build on FreeBSD

dashboard/app/api.go, dashboard/app/app_test.go, dashboard/app/config.go, dashboard/app/config_linux.go, dashboard/app/config_linux_test.go, dashboard/app/email_test.go, dashboard/app/entities.go, dashboard/app/reporting.go, dashboard/app/reporting_email.go, dashboard/dashapi/dashapi.go, pkg/report/linux.go, pkg/report/report.go, pkg/report/report_test.go, pkg/subsystem/extract.go, pkg/subsystem/extract_test.go, pkg/subsystem/maintainers.go, syz-manager/manager.go
This set of patches should enable us to change syzbot routing rules to the following:
1. If the guilty file of the crash is `fs/*.c`, don't report it until we have found a reproducer. Otherwise (even if the guilty file is in e.g. `fs/*/*.c`) do as we do now.
2. Once the reproducer is found, determine the exact filesystems from the `syz_mount_image$` calls.
3. Use this information to augment the Cc list and the title (e.g. `[syzbot] [ntf3?] WARNING in ...`).
For now, use the hard-coded Cc values. Some time later I'll publish a PR that parses the fresh version of the MAINTAINERS file, so it'll not be needed.
Also note that this PR contains tiny parts of the subsystem management infrastructure that's planned for implementation in the future, so the changes to database entities are more …
=> dashboard: improve fs bugs routing

dashboard/app/jobs.go
We can test them even though there's no explicit reproducer.
=> dashboard: do patch testing for build errors

dashboard/app/notifications_test.go, dashboard/app/reporting.go, dashboard/app/reporting_email.go, dashboard/dashapi/dashapi.go
If the original email thread is lost, it can be hard to get to the original bug.
=> dashboard: include dashboard link into the missing commit reply

dashboard/app/reporting.go, dashboard/app/reporting_test.go
Return bugs from decommissioned namespaces as closed to external reportings.
=> dashboard: adjust pollClosed behavior for decommissioned namespaces

dashboard/app/jobs.go
We are already quite cautious re. the retest results -- the reproducer is preserved if we have any type of crash/error. It seems to be highly unlikely that, once the reproducer stopped to cause any crashes at all, that it will start working again.
=> dashboard: don't retest revoked reproducers

dashboard/app/main.go, dashboard/app/terminal.html
Show the number of bugs that were closed automatically, because of the revoked repro, manually.
=> dashboard: share invalid bug stats

dashboard/app/main.go, dashboard/app/notifications_test.go, dashboard/app/reporting_email.go, dashboard/app/repos.html, dashboard/app/templates.html
Let's include e.g. top 4 and let users see the rest by following a link.
=> dashboard: include polled repos to the bad commit message

dashboard/app/main.go, dashboard/app/stats.go, dashboard/app/stats_test.go
I've adapted parts of the code I used to collect the stats for the [LPC'22](https://lpc.events/event/16/contributions/1311/attachments/1013/1951/Making%20syzbot%20reports%20more%20developer-friendly.pdf) talk to run directly on the dashboard side.
As of now, it can gauge the effect of several factors on whether a bug gets resolved in 100 days after reporting:
* The presence of strace output
* The presence of crash assets
* The presence of a reproducer
* The presence of a cause bisection
This is a very initial version of the code that's only invoke from the admin.go file. Later we'll add some proper GUI to that.
=> dashboard: collect bug fixing statistics

dashboard/app/asset_storage.go, dashboard/app/main.go, dashboard/app/reporting.go, dashboard/app/templates.html, pkg/html/pages/style.css
* Display build & crash assets in the crash table.
* Indicate whether the captured log is `console` or `strace` like we do in emails.
=> dashboard: show more info on the bug page

executor/common_linux.h, pkg/csource/generated.go
We already suppress them, but the current approach fails if syzkaller slightly corrupts the options string. Do the check more rigorously.
=> executor: better prevent the panic on ext4 errors

pkg/bisect/bisect.go, pkg/bisect/bisect_test.go, pkg/instance/instance.go, syz-ci/jobs.go, tools/syz-testbuild/testbuild.go
Previously we only used the linter from the syz-ci config when building the kernel for regular fuzzing. We were missing some plumbing to have this setting reach patch testing and bisection jobs.
=> syz-ci/jobs: use linker supplied in syz-ci config

dashboard/app/main.go, dashboard/app/main_test.go
The `manager=` filter limits the dashboard output only to the bugs that happened on the specified manager (but not exclusively there).
Introduce the `only_manager=` filter to only show the bugs that happened ONLY on the specified manager.
=> dashboard: support only_manager filter

pkg/report/linux.go, pkg/report/testdata/linux/report/681, pkg/report/testdata/linux/report/682
Two KMSAN reports belonging to different subsystems ended up being merged together because they both had netlink_ack in their origin. Let's skip this frame.
=> pkg/report: skip netlink_ack

pkg/host/syscalls_linux_test.go, sys/targets/targets.go
This PR fixes two problems that arise during syzkaller testing:
* There's no `-m64` and `-m32` on ARM64's GCC (see the commit description for more details).
* There are no `open` and `stat` syscalls.
=> all: run syz-ci on arm64 hosts

dashboard/app/bisect_test.go, dashboard/app/jobs_test.go, dashboard/app/notifications_test.go, dashboard/app/reporting_email.go
Make it more clear - de facto we're just sending the report to the next reporting stage. It does not always have to be "upstream", what implies some public mailing lists.
=> dashboard: adjust the upstream notification email

pkg/csource/csource_test.go
The problem was introduced in 4620c2d9bc4f ("sys/targets: take DataOffset from reference targets").
Example of the problem on s390x
-------------------------------
--- FAIL: TestSource (0.00s)
--- FAIL: TestSource/1 (0.00s)
csource_test.go:221: input:
csource2(&AUTO="12345678")
csource3(&AUTO)
csource4(&AUTO)
csource5(&AUTO)
csource6(&AUTO)
want:
NONFAILING(memcpy((void*)0x20000040, "\x12\x34\x56\x78", 4));
syscall(SYS_csource2, 0x20000040ul);
NONFAILING(memset((void*)0x20000080, 0, 10));
syscall(SYS_csource3, 0x20000080ul);
NONFAILING(memset((void*)0x200000c0, 48, 10));
syscall(SYS_csource4, 0x200000c0ul);
NONFAILING(memcpy((void*)0x20000100, "0101010101", 10));
syscall(SYS_csource5, 0x20000100ul);
NONFAILING(memcpy((void*)0x20000140, "101010101010", 12));
syscall(SYS_csource6, …
=> pkg/csource: fix unit tests for arches with non-default DataOffset

dashboard/app/api.go, dashboard/app/bisect_test.go, dashboard/app/entities.go, dashboard/app/index.yaml, dashboard/app/jobs.go, dashboard/app/jobs_test.go, dashboard/app/main.go, dashboard/dashapi/dashapi.go, pkg/bisect/bisect.go, pkg/instance/instance.go, syz-ci/jobs.go, syz-ci/manager.go, syz-ci/syz-ci.go, syz-ci/updater.go, tools/syz-linter/linter.go, tools/syz-testbuild/testbuild.go
Main issue: https://github.com/google/syzkaller/issues/1770
Resolve the problem of long patch test processing delays because of bisections (or other kinds of long jobs) by allowing up to 2 job processing threads per syz-ci.
* Modify job_poll never to return already started jobs.
* Introduce a special job_reset API call to clear the "started" flag for the specified list of managers.
* Introduce a new ParallelJobs configuration parameter. If set, syz-ci will execute the specified kinds of jobs in parallel to the main job processing thread.
=> syz-ci: support parallel jobs

CONTRIBUTORS, vm/gvisor/gvisor.go
This adds VM info for runsc (gVisor) instances, showing the flags passed to runsc.
=> vm/gvisor: implement vmimpl.Infoer for runsc instances

docs/starnix/README.md
Remove extra comma in the manager config json template that caused the syz-manager run to fail due to error in parsing the config file.
=> docs/starnix: fix typo in manager config json template

pkg/build/freebsd.go
Commit 6f9c033e1 ("pkg/build: try a clean toolchain build on FreeBSD") doesn't appear to be sufficient, so let's try blowing away the entire object directory.
=> pkg/build: try harder to get a clean build on FreeBSD

pkg/build/gvisor.go
This enforces that the configuration string passed to gVisor is only made up of known flags. Prior to this change, it was possible to pass any arbitrary flags as configuration, which would be silently ignored.
=> pkg/build/gvisor: make gVisor configuration parsing stricter

syz-ci/jobs.go
Currently a suffix is appended twice.
=> syz-ci: don't duplicate job instance suffixes

dashboard/app/util_test.go
If the underlying request fails, we get the `panic: runtime error: invalid memory address or nil pointer dereference` error.
Gracefully handle the possible edge cases.
=> dashboard: make Ctx.ContentType more robust

dashboard/app/api.go, dashboard/app/reporting.go, dashboard/app/reporting_test.go, dashboard/dashapi/dashapi.go, tools/syz-fillreports/fillreports.go
The tool is needed to fill in the report elements necessary for the automatic bug subsystem extraction (i.e., the guilty paths info).
It is meant to be run locally when needed and requires the API credentials for the dashboard application.
=> tools: introduce syz-fillreports

pkg/build/android.go
The upstream kernel headers path was changed to the dist directory.
=> pkg/build: update kernel headers path

dashboard/app/app_test.go, dashboard/app/jobs_test.go, dashboard/app/reporting_test.go
These tests require a change in the global configuration during the test execution, so they at least need their own namespaces in order not to interfere with other tests.
Fixes #3641
=> dashboard: fix racy decommission tests

tools/docker/env/Dockerfile, tools/docker/syzbot/Dockerfile
The new compiler introduced some test failures, so we had to roll back the containers. Revert the patch to Docker specs, so that they reflect the actual state of the things.
This reverts commit 3d904c7acdbdd69b8c6e85799af7565955025201.
=> Revert "tools/docker: switch to Clang 15"

vm/proxyapp/init.go, vm/proxyapp/proxyappclient.go, vm/proxyapp/proxyappclient_tcp_test.go
If the server_tls_cert field is set in the config, then the ProxyApp will use the certificate to authenticate the server. If not, it will fall back to the previous behavior.
=> vm/proxyapp: add TLS authentication

dashboard/app/util_test.go
Now it's quite difficult to recognize it in the dashboard testing logs, especially when the error message itself is not very clear.
=> dashboard: make expectOK more elaborate

dashboard/app/asset_storage.go
Without sleeping there's a big risk of getting an `API error 2 (datastore_v3: CONCURRENT_TRANSACTION): too much contention on these datastore entities. please try again.` error.
=> dashboard: prevent contention on mass crash update

pkg/vcs/git.go
Added recurse-submodules flag in git reset to recursively reset submodules.
Additionally, added command to recursively clean each subdirectory.
=> pkg/vcs: git clean submodules

executor/common_linux.h, pkg/csource/generated.go
Android devices often fail during the initial check with the error:
SYZFAIL: tun: ioctl(TUNSETIFF) failed
We need the same namespacing here that is used for other sandboxing configurations.
=> executor: fix initialize_tun() for Android

tools/docker/env/Dockerfile, tools/docker/syzbot/Dockerfile
This is a prerequisite for building KMSAN-instrumented kernels.
Now that https://github.com/google/syzkaller/pull/3649 is landed, the tests should be passing.
=> tools/docker: switch to Clang 15

vm/proxyapp/init.go, vm/proxyapp/proxyappclient.go, vm/proxyapp/proxyrpc/proxyrpc.go
Instead of just passing the path to the file (on the local machine) to the ProxyApp, we need to pass the file data. This applies for both calls to Copy() and CreateInstance().
=> vm/proxyapp: pass file data when running in tcp mode

tools/docker/env/Dockerfile, tools/docker/syzbot/Dockerfile
We are using stock Clang to build KMSAN now
=> tools/docker: delete clang-kmsan

pkg/report/linux.go, pkg/report/testdata/linux/guilty/58, pkg/report/testdata/linux/guilty/59, pkg/report/testdata/linux/guilty/60
The existing code is broken - the console output does not contain a whitespace before the apic_timer_interrupt frame. Also, it makes sense to cut not from its first, but rather from its last occurence.
=> pkg/report: extract guilty files for rcu errors correctly

pkg/build/build.go, pkg/build/cuttlefish.go
Building images for physical Android devices has different logic and options and should be in separate files. This makes it less ambiguous and frees up android.go for Android device code.
=> pkg/build: rename android.go to cuttlefish.go

dashboard/app/app.yaml, dashboard/app/asset_storage_test.go, dashboard/app/cron.yaml, dashboard/app/kcidb.go, dashboard/app/main.go, dashboard/app/util_test.go
This lets us keep only one access rule and reliefs from the need to keep handlers and app.yaml in sync for cron jobs that'll be added in the future.
=> dashboard: move all cron endpoints to cron/

dashboard/app/cron.yaml, dashboard/app/graphs_test.go, dashboard/app/reporting_email.go, dashboard/app/util_test.go
Currently it's the only cron job that is still occupying a top level URL.
=> dashboard: move /email_poll to /cron/email_poll

dashboard/app/bug.html, dashboard/app/main.go, pkg/html/pages/style.css
Currently the information is only displayed on the main page, which is not very convenient.
=> dashboard: display subsystems on the bug page

prog/clone.go, prog/collide.go, prog/collide_test.go, syz-fuzzer/proc.go
It duplicates random calls in a program and makes the duplicated copies async.
E.g. it could transform
```
r0 = test()
test2(r0)
```
to
```
r0 = test()
test2(r0) (async)
test2(r0)
```
or
```
test() (async)
r0 = test()
test2(r0)
```
=> prog: add a new DupCallCollide collide type

prog/encoding_test.go, prog/validation.go, sys/linux/test/gup_fast
We already try as hard as possible to not generate escaping (global) filenames.
However, it's possible we read them from the corpus if it happens to contain some.
Also check for escaping filenames during deserialization.
Fixes #3678
=> prog: reject escaping filenames during deserialization

pkg/report/linux.go, pkg/report/testdata/linux/guilty/61
Currently we return ".", which is not really expected by all the surrounding logic.
=> pkg/report: handle guilty file extraction for non-symbolized reports

syz-manager/manager.go
Only set the guilty file field if it's non empty.
Report guilty files for reproducers.
=> syz-manager: report guilty files correctly

tools/demo_setup.sh
It original was deleted or something.
I hope the new corpus will be parsed by the old manager.
Fixes #3688
=> tools/demo_setup.sh: fix corpus location

tools/syz-cover/syz-cover.go
pkg/cover expects absolute paths and mis-handles paths if they are relative.
Abs-ulitize all paths.
Fixes #3686
=> tools/syz-cover: use absolute paths

dashboard/app/api.go, dashboard/app/cron.yaml
Increase the rate by 66% to ~2400 bugs per day.
=> dashboard: refresh subsystems more often

pkg/cover/backend/dwarf.go, pkg/cover/backend/elf.go, pkg/cover/backend/mach-o.go, pkg/cover/html.go
- pkg/cover: move a helper function from the top of the file
- pkg/cover: move PC fix up into RestorePC
- pkg/cover/backend: group dwarf parameters in a struct
- pkg/cover/backend: close ELF files
- pkg/cover/backend: apply PC fix up only if .plt section is present
=> dvyukov coverage restore pc fix

pkg/build/gvisor.go
Now we need to use the race config to compile gVisor with the race detector.
=> gvisor: fix race builds

dashboard/app/reporting.go, dashboard/app/reporting_test.go, dashboard/dashapi/dashapi.go
Include the link to the subsystem page on the dashboard.
=> dashboard: include subsystem links in BugReport

vm/proxyapp/proxyappclient.go, vm/proxyapp/proxyrpc/proxyrpc.go
We need the kernel built by Syzkaller to start the VM.
If transfer_file_content is set, pass the image data in addition to the path.
=> vm/proxyapp: pass kernel image data to ProxyApp

pkg/report/gvisor.go, pkg/report/linux.go, pkg/report/report.go, pkg/report/testdata/all/report/6, pkg/report/testdata/all/report/7
This several small improvements:
1. Move these patterns into the common part.
We run Go code on (almost) all OSes and error messages
are the same for all of them.
2. Detect "fatal error:" as a bug as well.
This is what I currently see from Go 1.20 runtime,
but we don't recognize it, so these reports probably
go into "lost connection" bucket now (bad).
3. Add a pattern for panic(ENOMEM) message.
pkg/image/compression_optimized.go can produce it
on mmap failure.
4. Add tests.
=> pkg/report: improve Go throw/panic parsing

pkg/report/gvisor.go, pkg/report/report.go, pkg/report/testdata/all/report/8
Of course something in the kernel prints "fatal error"
and it's not a kernel bug.
=> pkg/report: ignore ALSA fatal errors

dashboard/app/cache.go, dashboard/app/main.go, dashboard/app/main_test.go, dashboard/app/subsystems.html, dashboard/app/templates.html
1. By default, hide empty subsystems from the subsystem list.
2. Count the number of bugs without a subsystem and let users filter them.
=> dashboard: better handle non-classified bugs and empty subsystems

dashboard/app/main.go, dashboard/app/subsystems.html
1) Add more space between the lines above the table. 
2) Rename the "no subsystems" row and move it to the bottom. 
3) Display the correct count of fixed unclassified bugs.
=> dashboard: cosmetic changes to the subsystems list

dashboard/app/api.go, dashboard/app/app_test.go, dashboard/app/email_test.go, dashboard/app/entities.go, dashboard/app/reporting.go, dashboard/app/reporting_email.go, dashboard/app/subsystem.go, dashboard/app/subsystem_test.go, dashboard/dashapi/dashapi.go, docs/syzbot.md, pkg/email/parser.go, pkg/email/parser_test.go
1. Introduce a `#syz set subsystems: A, B, C` command
2. Don't overwrite such subsystem assignment automatically.
=> dashboard: let users manually set subsystems

pkg/host/features_linux.go
Initialize_devlink_pci in executor fails w/o /proc/self/ns/net.
See https://groups.google.com/g/syzkaller/c/yJWM1_2DxUY
=> pkg/host: check for /proc/self/ns/net presence in devlink PCI

pkg/build/cuttlefish.go
Bazel builds create a new output directory instead of overwriting previous dir.
Cleaning the output directory before each build to prevent multiple output directories being stored.
=> pkg/build: clean Cuttlefish build output

docs/syzbot.md
* Add an example of an inlined patch testing request.
* Add a link to the real-word #syz test commands.
* Remove the mention of delays due to bisections -- it's no longer the case.
=> docs: update the patch testing documentation

dashboard/app/templates.html
In some cases we don't have the bisection log, but only the error log. Adjust the template.
=> dashboard: display the bisect error log

dashboard/app/api.go, dashboard/app/app_test.go, dashboard/app/config.go
There are cases when a previously fuzzed tree was obsoleted and can no longer be polled for commits. At the same time, we still want to display short repo aliases in bug reportings and on the dashboard.
The dashboard tests cover that obsolete repos are not returned from `CommitPoll()`.
=> dashboard: support obsolete KernelRepo entries

pkg/build/android.go, pkg/build/build.go, vm/vm.go, vm/vm_test.go
Booting physical Android devices requires building a few artifacts, as described at https://source.android.com/docs/setup/build/building-kernels.
When a ProxyVM type is used, we need to differentiate whether or not to use the Android build logic, so we add an additional mapping which uses a different name but the same VM logic.
=> pkg/build: add build code for Android devices

syz-manager/manager.go
Adds "candidates" as an extra entry in the JSON 
produced from initBench().
=> syz-manager: add candidate length to bench file

docs/coverage.md, pkg/cover/html.go, tools/syz-cover/syz-cover.go
Add a `json` CLI flag that allows for writing out a JSON file with the following coverage information.
* Module
* Filename
* Covered source lines
* Uncovered source lines
* Both source lines
This can be used to view syzkaller coverage information on other source browsing/viewing tools.
Usage:
$ ./syz-cover -kernel_obj <path/to/vmlinux> -json <output_json> rawcover
=> tools/syz-cover: allow for exporting source line coverage info

tools/create-ec2-rootfs.sh
This script creates a rootfs based on Amazon Linux 2023 container image to run syzkaller easily on Amazon EC2 instances.
I have been running syzkaller with a rootfs created by this script for more than half a year and fixed some bugs which were found by the local syzkaller but not listed in the public syzbot dashboard.
=> tools: Add script to build rootfs for EC2.

dashboard/app/main.go
Currently we give links to the filtered views of open bugs, while the subsystem page is more informative.
=> dashboard: point to subsystem page(s) from the bug page

executor/common.h, pkg/csource/generated.go
The call to mkdtemp() will fail when given
/data/data/syzkaller/syzkaller-XXXXXX, since /data/data/syzkaller/ doesn't exist. The correct temporary dir on Android is /data/local/tmp, which exists by default.
=> executor: use valid temporary dir on Android

dashboard/app/asset_storage.go, dashboard/app/index.yaml
For the Admin page, we query all managers from all namespaces. That was not supported by queryLatestManagerAssets, so we always returned the fallback coverage URLs.
Make queryLatestManagerAssets support ns="".
=> dashboard: provide correct coverage URLs for the Admin page

dashboard/app/bug.html, dashboard/app/main.go
Some bugs were fixed/invalidated before they could be publicly reported. Don't show an ambiguous `Reported-by: syzbot+@syzkaller.appspotmail.com` in this case.
=> dashboard: don't show Reported-by for never reported bugs

dashboard/app/mail_subsystem.txt, dashboard/app/subsystem_test.go
We do not really know all reported issues per subsystem (e.g. we don't assign labels to invalid bugs), so let's just mention currently open bugs count.
=> dashboard: improve the subsystem report template

pkg/build/android.go, pkg/build/build.go, syz-ci/manager.go, syz-ci/syz-ci.go
Added config structure in build/Android to allow specifying specific Android targets.
Build config is optional and extensible for individual build instances.
=> pkg/build: added build configs for android

dashboard/app/entities.go, dashboard/app/reporting_lists.go
Try to construct a bug list for each subsystem each cron job execution until we succeed and skip list querying only after we have successfully saved the new SubsystemReport object.
It will force the dashboard to react to subsystem reporting config changes much more quickly.
=> dashboard: change subsystem report polling strategy

tools/syz-fmt/syz-fmt.go
There is a bug when formatting syscall descriptions using syz-fmt, which is because of the wrong api when updating golang.
=> tools/syz-fmt.go: fix a bug of file info api when updating golang

dashboard/app/reporting_email.go, dashboard/app/subsystem_test.go
Google groups do not seem to adequately parse the existing `[syzbot] [subsystemName] Monthly Report` format. Instead, the service just combines all such email threads into one big thread.
Use the `[syzbot] Monthly subsystemName report` format.
=> dashboard: change the title for subsystem reports

dashboard/app/subsystem.go, pkg/subsystem/extractor.go, pkg/subsystem/extractor_test.go
We're not yet perfect at eliminating unneeded calls from reproducers, so let's make the subsystem extraction rules stricter: only take a subsystem from the reproducer if it's present in all reproducers.
Consider more crashes (7 instead of 5) to give more opportunities to drop an unneeded call.
=> pkg/subsystem: take only always present calls from repros

dashboard/app/reporting_email.go, dashboard/app/reporting_lists.go, dashboard/app/subsystem_test.go, dashboard/dashapi/dashapi.go, pkg/email/parser.go
If the `#syz regenerate` command is sent in response to a bug list, dashboard will schedule its regeneration the next time the corresponding cron job is run.
=> dashboard: support `#syz regenerate` command

.clang-format
New versions of clang-format start complaining about the dup attribute.
Remove it.
=> .clang-format: remove duplicate attribute

dashboard/app/subsystems.html, dashboard/app/templates.html, pkg/html/pages/style.css
- dashboard/app: remove repetition on subsystems page
- dashboard/app: move aux notes to the bottom of the page
- dashboard/app: move manager to the end of crashes table
- dashboard/app: don't wrap assets column in crashes table
=> dashboard/app: tidy UI

tools/syz-env
Docker now supports rootless mode, which allows you to run your dockerd as a non-root user. This is helpful for security, as traditional rootful Docker can trivially be used to obtain root privileges outside of a container.
Rootless Docker is implemented using RootlessKit (a fancy version of fakeroot that uses user namespaces) to create a new user namespace that maps the uid of the user running dockerd to 0. Files in mounted volumes that are owned by that user will appear in the container as belonging to root.
Currently, syz-env invokes "docker run" with --user to set the uid inside the container to match the user's uid outside the container, to ensure that file ownership and permissions behave as expected. This breaks under rootless mode, as the files will appear to be owned by root …
=> syz-env: don't invoke docker with --user in rootless mode

pkg/subsystem/linux/rules.go, pkg/subsystem/lists/linux.go
Adjust the rules so that syz_mount_image$nilfs2 begins to point to nilfs.
=> pkg/subsystem: fix nilfs syscalls

pkg/subsystem/extractor.go, pkg/subsystem/lists/linux_test.go
There was a small bug and, as a result, subsystems from reproducers always superceded all other ones. That was not the desired side-effect.
Fix the logic and add a test to linux_test.go.
=> pkg/subsystem: update the bug subsystem extraction logic

dashboard/app/subsystem.go
We need to log the subsystem change before it's updated. After update there won't be any difference.
=> dashboard: fix subsystem change logging

dashboard/app/api.go, dashboard/app/app_test.go, dashboard/app/bug.html, dashboard/app/config.go, dashboard/app/discussion.go, dashboard/app/discussion_test.go, dashboard/app/entities.go, dashboard/app/index.yaml, dashboard/app/main.go, dashboard/app/reporting_email.go, dashboard/app/templates.html, dashboard/app/util_test.go, dashboard/dashapi/dashapi.go, pkg/email/lore/parse.go, pkg/email/lore/parse_test.go, pkg/email/lore/read.go, pkg/email/parser.go, pkg/email/parser_test.go, pkg/vcs/fuchsia.go, pkg/vcs/git.go, pkg/vcs/git_test.go, pkg/vcs/git_test_util.go, pkg/vcs/vcs.go, tools/syz-lore/query_lkml.go
With the changes from this PR syzbot will be able to collect the latest information about the bug-related discussion on LKML: bug reporting thread and bug fixing patches that include syzbot's `Reported-by` (and therefore Cc syzbot).
The `tools/syz-lkml` tool will need to be run once to extract existing discussions from LKML archives. All new discussions and messages will be picked up automatically.
TODO:
Changes that'll be (hopefully) covered in further PRs:
- Instead of ambiguous `Last activity` column show the number of replies in discussions and the number of sent patches.
- Add something like `#syz add discussion` to let users add relevant discussions that did not Cc syzbot.
=> dashboard: collect and display bug-related discussions

dashboard/app/config.go, dashboard/app/main.go, dashboard/app/templates.html, pkg/html/pages/common.js, pkg/html/pages/style.css
This should help users clearly distinguish silently ignored bug reports, bug reports with discussions and bugs for which patches have already been sent.
=> dashboard: display discussion info on the main page

sys/linux/dev_msm.txt
The handle is an output value, used for other gem handle inputs. Mark it as such to clarify where gem handles come from.
=> sys/linux: mark drm_msm_gem_new 'handle' as out

executor/gen_linux_amd64.go, executor/kvm_amd64.S
This soothes two compiler warnings:
- kvm_gen defaulted to executable stack due to a missing `.note.GNU-stack` elf section.
- kvm_amd64.S contained an at&t instruction with a missing instruction mnemonic suffix.
The kvm_gen bin is used to generate the kvm_amd64.S.h. Neither change affects the final kvm_amd64.S.h
=> Fix compiler warning for kvm_gen

pkg/email/lore/parse.go, pkg/email/lore/parse_test.go
Patches are not always spelled upper case. Also, looking for just PATCH may lead to false positives, so first put the subject to lower case and then look for the "[patch" substring.
=> pkg/email/lore: better classify emails

dashboard/app/app_test.go, dashboard/app/reporting_lists.go, dashboard/app/subsystem_test.go, pkg/subsystem/entities.go, pkg/subsystem/linux/rules.go, pkg/subsystem/linux/subsystems.go, pkg/subsystem/lists/linux.go, tools/syz-query-subsystems/generator.go
For some subsystems (e.g. `kernel`) such reports just don't make much sense, since there are too many incorrectly classified bugs in there. Make it possible to exclude such subsystems from periodic reminders.
=> dashboard: optionally disable monthly reports

sys/linux/dev_msm.txt
The msm gpu driver has a submit queue and some associated ioctls for it. The driver uses an 'id' to identify an element in the queue. Make a resource for this id and update the descriptions to use the resource so we can provide better hints about what sorts of numbers to try here.
@zsm-oss @robclark
=> sys/linux: describe submit queue id as a resource in msm

docs/research.md
tl;dr they try to identify the data structure involved in a crash, e.g. by parsing the WARN_ON condition. they modify the compiler instrumentation to overwrite some of the upper bits in the program counters, for program counters that modify the data structure. then they guide coverage by these magic PCs. they do this to find other failure modes of buggy code found by syzkaller.
=> docs: add GREBE reference

pkg/report/linux.go, pkg/report/testdata/linux/report/694
Also, skip more workqueue functions.
=> pkg/report: skip stack trace handling functions

pkg/vcs/git.go
The Pixel repository from partner-android takes ~2 hours to initialize, so increased the git command timeout to 3 hours.
=> pkg/vcs: lengthen command timeout

dashboard/app/api.go, dashboard/app/app_test.go, dashboard/app/bisect_test.go, dashboard/app/cron.yaml, dashboard/app/entities.go, dashboard/app/index.yaml, dashboard/app/jobs.go, dashboard/app/jobs_test.go, dashboard/app/main.go, dashboard/app/util_test.go
Refactor patch testing functionality.
Instead of creating patch testing jobs per cron, create them on demand
during pollJob(). This allows to only create jobs for managers that do
support jobs and also simplifies further changes that are related to
patch testing.
As there are too many bugs and poll period is quite small, don't query
all the database each time. Consider a random subset of bugs each time,
this should be enough given high poll rate.
=> datastore: refactor patch retesting functionality

docs/syzbot.md, pkg/vcs/linux.go, tools/create-buildroot-image.sh
The buildroot based rootfs we have been using for a while has resulted in a lot of bad and inconclusive bisections. Reasons are:
- It enabled the ext4 feature verity, which makes the image not (rw) mountable at v5.3 and below.
- Kernels at v4.18 and below simply refuse to boot with this rootfs.
Hence in this PR I propose disabling ext4 verity and not trying to bisect beyond v4.19. See commit messages for more details.
After this I'll be working on:
- [This PR to not markt this kind of issue as "inconclusive" ](https://github.com/google/syzkaller/pull/3663)
- [Bisection fixes specific to clang](https://github.com/google/syzkaller/issues/3814)
In the future we should probably teach the bisect code to pick different rootfs images based on kernel version, however I'm not planing to do this …
=> pkg/bisect: support linux gcc builds back to v4.19+ again

dashboard/app/handler.go
Still don't show them in the header, but at least serve all direct links to the bugs of a decommissioned namespace.
=> dashboard: let users see decommissioned namespaces

pkg/cover/canonicalizer.go, pkg/cover/canonicalizer_test.go, pkg/host/machine_info.go, pkg/host/machine_info_linux.go, syz-manager/manager.go, syz-manager/rpc.go
Created a hash in syz-manager to map between each
instance address and a stored canonical address.
Translate PC coverage values when receiving inputs
from VMs and when sending inputs to each VM.
Signal conversion will be fixed in a future commit.
=> syz-manager, pkg/cover: normalize module PCs between VM instances

sys/netbsd/init_test.go, sys/targets/common.go
Otherwise we may end up corrupting device memory.
See https://groups.google.com/g/syzkaller-netbsd-bugs/c/Iy8-NZ_M9Ug/m/5jKKfncsAQAJ
=> sys/netbsd: neutralize compat_50_mknod

tools/create-openbsd-gce-ci.sh
It's not worth the trouble to figure out how to quote things to save a single copy for a short literal.
=> tools: simplify openbsd startup script

vm/cuttlefish/cuttlefish.go
Cuttlefish instances are running out of memory;
increased size to allow for a margin on
running processes.
=> vm/cuttlefish: increase cuttlefish memory

dashboard/app/main.go
It's the most important label type, so let's avoid displaying label names like 'subsystem:fs'.
=> dashboard: use shorter labels for subsystems

dashboard/app/asset_storage_test.go, dashboard/app/bisect_test.go, dashboard/app/email_test.go, dashboard/app/mail_bug.txt
We don't mention the whole list of #syz set labels there, so it will only confuse people.
=> dashboard: drop #syz unset from bug's template

dashboard/app/entities.go, dashboard/app/main.go
It got broken during recent label-related changes.
=> dashboard: fix subsystem page filtering

syz-fuzzer/testing.go
Just got this pearl:
2023/04/28 06:46:56 unsupported syscall: quotactl_fd$Q_GETINFO: sys_quotactl_fd is not
enabled in the kernel (not present in /proc/kallsyms)
...
2023/04/28 06:47:26 vm-0: crash: INFO: sys_quotactl_fd is not
enabled in the kernel (not present in /proc/kallsyms)
=> syz-fuzzer: avoid recognizing unsupported syscalls as kernel oops

dashboard/app/bug.html
It's more intuitive for users to see a down-facing triangle for collapsed blocks.
=> dashboard: use a down-pointing triangle in collapsible blocks

dashboard/app/api.go, dashboard/app/app_test.go, dashboard/app/config.go, dashboard/app/email_test.go, dashboard/app/entities.go, dashboard/app/jobs.go, dashboard/app/label.go, dashboard/app/main.go, dashboard/app/reporting.go, dashboard/app/templates.html, dashboard/app/tree.go, dashboard/app/tree_test.go, dashboard/app/util_test.go, dashboard/dashapi/dashapi.go, pkg/vcs/fuchsia.go, pkg/vcs/git.go, pkg/vcs/git_test.go, pkg/vcs/vcs.go, syz-ci/jobs.go
Run reproducers on other trees in order to determine:
1) The tree where the bug originated.
2) The tree to which the bug has already spread.
3) Missing backports for bugs.
Extend the KernelRepo structure to contain the information about commit
flow and about the exact labels that need to be assigned for (1) and
(2).
Fore better understanding look at the tests in tree_test.go.
TODO (before merging):
=> all: determine bug origin trees and missing backports

dashboard/app/jobs.go, dashboard/app/reporting.go
There's a chance jobs will be created at the time between a namespace is decommissioned and syz-ci's are stopped.
=> dashboard: don't create jobs for decommissioned namespaces

tools/docker/env/Dockerfile, tools/docker/syzbot/Dockerfile
The git version used in bullseye is too old and is not compatible with Fuchsia. This change modifies the dockerfile to install git from bullseye-backports, which is more recent.
=> tools/docker: fix docker for Fuchsia

executor/common.h, executor/common_bsd.h, executor/common_linux.h, executor/common_usb.h, executor/common_usb_linux.h, executor/common_usb_netbsd.h, pkg/csource/csource_test.go, pkg/csource/generated.go, prog/rand.go
There seem to be a lot of unclear dependencies between pseudo syscall
code and global methods. By testing them only together we have little
chance to detect these problems because implementations can indiretly
help one another.
In addition to existing tests, also compile all pseudo syscalls
independently.
=> pkg/csource: compile pseudo syscalls individually

vm/gvisor/gvisor.go
In this case, CPU time will be divided equally between vm-s.
=> gvisor: set cpu cgroups for VM-s

vm/gvisor/gvisor.go
ptrace and systrap platforms don't work if rseq is enabled.
=> gvisor: disable glibc rseq

pkg/build/cuttlefish.go
Android bazel builds are currently failing due to
a failure when running `rsync` from root. Building the kernel from the syzkaller sandbox to circumvent this issue.
=> pkg/build/cuttlefish: sandbox cuttlefish bazel build

pkg/log/log.go, syz-manager/manager.go
1. Update the default syzkaller log format to facilitate automated log analysis.
2. Set the type of some syz-manager log messages to `Error`.
=> RFC: syz-manager: facilitate automated log analysis

dashboard/app/reporting.go
These sanity checks need correction since with reproducer retesting it's possible to have the top crash not match the ReproLevel.
=> dashboard: assert repro presence against HeadReproLevel

pkg/bisect/bisect.go, pkg/bisect/bisect_test.go, pkg/report/report.go
When a bisection is started, we only know the kernel commit on which syzkaller encountered the crash. Before the actual bisection begins, bisect() needs to find a good commit. Then we can bisect between them.
For fix bisections bisect() tests HEAD. If HEAD doesn't have the bug the fixing commit must be somewhere in the middle. For cause bisection we test a number of old releases, starting with the newest release.
Both this commit range search and the actual bisection later use test() to build the kernel and run the reproducer.
During actual bisections we invoke test() for every step. If any test() invocation returns a non nil error, the bisection it was called from is aborted. Any non-fatal errors should be signaled via the testResult returned from test(). For this reason a build/boot …
=> pkg/bisect: mark jobs with untestable history as failed

pkg/build/cuttlefish.go
Distribution directory ("dist") is not being cleaned in Cuttlefish build. Remove directory during clean.
=> pkg/build: clean dist directory

syz-ci/jobs.go
Earlier it was limited to 8 hours mostly because syz-ci could execute only one job at a time. Now that it's no longer the case, we can increase the timeout to 12 hours.
Cc @HerrSpace
=> syz-ci: increase bisection job timeout

dashboard/app/entities.go, dashboard/app/jobs.go, dashboard/app/jobs_test.go, dashboard/app/main.go, dashboard/dashapi/dashapi.go, pkg/bisect/bisect.go, pkg/bisect/bisect_test.go, pkg/instance/instance.go, syz-ci/jobs.go, vm/vm.go, vm/vmimpl/vmimpl.go, vm/vmm/vmm.go
Closes https://github.com/google/syzkaller/issues/3854
See descriptions of individual commits.
TL;DR:
* Separate boot/test errors and infrastructure errors.
* If more than 50% of runs failed due to infra problems, abort a bisection.
* Restart cause and fix bisections if they were aborted due to infrastructure problems.
=> dashboard: retry bisections on infrastructure errors

dashboard/app/main.go, dashboard/app/main_test.go, dashboard/app/templates.html, pkg/html/html.go, pkg/html/html_test.go
For each label, allow only one value to be specified. At the same time, allow multiple different labels (subsystem, origin, prio, etc) be specified together.
=> dashboard: support filtering over multiple labels

syz-ci/manager.go
It should be defined by the bucket's settings and not for individual files.
=> syz-ci: don't publish uploaded files

dashboard/app/tree.go, dashboard/app/tree_test.go
If the tested tree is build/boot/test broken, repeat the job in 2 weeks.
If we are waiting for a bug to get fix, repeat every 45 days.
=> dashboard: adjust bug origin tree testing periods

dashboard/app/jobs.go, dashboard/app/main.go, dashboard/app/reporting.go, dashboard/app/reporting_email.go, dashboard/app/reporting_lists.go, dashboard/app/reporting_test.go
Context: https://lore.kernel.org/lkml/ZFi5FfjVpxLEk48A@mit.edu/
The former one is consistent with the dashboard URL from our bug reports.
This PR fixes URLs for open/closed/fixed/subsystem bug lists, but still leaves a few exceptions:
* Links to bugs about kernel/syzkaller build problems from the manager table.
* Links from /admin page.
* Bugs that were never reported.
In the first two cases we'd have to do extra loads the Bug entity from the database. For now it doesn't seem to be worth it, as nobody except syzbot maintainers usually follows those links. In the third case there's no extid.
=> dashboard: prefer bug?extid= links over bug?id=

dashboard/app/bug.html, dashboard/app/jobs.go, dashboard/app/main.go, dashboard/app/templates.html, dashboard/app/tree.go, dashboard/app/tree_test.go, dashboard/dashapi/dashapi.go, pkg/html/pages/style.css
Display them as a collapsible block on the bug info page.
=> dashboard: display bug origin tree testing results

syz-ci/manager.go, syz-ci/syz-ci.go
Earlier `syz-ci: don't publish uploaded files` commit completely disabled the GCS object publishing after each object.
However, it turns out that otherwise the objects quickly lose the `public to internet` flag.
Make the option configurable.
=> syz-ci: optionally publish GCS objects

pkg/asset/backend_dummy.go, pkg/asset/backend_gcs.go, pkg/asset/backend_gcs_test.go, pkg/asset/storage.go, pkg/asset/storage_test.go
If several syz-cis with different GCS buckets for assets are connected to a single dashboard, we currently face problems during the asset deprecation process.
If we receive from the dashboard a valid GCS URL that belong to an unknown bucket, don't abort the process. Just ignore the URL.
Test this behavior.
=> pkg/asset: support deprecation in the many buckets case

syz-ci/syz-ci.go
The "syz-ci: assign RPC ports to instances" commit implied that it was "", but in reality it's set to ":0" by LoadPartialData().
=> syz-ci: use the right default RPC port value

pkg/build/cuttlefish.go
Android13 build .config files for bazel are located in 
'<tmp_build_dir>/virtual_device_x86_64_config/.config', 
while Android14 bazel .build config files are located in 
'<tmp_build_dir>/virtual_device_x86_64_config/out_dir/.config.'
Updating the path to account for both cases.
=> pkg/build: update .config path for Bazel Cuttlefish builds

dashboard/app/api.go
There are cases when we have revoked a reproducer, but quickly found a newer one. In that case we should update HeadReproLevel.
=> dashboard: update HeadReproLevel separately

pkg/instance/execprog.go, pkg/repro/repro.go, pkg/repro/repro_test.go, syz-manager/manager.go
Closes https://github.com/google/syzkaller/issues/3903
1. Refactor `pkg/repro` to facilitate testing and add a smoke test.
2. Repeat executions one more time in case of errors (we're getting a lot of `failed to copy prog to VM` that seem transient).
3. Wait for all `pkg/repro` routines to finish before returning.
4. Decrease the default number of VMs dedicated for bug reproduction from 4 to 3.
See individual commit messages.
=> pkg/repro: assorted improvements

pkg/vcs/linux.go, pkg/vcs/linux_test.go
This was already the case before #3420. Using the default compiler so far back was overly optimistic, as pointed out in #3814.
=> pkg/vcs: use gcc 10.1 for linux v5.8..v5.16

dashboard/app/mail_label_notif.txt, dashboard/app/tree_test.go
Full commit ids are not necessary in the notification email.
=> dashboard: use short hashes in mail_label_notif.txt

dashboard/app/config.go, dashboard/app/jobs.go, dashboard/app/tree.go, dashboard/app/tree_test.go
There are cases when e.g. an LTS kernel does not build if provided with some downstream kernel config.
Introduce a special AppendConfig option to KernelRepo that can help in this case.
=> dashboard: amend configs during tree origin testing

pkg/subsystem/linux/names.go
The current syz-query-subsystems raise below error: failed to query subsystems: failed to set names: failed to extract a name from kernel-tls-handshake@lists.linux.dev
This patch adds this email to exception list to fix that.
=> pkg/subsystem: add tls email exception

docs/akaros/README.md, docs/contributing.md, docs/coverage.md, docs/linux/external_fuzzing_network.md, docs/linux/reporting_kernel_bugs.md, docs/linux/setup_linux-host_isolated.md, docs/linux/setup_ubuntu-host_odroid-c2-board_arm64-kernel.md, docs/linux/setup_ubuntu-host_vmware-vm_x86-64-kernel.md, docs/netbsd/README.md, docs/setup_syzbot.md, docs/strace.md, docs/syscall_descriptions.md, docs/syzbot.md
Fix various typos within the documentation directory.
While reading some of the docs I came across a few typos, plug them.
=> docs: typo fixes

pkg/repro/repro.go, syz-manager/manager.go
Otherwise we're getting "repro failed: all VMs failed to boot" `pkg/repro` errors if a sykaller instance is shutting down.
=> syz-manager: don't report all pkg/repro errors on shutdown

executor/executor.cc, pkg/cover/canonicalizer.go, pkg/cover/canonicalizer_test.go, pkg/signal/signal.go, syz-manager/rpc.go
Adjust signal creation in syz-executor so hash
is independent of module offsets. This allows
for canonicalization of the signal between VMs.
Added signals to canonicalization/decanonicalization between instances.
Coverts serialized Signal values as they have already been serialized in rpc.go. Added a function in signal.go to update serial signal elements.
=> syz-manager, pkg/cover: normalize signals between VM instances

CONTRIBUTORS, vm/adb/adb.go
Android emulator generates an invalid android ID for syzkaller. Solved by removing android ID check in adb.go
=> vm/adb: have adb work with android emulator by default

executor/common_linux.h, pkg/csource/generated.go
Given that we must chose only one version, fuzzing v1 of itseems to be of higher value at the moment.
Later we might make it a configurable option and do both versions.
=> executor: use v1 memory cgroup controller

executor/common.h, executor/common_fuchsia.h, executor/common_linux.h, executor/common_windows.h, executor/executor.cc, pkg/csource/generated.go
We have a long history of executor managing to corrupt itself in various interesting ways (e.g. using read with a pointer pointing to some global/stack variable and then kernel overwrites it). Or rt_sigreturn can corrupt other registers which won't cause immediate SIGSEGV, but rather some random behavior later.  This is the race we can't win.
We can't rely on memory consistency when the test already started, so we should use exitf instead of fail outside of setup sequence (and relying more on unit testing to ensure that executor works as expected for sane programs).
=> executor: use exitf instead of fail outside of setup sequence

pkg/bisect/bisect.go
This was one of https://github.com/google/syzkaller/pull/3952  commits.
----
If there are only a few non-crashed results among many boot/test errors, we cannot really be sure that the commit is good. It might be that the reproducer is not 100% reliable and we just needed more runs.
Require > 50% of runs to be successful in order to claim that the revision is good. Otherwise skip it.
=> pkg/bisect: skip commits with too many boot/test errors

pkg/vcs/linux.go
We sometimes cherry-pick fixes to a bisected branch, for issues that make large parts of history untestable. Previously we cherry-picked if the fix commit hash isn't already present.
This is incorrect, as forks / lts trees may already cherry-picked the fix. In this case the fix would be present, but not have the expected hash. Unfortunately git doesn't have Change-Ids like gerrit, so there is no great way to check if a fix is already present.
Instead we now just check whether any commit with the expected title is present.
=> pkg/vcs: search cherry-picks by title

executor/common.h, executor/common_linux.h, executor/executor_linux.h, pkg/csource/common.go, pkg/csource/generated.go, pkg/csource/options.go, pkg/csource/options_test.go, pkg/host/features.go, pkg/host/features_linux.go, pkg/repro/repro.go, pkg/runtest/run.go
If the feature is supported on the device, allocate a 128MB swap file after VM boot and activate it.
=> all: add swap feature for Linux fuzzing

pkg/host/machine_info.go, syz-manager/html.go, tools/syz-cover/syz-cover.go
Allow syz-cover to accept canonical module information when generating kernel module coverage reports.
=> syz-cover: accept canonical module info

executor/common_linux.h, pkg/csource/generated.go
Its needed for FALLOC_FL_ZERO_RANGE which needs this header, it works with glibc because fcntl.h includes this header indirectly, however the failure comes to fore with musl C library where this header is not included indirectly by other system headers, therefore include it as required.
Fixes
In file included from executor/common.h:505:
executor/common_linux.h:5604:16: error: use of undeclared identifier 'FALLOC_FL_ZERO_RANGE'
fallocate(fd, FALLOC_FL_ZERO_RANGE, 0, SWAP_FILE_SIZE);
^
=> executor: Include missing linux/falloc.h

pkg/mgrconfig/config.go
Updated ModuleObj documentation, as Syzkaller can now compare coverage of dynamically loaded modules.
=> pkg/mgrconfig: update ModuleObj documentation

vm/qemu/qemu.go
The `-accel tcg,thread=multi` option speeds up boot by ~25%. Execution speed shoud also increase.
=> vm: speed up arm64 emulation

pkg/cover/backend/dwarf.go
The arguments `objDir`and `srcDir` of cleanPath() are absolute paths, see osutil.Abs() calls in:
* syz-cover: tools/syz-cover/syz-cover.go
* syz-manager: pkg/mgrconfig/load.go
However, when the `path` argument is not absolute, the first two checks of cleanPath (when file is built in path or when file was moved from builDir to srcDir) always evaluate to false.
Instead use absolute path for those checks.
=> pkg/cover/backend: check absolute path when cleaning path

pkg/bisect/bisect.go, pkg/bisect/bisect_test.go, tools/syz-bisect/bisect.go
Last rewritten piece of https://github.com/google/syzkaller/pull/3952
----
The current code only supports fix/cause bisections when the known bad commit is reachable from Kernel.Repo/Kernel.Branch.
Add a CrossTree parameter to pkg/bisect. If it's set to true and we're doing a fix bisection, the bisection algorithm first operates with the original commit message (i.e. checks that it indeed crashes the kernel and performs config minimization), but the actual bisection starts from the merge base of Commit and Branch.
We could have calculated the merge base outside of pkg/bisect and just started the algorithm from that merge base, but there's a problem: there's no guarantee that the kernel will build/boot with a syzbot config at the merge base. So we take the commit known to work well and …
=> pkg/bisect: support bisections on other trees

pkg/bisect/bisect.go, pkg/bisect/bisect_test.go
Fail the whole bisection if 1/3 of runs failed due to infrastructure problems.
If 1/3 of runs failed due to boot/test errors, skip the revision. With such a big failure rate it's too likely to get a false positive/false negative result.
=> pkg/bisect: change revision skip conditions

pkg/build/cuttlefish.go
Android Bazel requires an input 'defconfig' file to build.
This is ensured by check_defconfig
(https://cs.android.com/android/kernel/superproject/+/common-android-mainline:build/kernel/_setup_env.sh;l=283).
Create an input 'defconfig' file from a given config, then build the kernel.
=> build/cuttlefish: build from config file

syz-ci/jobs.go
Now that almost all upstream kernel builds are broken, we're experiencing problems with job execution -- attempts to rebuild a kernel on each syz-ci restart keep global locks taken almost all the time.
----
This condition is no longer really important -- build and test are anyway controlled by semaphores, so if we don't take the job, nobody else will be able to finish it sooner.
Also, we reset job statuses on syz-ci restart, so it won't be a problem to take a job again.
=> syz-ci: don't wait for semaphore to query a job

dashboard/app/getjson_test.go, dashboard/app/main.go, dashboard/app/public_json_api.go
Let's assume we don't know fixing commit.
Exporting bug id we allow external systems to group our reports.
=> dashboard/app: export bug id

pkg/cover/report.go, pkg/cover/report_test.go, pkg/host/machine_info.go, pkg/host/machine_info_linux.go, syz-manager/cover.go, tools/syz-cover/syz-cover.go
Improve syz-cover to
1. read params from cfg file
2. pass cfg to MakeReportGenerator
3. use all pcs from rg.Symbols if flag.Args() == 0
4. parse modules info from file dumped from /proc/modules
=> syz-cover improvements

pkg/bisect/bisect.go, pkg/bisect/bisect_test.go, pkg/report/crash/types.go, pkg/report/freebsd.go, pkg/report/report.go, pkg/report/testdata/all/report/5, pkg/report/testdata/linux/report/601, pkg/report/testdata/linux/report/660
This is a rewritten part of https://github.com/google/syzkaller/pull/3952
----
There are cases when a crash, even though it didn't occur during boot
and image testing phases, still should not be counted during bisection.
Otherwise we risk diverting the whole process in the wrong direction.
One of such problem classes is getting SYZFATAL errors when we are not
bisecting a SYZFATAL crash.
=> pkg/bisect: ignore transient crashes

dashboard/app/api.go, dashboard/app/subsystem_test.go
Don't recalculate subsystems when a user has already specified them. Add a test to verify this behavior.
=> dashboard: don't overwrite user-set subsystems

pkg/bisect/bisect.go, pkg/bisect/bisect_test.go
After the previous change, pkg/bisect is unable to bisect SYZFATAL errors. Fix the bug in the logic and add a test.
=> pkg/bisect: fix SYZFATAL bisections

pkg/instance/execprog.go
The `instance.test()` code is used for reproducer generation and kernel bisections, we don't really need symoblized reports there.
Instead of retuning an error, just print it as a log message.
=> pkg/instance: don't fail on symbolization error

pkg/vcs/linux_configs.go
Let's keep it enabled for newer Linux kernel versions as it keeps the environment closer to the one where the bug happened.
We disable KCOV in baseline configs, so we'll try to drop it at the kernel config bisection stage anyway.
=> pkg/bisect: keep KCOV enabled for newer Linux versions

pkg/vcs/linux_configs.go, pkg/vcs/linux_configs_test.go
We also need to disable CONFIG_PROVE_LOCKING, which forces CONFIG_LOCKDEP to be enabled.
=> pkg/vcs: properly disable lockdep

pkg/cover/canonicalizer.go, pkg/cover/canonicalizer_test.go, syz-manager/covfilter.go, syz-manager/manager.go, syz-manager/rpc.go
Apply module conversion to filter bitmap to support coverage filtering when modules are used.
Coverage bitmap is decanonicalized to match each instance's module PCs.
This was done by decanonicalizing the map of bitmap PCs before bitmap creation to simplify conversion. I could convert the final bitmap or pass in the canonicalization instance to createCoverageFilter() to prevent this change.
The "coverFilter" used by the manager is only used on canonicalized PCs, so it remains unchanged.
=> pkg/cover, syz-manager: support coverage filtering with modules

syz-manager/covfilter.go, syz-manager/covfilter_test.go
PR https://github.com/google/syzkaller/pull/3953 caused the error 'SYZFAIL: coverage filter was enabled but bitmap initialization failed' when filter was not instantiated.
The previous PR ran createCoverageBitmap() regardless of whether or not the coverage filtering was used, instantiating a bitmap with an empty size.
=> syz-manager/covfilter: return nil bitmap if filtering is not used

syz-ci/config_test.go, syz-ci/syz-ci.go
If a kernel config is specified, infer it's `-base.config` counterpart. If such a file is present, use it as a default value for KernelBaselineConfig.
=> syz-ci: auto-guess baseline kernel configs

pkg/report/testdata/linux/decompile/amd64/4.out, pkg/report/testdata/linux/decompile/arm/0.out, tools/docker/big-env/Dockerfile, tools/docker/env/Dockerfile, tools/docker/syzbot/Dockerfile
We ultimately want to merge all these 3 docker images to 1, but let's update them all to bookworm first, it was already quite challenging per se. During merging there will likely be another set of problems.
---
Closes #3973.
As Python 2.7 is no longer present in the packages, build it directly in Dockerfile. It's rather small and doesn't take much time.
=> tools/docker: update to bookworm images

pkg/symbolizer/nm.go
The remaining checks (elf.SHF_ALLOC and elf.SHF_EXECINSTR) seem to a good enough filter for matching symbols.
Additionally, there have already been cases when absolutely valid functions ended up in SHF_WRITE sections:
https://git.kernel.org/pub/scm/linux/kernel/git/arm64/linux.git/commit/?id=0fddb79bf283
=> pkg/symbolizer: skip the elf.SHF_WRITE check

pkg/build/gvisor.go
sync.gateCommit() is also a go:norace function called during runtime.gopark().
=> pkg/build: don't coverage-instrument gVisor sync package in race builds

pkg/bisect/bisect.go, pkg/bisect/bisect_test.go, syz-ci/jobs.go
Estimate reproducer's flakiness more carefully, as it can help us get better results.
During config minimization, do not let reproducibility drop too low.
For each `test()` run, estimate our confidence in the result. For now, only consider the false negative case: if we got no crashes, it's likely that the bug is there, but the reproducer was not lucky enough. Given an estimate of reproduction likelihood, we can easily calculate the chance of an invalid result: `(1-probability)^runs`.
Combine all individual `test()` confidences into `Result.Confidence`. If the resulting Confidence is too low, ignore the bisection result.
=> pkg/bisect: estimate confidence in the result

dashboard/app/admin.html, dashboard/app/index.yaml, dashboard/app/main.go, dashboard/app/main_test.go, dashboard/app/templates.html
Currently we only show running/pending/recent jobs. Let admins also see the list of the latest cause/fix bisections.
=> dashboard: show per-bisect type job lists for admins

dashboard/app/reporting.go
We have 1014 unfixed /upstream bugs.
Increasing batch size 2* we'll improve answer latency for the /upstream page.
=> dashboard/app: increase batch size to 2000

executor/common_usb_linux.h, pkg/csource/generated.go
The loop in lookup_endpoint incorrectly iterates over endpoints.
Fixes #4038.
Reported-by: @cyruscyliu
=> executor: fix loop condition in lookup_endpoint

pkg/bisect/bisect.go, pkg/vcs/linux.go, pkg/vcs/linux_patches.go, pkg/vcs/testos.go, pkg/vcs/vcs.go, syz-ci/jobs.go, syz-ci/syz-ci.go, tools/syz-bisect/bisect.go, tools/syz-testbuild/testbuild.go
* Refactor cherry picking for older kernel revisions in `pkg/vcs`.
* Add more Linux-specific cherry-picks.
* Let users specify custom cherry-picks in the `syz-ci` config.
=> pkg/vcs: cherry-pick more fixes for Linux

pkg/repro/repro.go, pkg/repro/repro_test.go
Retrying once has greatly reduced the number of "failed to copy prog to VM" errors, but they still periodically pop up. The underlying problem is still not 100% known.
Supposedly, if a booted VM with an instrumented kernel has to wait too long, it can just hang or crash by itself. At least on some problematic revisions.
Investigation wouldbe quite time-consuming -- we need to do a complicated refactoring in order to also capture serial output for Copy() failures. So far it does not seem to be totally worth it.
Let's do 3 runOnInstance() attempts. If the problem still persists, there's no point in doing more runs -- we'd have to determine the exact root cause.
=> pkg/repro: tolerate two consequential run errors

tools/docker/env/Dockerfile
By mistake, we're installing Go twice in this Dockerfile. Remove the 1.19 installation and only leave the 1.20 one.
=> tools/docker/env: use Go 1.20

syz-manager/covfilter_test.go
Error when creating a coverage bitmap without
input pcs.
=> syz-manager/covfilter_test: test nil coverage bitmap

pkg/build/linux_generated.go, tools/create-gce-image.sh, tools/create-image.sh
- Workarounds for some ppc64le platform quirks
- Add the `non-free-firmware` Debian archive component so that we can install `firmware-atheros` on new Debian releases
- Preserve proxy variables when invoking debootstrap via sudo in `create-image.sh` for environments where you have a proxy set
=> tools: misc create-image.sh, create-gce-image.sh updates

.github/workflows/ci.yml
"self-hosted" is the automatically assigned label.
k8s cluster runners are also "self-hosted".
To distinguish k8s and gce instances additional label is needed.
"any-env" will be temporarily used until full migration to k8s.
=> ci.yml: run on any-env not self-runner

dashboard/app/config.go, dashboard/app/entities.go, dashboard/app/jobs.go, dashboard/app/reporting.go, dashboard/app/tree.go, dashboard/app/tree_test.go, dashboard/dashapi/dashapi.go, syz-ci/jobs.go
If tree origin assessment code has identified that the bug is not reproducible in a tree from which we merge/cherry-pick commits, use fix bisection to identify that commit. This can e.g. be used to find fixing commits that were not backported from Linux kernel mainline into LTS branches.
This PR does not (yet?) include the code to share/display such findings.
=> all: perform cross-tree fix bisections

.github/arc_config/runner.yaml, .github/workflows/ci.yml
We have a GKE cluster with up to 32 cores * 10 nodes.
This PR forwards testing to it and enables autoscaling 3 - 10 nodes.
For every job it downloads syz-env container which takes ~2.5 minutes.
Single PR check time will be the same because "race" job was typically waiting for the build node availability (~3 min). We had 2 nodes (1 used by "build" and 1 by "dashboard").
Potential improvements:
1. Switch to "sysbox".
2. Somehow cache syz-env downloads.
=> ci.yml: run dashboard tests on k8s

syz-ci/jobs.go
Given that mail_bisect_template.txt refers to that data as "start commit", let's directly use the information about the starting commit that we already have.
Otherwise we get `start commit:   [unknown]` in our reports.
=> syz-ci: set bisection job build to start commit

pkg/vcs/linux.go
The transform() call is assumed to be idempotent, so let's also run it before all predicate runs. It will ensure that we return exactly the same config from getConfig() as the one that was actually tested.
Context: there've been some mysteriously incorrect bisection results lately. See e.g. https://syzkaller.appspot.com/x/bisect.txt?x=122e2c31a80000
The exact reason is still unclear, but let's submit this change as it can only improve things anyway.
=> pkg/vcs: ensure config transformation in predicates

dashboard/app/bug.html, dashboard/app/jobs.go, dashboard/app/main.go, dashboard/app/templates.html, dashboard/dashapi/dashapi.go, pkg/html/pages/style.css
Display potential fix candidates on the per-bug web pages.
=> dashboard: display fix candidate info on the bug page

syz-ci/jobs.go
Judging from the bisection logs, the confidence level statistic indeed correlates with the chance of the result being true positive.
Let's use a stricter threshold to publish fewer false positives.
=> syz-ci: increase bisection confidence cut-off to 0.66

syz-manager/rpc.go
Signal was deserialized before running canonicalization; moved to after to ensure all signals are correct.
=> syz-manager/rpc: canonicalize input before merging signal

syz-ci/jobs.go, syz-ci/syz-ci.go
Make syz-ci configuration more flexible by allowing users to set the list of commits that should never be reported as valid bisection results.
Keep the list of such upstream Linux commits in the code in order not to duplicate it everywhere.
=> syz-ci: specify custom ignore lists for bisections

dashboard/app/jobs.go
We always set it for jobs and it's always relevant for the result.
The problem is that, for cross-tree bisections, the original crash points to a potentially different tree. As a result, we provide wrong links to the bisected commits.
=> dashboard: use the original KernelRepo

dashboard/app/jobs.go, dashboard/dashapi/dashapi.go
Add a new CrossTree field to dashapi.BisectResult in order to distinguish fix candidate results from normal fix bisections.
This is needed for further changes that will be published as a separate PR: https://github.com/google/syzkaller/commit/37cc32e4a46d218bba40426b091a8bc1f8cc8da8
=> dashboard: distinguish cross tree job reports

dashboard/app/jobs.go, dashboard/app/mail_fix_candidate.txt, dashboard/app/reporting_email.go, dashboard/app/tree_test.go
Enable reporting of the results of cross-tree bisections.
Adjust email reporting to differentiate between normal fix bisections and fix candidate reporting.
=> dashboard: report fix candidate commits per email

dashboard/app/app_test.go, dashboard/app/bisect_test.go, dashboard/app/jobs.go, dashboard/app/tree_test.go
Accept only normal fix bisections as a reason to auto-close a bug if FixBisectionAutoClose is set to true.
=> dashboard: don't close bugs on cross-tree fix findings

dashboard/app/tree.go, dashboard/app/tree_test.go
If bug's origin has not yet been determined, the dashboard app might crash with "panic: runtime error: invalid memory address or nil pointer dereference" at dashboard/app/tree.go:740.
Fix this and add a test.
=> dashboard: fix a nil pointer dereference

dashboard/config/linux/bits/x86_64.yml
It's not present in earlier versions.
=> dashboard: enable CONFIG_PVH from v5.0

dashboard/app/app_test.go, dashboard/app/config.go, dashboard/app/main.go, dashboard/app/main_test.go
There are cases when subsystem names change over time. As we share /namespace/s/name links in our reminder emails, we have to make sure they remain valid.
Introduce an old => new name map into the dashboard configuration.
=> dashboard: support subsystem redirects

pkg/bisect/bisect.go
We incorrectly log crash verdicts twice, which makes bisection logs more confusing. Don't do that.
=> pkg/bisect: don't log verdicts twice

pkg/cover/canonicalizer.go, pkg/cover/canonicalizer_test.go, pkg/signal/signal.go, syz-manager/rpc.go
Addresses https://github.com/google/syzkaller/issues/4078
Does not fix canonicalization when modules change over time, but does unblock fuzzing by avoiding a kernel panic when modules change.
=> pkg/cover: print a warning and discard coverage if module is invalid

pkg/vcs/linux_patches.go
The following error appears when bisecting older Linux versions:
check.c: In function 'validate_call':
check.c:2865:58: error: '%d' directive output may be truncated writing between 1 and 10 bytes into a region of size 9 [-Werror=format-truncation=]
2865 |                 snprintf(pvname, sizeof(pvname), "pv_ops[%d]", idx);
=> pkg/vcs: patch an objtool Linux bug

dashboard/app/main.go, dashboard/app/templates.html
Currently we only display the link for latest fix/cause bisections on the bug page.
Also display it inside the collapsible job lists.
=> dashboard: let admins retry jobs from job lists

pkg/bisect/bisect.go, pkg/bisect/bisect_test.go
_It might be easier to review the PR per-commit rather than as a whole._
If there's a merge from a branch that was based on a much older
revision, it's likely that it does not YET contain the bug. If we don't
consider this possibility, we're likely to get invalid fix bisection
results for bugs that existed only for a short period of time.
For every fix bisection step, determine first whether the guilty
revision is reachable from it. Cache resuls to speed up processing.
Closes https://github.com/google/syzkaller/issues/4117.
=> pkg/bisect: differentiate between revisions with a fixed and with a not-yet-introduced bug

pkg/vcs/linux_configs.go, pkg/vcs/linux_configs_test.go
First check if the cmdline config is already present.
=> pkg/vcs: don't supress rcu stall reports twice

tools/syz-build/build.go
syz-build implicitly requires a kernel config file to be present. Make it optional as it's not required by all syzkaller-supported OSes.
=> syz-build: don't require kernel config file

tools/syz-execprog/execprog.go
When coverfile option is used with multiple program inputs (e.g., with a corpus input), syz-execprog overwrites the output coverage files with each program run.
Create coverage file per program run instead, which would let save the coverage information for all inputs.
Fixes #4129
=> tools/syz-execprog: create coverage file per program run

dashboard/app/app_test.go, dashboard/app/backports.html, dashboard/app/cache.go, dashboard/app/handler.go, dashboard/app/index.yaml, dashboard/app/main.go, dashboard/app/templates.html, dashboard/app/tree_test.go
Add a per-namespace page that contains:
1) The list of commits to backport from the trees fuzzed in that
namespace.
2) The list of commits to backport into the namespace.
=> dashboard: display backport lists

.github/workflows/ci.yml
If some job is not a build bottleneck - let's remove caching.
The main focus points then are "build" and "race" then.
To cache test results independently let's use 2 different cache prefixes.
See https://markphelps.me/posts/speed-up-your-go-builds-with-actions-cache/.
The idea is to always generate cash miss using the second precision key.
After the miss we download latest uploaded one using "restore-keys".
=> ci.yml: cache build artefacts where it is needed

dashboard/app/admin.go, dashboard/app/bisect_test.go, dashboard/app/jobs.go, dashboard/app/main.go, dashboard/app/templates.html
In some cases restarting the failed bisection does not make sense,
because we know that the result will be the same.
Let admins choose between invalidating the job and restarting it.
=> dashboard: differentiate between restarting and invalidating a job

pkg/bisect/bisect.go, pkg/bisect/bisect_test.go
Consider the following situation: we're fix bisecting an lts bug on the mainline tree. Reproducer works on lts HEAD, but does not crash the mainline.
If the bug was not introduced in the mainline, but it's a purely lts bug, bisection would currently end up pointing to the mainline HEAD (in #4123, we assume env.commit to be a commit on the tree we're currently bisecting, otherwise we'd always hit the same merge base commit).
Let's first determine 100% correct bisection range on the mainline tree by testing that both the HEAD does not crash (we already do) and by testing that the new starting commit (=merge base) can be crashed by the reproducer.
=> pkg/bisect: test merge base for cross-tree bisections

dashboard/app/config.go
7 days was a too low figure that has caused too many unnecessary reproducer retests. Increase it to 14.
=> dashboard/app: increase the repro retesting start period

dashboard/app/jobs.go, dashboard/app/tree.go
Currently these jobs are heavily underrepresented -- we rarely get to generate them and, when we do, we only look up 3 random bugs.
At the same time, for the majority of issues, the check is rather cheap, we don't even have to query anything from the DB.
Split the job generation results into expensive (= extra DB queries needed) and non-expensive (= it was enough to examine *Bug) one. Limit only the amount of the former ones.
=> dashboard: generate more cross tree bisections

pkg/bisect/bisect.go, pkg/bisect/bisect_test.go, pkg/vcs/linux.go, pkg/vcs/vcs.go
For older bugs (or for bugs on stable trees), our cause bisection strategy times out while trying to iterate over all reachable tags.
Try to be smarter and only take a subset of them, thus limiting the time we spend detecting the bug-free release.
Closes #3376.
=> pkg/bisect: test a subset of releases

dashboard/app/jobs.go, dashboard/app/tree.go
Determine "expensive" lookups correctly, previously a few db lookups were overlooked.
Increase the limit, as 2 definitely discriminates such jobs.
=> dashboard: consider more bugs for fix candidate jobs

dashboard/app/index.yaml, dashboard/app/subsystem.go, dashboard/app/subsystem_test.go
Although we currently do not highlight the number of per-subsystem invalid and dup bugs, we still lack consistency in the Bug table, which complicates statistics collection for us.
Let's recalculate subsystems for invalidated and duped bugs as well. Do it after everything else is updated.
=> dashboard: update subsystems for all bugs

pkg/vcs/git.go
If the remote repo's tags conflict with the local ones, `git fetch` may fail with `error: cannot lock ref %: % exists`.
It seems that the only way to restore the repository in this case is to do `git fetch` with `--prune --prune-tags`. Since this also forces the repository to forget all tags not present in the remote, let's do it only when we got the error message.
It's unfortunately very hard to set up a unit test for it (it needs properly broken remotes), so I propose that we merge it as is.
=> pkg/vcs: circumvent ref conflicts during fetch

dashboard/app/admin.go, dashboard/app/api.go
If there's no config record for the manager, activeManager would return a nil pointer to ConfigManager. Assume the priority to be 0 in this case.
Update the admin.go function that recalculates priorities.
=> dashboard: improve crash priority calculation

vm/adb/adb.go
=> vm/adb: allow lower-case in serial number

pkg/report/linux.go, pkg/report/testdata/linux/report/626, pkg/report/testdata/linux/report/632, pkg/report/testdata/linux/report/633, pkg/report/testdata/linux/report/634, pkg/report/testdata/linux/report/635, pkg/report/testdata/linux/report/636, pkg/report/testdata/linux/report/670, pkg/report/testdata/linux/report/671, pkg/report/testdata/linux/report/672, pkg/report/testdata/linux/report/673, pkg/report/testdata/linux/report/674, pkg/report/testdata/linux/report/681, pkg/report/testdata/linux/report/682, pkg/report/testdata/linux/report/689, pkg/report/testdata/linux/report/690, pkg/report/testdata/linux/report/699, pkg/report/testdata/linux/report/700, pkg/report/testdata/linux/report/701, pkg/report/testdata/linux/report/702, pkg/report/testdata/linux/report/703
It was initially proposed in
https://github.com/google/syzkaller/issues/1575 that KMSAN reports with the same origin should be clustered together using an alt title.
This however turns out to be too aggressive: certain KMSAN reports have their uninitialized values originating from common functions - this leads to too many KMSAN reports being glued together. Because KMSAN reports can be also clustered with KASAN reports or other kernel panics, ultimately seemingly unrelated crashes are considered similar just because they share their top frames with two KMSAN reports that, in turn, share the same origin.
The resulting issues on the dashboard look confusing to the users, they are hard to find and require manual untangling, which probably outweighs the benefits of having KMSAN issues with …
=> pkg/report: drop "ALT: KMSAN origin" titles for uninit reports

dashboard/dashapi/dashapi.go, tools/syz-lore/query_lkml.go
Make the tool more flexible by supporting two modes of operation:
1) The already existing mode -- upload the results to dashboard.
2) The local mode -- save parsed LKML discussions as JSON files.
=> tools/syz-lore: save discussions as JSON files

sys/linux/filesystem.txt
Handle b62e71be2110 ("f2fs: support errors=remount-ro|continue|panic mountoption")
=> sys/linux/filesystem: Add f2fs errors=remount-ro|continue|panic mount option

dashboard/app/email_test.go, dashboard/app/reporting_email.go
Use the existing email title parsing mechanism that supports a much wider range of title prefixes. Add a test.
=> dashboard: support subsystems in titles for #syz dup

dashboard/app/jobs.go, dashboard/app/jobs_test.go, dashboard/app/reporting_email.go, docs/syzbot.md, pkg/email/parser.go, pkg/email/parser_test.go
We used to support this only for external reportings, but let's auto-guess repo and branch parameters for all incoming patch testing commands.
=> dashboard: auto-guess repo and branch for email-sent `#syz test`

pkg/bisect/bisect.go
I couldn't manage to add "pkg/bisect.env.log" to
"govet"."settings"."printf"."funcs", so let's use another way suggested by govet documentation.
Fix one instance of invalid arguments.
=> pkg/bisect: validate log() arguments

pkg/subsystem/linux/names.go
The new mailing list can be parsed by the generic algorithm.
=> pkg/subsystem: remove gfs2 from name exceptions

syz-ci/jobs.go
The "devlink: bump the instance index directly when iterating" commit has already appeared in too many invalid fix bisection results.
=> syz-ci: ignore one more bisection result

dashboard/app/reporting_external.go
Currently 2 lines emit the same error message.
Lets add more details to distinguish them.
=> dashboard/app/reporting_external.go: rephrase error message

.github/workflows/oss-fuzz.yml
Fix compilation error and make other improvements:
* Only upload crash on run fail, not build fail
* Enable SARIF notification. Fixes: https://github.com/google/oss-fuzz/issues/10989
=> oss-fuzz.yml: Fix compilation error

pkg/compiler/types.go, prog/any.go, prog/prog.go, prog/validation.go
Currently, we override it to `DirIn`. At the same time, if other calls continue using the resource, it should actually be `DirInOut`.
`Reported-by: John Miller <jm3228520@gmail.com>`
=> prog: preserve resource arg direction during squashing 

dashboard/app/app.yaml
We're still seeing "Exceeded soft memory limit" errors. Let's move to a higher instance class, now with the 512M limit.
=> dashboard: switch to the f4 instance class

tools/create-buildroot-image.sh
The newly built image resolves the following problem:
debug1: Sending subsystem: sftp
debug1: pledge: fork
subsystem request failed on channel 0
Also, ext2->ext4 transition allows to fuzz swap on arm32.
----
It didn't work earlier, but this time it for some reason worked locally. I've deployed the new image to syzbot, let's see how it goes.
=> tools: build a new ext4 image for arm32

vm/gce/gce.go
GCE has begun to fail on arm64 instance creation with: Arm based instances do not support display device.
Enable the feature for amd64 only.
=> vm/gce: only enable DisplayDevice for amd64

CONTRIBUTORS, sys/linux/dev_infiniband_rdma.txt
Currently, the descriptions for  `write$REREG_MR` and `write$DEREG_MR` use the wrong structs as arguments.
=> sys/linux: fix infiniband syzlang description

sys/linux/bpf.txt
`func_info` and `line_info` are both optional and should be marked as such.
Fixes: 934bb8cadebb57 ("modify")
=> sys/linux: mark optional BPF_PROG_LOAD arguments as opt

executor/common_zlib.h, pkg/csource/generated.go
The `mmap` size is `max_destlen`, but `munmap` size is `destlen`, which causes a memory leak.
=> executor/common_zlib: fix an mmap leak

pkg/compiler/attrs.go, pkg/compiler/check.go, pkg/compiler/testdata/errors.txt, pkg/compiler/testdata/errors2.txt, pkg/compiler/types.go, prog/validation.go
We had a problem -- ANYUNION being `(inout)` leads to syzkaller generating copyout instructions for fmt[X, resource] types. We get executor crashes and `pkg/csource` compilation errors.
Add a validation rule to detect such copyouts in syzkaller tests. Adjust `pkg/compiler` to fail on `fmt[X, resource]` not being `DirIn`.
Fix the problem with ANY types by supporting `(in)` for union fields. Previously, all union field direction attributes were banned as they were making things more complicated. But the (in) attribute is definitely safe and only allows for more flexibility.
=> pkg/compiler, prog: avoid copyout of fmt'ed resources

vm/gvisor/gvisor.go
There have been cases where gvisor ARM instances become inaccessible due to global OOMs, and it's possible that bounding memory usage per instance may help.
=> Apply memory limit to gVisor instances.

prog/resources.go, prog/resources_test.go, prog/types.go, sys/test/test.txt
First commit updates `getInputResources` to skip input resources that are optional. The third commit fixes a bug that could cause required input resources to be omitted. The second and fourth commits cover the other two in unit tests. See commit descriptions for details. 
Updates: https://github.com/google/syzkaller/issues/2721
=> prog: skip optional input resources

sys/syz-extract/fetch.go
```
Instead of an array of identifiers, we've been constructing an array of identifier + ast.Pos.
Reported-by: Damiano Melotti<damianomelotti97@gmail.com>
```
=> sys/syz-extract: fix a C code generation bug

dashboard/app/access.go, dashboard/app/access_test.go, dashboard/app/admin.go, dashboard/app/api.go, dashboard/app/app_test.go, dashboard/app/asset_storage.go, dashboard/app/asset_storage_test.go, dashboard/app/bisect_test.go, dashboard/app/cache.go, dashboard/app/config.go, dashboard/app/email_test.go, dashboard/app/entities.go, dashboard/app/graphs.go, dashboard/app/handler.go, dashboard/app/jobs.go, dashboard/app/jobs_test.go, dashboard/app/kcidb.go, dashboard/app/label.go, dashboard/app/main.go, dashboard/app/main_test.go, dashboard/app/notifications_test.go, dashboard/app/reporting.go, dashboard/app/reporting_email.go, dashboard/app/reporting_lists.go, dashboard/app/reporting_test.go, dashboard/app/subsystem.go, dashboard/app/subsystem_test.go, dashboard/app/tree.go, dashboard/app/tree_test.go, dashboard/app/util_test.go
We used to have a single global `config` variable and access it
throughout the whole dashboard application.
However, this approach has been more and more complicated test writing
-- sometimes we want the config to be only slightly different, so that
it's not worth it adding new namespaces, sometimes we have to test how
dashboard handles config changes over time.
This has already led to a number of hacky contextWithXXX methods that
mocked various parts of the global variable. The rest of the code had to
sometimes still use `config` directly and sometimes invoke getXXX(c)
methods. This is very inconsistent and prone to errors.
With more and more situations where we need to patch the config
appearing (see https://github.com/google/syzkaller/issues/4118), let's refactor the application to …
=> dashboard: access config through context

tools/docker/syzbot/Dockerfile
qemu 7.4 (default for bookworm) is not able to boot syzbot's arm64 MTE kernels.
Use qemu 8 from the backports instead.
=> tools/docker: upgrade qemu binaries

prog/encoding.go
This commit simply prints more information when failing to parse unions and structs in syzkaller programs. This is particularly useful when a syscall has multiple structs or unions (ex. for `bpf$PROG_LOAD`).
=> prog: more informative errors on parsing failures

syz-ci/jobs.go, syz-ci/manager.go, syz-ci/syz-ci.go
This is used to add a suffix to the kernel_src config field. This is used in Android where kernel source is under .../kernel/aosp/.
=> syz-ci: add kernel_src_suffix field to config

dashboard/app/jobs.go
Let's add the error itself to the message.
=> dashboard/app/jobs.go: add error details for throttling failure

dashboard/app/stats.go, pkg/stats/syzbotstats/bug.go
Export first crash time and fix commit hashes.
Calculate reporting time more precisely.
=> dashboard: export more stat data

dashboard/app/cron.yaml
It looks like the action is requiring more DB operations that we expected.
Do it less frequently until we've done profiling and optimized the code.
=> dashboard: do asset deprecation less frequently

pkg/report/freebsd.go
=> pkg/report/freebsd.go: nolint goconst for freebsdOopses

sys/syz-extract/linux.go
It contributes to #4285 unblocking.
=> sys/syz-extract/linux.go: remove dup include

dashboard/app/cache.go, dashboard/app/main.go
This is a relatively expensive operation (hundreds of ms) that queries
many types of entities. At the same time, the content does not change
that often.
Cache it for 5 minutes after querying.
=> dashboard: cache managers info on the main page

vm/starnix/starnix.go
After this change, the instance's `MonitorExecution` method runs concurrently with test program execution, as intended. Basic crash detection is working.
TODOs for follow-ups include:
- testing that crashes are repro'd and reports are generated
- restarting the vm after a crash
=> vm/starnix: don't block on syz-fuzzer command

dashboard/app/email_test.go, dashboard/app/jobs_test.go, dashboard/app/notifications_test.go, dashboard/app/reporting_email.go, dashboard/app/subsystem_test.go, dashboard/app/util_test.go
Instead of reminding users to mention our mailing lists, forward their emails there automatically.
Closes #4260.
=> dashboard: forward incoming commands emails

dashboard/app/cache.go, dashboard/app/config.go, dashboard/app/handler.go, dashboard/app/main_test.go, dashboard/app/util_test.go
To ensure service stability, let's rate limit incoming requests to our web endpoints.
=> dashboard: throttle incoming requests

dashboard/app/main.go
I don't think we'll benefit introducing constants for the URL parts. Let's mark as a false positive.
It contributes to #4317 unblocking.
=> dashboard/app/main.go: goconst complains /fixed

vm/vm_test.go
These duplicates improve test code readability.
It contributes to #4317 unblocking.
=> vm/vm_test.go: allow duplicates

tools/syz-linter/linter.go
This pull request address the following warning:
WARN plugin: 'AnalyzerPlugin' plugins are deprecated, please use
the new plugin signature:
https://golangci-lint.run/contributing/new-linters/#create-a-plugin
=> tools/syz-linter: fix golangci-lint plugin signature

syz-ci/updater.go
It contributes to #4317 unblocking.
=> syz-ci/updater.go: goconst complains on gopath=

vm/gvisor/gvisor.go
By default, gVisor is set fs.nr_open to the maximum. In this case, large allocations can be triggered in the Sentry and it can cause OOM-s on the test node.
=> vm/gvisor: set the fs.nr_open limit

prog/validation.go
Syz-executor fails if rerun > 0 && fail_nth > 0, but we don't do this check during prog validation.
It works fine when syzkaller runs as a standalone app (because it never generates such programs), but it can be a problem when receiving progs from other instances via syz-hub.
=> prog: validate call properties

syz-manager/hub.go, syz-manager/manager.go, syz-manager/rpc.go
If we received an invalid program from the fuzzer, log it as an error. It should never be happening under normal conditions.
Include the exact error text in log messages.
=> syz-manager: improve prog validation errors logging

dashboard/app/entities.go, dashboard/app/mail_subsystem.txt, dashboard/app/reporting_lists.go, dashboard/app/subsystem_test.go, dashboard/dashapi/dashapi.go
* Don't display low priority issues in monthly reports at all.
* Display the count of low priority bugs separately.
=> dashboard: change low-priority bugs reporting

syz-ci/updater.go
Trivial fix for an error message typo in syz-ci.
=> syz-ci: fix "build error fr" -> "build error for" typo

syz-ci/syz-ci.go, syz-ci/updater.go
By letting syz-ci just exit on update, we make it possible to also automatically pull the latest Docker container before starting the new version.
Fixes #2985
=> syz-ci: make auto-restart optional

docs/syscall_descriptions_syntax.md, pkg/compiler/check.go, pkg/compiler/compiler.go, pkg/compiler/consts.go, pkg/compiler/testdata/all.txt, pkg/compiler/testdata/errors.txt, pkg/compiler/testdata/errors2.txt, pkg/compiler/types.go, prog/encoding_test.go, sys/linux/bpf.txt, sys/test/test.txt
This pull request adds support for the following syntaxes:
int_flags = 1, 5, 8, 9
int32[int_flags]
int8[constant]
which is equivalent to:
int_flags = 1, 5, 8, 9
flags[int_flags, int32]
const[constant, int8]
The first two commits implement a bit of refactoring. The third and fourth add this support in the compiler. The fifth updates the documentation. The last commit uses this syntax in the BPF descriptions.
Fixes: https://github.com/google/syzkaller/issues/4269.
=> compiler: Unified const/flags definitions

dashboard/app/app.yaml, docs/linux/setup.md, tools/docker/env/Dockerfile, tools/docker/old-env/Dockerfile, tools/docker/syzbot/Dockerfile
https://tip.golang.org/doc/go1.21 will be the default one.
=> go: update to 1.21.4 everywhere and 1.20.11 in old-env

pkg/compiler/attrs.go, pkg/compiler/check.go, pkg/compiler/testdata/errors.txt, pkg/compiler/testdata/errors2.txt
This pull request adds a couple small test cases to cover error cases that I noticed weren't covered in `pkg/compiler/{check,compiler}.go`, according to Codecov. I then verified with the latest version of this pull request that all targeted cases are now covered.
=> compiler: increase test coverage

pkg/gce/gce.go
We seem to be getting more of ZONE_RESOURCE_POOL_EXHAUSTED_WITH_DETAILS errors rather than ZONE_RESOURCE_POOL_EXHAUSTED.
Let's support both.
=> pkg/gce: recognize more pool exhausted errors

dashboard/app/app_test.go, dashboard/app/reporting_lists.go, dashboard/app/subsystem_test.go
Currently we count all publicly visible bugs, which can get confusing now that we keep KCSAN bugs in public moderation. Only consider the reporting stage at which we generate the report.
This is tested in TestPeriodicSubsystemReminders().
=> dashboard: only count last stage bugs in monthly reports

CONTRIBUTORS, tools/docker/syzbot/Dockerfile
gVisor relies on eBPF since the following 2 commits, so libbpf-dev is required when building:
- https://github.com/google/gvisor/commit/2ae19ffb
- https://github.com/google/gvisor/commit/f6d380ad
Without this change, syzkaller can't build gVisor and gets the following error:
tools/xdp/cmd/bpf/redirect_host.ebpf.c:15:10: fatal error: 'bpf/bpf_endian.h' file not found
FAILED: Build did NOT complete successfully
=> tools/docker/syzbot: add libbpf-dev to Dockerfile

executor/common_linux.h, pkg/csource/generated.go, pkg/host/syscalls_linux.go, sys/linux/sys.txt, sys/targets/targets.go
This kernel interface provides access to fds of other processes, which is readily abused by the fuzzer to mangle parent syz-executor fds.
Pid=1 is the parent syz-executor process when PID namespace is created. Sanitize it in the new syz_pidfd_open() pseudo-syscall.
We could not patch the argument in `sys/linux/init.go` because the first argument is a resource.
=> executor: introduce syz_pidfd_open()

AUTHORS, CONTRIBUTORS, executor/test_linux.h
As discussed on the mailing list (see Link), the executor unit tests fail on some newer hardware, probably due to SVM virtualization not supporting older VMX virtualization features. So, we disable the tests for that. Before touching the file, we made the style checker happy. And afterwards, we add Piotr as contributor and Elektrobit as copyright holder.
Link: https://groups.google.com/g/syzkaller/c/jmb8Pt8qdQg
=> Selectively disable executor unit tests for hardware with SVM virtualization

syz-ci/manager_test.go
It uses randomization, so let's make more iterations.
=> syz-ci: make the TestManagerPollCommits() test not flaky

syz-manager/manager.go
There have been cases of `fail_nth>0` programs sneaking into the corpus.
Validate and drop such programs in `syz-fuzzer`.
Panic on `syz-fuzzer` attempts to report such a program to `syz-manager`.
=> syz-fuzzer: prevent fail_nth>0 programs from reaching corpus

prog/analysis.go
Per profiling, (*GroupArg).Size() calls from this function were one of the hottest paths during the BenchmarkMutate() benchmark.
Some of those calls are made only to issue a runtime panic, which we arguably don't need unless we're testing the code.
After the changes:
```
│ /tmp/original │              /tmp/new               │
│    sec/op     │   sec/op     vs base                │
Mutate-36     221.8µ ± 4%   179.0µ ± 3%  -19.31% (p=0.000 n=15)
```
=> prog: optimize foreachArgImpl()

sys/linux/vnet.txt
Double tagging is used in 802.1ad, which is identified by TPID=0x88a8. We were using an incorrect const.
=> sys/linux: fix vlang double tag const

executor/common_linux.h, executor/executor.cc, pkg/csource/generated.go
During fuzzing, it's expected that certain operations might return errors. Don't abort the whole syz-executor process in this case, this is too expensive.
=> syz-executor: don't fail on netlink errors during fuzzing

pkg/ipc/ipc.go, syz-fuzzer/fuzzer.go, syz-fuzzer/proc.go
Minor optimizations that significantly speed up the corpus triage stage and kernel fuzzing overall. More details are in commit descriptions.
* On a local qemu-based instance, the corpus triage speed is ~66% higher than it was.
* Fuzzing on GCE is ~27% faster than it was. Looks like there are also other bottlenecks there that still need to be found.
=> syz-fuzzer: assorted optimizations

dashboard/app/app_test.go, dashboard/app/reporting.go, dashboard/app/reporting_test.go
Fix a bug in the reporting of bugs with revoked reproducers. Add a test that reproduces the problematic situation.
Also, ensure that we don't include the revoked reproducer into the report we send to the next reporting stage.
Cc #4412.
=> dashboard: prevent infinite reporting of revoked repros

dashboard/app/app_test.go, dashboard/app/reporting.go, dashboard/app/reporting_test.go
A recent failure (#4412) could have been more constrained if our reproducer emails were included in our daily limits. Let's change that.
=> dashboard: include repro messages into daily limits

dashboard/app/admin.html, dashboard/app/api.go, dashboard/app/api_test.go, dashboard/app/entities.go, dashboard/app/main.go, dashboard/app/reporting_email.go, dashboard/app/reporting_external.go, pkg/html/pages/style.css
Add an emergency stop button that can be used by any admin. After it's clicked two times, syzbot stops all reporting and recoding of new bugs.
It's assumed that the stop mode is revoked by manually deleting an entry from the database.
Cc #4412
=> dashboard: introduce an emergency stop mode

syz-fuzzer/fuzzer.go, vm/qemu/qemu.go, vm/vmimpl/console.go, vm/vmimpl/vmimpl.go
* Expose a pprof endpoint from syz-fuzzer.
* Optionally forward the pprof port for qemu instances.
=> all: support pprof in syz-fuzzer

dashboard/app/asset_storage.go, dashboard/app/main.go, dashboard/app/reporting.go
There's no sense to restrict the list of build assets there.
=> dashboard: show coverage reports in per manager pages

prog/rand.go, prog/resources.go, prog/resources_test.go, prog/target.go, prog/types.go, sys/test/test.txt
During resource argument generation, we used to randomly select one of the matching resources. With so many descendants of fd, this becomes quite inefficient and most of the time syzkaller fails to build correct programs.
Give precise resource contructions priority. Experiment with other resource types only in 1/3 of cases.
=> prog: prefer precise constructors
