docs/gvisor/README.md, pkg/cover/backend/gvisor.go, pkg/cover/backend/gvisor_test.go
We have multiple file path representations now.
+ tests to cover all 3 scenarios
=> pkg/cover/backend/gvisor: relax parse regexp and add gvisor_test.go

docs/fuchsia/README.md
Fuchsia has not been properly supported for a while now, and the
documentation suggesting so has been a source of confusion. This updates
the README to add a caveat, while also doing some minor cleanup in the
process.
For more context, see https://fxbug.dev/101134.
=> docs/fuchsia: add caveat to Fuchsia readme

.github/workflows/ci.yml
Lets test self-hosted builder.
Builder is currently deployed, but additional configuration may be needed.
=> .github/workflows/ci.yml: add self-hosted builder

docs/fuchsia/README.md, docs/fuchsia/setup.sh
Also enhance the README.md somewhat.
=> docs/fuchsia: partially automate the setup process

.github/CODEOWNERS
We don't have user "@dean-deng".
=> .github/CODEOWNERS

docs/fuchsia/setup.sh
See https://bugs.fuchsia.dev/p/fuchsia/issues/detail?id=106099.
=> docs/fuchsia: make --debug optional

prog/rotation.go, prog/rotation_test.go
- prog: fix Rotator determinism
- prog: make TestRotationCoverage test more robust
=> dvyukov rotation test

sys/fuchsia/misc.txt, sys/fuchsia/sys.txt, sys/fuchsia/time.txt
Adds `ticks_get_via_kernel` and moves some from other files into misc.txt.
=> sys/fuchsia: update misc system calls

sys/fuchsia/task.txt
=> sys/fuchsia: update task system calls

sys/fuchsia/msi.txt
=> sys/fuchsia: fix msi syscall names

docs/syscall_descriptions_syntax.md
=> docs: fix syntax

sys/fuchsia/vcpu.txt
=> sys/fuchsia: update vcpu system calls

dashboard/app/index.yaml
This is required for the asset deprecation.
=> dashboard/app: add one more Bug index

pkg/asset/config.go, syz-ci/syz-ci.go
=> assorted fixes for asset storage

dashboard/app/jobs.go
Otherwise temporary errors might lead to revoke an otherwise still valid
reproducer.
=> dashboard: tolerate patch testing errors during repro retesting

dashboard/app/asset_storage.go, dashboard/app/main.go, pkg/asset/backend_gcs.go, pkg/asset/storage.go
=> all: minor asset storage changes

sys/fuchsia/event.txt, sys/fuchsia/eventpair.txt, sys/fuchsia/test/event, sys/fuchsia/test/eventpair
events.txt is split between event.txt and eventpair.txt
=> sys/fuchsia: update event and eventpair system calls

dashboard/app/jobs.go, dashboard/app/jobs_test.go
Branches and repo addresses for our tested kernels sometimes get changed over
time, that breaks repro retesting for some of our old repros.
Fix that behavior by retesting the repro not on the repo/branch on which
it was originally found, but on the ones from the latest successful
build for the corresponding syz-manager. Adjust tests.
Close #3341.
=> dashboard: retest repros on up-to-date branches

sys/openbsd/socket.txt, sys/openbsd/socket.txt.const
I recently added the recvmmsg system call to OpenBSD.
This should make it available for syzkaller.
=> add recvmmsg system call

sys/openbsd/socket.txt, sys/openbsd/socket.txt.const
=> sys/openbsd: add sendmmsg system call

dashboard/app/jobs.go, dashboard/app/jobs_test.go
We can test them even though there's no explicit reproducer.
=> dashboard: do patch testing for test errors

dashboard/config/openbsd/config.ci
=> dashboard/config: enable asset storage for OpenBSD

dashboard/app/jobs.go
This just wastes resources -- those bugs are marked as fixed on our dashboard anyway.
=> dashboard: don't retest repros for bugs with commits

executor/common_linux.h, pkg/csource/generated.go, sys/linux/socket_netlink_route.txt, sys/linux/socket_netlink_xfrm.txt
- executor: fix setup of xfrm device
- executor: fix setup of netdevsim device
=> executor: fix setup of net devices

syz-ci/manager.go
The existing rebuild check is not enough anyway -- as a result, we get build records in the DB that do not have any assets (e.g. the ones that appeared after syz-ci updated itself).
Instead do the upload unconditionally, now that we calculate hashes first and don't re-upload asset with the same hash, it's not a big problem.
=> syz-ci: always upload build assets

.github/CODEOWNERS, pkg/build/build.go, pkg/build/build_test.go, syz-ci/updater.go
- syz-ci: simplify code
- pkg/build: extract fuchsia build errors better
=> dvyukov fuchsia repair

docs/talks.md
=> docs: add two more talks from LPC'22

pkg/build/fuchsia.go
- pkg/build: fix fuchsia disk path
=> pkg/build: fix fuchsia disk path

pkg/config/config.go, pkg/mgrconfig/testdata/gce1.cfg
=> pkg/config: fix comments stripping

vm/cuttlefish/cuttlefish.go, vm/gce/gce.go
For Cuttlefish we want to read the console from the emulated device instead of the "host" GCE instance. This allows us to pass a custom command through to gce.Pool (and then to gce.instance) which is used instead.
We also need to update runOnHost() to use osutil directly instead of delegating to gceInst.Run(), since it's called during VM creation. When setting up the VM the kernel logs don't exist yet.
=> vm/cuttlefish, vm/gce: add custom commands for reading console

dashboard/app/asset_storage.go, dashboard/app/asset_storage_test.go
It's bad to deprecate them if there are no related crashes, because they may appear later.
Check if there are newer builds and only deprecate assets if there are. Add a test to check the new behavior.
=> dashboard: don't depreate assets of latest builds

pkg/cover/report_test.go
After merging #3409 the test case TestReportGenerator became flaky[0]. The problem is caused by our tests using the same 'Test' struct instance in multiple tests in parallel. Hence when overwriting test.Progs in one test run, another test run might be reading it at the same time.
[0] https://github.com/google/syzkaller/actions/runs/3198309451/jobs/5222669976
=> pkg/cover: mitigate datarace in generateReport

docs/fuchsia/setup.sh
For context, see fxbug.dev/110060
=> docs/fuchsia: look up Fuchsia dependency paths dynamically

sys/fuchsia/profile.txt
Recreating #3427 from a correct branch source.
=> sys/fuchsia: add the profile syscalls definitions

pkg/build/build.go, pkg/build/linux.go, sys/syz-extract/linux.go, syz-ci/manager.go, syz-ci/syz-ci.go, tools/syz-build/build.go
Otherwise we cannot use clang + ld.lld in syz-ci.
=> pkg/build,syz-ci: add support for custom linker

pkg/host/machine_info_linux_test.go
Default maxTokenSize is 64k.
On 128 cores, I experienced 120k long token (len(flags * 128)).
=> pkg/host: increase token size to enable 128+core CPUs

tools/docker/syzbot/Dockerfile
Now that we have the ability to specify the linker, make it possible to choose between ld and ld.lld.
=> tools/docker: add ld.lld to syzbot

vm/cuttlefish/cuttlefish.go
The current refactor does not return vmimpl.ErrTimeout() when a timeout occurs.
The error handling has been changed to parse the return string for the "timedout after" from osutil.RunCmd().
=> vm/cuttlefish: ignore timeout in Forward()

pkg/report/linux.go, pkg/report/testdata/linux/report/543, pkg/report/testdata/linux/report/665, pkg/report/testdata/linux/report/666, pkg/report/testdata/linux/report/667, pkg/report/testdata/linux/report/668, pkg/report/testdata/linux/report/669
- pkg/report: add some "inconsistent lock state" samples
- pkg/report: parse stack in "inconsistent lock state" reports
=> pkg/report: improve "inconsistent lock state" parsing

executor/executor_fuchsia.h
Needed since https://github.com/google/syzkaller/commit/2c6621289f027c498f3a06f8e9dc2ded7c5ea8dd.
=> executor: include sys/mman.h

executor/common.h, executor/common_ext.h, executor/common_ext_example.h, executor/common_ext_test.go, pkg/csource/build.go, pkg/csource/csource_test.go, pkg/csource/generated.go
- executor: test extension points
- executor: add setup_ext_test extension point
=> dvyukov executor ext

pkg/build/android.go
The directories the Android build scripts write to are controlled by environment variables. This defines the OUT_DIR variable so that we can get the .config file and copy it to the output directory.
This should improve Cuttlefish fuzzing in the short term while we figure out how to do the build the right way with syz-kconf.
=> pkg/build: add kernel config to output dir for android

.github/CODEOWNERS
=> .github: update CODEOWNERS for fuchsia

prog/heatmap.go, prog/heatmap_test.go, prog/mutation.go
- prog: refactor HeatMap
- prog: adjust number of image mutations
=> dvyukov heatmap size

tools/syz-db/syz-db.go
Allows to merge additional corpus or programs into an existing corpus file.
=> tools/syz-db: add merge command

pkg/email/parser.go, pkg/email/patch.go, pkg/email/patch_test.go
Currently the function returns the values that are not being used anywhere. Refactor it.
=> pkg/email: refactor ParsePatch

dashboard/app/api.go, dashboard/app/app_test.go, dashboard/app/entities.go, dashboard/app/jobs.go, dashboard/app/main.go, dashboard/app/reporting.go, dashboard/app/reporting_test.go, dashboard/app/util_test.go, dashboard/dashapi/dashapi.go
* Introduce the `/load_full_bug` API to query more information about a bug: several representative crashes, similar bugs and bisection info.
* Make it possible to report and unreport several crashes for each reporting stage.
* Various code refactorings.
=> dashboard: assorted bug reporting improvements

pkg/html/html.go
This will simplify the creation of git links in templates.
=> pkg/html: add a commitLink template function

dashboard/app/api.go, pkg/email/parser.go, pkg/runtest/run.go, tools/syz-linter/linter.go, tools/syz-linter/testdata/src/lintertest/lintertest.go, vm/proxyapp/proxyappclient.go
- all: fix duplicate parameter types
- tools/syz-linter: improve duplicate parameter type detection
=> tools/syz-linter: improve duplicate parameter type detection

pkg/cover/html.go
Fix /rawcoverfiles missing argument.
=> pkg/cover: add frame.EndLine in DoRawCoverFiles()

.github/workflows/ci.yml, dashboard/app/jobs_test.go, dashboard/app/util_test.go
=> dashboard: prevent hangs during testing

dashboard/app/admin.go
Sometimes bisections massively fail due to a problem in the bug bisection code / config. Add a code to reset all failed bisections in the specified namespace.
=> dashboard: add an admin function to restart failed bisections

tools/docker/README.md
Now that it's multi-arch, it's somewhat more complicated.
=> tools/docker: describe the syzbot container build process

dashboard/app/jobs.go, dashboard/app/jobs_test.go, dashboard/app/main.go
=> dashboard: fix repro retesting for decommissioned managers

README.md, docs/starnix/README.md, executor/common_linux.h, executor/executor_linux.h, pkg/csource/generated.go, pkg/osutil/osutil.go, pkg/report/report.go, sys/targets/targets.go, vm/starnix/starnix.go, vm/vm.go, vm/vmimpl/vmimpl.go
Added a new VM for fuzzing starnix. This VM will boot a fuchsia image using the `ffx` tool and will connect to an adb server inside it. Fuzzing will be done using `HostFuzzer` mode due to some features not being implemented yet in starnix. Once this is possible, fuzzing will be performed without `HostFuzzer` mode.
=> vm/starnix: add support for fuzzing starnix

pkg/report/linux.go, pkg/report/testdata/linux/report/683, pkg/report/testdata/linux/report/684, pkg/report/testdata/linux/report/685
=> pkg/report: detect custom VFS errors

sys/targets/targets.go
If a syz-ci is run on multiple arches, it's useful to be able to use the same set of env variables. For this to become possible, make SOURCEDIR_ configuration more granular.
Earlier it was just SOURCEDIR or SOURCEDIR_{TargetOS}. Support also the SOUREDIR_{TargetOS}_{TargetArch}_{HostOS}_{HostArch} variable.
=> sys/targets: make the SOURCEDIR setting more granular

pkg/build/freebsd.go
Continue digging into syzbot's FreeBSD failures: the buildkernel step looks like it's failing because it's using the host compiler, which is too old and doesn't support KASAN.  We *should* be populating the objdir with a toolchain in the earlier make step, though.  So let's include both kernel-toolchain and buildkernel output in error messages and see if that helps expose what's happening.
=> pkg/build: include all build output in FreeBSD buildkernel errors

tools/docker/env/Dockerfile, tools/docker/syzbot/Dockerfile
This is a prerequisite for building KMSAN-instrumented kernels.
=> tools/docker: switch to Clang 15

dashboard/app/api.go, dashboard/app/entities.go, dashboard/app/handler.go, dashboard/app/main.go, dashboard/app/main_test.go, dashboard/app/templates.html, dashboard/app/util_test.go, pkg/html/html.go, pkg/html/pages/style.css
* Augment the bug list by the bug subsystems. Both on the main page and on the bug terminal pages.
* Apply some test infastructure refactorings that simplify the implementation and testing for the code changes of this PR.
=> dashboard: filter by bug subsystems and display them

syz-ci/jobs.go
=> syz-ci: minor job-related changes

pkg/cover/report_test.go, sys/targets/targets.go
=> Extra compiler flags needed to switch to Clang 15

sys/targets/targets.go
The behavior of certain flags (in particular link-time ones) may depend on the target triple and other compiler options, therefore it's insufficient to test them in the default host configuration.
Collect all non-optional flags and pass them to checkFlagSupported(), so that support for optional flags is always tested in the presence of the non-optional ones.
This is going to fix the problem with Clang 15 not supporting -static-pie on MIPS, but silently passing the checkFlagSupported() check, because it used to be performed on x86_64. …
=> sys/targets: use non-optional flags to test for optional flags

pkg/report/linux.go, pkg/report/report.go, pkg/report/report_test.go, pkg/report/testdata/linux/guilty_raw/0, tools/syz-fillreports/fillreports.go
=> tools/syz-fillreports: fix bug update and guilty file extraction

pkg/report/linux.go, pkg/report/testdata/linux/report/687
This frame also distributes work to other functions.
=> RFC: pkg/report: anchor at netlink_dump frame

pkg/report/linux.go, pkg/report/testdata/linux/report/688
Let's merge this commit from #3666 separately.
=> pkg/report: improve rcu stall parsing on arm64

pkg/build/android.go
Added functionality to build with bazel instead of 'build.sh', as 'build.sh' is being depreciated.
Checks the branch information from 'build.config.constants' file and uses Bazel for android14+.
=> pkg/build: added bazel build for android

dashboard/app/cron.yaml, dashboard/app/subsystem.go, pkg/subsystem/service.go, tools/syz-fillreports/fillreports.go
=> all: minor subsystem-related fixes

pkg/subsystem/linux/names.go, pkg/subsystem/linux/rules.go, pkg/subsystem/lists/linux.go
There were cases when subsystems did not get reasonable enough names.
=> pkg/subsystem: improve naming rules

dashboard/app/main.html
Don't hide the managers list in this case.
=> dashboard: display managers if we filter by managers

dashboard/app/subsystems.html
Fix a bug in the sort function call arguments.
=> dashboard: sort subsystems table by Open bugs

prog/prio.go
Adds comments about how choice table runs values are populated based on information from dynamic and static priorities.
=> prog: add comments about choicetable

dashboard/app/config.go, dashboard/app/handler.go, dashboard/app/main.go, dashboard/app/subsystems.html, dashboard/app/templates.html, pkg/html/pages/style.css
=> dashboard: assorted UI improvements

dashboard/app/access.go, dashboard/app/handler.go
=> dashboard: minor unauthorized access logging changes

dashboard/app/bug.html, dashboard/app/main.go, dashboard/app/subsystem_page.html, dashboard/app/subsystems.html
=> dashboard: minor ux changes for subsystems

dashboard/app/main.go
Do all the memcache and DB queries in parallel in order to reduce the latency.
=> dashboard: speed up the admin page

tools/docker/syzbot/Dockerfile
Fixes internal bug b/266305387
=> tools/docker: use pahole v1.22 from backports

dashboard/app/reporting_lists.go
=> dashboard: assorted fixes for bug lists reporting

dashboard/app/mail_subsystem.txt, dashboard/app/reporting_email.go, dashboard/app/subsystem_test.go
=> dashboard: assorted subsystem report fixes (2)

docs/linux/setup_ubuntu-host_qemu-vm_x86-64-kernel.md
Recommend CONFIG_DEBUG_INFO_DWARF4 (syzkaller doesn't work with DWARF5) and bump the kernel version.
=> docs: minor updates to setup_ubuntu-host_qemu-vm_x86-64-kernel.md

dashboard/app/reporting_lists.go, dashboard/app/subsystem_test.go
=> dashboard: display the correct bug number in subsystem reports

dashboard/app/main.go, pkg/subsystem/linux/rules.go, pkg/subsystem/lists/linux.go
We currently generate incorrect links in the list of similar bugs and in the list of bugs on a subsystem's page.
=> dashboard: fix subsystem link generation

dashboard/app/subsystem.go
It will help evaluate the results of bug inference logic updates.
=> dashboard: log subsystem changes

pkg/report/linux.go, pkg/report/testdata/linux/guilty/64, pkg/report/testdata/linux/report/693
=> pkg/report: ignore mm/folio-compat.c and (un)lock_page

pkg/subsystem/extractor.go, pkg/subsystem/lists/linux_test.go
Done after looking at false positives on the syzbot dashboard. Let's see if these changes make the situation better.
See individual commit descriptions for details.
=> pkg/subsystem: improve inference

dashboard/app/admin.go, dashboard/app/api.go, dashboard/app/discussion.go, pkg/email/patch.go
These commits are addressing minor problems that arised during the deployment of https://github.com/google/syzkaller/pull/3773
=> all: misc discussion-related fixes

dashboard/app/bug.html, dashboard/app/main.go, dashboard/app/templates.html, pkg/html/pages/common.js, pkg/html/pages/style.css
1) Display fix and cause bisection info side by side.
2) Display information in collapsible blocks.
=> dashboard: bug page UX improvements

docs/research.md
adds reference to https://github.com/cmu-pasta/linux-kernel-enriched-corpus
=>  docs: add Enriched corpus reference

dashboard/app/main.go
=> dashboard: minor UI improvements

pkg/compiler/consts.go, pkg/csource/csource.go, sys/syz-sysgen/sysgen.go, sys/targets/targets.go
=> pkg/csource: introduce more structure into emitCallBody

vm/vmm/vmm.go
The flags now must precede the VM id. The IP address can no longer be determined by looking at the VM output which was previously possible due to dhclient printing it. Now that we don't have dhclient we instead look up the VM id in `vmctl status` output and the VM IP uses a fixed pattern.
With the two changes I can run `syz-manager` and it gets far enough to report missing coverage.
=> vm/vmm: adapt to recent vmctl changes

syz-verifier/execresult_test.go
Instead of parallel tests we were running last test len(tests) times.
=> syz-verifier/execresult_test.go: fix loop variable misuse

dashboard/config/openbsd/recreate.sh, tools/create-openbsd-gce-ci.sh
https://github.com/google/syzkaller/blob/master/docs/setup_syzbot.md
=> tools: switch to approved syz-ci buliding recipe

dashboard/app/api.go, dashboard/app/bug.html, dashboard/app/main.go, dashboard/app/subsystem.go, pkg/subsystem/extractor.go
For bugs without manually assignment subsystems, let admins request a trace of automatic subsystem assignment for the bug.
=> dashboard: debug subsystem assignment

sys/syz-extract/extract.go
If syz-extract is executed with explicit file list and some of these
files have meta tags that exclude them from processing for an arch,
currently it leads to "const info for input file is missing" error.
Check meta tags even for explicit file list.
=> sys/syz-extract: fix meta checking when using explicit file list

dashboard/app/main.go
We need more details for root cause analysis.
=> dashboard/app/main.go: return 4xx, not 5xx for bad request

syz-ci/jobs.go, syz-ci/manager.go, syz-ci/syz-ci.go
1) Set the name of the instace to improve log analysis.
2) Use log.Errorf for errors that deserve human attention (not for everything, just for some so far in order to get us going).
=> syz-ci: improve logging

pkg/report/linux.go, pkg/report/testdata/linux/report/695
See https://syzkaller.appspot.com/bug?id=88b03615bcf53f3cdc9b987ad26207a9b8d47d8f
=> pkg/report: ignore arm64 fault handling

tools/syz-hubtool/hubtool.go
Support not only a single corpus file, but also a glob pattern for corpus programs.
=> tools/syz-hubtool: support glob pattern for corpus progs

dashboard/app/main.go, dashboard/app/reporting.go, dashboard/app/reporting_email.go, dashboard/app/stats.go
=> dashboard: assorted logging improvements

dashboard/app/main.go, pkg/html/pages/style.css
=> dashboard: minor UI changes

dashboard/app/bisect_test.go, dashboard/app/jobs.go, dashboard/app/reporting.go, dashboard/app/util_test.go
=> dashboard: preserve Bug modifications in doneJob

dashboard/app/tree.go
Not all bugs will get the C repro.
=> dashboard: do tree origin testing also with syz repros

dashboard/app/tree.go
There's no need to query the same entity twice, it was done just for convenience. It might also contribute to the `too much contention on these datastore entities` error (see https://github.com/google/syzkaller/issues/3917).
=> dashboard: don't load Build twice for tree origin jobs

dashboard/app/admin.go, dashboard/app/entities.go, dashboard/app/jobs.go, dashboard/dashapi/dashapi.go
=> dashboard: restore bisection flags display

dashboard/app/reporting.go, dashboard/app/tree_test.go, dashboard/dashapi/dashapi.go
=> dashboard: include tree origin jobs into full bug info

dashboard/app/jobs.go
Query bugs for all related syz-managers, but deduplicate the results after that.
It should lead to fewer examined bugs and, hopefully, to fewer CONCURRENT_TRANSACTION errors.
Cc https://github.com/google/syzkaller/issues/3917
=> dashboard: optimize patch test job generation

docs/linux/setup_linux-host_qemu-vm_arm64-kernel.md
Fixes https://github.com/google/syzkaller/issues/3937
=> docs/linux/qemu: fix the link to ARM64 toolchain

pkg/report/linux.go, pkg/report/testdata/linux/report/698
See https://syzkaller.appspot.com/bug?extid=d8fc21bfa138a5ae916d
=> pkg/report: ignore crc_itu_t

tools/syz-bisect/bisect.go
This was one of https://github.com/google/syzkaller/pull/3952  commits.
=> tools/syz-bisect: support Linker parameter

executor/common.h, executor/executor.cc, pkg/csource/generated.go
It makes these extentions much more flexible as they can now also customize what other features set up.
=> executor: move setup_ext() below other features

pkg/ipc/ipc.go
This can happen when c.cmd.Wait returns an error.
=> ipc: handle a case when c.cmd.ProcessState is nil

pkg/vcs/git.go
We are currently seeing errors that there are "untracked working tree files which would be overrwritten by checkout".
This error occurs when files of the same path differ between branches, regardless of whether the repository is clean or not.
Forcing FETCH_HEAD checkout, then moving repair() to after checkout to clean repository to the current checkout.
Additionally, added a second "force" to git clean to clean directories with '.git' subdirectories.
=> pkg/vcs: force git branch checkout

dashboard/app/getjson_test.go, dashboard/app/main.go, dashboard/app/public_json_api.go
Let's export bugs list as a json.
=> dashboard/app: export buglist pages as json

dashboard/app/main.go
3/6 fields on uiCommit currently used
=> dashboard/app: merge dashapi.Commit and uiCommit

pkg/report/linux.go, pkg/report/testdata/linux/report/704
Reference: https://syzkaller.appspot.com/bug?extid=c370a63abf53498ae3e2
=> pkg/report: skip more lib/xarray.h and mm/filemap.c functions

pkg/repro/repro.go
In the current code, there's a possibility that we write to ctx.bootRequests after it was quickly closed. That could happen when we immediately abort the reproduction process after it's started.
To avoid this, don't send elements over the bootRequests channel in the createInstances() function.
Hopefully closes #4016.
=> pkg/report: request VMs outside of createInstances()

dashboard/app/jobs.go, dashboard/app/main.go, dashboard/app/reporting.go
This change is necessary for further cross-tree bisections work. Right now there are only automatically initiated bisections, so we can take the latest one and show it. Later, there'll be both bisections on the bug's tree and on other trees, and we'll need to filter them out. This PR makes such filtering possible.
---
Query all bisection jobs for a bug and then explicitly pick the most suitable one for display on the bug page / sending a notification.
Don't take a manually invalidated job while filtering. Later we'll also skip all cross tree bisections to only leave the result worth displaying to the user.
As a side effect of the changes, display cause/fix bisection history if there's been more than 1 attempt.
=> dashboard: refactor bisection job querying

pkg/vcs/linux_patches.go
So far we don't really need it.
There's also a problem that we only find commits within a certain time frame (5 years fro, now), so for old-introduced problems we cannot reliably determine their presence.
It does not seem to be worth it to re-write the GetCommitsByTitles logic now.
=> pkg/vcs: remove the check for the guilty commit

.github/workflows/ci.yml
It is needed to know the "docker pull gcr.io/syzkaller/env" cost.
=> ci.yml: pull syz-env separately

.github/workflows/closestale.yaml
The problem are inactive PRs.
As a first step, let's mark stale PRs.
We can autoclose them as a next step.
=> closestale.yaml: notify about stale PRs

dashboard/app/jobs.go
The only significant difference is what Bug's field should be cleared up.
=> dashboard: support cross tree origin job retrying

tools/docker/syzbot/Dockerfile
These are required for building linux with LLVM=1.
=> tools/docker: install llvm package and add some tools to path

pkg/vcs/linux_patches.go, pkg/vcs/linux_patches_test.go
=> pkg/vcs: make backport configs more elaborate

dashboard/app/templates.html
Distinguish them from normal fix bisections.
=> dashboard/app: mark fix candidate jobs in job lists

dashboard/config/openbsd/recreate.sh
Let's spread the load more evenly.
=> dashboard/config: move OpenBSD to us-central1-b

pkg/mgrconfig/config.go
=> pkg/mgrconfig: fix a typo

pkg/host/features_linux.go
The first attempt to tackle the problem: https://github.com/google/syzkaller/pull/3985
This PR uses a different approach.
---
Test the filesystem for the `fallocate` support. It's cheaper than having to manually zero-write the whole swap file, which can be quite slow on emulated VMs.
As testing /tmp does not make much sense (it can be a totally different filesystem), create a temp file directy in the user home directory.
=> pkg/host: require fallocate for swap

dashboard/app/reporting.go, dashboard/app/reporting_test.go
Rely on the Poisson distribution to determine the moment when we should give on a bug.
We don't have to wait 100x the average time between the crashes.
=> dashboard/app: calculate obsoletion periods differently

dashboard/app/graphs.go
Currently we remove all invalidated and deduplicated bugs, which skews the graph over time - many of the currently open bugs will be invalidated, too, and disappear from the graph later.
Let's be more historically correct and display the actual number of open bugs at every moment in history.
=> dashboard: display historically open bugs in Kernel Health

dashboard/app/bug.html, dashboard/app/main.go, docs/syzbot.md
=> dashboard: improve labels UX

dashboard/app/api.go, dashboard/app/entities.go, dashboard/app/main.go, dashboard/app/repro_test.go, dashboard/dashapi/dashapi.go, syz-manager/manager.go
This will help analyze reasons for bug reproduction failures.
This commit does not include visual display of the results, it will follow later.
=> dashboard: remember failed repro logs

dashboard/app/bug.html, dashboard/app/main.go, dashboard/app/templates.html
=> dashboard: display failed bug repro attempts

pkg/report/linux.go, pkg/report/testdata/linux/report/709
=> Kmsan strstr

sys/linux/sys.txt, sys/linux/sys.txt.const
Handle torvalds/linux@cf264e1329fb ("cachestat: implement cachestat syscall")
=> sys/linux: add cachestat description

pkg/repro/repro.go, syz-manager/manager.go
=> syz-manager: improve bug repro logging

tools/syz-fmt/syz-fmt.go
Introduce the `--dry-run` mode to enable syz-fmt use for description validation only.
=> tools/syz-fmt: support --dry-run mode

vm/gce/gce.go
We've been seeing an increase in "failed to init gce" errors on syzbot. These problems seem totally transient, so let's address it by retrying the initialization one more time instead of aborting syz-manager's execution.
=> vm/gce: try gce init twice

tools/create-openbsd-gce-ci.sh
This should fix the image build problem.
=> tools/openbsd: explicitly require llvm-13 to avoid ambiguity

dashboard/app/jobs.go
We currently query all finished non-reported Jobs every reporting_poll_bugs request.
That's very slow and inefficient -- there are more than 50k of such jobs.
In reality, we are never interested in reporting old jobs, so let's only query jobs finished within last month. That's only a few thousands jobs.
=> dashboard/app: optimize pollCompletedJobs()

dashboard/app/email_test.go, dashboard/app/jobs_test.go
=> dashboard/app: deduplicate syz test string

dashboard/app/access_test.go
It contributes to #4285 unblocking.
=> dashboard/app/aceess_test.go: disable goconst for TestAccess

pkg/csource/options.go
It contributes to #4285 unblocking.
=> pkg/csource/options.go: refactor deserializeLegacyFormats

dashboard/app/asset_storage_test.go, dashboard/app/bisect_test.go, dashboard/app/email_test.go, dashboard/app/mail_bug.txt, dashboard/app/subsystems.html
=> dashboard: use softer wordings

tools/syz-trace2syz/proggen/proggen.go, tools/syz-trace2syz/trace2syz.go
=> chore: remove refs to deprecated io/ioutil

dashboard/app/cache.go
At the peak times, concurrency at individual keys can be high.
Do the updates more carefully - if we denied the request and another instance did the same concurrently, there's no point in retrying the write. The object stored at the key already exceeds the limit.
=> dashboard: optimize throttling

docs/coverage.md
Replace --kernel_obj with --config
=> docs/coverage.md: replace --kernel_obj with --config

pkg/build/fuchsia.go
Addressinng goconst recommendation it contributes to #4317 unblocking
=> pkg/build/fuchsia.go: strings to const

vm/starnix/starnix.go
Two fixes for issues that were causing hangs during Close():
- Close our copy of the pipe end we pass to `ffx log`.
- Call `ffx` directly, not through the bash script trampoline that doesn't propagate kill signals to its children.
=> vm/starnix: prevent hangs during instance shutdown

pkg/report/linux.go, pkg/report/testdata/linux/report/710
These are just informative messages.
=> pkg/report: ignore CPU bug mitigation warnings

pkg/build/linux_test.go
It's prohibited by the Go testing library. Use T.Error() instead.
Cc #4315
Reported-by: Andrew Donnellan
=> pkg/build: don't use Fatal() inside goroutines

dashboard/app/asset_storage.go, dashboard/app/entities.go, dashboard/app/index.yaml, dashboard/app/main.go, dashboard/app/main_test.go, dashboard/app/manager.html, dashboard/app/templates.html
Display last 500 successful builds for every manager.
=> dashboard: serve per-manager pages

tools/syz-execprog/execprog.go
- pkg/cover/backend: adjust module base address by .text offset
- tools/syz-execprog: use more precise addresses when collecting coverage
=> Coverage improvements for Android

dashboard/dashapi/dashapi.go, pkg/asset/storage.go, pkg/asset/storage_test.go, pkg/vcs/fuchsia.go, pkg/vcs/git.go, pkg/vcs/git_repo_test.go, pkg/vcs/vcs.go, syz-ci/manager.go, syz-ci/manager_test.go
See descriptions of individual commits.
Closes #4347
=> syz-ci: query manager commits and commit info similarly 

pkg/repro/repro.go
If an instance fails to boot 3 times in a row,
we drop it on the floor. If we drop all instances this way,
the repro process deadlocks infinitly.
Retry infinitly instead. There is nothing else good we can do
in this case. If the instances becomes alive again, repro will resume.
=> pkg/repro: fix potential deadlock

syz-ci/syz-ci.go
=> syz-ci: add a missing json name in the manager config

.github/CODEOWNERS, .github/dependabot.yml
We are getting too many PRs too often to react on all.
=> dependabot: use monthly schedule

pkg/ipc/ipc.go, syz-fuzzer/proc.go
On a loaded VM, the restar may easily take 10-20 second, during which all other procs have to wait due to gate ticketing.
Restart executor processes outside of synchronization primitives.
=> syz-fuzzer: take executor restart out of gate tickets

pkg/gce/gce.go, pkg/gce/gce_test.go, vm/gce/gce.go
Co-authored-by: Alex Tyler <alextyler@google.com>
Co-authored-by: Aleksandr Nogikh <nogikh@google.com>
=> vm/gce: use regional serial port connections

vm/starnix/starnix.go
This PR bundles together a few changes that we've been testing locally. Retrying adb commands and running adbd with higher privilege seem to be essential. The network configuration and logs formatting changes are minor improvements. I'm happy to split this into separate PRs if there's a reason to take only a subset now.
=> Improve starnix VM startup process

pkg/build/netbsd.go
vm now expects SysTarget to be present.
=> pkg/build: fix incorrect vm instantiation

pkg/build/android.go
Copy unstripped module files in the output directory to be stored
in the object dir, to be used when generating module coverage.
=> pkg/build: extract unstripped module object files for Pixel

syz-manager/manager.go
It will help better understand #4495.
=> syz-manager: log failed repro log size

dashboard/app/app.yaml, pkg/html/html.go
The deployment takes 1.1G now. Let's check what can be removed after deployment.
=> dashboard/app: move to GOMOD from GOPATH

dashboard/dashapi/dashapi.go
This format is much better suitable for our API since we're including a potentially very big binary blob into every request.
No changes have to be made on the server side -- it already supports both formats.
Hopefully it will help remediate #4495.
=> dashapi: send requests using multipart/form-data

prog/prio.go
It was part of https://github.com/google/syzkaller/pull/4509
***
The function modifies its arguments, which makes it problematic to call it multiple times. Refactor it.
=> prog: remove side effects of BuildChoiceTable

pkg/repro/repro.go
In many cases bisection does not seem to bring any results, but it takes quite a while to run. Let's save some time by running the whole log before the process.
=> pkg/repro: check reproducibility before bisecting

dashboard/app/main.go, syz-manager/http.go
Currently json=0 and json=1 give the same result.
=> all: fix json=0 error

executor/common_linux.h, pkg/csource/generated.go
=> executor: temporarily disable IORING_SETUP_CQE32 and IORING_SETUP_SQE128

prog/clone.go, prog/encoding.go, prog/expr.go, prog/expr_test.go, prog/minimization.go, prog/mutation.go, prog/prog.go, prog/rand.go, prog/test/fuzz_test.go, prog/types.go, prog/validation.go, sys/linux/init_iptables.go, sys/linux/init_vusb.go, sys/test/expressions.txt
Reverts google/syzkaller#4556
The world is not ready for these changes yet.
https://syzkaller.appspot.com/bug?extid=2b1e5340372da8d3372b
=> Revert "prog: assorted fixes for conditional fields"

pkg/build/android.go
More recent Android kernels may not use the DEFCONFIG_FRAGMENT and BUILD_TARGET environment variables. Instead, they may require passing additional flags the build script.
This allows specifying those additional flags and makes the previously-required (and no longer used) configuration fields optional.
We also need to look for the `autoconf.h` file in a different location. This can now be configured using the `autoconf_path` configuration field.
=> pkg/build: pass additional flags from Android build config

docs/translations/README.md, docs/translations/zh_CN/internals.md
1. We add a disclaimer in docs/translations;
2. We add the first article in docs/translations/zh_CN;
=> docs/translations: Add a disclaimer and the first article in zh_CN

syz-verifier/exectask.go
=> syz-verifier: fix a typo in comments

pkg/rpctype/rpc.go, syz-manager/rpc.go, syz-manager/stats.go
Measure and display the total RPC communication traffic. It will help better evaluate #4579.
=> pkg/rpc: measure total RPC traffic

pkg/corpus/corpus.go, pkg/corpus/corpus_test.go, pkg/fuzzer/cover.go, pkg/fuzzer/fuzzer.go, pkg/fuzzer/fuzzer_test.go, syz-fuzzer/fuzzer.go, syz-manager/http.go, syz-manager/manager.go
By merging these commits now we simplify the review of #4579
=> all: assorted pkg/fuzzer and pkg/corpus improvements

tools/syz-testbed/table.go, tools/syz-testbed/table_test.go, tools/syz-testbed/templates/table.html
=> tools/syz-testbed: assorted fixes

prog/analysis.go, prog/expr.go, prog/size.go
It was a performance/code optimization that was originally done in https://github.com/google/syzkaller/pull/4380, but was later dropped because of the suspicions that it affected the overall fuzzing performance. Now that the big PR is merged, we can consider this change separately.
***
This change spares the need to construct a parents map for len[A, T] and conditional fields calculations.
=> prog: collect parents during arg traversal

pkg/fuzzer/prio_queue.go, pkg/fuzzer/prio_queue_test.go
=> pkg/fuzzer: remove async priority queue operations

syz-manager/manager.go
An atomic pointer is enough for our use cases. This should somewhat reduce the lock contention.
=> syz-manager: take the fuzzer object out of the mutex

pkg/rpctype/rpctype.go, syz-fuzzer/fuzzer.go, syz-manager/http.go, syz-manager/manager.go, syz-manager/rpc.go, syz-manager/stats.go
=> Extend manager stats

docs/fuchsia/README.md, docs/fuchsia/setup.sh
This replaces the hard coded paths to files with running ffx commands to retrieve the value. This accomodates the changes that are being made to the structure of the Fuchsia build output.
=> docs/fuchsia: update setup instructions to use ffx

syz-manager/manager.go
With load of inputs and slow disk preloading can take
tens of seconds. During that time we don't even serve
web interface, and don't start VMs.
Preload it asynchronously, we need it much later.
=> syz-manager: preload corpus asynchronously

docs/linux/setup_linux-host_android-device_arm-kernel.md
=> fix a typo in the android device setup document

syz-ci/manager.go
I observe empty reports.
I'm sure it happens because of the connection timeouts etc.
=> syz-ci/manager.go: don't upload empty reports

pkg/report/linux.go
It should hopefully help debug #4198.
=> pkg/report: add more assertions

dashboard/app/api.go
We're periodically seeing "failed to report build error" errors on the ci, but the error messages are missing necessary details.
=> dashboard: make errors more detailed

pkg/build/netbsd.go, pkg/instance/execprog.go, pkg/instance/instance.go, pkg/repro/strace.go, pkg/rpctype/rpc.go, syz-fuzzer/fuzzer.go, syz-fuzzer/proc.go, syz-manager/hub.go, syz-manager/manager.go, syz-runner/runner.go, syz-verifier/verifier.go, tools/syz-crush/crush.go, tools/syz-hubtool/hubtool.go, tools/syz-runtest/runtest.go, vm/vm.go, vm/vm_test.go
- pkg/rpctype: allow to disable timeouts
- syz-fuzzer: remove output flag
- vm: combine Run and MonitorExecution
=> refactor things

pkg/report/bsd.go, pkg/report/fuchsia.go, pkg/report/linux.go, pkg/report/report.go
=> pkg/report: don't use NewScanner() on the VM logs

pkg/rpctype/rpc.go, pkg/stats/set.go, vm/vm.go, vm/vm_test.go
- vm: allow to inject additional output
- vm: export VM output metric
=> dvyukov vm output inject

pkg/cover/html.go
These numbers seem confusing to syzkaller users.
If there's demand for them, we may consider re-enabling the calculation under some extra syzkaller config parameter.
@JoeyJiao if you still need these statistics, please let me know.
=> pkg/cover: remove function coverage percents

pkg/ifuzz/ifuzz_test.go
Make sure random text generation works as a whole, not just for single instructions.
=> pkg/ifuzz: test Generate()

executor/common_kvm_arm64.h, pkg/csource/generated.go
=> executor: arm64: call KVM_ARM_PREFERRED_TARGET on vmfd instead of cpufd

docs/db.md, tools/syz-db/syz-db.go
Add some short notes on how syz-db can also be used manually.
=> docs: add documentation for syz-db

syz-manager/http.go, syz-manager/manager.go, syz-manager/rpc.go, syz-manager/stats.go
- syz-manager: refactor periodic goroutines
- syz-manager: untie corpus minimization from fuzzer connects
- syz-manager: refactor filtered coverage updates
=> refactor periodic goroutines

dashboard/app/handler.go
Single threaded curl and wget are Ok to use.
Current logic returns 429 client err requiring users to rate limit requests.
Let's add the backpressure to guarantee acceptable request rate.
=> dashboard/app: backpressure robots

docs/syzbot.md
=> Fix typo in  syzbot.md

tools/syz-testbed/stats.go
In long runs, it can be thousands of points for every single graph that we render. It's much more than is actually needed.
=> tools/syz-testbed: limit the number of graph data points

pkg/host/machine_info.go, pkg/host/syscalls.go, pkg/host/syscalls_linux.go, pkg/mgrconfig/load.go, prog/encoding.go, prog/resources.go, prog/resources_test.go, prog/validation.go, sys/darwin/sys.txt, sys/freebsd/sys.txt, sys/fuchsia/sys.txt, sys/linux/init_test.go, sys/linux/sys.txt, sys/netbsd/sys.txt, sys/openbsd/sys.txt, sys/syz-sysgen/sysgen.go, sys/test/test.txt, syz-fuzzer/testing.go, syz-manager/covfilter.go, syz-manager/rpc.go
- **syz-manager: make nextRequestID non-atomic**
- **pkg/mgrconfig: add HasCovFilter helper**
- **pkg/host: explicitly disable syz_execute_func**
- **pkg/host: remove special case for EXT4_IOC_SHUTDOWN**
- **prog: add raw deserialization mode**
- **pkg/host: fix file reading bug**
- **syz-manager: print better message about disabled syscalls**
=> dvyukov things

executor/common_ext_test.go, pkg/fuzzer/fuzzer.go, pkg/fuzzer/fuzzer_test.go, pkg/fuzzer/job.go, pkg/instance/instance.go, pkg/ipc/ipc.go, pkg/ipc/ipc_priv_test.go, pkg/ipc/ipc_test.go, pkg/ipc/ipcconfig/ipcconfig.go, pkg/rpctype/rpctype.go, pkg/runtest/run.go, syz-fuzzer/fuzzer.go, syz-fuzzer/proc.go, syz-fuzzer/testing.go, syz-manager/manager.go, syz-manager/rpc.go, syz-runner/runner.go, tools/syz-execprog/execprog.go, tools/syz-runtest/runtest.go, tools/syz-stress/stress.go
- pkg/ipc: make it possible to change EnvFlags between executions
- pkg/ipc: dedup features to flags conversion
- syz-fuzzer: minor refactoring
- syz-manager, syz-fuzzer: pass ExecOpts in exec requests
- pkg/fuzzer: move Signal type from rpctype
- syz-manager: check revisions on the host
- pkg/fuzzer: minor cleanup
- syz-fuzzer: pass bug frames in connect result
=> dvyukov more things

pkg/ifuzz/ifuzz_test.go, pkg/ifuzz/x86/decode.go, pkg/ifuzz/x86_test.go
=> Fix x86 decoding

executor/executor.cc, pkg/ipc/ipc.go, pkg/rpctype/rpctype.go, pkg/vminfo/linux.go, pkg/vminfo/linux_syscalls.go, pkg/vminfo/linux_test.go, pkg/vminfo/syscalls.go, pkg/vminfo/vminfo.go, pkg/vminfo/vminfo_test.go, syz-fuzzer/fuzzer.go, syz-fuzzer/testing.go, syz-manager/covfilter.go, syz-manager/http.go, syz-manager/manager.go, syz-manager/rpc.go, syz-manager/stats.go, tools/syz-runtest/empty.go, tools/syz-runtest/runtest.go
=> Check syscalls on the host

syz-manager/manager.go, syz-manager/rpc.go, vm/vm.go
If the crash did not result in a panic, we continue normal fuzzing operation for several more seconds until a delay has passed and the VM was stopped.
It results in 20-30 more programs that are:
1) Run on a potentially corrupted machine.
2) Litter the logs -- these programs are definitely not related to the
crash.
3) Make it trickier to automatically track crash risk for individual
syscalls/programs (if we get to this).
Add an option to vm.Run that allows to determine a crash immediatey after it was detected. Use it to stop program exchange and program injection in rpc.go.
=> syz-manager: abort fuzzing immediately after crash detection

syz-manager/rpc.go
It's possible that a VM crashes after checking was done
but before the corpus is loaded, check checkDone after
the serv.mu to avoid this.
Also double-check checkDone in ExchangeInfo under serv.mu.
It's possible that the check is being finished, but checkDone
is not set yet. It looks like nothing bad happened by accident,
but this whole race wasn't intentional.
=> syz-manager: fix up checkDone checks

CONTRIBUTORS, docs/linux/setup.md
Also add myself to CONTRIBUTORS
=> Documentation fix: bump required Go version

pkg/log/log.go, syz-fuzzer/fuzzer.go, syz-fuzzer/testing.go
Convenience function like Fatal.
To minimize future diffs.
=> pkg/log: add SyzFatal

pkg/cover/backend/backend.go, pkg/cover/backend/dwarf.go, pkg/cover/backend/elf.go, pkg/cover/backend/gvisor.go, pkg/cover/backend/mach-o.go, pkg/cover/backend/modules.go, pkg/cover/canonicalizer.go, pkg/cover/canonicalizer_test.go, pkg/cover/report.go, pkg/host/machine_info.go, pkg/vminfo/linux.go, pkg/vminfo/vminfo.go, syz-manager/cover.go, syz-manager/covfilter.go, syz-manager/rpc.go, tools/syz-cover/syz-cover.go
Test package uses a different package name only in very special cases
(e.g. import cycles). No special cases here.
=> pkg/cover: don't rename test package

executor/embed.go
common_usb.h is included by both common_linux.h and common_netbsd.h.
The current version may fail to replace one of these common_usb.h,
if say common_linux.h is already replaced, but common_netbsd.h is not yet.
Make the replacement algorithm more robust and just replace everything
on each iteration until we can't replace anything anymore.
Fixes #4783
=> executor: fix embeding of headers

pkg/symbolizer/nm.go
=> pkg/symbolizer: remove unused parameter: target

pkg/vminfo/linux_test.go
The test becomes very restrictive in cases when custom descriptions are present.
Let's only check for the filesystems we expect to see.
=> pkg/vminfo: make TestLinuxSyscalls() more contained

.github/workflows/ci.yml
=> ci.yml: add codecov token and switch to v4

syz-manager/rpc.go
logProgram() may race with Request.Done(), in which case the request producer (fuzzer.Fuzzer) may well have already mutated a previously executed prog.Prog instance.
=> syz-manager: fix a race in logProgram()

pkg/flatrpc/flatrpc.fbs, pkg/flatrpc/flatrpc.go, pkg/flatrpc/flatrpc.h, pkg/flatrpc/helpers.go
- **pkg/flatrpc: use []byte for cover filter**
- **pkg/flatrpc: remove executing info from execution result**
- **pkg/flatrpc: move wait stats into start executing message**
=> dvyukov flatrpc fixes

pkg/fuzzer/fuzzer.go, pkg/fuzzer/fuzzer_test.go, pkg/fuzzer/job.go, pkg/fuzzer/queue/queue.go, pkg/host/features.go, pkg/host/machine_info.go, pkg/ipc/ipc.go, pkg/ipc/ipc_test.go, pkg/ipc/ipcconfig/ipcconfig.go, pkg/rpctype/rpctype.go, pkg/runtest/run.go, pkg/vminfo/features.go, pkg/vminfo/linux_test.go, pkg/vminfo/syscalls.go, pkg/vminfo/vminfo.go, pkg/vminfo/vminfo_test.go, syz-fuzzer/proc.go, syz-fuzzer/testing.go, syz-manager/manager.go, syz-manager/rpc.go, tools/syz-execprog/execprog.go, vm/vm.go, vm/vm_test.go
- **pkg/host: return slices of pointers**
- **pkg/ipc: use flatrpc flags**
- **syz-manager: don't distribute empty signal**
- **syz-manager: remove stopFuzzing**
=> dvyukov prepare for flatrpc

vm/adb/adb.go
=> vm/adb: fixe permission when running under WSL

syz-fuzzer/proc.go, syz-manager/rpc.go
The dumber the fuzzer, the better.
=> syz-fuzzer: move state reset logic to manager

sys/syz-extract/extract.go, sys/syz-extract/linux.go
=> sys/syz-extract: add -config option to specify base kernel config

dashboard/app/graphs.go, dashboard/app/templates.html
- **dashboard/app: add per-manager bug links**
- **dashboard/app: improve bug lifetime graph**
=> dvyukov manager bug links

dashboard/app/api.go, dashboard/app/entities.go, dashboard/app/main.go, dashboard/app/templates.html
This will help us understand how exactly how we have arrived at the reproducer.
=> dashboard: collect and display repro logs

pkg/flatrpc/flatrpc.fbs, pkg/flatrpc/flatrpc.go, pkg/flatrpc/flatrpc.h, pkg/flatrpc/helpers.go, pkg/mgrconfig/load.go, syz-fuzzer/fuzzer.go, syz-fuzzer/proc.go, syz-manager/last_executing.go, syz-manager/last_executing_test.go, syz-manager/manager.go, syz-manager/rpc.go, vm/vm.go, vm/vm_test.go
- **syz-fuzzer: repair leak checking**
- **syz-fuzzer: remove ipc gate**
- **syz-manager: repair VM-less mode**
- **pkg/flatrpc: send parameters to the fuzzer in RPC**
=> dvyukov ipc gate

docs/freebsd/README.md, vm/bhyve/bhyve.go
This feature is useful for running syzkaller on a FreeBSD host, as it requires less setup.
=> Add support for usermode networking to the bhyve backend

sys/syz-extract/linux.go
=> Fix missing resolution in previous PR

pkg/cover/report_test.go, syz-manager/covfilter_test.go
Minor unit test fixes failing on Fedora 40 s390x.
=> s390x upstream fixes

.clang-format, Makefile, sys/targets/targets.go, tools/docker/old-env/Dockerfile
- **tools/docker/old-env: switch to Ubuntu 20.04**
- **sys/targets: switch to C++17**
- **.clang-format: prepare for C++ code**
=> dvyukov c++17

sys/targets/targets.go
debian:bookworm has broken C++ arm64->amd64 cross-compiler:
x86_64-linux-gnu-g++ -static-pie fails with:
cannot find /usr/lib/x86_64-linux-gnu/libm-2.36.a: No such file or directory
cannot find /usr/lib/x86_64-linux-gnu/libmvec.a: No such file or directory
collect2: error: ld returned 1 exit status
These are installed in a different dif in the image.
Test that C++ compiler works as well.
=> sys/targets: test that C++ compiler works as well

pkg/cover/cover.go, pkg/flatrpc/flatrpc.fbs, pkg/flatrpc/flatrpc.go, pkg/flatrpc/flatrpc.h, pkg/fuzzer/fuzzer.go, pkg/fuzzer/job.go, pkg/fuzzer/job_test.go, pkg/fuzzer/queue/queue.go, pkg/fuzzer/queue/queue_test.go, pkg/fuzzer/stats.go, pkg/signal/signal.go, syz-fuzzer/fuzzer.go, syz-fuzzer/fuzzer_test.go, syz-fuzzer/proc.go, syz-manager/hub.go, syz-manager/manager.go, syz-manager/rpc.go, tools/syz-testbed/html.go, tools/syz-testbed/instance.go, tools/syz-testbed/stats.go, tools/syz-testbed/targets.go, tools/syz-testbed/testbed.go
- **pkg/fuzzer: refactor progTypes**
- **pkg/fuzzer: smarter retry for corpus candidates**
- **pkg/fuzzer: improve triage procedure**
- **pkg/fuzzer: refactor deflake tests**
=> pkg/fuzzer: optimize triage

executor/executor.cc, executor/test.h, pkg/cover/canonicalizer.go, pkg/cover/canonicalizer_test.go, pkg/cover/html.go, pkg/cover/report_test.go, pkg/flatrpc/flatrpc.fbs, pkg/flatrpc/flatrpc.go, pkg/flatrpc/flatrpc.h, pkg/instance/instance.go, syz-fuzzer/fuzzer.go, syz-manager/covfilter.go, syz-manager/covfilter_test.go, syz-manager/http.go, syz-manager/manager.go, syz-manager/rpc.go, tools/syz-cover/syz-cover.go
- **pkg/cover: cover less**
- **syz-manager: remove the beginnings of weighted coverage filter**
- **executor: allow to run a single test**
- **pkg/flatrpc: send parameters to the fuzzer in RPC**
=> more changes in preparation for moving fuzzer into executor

pkg/cover/backend/elf.go
=> pkg/cover: ignore append 0 sized symbol

pkg/runtest/run.go
Use the intended Request.OnDone() mechanism to implement the retry logic.
Fixes #4843.
=> pkg/runtest: properly resubmit requests on retry

dashboard/app/graphs.go
Bugs that are delayed from reaching the final reporting only by embargo
can also be considered found and stable (e.g. not one-off corruptions
staged in moderation).
=> dashboard/app: show embargoed bugs in bugs/month graph

executor/common_linux.h
There were some cases where the return value was not checked, allowing errors to propagate. This fixes them to return early with a message.
=> executor: handle errors from netlink_query_family_id

pkg/cover/backend/backend.go, pkg/cover/backend/dwarf.go, pkg/cover/backend/elf.go, pkg/cover/backend/gvisor.go, pkg/cover/backend/mach-o.go, pkg/cover/backend/modules.go, pkg/cover/canonicalizer.go, pkg/cover/canonicalizer_test.go, pkg/cover/report.go, pkg/vminfo/linux.go, pkg/vminfo/netbsd.go, pkg/vminfo/openbsd.go, pkg/vminfo/vminfo.go, syz-manager/cover.go, syz-manager/covfilter.go, syz-manager/rpc.go, tools/syz-cover/syz-cover.go
=> Unify Module and KernelModule usage

pkg/report/fuchsia.go, pkg/report/testdata/starnix/report/0, pkg/report/testdata/starnix/report/1, pkg/report/testdata/starnix/report/2, pkg/report/testdata/starnix/report/3
Also updates the title template for starnix kernel panics to use dashboard space a little more efficiently.
=> pkg/report: support prettified starnix logs

syz-manager/manager.go
In this mode, syz-manager continuously runs programs from the corpus - not as the full triage process, but just as ordinary programs.
=> syz-manager: introduce a corpus run mode

pkg/csource/build.go, pkg/runtest/run.go, pkg/runtest/run_test.go
- **pkg/runtest: shorted parsing tests**
- **pkg/csource: build executor w/o optimizations**
=> dvyukov runtest shorter

executor/executor_test.h
Otherwise we may leave orphaned executor process children, which prevent the cleanup of the executor directory.
Closes #4920.
=> executor: set PR_SET_PDEATHSIG for TestOS

executor/common_test.h, executor/executor_runner.h, executor/executor_test.h, pkg/runtest/executor_test.go, pkg/runtest/run_test.go
- **executor: handle features that fail in non-fatal way**
- **pkg/runtest: test feature detection**
=> dvyukov executor remote cover fail

vm/adb/adb.go, vm/isolated/isolated.go, vm/qemu/qemu.go, vm/vm.go, vm/vm_test.go, vm/vmimpl/vmimpl.go, vm/vmware/vmware.go
=> vm/qemu: refactor + add a delay after Run() failures

pkg/report/testdata/linux/report/718, pkg/report/testdata/linux/report/719, pkg/report/testdata/linux/report/720
These are mis-parsed for now. Just add test cases.
Filed #4967
=> pkg/report: add new Linux rcu stall report format

executor/cover_filter.h, executor/executor_runner.h, executor/test.h, pkg/flatrpc/flatrpc.fbs, pkg/flatrpc/flatrpc.go, pkg/flatrpc/flatrpc.h, pkg/fuzzer/cover.go, pkg/fuzzer/fuzzer.go, pkg/fuzzer/fuzzer_test.go, pkg/fuzzer/job.go, pkg/fuzzer/job_test.go, pkg/fuzzer/stats.go, pkg/hash/hash.go, pkg/rpcserver/rpcserver.go, pkg/rpcserver/runner.go, pkg/signal/signal.go, pkg/signal/signal_test.go, prog/analysis.go, prog/hints.go, prog/hints_test.go, prog/rand.go, prog/target.go, prog/types.go, sys/test/related.txt, syz-manager/manager.go
- **prog: reduce amount of hint replacements**
- **pkg/fuzzer: optimize smash jobs**
- **pkg/fuzzer: remove signal rotation**
=> dvyukov no rotate

vm/gce/gce.go, vm/vmimpl/vmimpl.go
It will let us reduce code duplication and use the more appropriate approach to the graceful Run() shutdown - by enforcing a delay between stopping the command and stopping the collection of the console output.
Closes #4887.
=> vm/gce: use vmimpl.Multiplex()

pkg/fuzzer/fuzzer_test.go
Currently we can get either:
WARNING: DATA RACE
Read at 0x00c0018fe1e0 by goroutine 11:
github.com/google/syzkaller/pkg/fuzzer.(*testFuzzer).run()
pkg/fuzzer/fuzzer_test.go:183 +0x62a
github.com/google/syzkaller/pkg/fuzzer.TestFuzz()
pkg/fuzzer/fuzzer_test.go:86 +0xa96
testing.tRunner()
testing/testing.go:1595 +0x238
testing.(*T).Run.func1()
testing/testing.go:1648 +0x44
Previous write at 0x00c0018fe1e0 by goroutine 36:
runtime.mapassign_faststr()
runtime/map_faststr.go:203 +0x0
github.com/google/syzkaller/pkg/fuzzer.(*testFuzzer).OnDone()
pkg/fuzzer/fuzzer_test.go:210 +0x404
github.com/google/syzkaller/pkg/fuzzer.(*testFuzzer).OnDone-fm()
<autogenerated>:1 +0x47
github.com/google/syzkaller/pkg/fuzzer.(*testFuzzer).Next.(*Request).OnDone.func1()
pkg/fuzzer/queue/queue.go:62 +0xa1 …
=> pkg/fuzzer: fix races in test

pkg/rpcserver/rpcserver.go, pkg/rpcserver/runner.go
More changes to split off Runner from RPCServer.
=> pkg/rpcserver: further refactorings

syz-manager/manager.go
Since we don't upload bugs/repros to dashboard, it likely won't have
the reproducer even if we succeeded last time, and will repeatedly
say it needs a repro.
=> syz-manager: reproduce each bug at most once in DashboardOnlyRepro mode

pkg/runtest/run_test.go
I still see the following errors in every other run:
=== CONT  TestCover/64/1
=== NAME  TestCover/64/3
testing.go:1232: TempDir RemoveAll cleanup: unlinkat /tmp/TestCover6431888025363/001: directory not empty
=== CONT  TestCover/64_fork/0
=== CONT  TestCover/64_fork/9
=== NAME  TestCover/64/1
testing.go:1232: TempDir RemoveAll cleanup: unlinkat /tmp/TestCover6412810450597/001: directory not empty
We set PR_SET_PDEATHSIG for subprocesses, but we still don't wait for them to terminate.
=> pkg/runtest: fix episodic "directory not empty" failures in tests

dashboard/app/entities_spanner.go, tools/syz-bq.sh, tools/syz-covermerger/db.go, tools/syz-covermerger/syz_covermerger.go
Normalized db shoud remove the update anomalies.
The only detail - I don't remove the old sessions details. The removal logic may be added in the future if needed.
The most interesting part is the merge_history primary key change.
=> coverage: use the sessions based logic instead of date based

pkg/cover/backend/backend.go, pkg/cover/backend/dwarf.go, pkg/cover/backend/elf.go, pkg/cover/backend/gvisor.go, pkg/cover/backend/mach-o.go, pkg/cover/backend/modules.go, pkg/cover/canonicalizer.go, pkg/cover/canonicalizer_test.go, pkg/cover/report.go, pkg/rpcserver/local.go, pkg/rpcserver/rpcserver.go, pkg/vminfo/linux.go, pkg/vminfo/netbsd.go, pkg/vminfo/openbsd.go, pkg/vminfo/vminfo.go, pkg/vminfo/vminfo_test.go, syz-manager/cover.go, syz-manager/covfilter.go, syz-manager/manager.go, tools/syz-cover/syz-cover.go
=> all: move KernelModule into vminfo package

pkg/flatrpc/conn.go, pkg/flatrpc/conn_test.go
This should prevent possible OOM kills.
See the added comment for details.
=> pkg/rpcserver: verify executor messages better

executor/executor.cc, executor/executor_runner.h
This will allow to reuse finish_output function for snapshot mode as well.
NFC
=> executor: factor output finishing into separate function

syz-manager/repro.go
We need to consider all reproduction attempts, not just the current queue.
=> syz-manager: fix the one time reproduction check

vm/vmimpl/vmimpl.go
The sleep in Multiplex is unconditional and it sleeps idle
even for commands that has nothting to do with executor,
and for executor in other modes that has nothing to do with fuzzing.
Since the original reason for the sleep was related to failing executor,
sleep only when the command fails. This allows to at least run
successful commands fast.
=> vm/vmimpl: don't wait commands that have not failed

pkg/repro/repro.go, syz-manager/hub.go, syz-manager/manager.go, syz-manager/repro.go, tools/syz-repro/repro.go
=> syz-manager: some bug repro fixes and improvements

pkg/fuzzer/job.go
Hints can produce insane amounts of candidates (up to 30K). So run deflaking one more time, even if it reduces amount of candidates by few percents, it's still profitable.
=> pkg/fuzzer: deflake hints 3 times instead of 2

tools/gvisor-smoke-test.sh
The gVisor smoke test script now accepts the `GVISOR_VMLINUX_PATH` environment variable. When set and non-empty, it will use this path to find the `runsc` runtime, rather than downloading it from the Internet.
The intent is to use this as part of the gVisor testing pipeline using a locally-built version of the gVisor runtime (`runsc`).
=> vm/gvisor: Smoke test script: Allow specifying gVisor path as env var.

executor/common_linux.h
cad_pid must not point to a persistent runner process,
b/c it will be killed on ctrl+alt+del.
Fixes #5027
=> executor: fix setup of cad_pid

docs/translations/zh_CN/contributing.md
Finish the translation of docs/contributing.md, which has also been proofread by HCTT translation group.
Please note that pr https://github.com/google/syzkaller/pull/5038 is obsolete and closed, so please ignore it.
=> docs/translations: add the translation of contributing.md

executor/executor_runner.h
There are also synchnous fatal signals that can happen due to bugs
in executor code. So handle them as SIGSEGV.
=> executor: print signal info for SIGILL/SIGFPE as well

pkg/fuzzer/job.go
If we have found new signal for several calls of the same programs, triage them in parallel.
=> pkg/fuzzer: speed up triage jobs

executor/conn.h
In case only ipv6 is supported, we should try ipv4-localhost first and see if it fails, and then go on to trying ipv6.
=> executor: fix localhost handling for machines with only ipv6

pkg/fuzzer/job.go
Use 2/6 criteria during corpus triage.
See the large added comment for details.
=> pkg/fuzzer: use more permissive criteria during corpus triage

executor/executor.cc
This kind of deduplication is confusing for the fuzzer, which expects to control the process itself (by MaxSignal and by specifying the calls for which full signal must be returned).
There's also a chance that it may contribute to the difficulties during program triage and minimization.
Let's err on the safe side and deduplicate signal only per-call.
=> executor: deduplicate signal per-call

dashboard/app/api.go
Filter out the obviously unnecessary bugs.
=> dashboard: better filter logs for reproduction

vm/dispatcher/pool_test.go
There was a race between starting the job and resetting the reserved VM count.
Rewrite the test to let it run regardless of the thread interleaving.
Closes #5090.
=> vm/dispatcher: make the test more deterministic

pkg/cover/backend/dwarf.go, pkg/mgrconfig/load.go, pkg/report/linux.go, pkg/report/linux_test.go, pkg/report/report.go, pkg/rpcserver/rpcserver.go
=> Support symbolizing line with module+offset in report

vm/adb/adb.go, vm/bhyve/bhyve.go, vm/cuttlefish/cuttlefish.go, vm/gce/gce.go, vm/gvisor/gvisor.go, vm/isolated/isolated.go, vm/proxyapp/init.go, vm/qemu/qemu.go, vm/starnix/starnix.go, vm/vm.go, vm/vm_test.go, vm/vmimpl/vmimpl.go, vm/vmm/vmm.go, vm/vmware/vmware.go
- **vmimpl: refactor VM type registration**
- **vm: check preemption string only for gce instances**
=> dvyukov vm refactor

dashboard/app/api.go
We're currently receiving only "unauthorized".
=> dashboard/app/api.go: more logging

dashboard/app/api.go
Let's resist the timing attacks.
=> dashboard/app/api.go: constant time compare secrets

executor/common.h, executor/executor.cc, executor/executor_runner.h, executor/files.h, executor/snapshot.h, pkg/flatrpc/flatrpc.fbs, pkg/flatrpc/flatrpc.go, pkg/flatrpc/flatrpc.h, pkg/flatrpc/helpers.go, pkg/fuzzer/fuzzer.go, pkg/fuzzer/job.go, pkg/fuzzer/queue/stats.go, pkg/log/log.go, pkg/mgrconfig/config.go, pkg/mgrconfig/load.go, pkg/rpcserver/rpcserver.go, syz-manager/manager.go, syz-manager/snapshot.go, vm/qemu/qemu.go, vm/qemu/snapshot_linux.go, vm/qemu/snapshot_unimpl.go, vm/vm.go, vm/vmimpl/vmimpl.go
- **pkg/fuzzer/queue: move common fuzzing stats**
- **vm: add snapshot interface**
- **all: add qemu snapshotting mode**
- **pkg/fuzzer: tune parameters for snapshot mode**
Fixes #4833
=> add snapshot-based fuzzing

pkg/runtest/run.go
Instead of bailing out on the first program with parsing errors, create a "broken" runRequest for each of such programs.
=> pkg/runtest: report programs that cannot be parsed as broken

executor/conn.h
ConnectWait is directly from OpenBSD man page.
=> executor: handle EINTR in connect

vm/dispatcher/pool.go, vm/dispatcher/pool_test.go
It was possible for poolInstance.reserve() and free() to race with instance restart in Pool.Loop().
Add more locking to poolInstance. Remove locks in one case where it was excessive.
=> vm/dispatcher: fix data races

syz-manager/manager.go
=> syz-manager: preload corpus in corpus-run mode

executor/executor.cc
=> executor: fix coverage collection in snapshot mode

syz-manager/manager.go
We should have been closing only the context of the Pool.Loop().
=> syz-manager: restore crash collection in snapshotting mode

pkg/csource/csource_test.go, pkg/fuzzer/job.go, pkg/repro/repro.go, prog/encoding_test.go, prog/expr_test.go, prog/minimization.go, prog/minimization_test.go, prog/prog_test.go, prog/rand_test.go
- **prog: replace MinimizeParams with MinimizeMode**
- **prog: don't minimize int/resource for corpus**
=> dvyukov minization improvements

prog/minimization.go, prog/minimization_test.go
- **prog: remove minimization TODOs**
- **prog: don't minimize file names for corpus**
- **prog: optimize array minimization**
- **prog: try to remove all unrelated calls during minimization**
=> More minimization optimizations

dashboard/app/graphs.go, pkg/cover/heatmap.go
It enables the requests like "upstream/graph/coverage_heatmap **?subsystem=kvm**".
=> dashboard/app: enable subsystem targeted heatmaps

pkg/covermerger/covermerger.go, pkg/covermerger/provider_monorepo.go, pkg/covermerger/provider_web.go, tools/syz-covermerger/syz_covermerger.go
It allows to speed up the single file calculations because we don't need git clone.
=> covermerger: add web-git source provider

sys/linux/filesystem.txt
=> sys/linux/filesystem: add mount flags for ufs

sys/linux/filesystem.txt
=> sys/linux/filesystem: add mount flags for ocfs2

sys/linux/filesystem.txt
Added mount flags for squashfs
=> sys/linux/filesystem: add mount flags for squashfs

pkg/flatrpc/conn.go, syz-manager/snapshot.go
Use logic similar to flatrpc to avoid panics during result parsing.
=> syz-manager: make snapshot result parsing robust

syz-manager/snapshot.go
=> syz-manager: check for the minimum reply buffer size

pkg/cover/file.go, pkg/covermerger/provider_web.go, tools/syz-cover/syz-cover.go
To test:
```
gcloud auth login
gcloud auth application-default login
go run ./tools/syz-cover -for-file virt/kvm/binary_stats.c -from 2024-08-01 -to 2024-08-10
```
=> tools/syz-cover: add toolFileCover

pkg/covermerger/covermerger.go, pkg/covermerger/provider_monorepo.go, tools/syz-covermerger/syz_covermerger.go
We're logging too much now. Let's disable it by default.
=> tools/syz-covermerger: use pkg/log

executor/executor_linux.h, syz-manager/manager.go, syz-manager/snapshot.go
- **executor: simplify mapping of kcov guard pages**
- **syz-manager: distribute requests across instances**
=> dvyukov snapshot randomization

executor/common_linux.h, executor/executor.cc, executor/executor_linux.h, executor/executor_runner.h, executor/snapshot.h, vm/qemu/snapshot_linux.go
- **vm/qemu: extend error messages**
- **executor: keep SYZFAIL messages during machine check**
- **executor: protect kcov/output regions with pkeys**
=> dvyukov pkey

docs/translations/zh_CN/linux/reporting_kernel_bugs.md
Finish the translation of docs/linux/reporting_kernel_bugs.md, which has also been proofread by HCTT translation group.
=> docs/translations: add the translation of linux/reporting_kernel_bugs.md

docs/translations/zh_CN/linux/setup_linux-host_qemu-vm_arm64-kernel.md
Finish the translation of /docs/linux/setup_linux-host_qemu-vm_arm64-kernel.md, which has also been proofread by HCTT translation group.
=> docs/translations: add the translation of linux/setup_linux-host_qemu-vm_arm64-kernel.md

tools/syz-cover/syz-cover.go
This fixes syz-cover tool breaking after the removal of DiscoverModules() down the stack from MakeReportGenerator().
I'm not sure if syz-cover should overwrite modules if they're provided on the command line, or if they should be added to the manager config modules. If we're using the config, then it might even make sense to just strip that command line option entirely.
Fixes #5086
=> tools/syz-cover: add missing DiscoverModules()

dashboard/app/config.go, pkg/covermerger/bq_csv_reader.go, pkg/validator/validator.go, pkg/validator/validator_test.go
We use validation in many places. I checked the existing packages and product specific one looks better to me.
I'll primarily need it for the http parameters and sql inputs validation.
Domain specific functions look more readable to me. WDYT?
=> pkg/validator: introduce validation pkg

pkg/bisect/bisect.go, pkg/build/build.go, pkg/build/freebsd.go, pkg/build/linux.go, pkg/build/netbsd.go, pkg/build/openbsd.go, pkg/instance/instance.go, syz-ci/jobs.go, syz-ci/manager.go, syz-ci/syz-ci.go
The latter is a better suitable name.
=> all: rename build_jobs to build_cpus

pkg/bisect/minimize/slice.go, pkg/bisect/minimize/slice_test.go, pkg/instance/execprog.go, pkg/repro/repro.go
=> pkg/repro: assorted improvements

sys/linux/filesystem.txt
Added mount flags for filesystems.
=> sys/linux/filesystem: add mount flags for filesystems

executor/executor.cc
Reset coverage right before scheduling next syscall for execution.
See the added comment for details.
=> executor: fix corner case of misinterpreting comparison data

tools/syz-covermerger/init_db.sh
It looks save because the data can always be recalculated.
=> tools/syz-covermerger/init_db.sh: drop all data on call

pkg/covermerger/covermerger_test.go, pkg/covermerger/file_line_merger.go, pkg/covermerger/provider_monorepo.go, pkg/covermerger/provider_web.go
pkg/covermerger: rename variables, delete unused
pkg/covermerger: delete trivial function
=> pkg/covermerger: cleanup

dashboard/app/coverage_batch.go, tools/syz-bq.sh
This code was deleted accidentally.
Branch information is needed here to get the last target day commit.
=> dashboard/app: branch info is needed to get target commit

syz-manager/manager.go
We smash the program only once after we add it to the corpus, but it can be that
1) It did not finish before the instance was restarted.
2) The fuzzing algorithms have become smarter over time.
3) That kernel code has changed over time.
It would be best to track it in pkg/db, but until it's capable of that, let's just re-smash some corpus subset on each syz-manager restart.
=> syz-manager: re-smash a subset of the corpus on restart

pkg/fuzzer/job.go
Specify the exact call that is being minimized.
Print new signal delta if it's small (these are most suspicious kinds of triage jobs).
=> pkg/fuzzer: improve job logging

pkg/cover/backend/dwarf.go
=> fix loopvar bug in go func inside loop

tools/syz-env
=> tools/syz-env: export https_proxy to docker in case behind proxy

pkg/manager/repro.go, pkg/manager/repro_test.go
First consider how many times we've tried to reproduce the crash, and only then look at other criteria.
This will make the reproduction process more just since in the presence of multiple crashes in the queue we will give at least one chance to a wider range of different crashes.
=> pkg/manager: give preference to never reproduced crashes

pkg/cover/html.go, pkg/cover/report_test.go, syz-manager/http.go, tools/syz-cover/syz-cover.go
=> improve syz-cover and function names

.golangci.yml, dashboard/app/coverage_batch.go, dashboard/app/cron.yaml
Quarter long numbers calculation takes 2 hours.
Month long numbers calculation takes 15 minutes.
Let's update quarters data once per week.
=> dashboard/app: tune coverage update schedule

dashboard/app/main.go, dashboard/app/templates/templates.html
No comments. It was an evening code I guess...
=> dashboard/app: fix url routing bug

dashboard/app/coverage_batch.go
Month long merges are the default now.
=> dashboard/app: delete unused week->day coverage merges

tools/syz-bq.sh
For the dateTo=2024-08-10 and duration=1 expected dateFrom is 2024-08-10.
=> tools/syz-bq: fix date range calculation

tools/docker/env/Dockerfile, tools/docker/old-env/Dockerfile, tools/docker/syzbot/Dockerfile
=> tools/docker: update Go in the containers

dashboard/app/api.go, dashboard/app/cache.go, dashboard/app/entities_datastore.go, dashboard/app/jobs.go, dashboard/app/main.go, dashboard/app/public_json_api.go, dashboard/app/reporting_lists.go, dashboard/app/stats.go, dashboard/app/templates/backports.html
Include more information into the output: kernel config and reproducer links.
+ some dashboard refactorings.
=> dashboard: export missing backports as json

dashboard/app/public_json_api.go
Also, slightly refine the field names.
=> dashboard: add syzkaller commit to the backports json

syz-hub/hub.go, syz-hub/state/state.go
Discard manager data after 30 days of inactivity.
This should automatically get rid of decomissioned managers,
and old manual instances.
=> syz-hub: purge inactive managers

pkg/manager/repro.go, pkg/manager/repro_test.go, syz-manager/manager.go
=> pkg/manager: fixes and improvements to ReproLoop

docs/linux/reporting_kernel_bugs.md
Add more guidelines and be more concrete.
=> docs: refine Linux bug reporting instructions

pkg/build/netbsd.go, pkg/instance/instance.go, syz-manager/manager.go, syz-verifier/main.go, tools/syz-crush/crush.go, tools/syz-repro/repro.go
Add calls to Close() from all locations that call Create().
=> vm: make sure vm.Pools are cleaned up

executor/common_kvm_arm64.h, executor/common_kvm_arm64_syzos.h, executor/common_linux.h, pkg/csource/csource_test.go, pkg/subsystem/linux/rules.go, pkg/subsystem/lists/linux.go, pkg/vminfo/linux_syscalls.go, pkg/vminfo/linux_test.go, sys/linux/dev_kvm.txt, sys/linux/test/arm64-syz_kvm_setup_syzos_vm, sys/linux/test/arm64-syz_kvm_setup_syzos_vm-memwrite, sys/linux/test/arm64-syz_kvm_setup_syzos_vm-msr, sys/linux/test/arm64-syz_kvm_setup_syzos_vm-smc, sys/linux/test/arm64-syz_kvm_setup_syzos_vm-vgicv3, sys/linux/test/arm64-syz_kvm_setup_syzos_vm-vgicv3-cpu1, vm/qemu/qemu.go
=> KVM: refactor CPU creation API

executor/common_kvm_arm64.h, pkg/csource/csource_test.go
=> Kvm fix syz kvm

pkg/asset/storage.go, pkg/asset/storage_test.go, syz-ci/syz-ci.go
Let's have a bit more introspection into the asset storage deprecation code.
=> pkg/asset: report deprecation figures

dashboard/app/graphs.go, pkg/cover/heatmap.go, pkg/cover/heatmap_test.go, pkg/cover/templates/heatmap.html, pkg/coveragedb/time_period.go, pkg/coveragedb/time_period_test.go, tools/syz-cover/syz-cover.go
The final page will probably explode. Let's address it later if needed.
P.S. compressed page is just 10k.
=> pkg/cover: reports have links to "line coverage" html chunks

pkg/manager/crash.go, pkg/manager/crash_test.go, pkg/manager/http.go, syz-manager/hub.go, syz-manager/manager.go, tools/syz-reporter/reporter.go, tools/syz-testbed/stats.go
Make the functionality better testable and reusable.
=> syz-manager: move crash storage and HTTP server into pkg/manager

tools/syz-repro/repro.go
There used to be no strict ordering between cancelling the loop context and the actual moment the Loop() method exits. Now that we assert that all instances are freed in vmPool.Close(), we need to wait until Loop() finishes before closing the VM pool.
Restructure the main() method to ensure this order.
=> tools/syz-repro: order Loop() and vmPool.Close()

tools/syz-reprolist/reprolist.go
- **tools/syz-reprolist: fix typo**
- **tools/syz-reprolist: fix a data race**
- **tools/syz-reprolist: fix throttling**
=> dvyukov reprolist fixes

tools/syz-declextract/run.go, tools/syz-declextract/syz-declextract.cpp
Minimal descriptions are netlink commands and syscall names, while final descriptions are complete syzkaller descriptions.
=> tools/syz-declextract: add outputFormat flag to choose between minimal and final descriptions

pkg/manager/crash.go, pkg/manager/crash_test.go
=> pkg/manager: small crash store fixes

dashboard/app/api.go
Instead of iterating over all possible seq values, first query the maximum existing value outside of the transaction and then only consider the higher numbers inside the transaction.
That should avoid "operating on too many entity groups in a single transaction" errors that we observe on syzbot.
Closes #5440.
=> dashboard: optimize reportCrash()

docs/talks.md
=> docs: add two more talks

dashboard/app/subsystem_test.go, dashboard/app/templates/mail_subsystem.txt
=> dashboard: adjust the monthly reporting template

pkg/html/pages/style.css, pkg/manager/http.go, pkg/manager/http_test.go, pkg/testutil/testutil.go
- **pkg/manager: move style to CSS file**
- **pkg/manager: dedup HTML page creation code**
- **pkg/manager: add test for all HTTP templates**
=> Add tests for manager http templates

Makefile, dashboard/app/templates/backports.html, dashboard/app/templates/custom_content.html, dashboard/app/templates/graph_fuzzing.html, dashboard/app/templates/main.html, dashboard/app/templates/templates.html, pkg/cover/templates/cover.html, tools/check-html.sh, tools/syz-testbed/templates/table.html, tools/syz-testbed/templates/testbed.html
- **all: fix HTML file formatting**
- **tools: add HTML checking script**
=> Ensure consistent HTML file formatting

pkg/manager/http.go, pkg/repro/repro.go, pkg/repro/strace.go, pkg/rpcserver/rpcserver.go, syz-manager/manager.go, tools/syz-diff/diff.go, vm/vm.go
- **vm: simplify code**
- **pkg/manager: set more http fields before calling Serve**
- **pkg/rpcserver: export modules stat**
=> some assorted refactorings

dashboard/app/batch_main.go, dashboard/app/batch_reproexport.go, dashboard/app/cron.yaml, tools/syz-db-export/README.md, tools/syz-db-export/reprolist.go, tools/syz-reprolist/reprolist.go
If it generally looks good I'll add other changes to batch_reprolist.
=> tools/syz-reprolist: save json for every bug, rename tool

sys/linux/auto.txt.json, tools/syz-declextract/run.go, tools/syz-declextract/syz-declextract.cpp
- **tools/syz-declextract: add entry function and access level**
- **tools/syz-declextract: add io_uring function/access**
- **tools/syz-declextract: add syscall entry function**
=> tools/syz-declextract: add entry function and access level

tools/syz-db/syz-db.go, tools/syz-db/syz-db_test.go
=> Add syz-db print and rm cmd

docs/syscall_descriptions_syntax.md, pkg/ast/ast.go, pkg/ast/format.go, pkg/ast/parser.go, pkg/ast/scanner.go, pkg/ast/testdata/all.txt, pkg/ast/testdata/errors.txt, pkg/compiler/gen.go, pkg/fuzzer/job_test.go, prog/expr.go, prog/expr_test.go, prog/types.go, sys/test/expressions.txt, sys/test/test/expressions
=> all: support || operator in if condition

pkg/report/linux.go, pkg/report/testdata/linux/report/729
We've got a dup:
https://syzkaller.appspot.com/bug?extid=d6f5b7a41831ca1a99a0
for an exising report:
https://syzkaller.appspot.com/bug?extid=be32baeb2433f286bc24
=> pkg/report: improve "Bad page state" parsing

pkg/auth/auth.go
We're getting 500 error from auth.DetermineAuthSubj with "read: connection reset by peer".
=> pkg/auth: better error description

syz-manager/manager.go
Makes modes more scalable and easier to add.
Currently the name, descritpion, and logic for each mode
is spread across the code.
Make most things related to a mode described in the mode
description, but also possible to check for a concrete
mode in the code if necessary.
=> syz-manager: refactor mode handling

executor/files.h
Don't follow symlinks when globbing.
It's haarmful for both files and dirs
(see the added comment for details).
=> executor: improve glob

pkg/compiler/compiler_test.go, pkg/compiler/const_file.go, pkg/compiler/consts.go, pkg/compiler/testdata/auto.txt, pkg/compiler/testdata/auto.txt.const, pkg/compiler/testdata/auto0.txt, pkg/compiler/testdata/auto0.txt.const, pkg/osutil/osutil.go, pkg/rpcserver/local.go, pkg/rpcserver/mocks/Manager.go, pkg/rpcserver/rpcserver.go, pkg/rpcserver/rpcserver_test.go, sys/syz-extract/linux.go, syz-manager/manager.go, tools/syz-declextract/run.go, tools/syz-diff/diff.go
- **tools/syz-declextract: accept manager config**
- **sys/syz-extract: support kvm on arm**
- **pkg/compiler: allow manual consts to override auto-extracted consts**
=> tools/syz-declextract: more preparation for file_operations extraction

tools/syz-declextract/run.go
Add caching mode where results of running the Clang tool
are cached for each file and can be reused.
It saves lots of time when only the Go tool changes.
Also allows to look at the output for each file for debugging.
Group all assorted variables in a context struct.
There are lots of assorted vars and will be more.
Support defines in the tool output.
Fix up some includes to more generic ones.
=> tools/syz-declextract: a bunch of refactorings

pkg/build/starnix.go
The `--no-environment` flag to the ffx tool allows it to proceed without assumptions about environment variables and/or the presence of an environment config file. All of the configuration we need can either be passed to ffx as key/value pairs, or from the `ffx-config.json` file that is generated by the Fuchsia build.
=> pkg/build: avoid relying on environment file for ffx

pkg/manager/http.go
=> add /addcandidate rest api to upload new prog to candidate

executor/common_kvm_arm64.h, executor/common_linux.h, pkg/runtest/run.go, pkg/vminfo/linux_syscalls.go, sys/linux/dev_kvm_arm64.txt, sys/linux/test/arm64-syz_kvm_setup_syzos_vm, sys/linux/test/arm64-syz_kvm_setup_syzos_vm-memwrite, sys/linux/test/arm64-syz_kvm_setup_syzos_vm-msr, sys/linux/test/arm64-syz_kvm_setup_syzos_vm-smc, sys/linux/test/arm64-syz_kvm_setup_syzos_vm-vgicv3, sys/linux/test/arm64-syz_kvm_setup_syzos_vm-vgicv3-cpu1, sys/linux/test/arm64-syz_kvm_setup_syzos_vm-vgicv3-its, sys/linux/test/arm64-syz_kvm_setup_syzos_vm-vgicv3-its-cmd, sys/linux/test/arm64-syz_kvm_setup_syzos_vm-vgicv3-unroll
=> Uexit asserts

dashboard/app/graphs.go
Before <img width=300 src="https://github.com/user-attachments/assets/ef68dd7e-86ab-4b5c-b7dd-52004a4b9e1f">
After <img width=300 src="https://github.com/user-attachments/assets/7851de40-1281-482b-8470-123433ec38d8">
=> dashboard/app: fix total coverage visualization

dashboard/app/api.go, dashboard/app/config.go, dashboard/app/reporting_external.go, dashboard/dashapi/dashapi.go, tools/syz-covermerger/syz_covermerger.go
It deserves integration testing...
=> upload coverage using gcs

executor/common_kvm_arm64.h, executor/common_linux.h, pkg/vminfo/linux_syscalls.go, sys/linux/dev_kvm_arm64.txt, sys/linux/test/arm64-syz_kvm_setup_syzos_vm-enable-pmu, sys/linux/test/arm64-syz_kvm_setup_syzos_vm-msr
=> PMU seed, syz_kvm_assert_reg()

tools/syz-covermerger/syz_covermerger.go
It allows to skip communication with dashboard and test merge+"upload to gcs".
=> tools/syz-covermerger: specify to-gcs destination

pkg/osutil/osutil.go, syz-manager/manager.go
=> pkg/osutil: add a WriteJSON helper

tools/create-ec2-rootfs.sh
Added a platform option, so an arm64 image could be created with the script.
Also fixed some problems with networking that I discovered while using an ec2 rootfs with syzkaller.
=> tools: improvements to ec2 rootfs

pkg/manager/crash.go, pkg/manager/html/main.html, pkg/manager/http.go, pkg/osutil/osutil.go, pkg/osutil/osutil_bsd.go, pkg/osutil/osutil_darwin.go, pkg/osutil/osutil_fuchsia.go, pkg/osutil/osutil_linux.go, pkg/osutil/osutil_windows.go
This allows to understand if a bug is new
(found in the current run) or old.
=> pkg/manager: show bug first time

pkg/instance/instance.go, syz-ci/manager.go
Move the logic from `syz-ci` to `pkg/instance` to make it reusable.
In case of a failure without a crash report, report the issue as a `SYZFATAL` crash instead of just printing to the error log.
=> pkg/instance: extract the smoke test method

pkg/fuzzer/queue/queue.go, pkg/vminfo/vminfo.go
=> pkg/fuzzer/queue: remove unnecessary Context usage

pkg/covermerger/bq_csv_reader.go
It fixes the query error.
Tested it locally as far as it is possible.
=> pkg/covermerger: group by func_name

pkg/coveragedb/init_db.sh
It fixes the misalignment with the code.
=> pkg/coveragedb: use funcname instead of function

pkg/manager/diff.go
We must not only call Listen(), but also Serve().
=> pkg/manager: fix RPCServer ops in RunDiffFuzzer()

syz-cluster/pkg/api/client.go
Refactor the helper methods to reduce code duplication.
Add context argument support for GET methods.
Add a one minute deadline on top of the deadline imposed by the context.
=> syz-cluster/pkg/api: set deadlines for requests

syz-cluster/workflow/fuzz-step/main.go
We cannot use the single context with a deadline for all processing because it does not let us report the final status after finishing fuzzing.
=> syz-cluster/workflow/fuzz-step: use deadline only for fuzzing

syz-cluster/controller/deployment.yaml, syz-cluster/dashboard/deployment.yaml, syz-cluster/series-tracker/deployment.yaml, syz-cluster/workflow/build-step/workflow-template.yaml, syz-cluster/workflow/fuzz-step/workflow-template.yaml, syz-cluster/workflow/triage-step/workflow-template.yaml
It will be important once we deploy to GKE.
For now, let's set just some limits, we'll adjust them over time.
=> syz-cluster: set resource limits

dashboard/app/batch_coverage.go, dashboard/app/batch_db_export.go
It looks cheaper than appengine.NewContext().
=> dashboard/app: use request context

dashboard/app/asset_storage_test.go, dashboard/app/templates/mail_bug.txt
=> dashboard: include fsck results into email reports

syz-cluster/workflow/fuzz-step/workflow-template.yaml
2h session is too short (at least for now).
=> syz-cluster: fuzz for 3 hours

dashboard/app/static/coverage.js
It currently generates &subsystem=null&manager=null&unique-only=null.
I'd like to see &subsystem=&manager=&unique-only=
=> dashboard/app: fix url generation

pkg/cover/html.go, pkg/cover/report.go
Reads from this map return Progs, not PCs.
=> pkg/cover: rename progPCs to pcToProgs

syz-cluster/README.md, syz-cluster/kernel-disk/cron.yaml, syz-cluster/overlays/common/kustomization.yaml, syz-cluster/overlays/common/network-deny-all.yaml, syz-cluster/overlays/common/network-policy-controller.yaml, syz-cluster/overlays/common/network-policy-git-access.yaml, syz-cluster/overlays/dev/fake-gcs.yaml, syz-cluster/overlays/dev/kustomization.yaml, syz-cluster/overlays/dev/network-policy-spanner.yaml, syz-cluster/pkg/workflow/template.yaml, syz-cluster/run-local.sh
* By default, disable all ingress traffic. For now, keep all egress traffic enabled.
* Configure ingress traffic on the per-need basis.
=> syz-cluster: configure network policies

pkg/rpctype/rpctype.go, syz-hub/http.go, syz-hub/hub.go, syz-hub/state/state.go, syz-hub/state/state_test.go, syz-manager/hub.go
=> all: show manager url in syz-hub

syz-manager/manager.go
=> syz-manager: only log distributing msg when newSignal len not 0

pkg/cover/report.go, pkg/cover/report_test.go, pkg/manager/report_generator.go, tools/syz-cover/syz-cover.go
=> all: reduce params to MakeReportGenerator

docs/configuration.md, docs/reproducing_crashes.md, pkg/mgrconfig/testdata/qemu-example.cfg
Add a sample syzkaller config with comments so that we could refer to it in the tutorials.
=> docs/linux: add a sample syzkaller config

pkg/cover/report.go, pkg/symbolizer/addr2line.go, pkg/symbolizer/addr2line_test.go
=> pkg/symbolizer: retain the frame if line number is 0

sys/targets/targets.go
Context is [here](https://groups.google.com/g/syzkaller/c/V0BfPGCj_PM/m/1bduyu6EAQAJ).
=> sys/targets: extend broken compiler error message

.golangci.yml, dashboard/app/reporting.go, pkg/compiler/check.go, pkg/cover/backend/backend.go, pkg/cover/backend/dwarf.go, pkg/cover/backend/elf.go, pkg/cover/backend/gvisor.go, pkg/cover/backend/mach-o.go, pkg/cover/file.go, pkg/cover/report.go, pkg/instance/instance.go, pkg/mgrconfig/load.go, pkg/report/bsd.go, pkg/report/bsd_test.go, pkg/report/fuchsia.go, pkg/report/linux.go, pkg/report/linux_test.go, pkg/report/report.go, prog/size.go, vm/bhyve/bhyve.go, vm/gce/gce.go, vm/isolated/isolated.go, vm/qemu/qemu.go, vm/vmimpl/util.go, vm/vmm/vmm.go
Let's limit function parameters count to 7.
=> limit functions parameter count to 7

vm/qemu/qemu.go
=> vm/qemu: fix wrong arg usage

tools/syz-covermerger/syz_covermerger.go
It is needed to understand #5889 .
=> tools/syz-covermerger: enable profiling

vm/adb/adb.go
=> vm/adb: change printk level to allow findConsole

pkg/cover/file.go, pkg/covermerger/bq_csv_reader.go, pkg/covermerger/bq_csv_reader_test.go, tools/syz-covermerger/syz_covermerger.go
I expect it to help with #5889.
And I'm still thinking about the tests for this sequential reader...
=> pkg/covermerger: read files sequentially

dashboard/app/batch_main.go
=> dashboard/app: use machines with more memory for batch processing

dashboard/app/main.go, pkg/html/html.go, pkg/html/urlutil/urls.go, pkg/html/urlutil/urls_test.go, syz-cluster/controller/processor_test.go, syz-cluster/dashboard/Dockerfile, syz-cluster/dashboard/handler.go, syz-cluster/dashboard/templates/index.html, syz-cluster/dashboard/templates/series.html, syz-cluster/pkg/db/entities.go, syz-cluster/pkg/db/series_repo.go, syz-cluster/pkg/db/series_repo_test.go, syz-cluster/pkg/db/session_repo_test.go
Add a simple series filtering form (by status and Cc'd lists) + a simple pagination,.
=> syz-cluster: add filtering and pagination

syz-cluster/dashboard/handler.go, syz-cluster/dashboard/templates/index.html, syz-cluster/pkg/db/finding_repo_test.go, syz-cluster/pkg/db/series_repo.go, syz-cluster/pkg/db/series_repo_test.go, syz-cluster/pkg/db/util_test.go
It will help identify the series to highlight.
=> syz-cluster: display the number of findings per series and more

pkg/manager/diff.go, pkg/manager/diff_store.go, pkg/manager/repro.go, pkg/manager/repro_test.go, syz-cluster/dashboard/handler.go, syz-cluster/pkg/db/entities.go, syz-cluster/pkg/db/series_repo.go, syz-cluster/workflow/build-step/main.go, syz-cluster/workflow/fuzz-step/main.go, syz-manager/manager.go, tools/syz-diff/diff.go
Set of diverse changes to fix some syz-cluster bugs and to make it easier to analyze its results.
=> syz-cluster, pkg/manager: assorted improvements

docs/syz_verifier.md
Don't confuse the users by making it look like the tool works.
Fixes #5950.
=> docs: mention that syz-verifier is broken

pkg/rpcserver/runner.go
If we set it too early, it will be filtered out as it is not within the addresses of the .text segment.
=> pkg/rpcserver: fix fallback coverage

pkg/report/linux.go, pkg/report/testdata/linux/report/739
=> pkg/report: ignore xfs-printed warnings

Makefile
=> Makefile: add DEBUG=true env to enable debug symbols

pkg/email/lore/read.go, pkg/vcs/fuchsia.go, pkg/vcs/git.go, pkg/vcs/git_test.go, pkg/vcs/vcs.go, syz-cluster/email-reporter/deployment.yaml, syz-cluster/email-reporter/handler.go, syz-cluster/email-reporter/handler_test.go, syz-cluster/email-reporter/kustomization.yaml, syz-cluster/email-reporter/lore-disk-pvc.yaml, syz-cluster/email-reporter/main.go, syz-cluster/email-reporter/stream.go, syz-cluster/email-reporter/stream_test.go, syz-cluster/pkg/api/reporter.go, syz-cluster/pkg/app/config.go, syz-cluster/pkg/db/entities.go, syz-cluster/pkg/db/migrations/1_initialize.up.sql, syz-cluster/pkg/db/report_reply_repo.go, syz-cluster/pkg/db/report_reply_repo_test.go, syz-cluster/pkg/db/report_repo.go, syz-cluster/pkg/db/report_repo_test.go, syz-cluster/pkg/db/spanner.go, syz-cluster/pkg/db/util_test.go, syz-cluster/pkg/reporter/api.go, syz-cluster/pkg/reporter/api_test.go, syz-cluster/pkg/reporter/generator.go, syz-cluster/pkg/service/discussion.go, syz-cluster/reporter-server/main.go, syz-cluster/series-tracker/main.go, tools/syz-lore/query_lkml.go
=> syz-cluster: poll a lore archive for incoming email messages

syz-cluster/db-mgmt/main.go, syz-cluster/pkg/db/migrations/1_initialize.down.sql, syz-cluster/pkg/db/spanner.go, syz-cluster/pkg/db/spanner_test.go
Add a test that verifies that we have correct down migrations. Fix the down migrations sql file.
=> syz-cluster/pkg/db: test migrations

pkg/manager/diff.go
When running the reproducer from the patched kernel on the base kernel, stay on the safe side when encountering errors and context cancellations.
Always demand 3 successful executions before declaring a bug patched-only.
=> pkg/manager: improve error accounting during diff fuzzing

pkg/report/testdata/linux/report/740
The DEBUG_LIST/LIST_HARDENED changed the internal symbol names. Add a test so that this does not regress.
=> pkg/report: add test for __list_add_valid_or_report

dashboard/app/reporting_email.go, dashboard/app/reporting_test.go, pkg/cover/heatmap.go
The lines about folders don't look actionable.
=> dashboard/app: email regressions in files only

tools/docker/env/Dockerfile, tools/docker/syzbot/Dockerfile
Add the new dependencies necessary for generating RUST=y Linux configs and for building RUST=y kernels.
=> tools/docker: add rust compiler

vm/gvisor/gvisor.go
Many jobs can run concurrently on the same server. Without CPU limits, each job will attempt to utilize all available processing power.
=> vm/gvisor: allow to set a number of cpu-s

dashboard/app/coverage.go, dashboard/app/public_json_api.go, dashboard/app/public_json_api_test.go, pkg/coveragedb/coveragedb.go, pkg/coveragedb/time_period.go
Introduce function options. Build them from http.Request.
Closes #6073
=> dashboard/app: add  manager param to /cover?jsonl=1 output

syz-cluster/workflow/boot-step/main.go
Retry the boot test up to 3 times before letting it fail and reporting the failure as a finding. That should make sure there are fewer false positives amoung the "boot error" and "test error" bugs.
=> syz-cluster/workflow/boot-step: retry before failing

dashboard/app/api.go, dashboard/app/config.go, dashboard/app/email_test.go, dashboard/app/reporting_email.go, dashboard/app/util_test.go, dashboard/dashapi/dashapi.go, pkg/email/parser.go
=> dashboard: assorted email-related changes

pkg/report/crash/types.go, pkg/report/testdata/linux/report/427, pkg/report/testdata/linux/report/428, pkg/report/testdata/linux/report/449, pkg/report/testdata/linux/report/750, pkg/report/title_to_type.go
Introduce crash.KCSANAssert. We didn't have tests for this type.
Introduce crash.KCSANUnknown.
=> pkg/report: split crash.KCSAN

pkg/corpus/corpus.go, pkg/manager/diff.go, syz-cluster/workflow/fuzz-step/main.go
Don't waste time doing focused fuzzing if no modified code has been reached in 30 minutes after corpus triage.
=> pkg/manager: abort fuzzing if no patched code is reached

pkg/build/linux.go
=> pkg/build: set KERNELRELEASE for more reproducible builds

syz-cluster/email-reporter/handler.go, syz-cluster/email-reporter/main.go, syz-cluster/email-reporter/stream.go, syz-cluster/overlays/gke/prod/global-config.yaml
Give more visibility into what the component is doing and why it fails.
=> syz-cluster: improve email-reporter logging

syz-cluster/email-reporter/Dockerfile
Use a more advanced base container in order to install git.
=> syz-cluster: update email-reporter's Dockerfile

syz-cluster/kernel-disk/fetch-kernels-template.yaml, syz-cluster/pkg/api/api.go
=> syz-cluster: fix netdev-next tree URL

syz-cluster/overlays/gke/prod/global-config.yaml, syz-cluster/pkg/api/api.go, syz-cluster/workflow/configs/bpf/base.cfg, syz-cluster/workflow/configs/bpf/patched.cfg
* Add separate trees and configs for bpf.
* Poll the bpf and netfilter mailing lists.
=> syz-cluster: fuzz more net series

syz-cluster/kernel-disk/fetch-kernels-template.yaml
Set TTL for the workflow and the pods it creates.
=> syz-cluster: don't keep kernel fetch jobs for too long

dashboard/config/openbsd/recreate.sh, tools/create-openbsd-gce-ci.sh
Make the host name configurable.
=> dashboard/config/openbsd, tools: fixes to update ci-openbsd

pkg/fuzzer/fuzzer_test.go
Ensure that corpus and signal are non-zero after the bugs have been found.
Fix coverage configuration - the test was de facto running on a fallback coverage.
***
Something changed. At the beginning, any extra checks for coverage and corpus were not necessary - by the time the planted crashes were found, the fuzzer already had fully triaged several candidates and had non-zero signal. It's worth extra debugging, but for now let's just tighten the test.
=> pkg/fuzzer: improve TestFuzz

syz-cluster/overlays/gke/prod/global-config.yaml, syz-cluster/pkg/api/api.go, syz-cluster/workflow/configs/io-uring/base.cfg, syz-cluster/workflow/configs/io-uring/patched.cfg
=> syz-cluster: fuzz io-uring and wireless patch series

tools/syz-lore/query_lkml.go
Instead of accepting a folder name and traversing all nested folders in it, accept the directories to process as separate arguments. This allows for more flexibility - one can either specify just one archive to process or one can use bash wildcards to achieve the previously default functionality.
=> tools/syz-lore: support bash wildcard results

syz-cluster/dashboard/templates/index.html, syz-cluster/pkg/db/entities.go
=> syz-cluster: display the session processing time

syz-cluster/controller/processor.go
Print a bit more info to the logs to make them more understandable.
=> syz-cluster: log finished session status
