google/syzkaller

executor/common_linux.h, pkg/csource/generated.go
When BLK_DEV_WRITE_MOUNTED is set, the kernel treats the loopfd reference as a writer and does not let us issue mount() calls over the same block device.
=> executor: don't hold a loop device fd

pkg/vcs/git.go, pkg/vcs/git_test.go, pkg/vcs/linux.go
This should make syzkaller only fetch the commits relevant for further processing. Also, specifying the exact commit/branch name to fetch allows us to access commits from custom refs.
Test the new behaviour and double-check that remote tags fetch was not broken.
=> pkg/vcs: make git fetch calls more specific

prog/rand.go
Only the values of the returned array are of interest.
=> prog: fix an invalid rnd.Perm() invocation

syz-ci/manager.go, syz-ci/syz-ci.go
Introduce a new manager config -- the maximum allowed (non-)freshness of the kernel image that we fuzz. Once the kernel image is old enough and we're unable to build a newer version, don't start the instance.
=> syz-ci: limit fuzzing of old kernel images

prog/minimization.go
In many cases we can remove all calls that follow the call of interest.
Try this before deleting them one-by-one.
---
I've set up a syz-testbed experiment. Let's see how it goes.
=> prog: optimize call minimization

dashboard/app/jobs.go, dashboard/app/reporting.go, dashboard/app/reporting_test.go, dashboard/app/util_test.go
In case or build/boot/test errors there will never be a reproducer. It's better to report them right away, without waiting.
=> dashboard: wait for repro only when it makes sense

pkg/instance/instance.go, syz-fuzzer/fuzzer.go, syz-manager/manager.go, vm/gvisor/gvisor.go, vm/vm.go, vm/vmimpl/vmimpl.go
In some cases (e.g. gVisor instances using host's network namespace) attempts to bind() all syz-fuzzer processes to the same port result in conflicts and fuzzing breakages.
Refactor the code to enable custom pprof configuration depending on the vm type.
For now, just disable pprof endpoints for gVisor VMs. Once we actually need the feature there, we can generate custom ports for every gVisor VM.
Cc @avagin
=> all: refactor pprof endpoint configuration

dashboard/app/api.go, dashboard/app/entities.go, dashboard/app/graph_fuzzing.html, dashboard/app/graphs.go, dashboard/dashapi/dashapi.go, syz-manager/manager.go
This statistics allows us to better estimate the amount of coverage that is lost after every syzbot instance is restarted.
=> dashboard: capture cover and PCs after corpus triage

syz-ci/manager.go
If the kernel build is broken, we must have already filed a bug for it. Let's just print to the logs instead of recording an error.
=> syz-ci: make stale kernel error less noticeable

pkg/rpctype/rpctype.go, syz-fuzzer/fuzzer.go, syz-manager/rpc.go
Add an RPC call to post a log message to syz-manager directly from syz-fuzzer.
It's very convenient during the debugging and profiling of the actual fuzzing code.
=> syz-fuzzer: add logging RPC call

pkg/instance/instance.go, pkg/ipc/ipc.go, pkg/mgrconfig/config.go, syz-fuzzer/fuzzer.go, syz-fuzzer/proc.go, syz-manager/manager.go
In the cases where we do not / cannot sandbox individual prog executions well enough, some share of progs end up being dependent on the previously accumulated state of the whole VM.
As the result,
* We lose 5-10% of coverage/signal on every instance restart.
* A share of our corpus programs do not actually trigger the coverage they were thought to reliably trigger.
This significantly affects fuzzing efficiency and prevents syzkaller from accumulating bigger and better corpus over multiple runs.
Let's see if the situation becomes better if we restart syz-executor before most of prog executions.
=> all: experiment with an option to reset accumulated state

pkg/cover/backend/backend.go, pkg/cover/backend/dwarf.go, pkg/cover/html.go, pkg/cover/report.go
Some regression happened in Jun 2021. This PR fixes that regression and return additional frames to our coverage.
Briefly - if some addr has 10 associated frames, we take first for the visualization and drop others.
rawcoverfiles shows all the frames now and additionally explains Inlining context.
=> pkg/cover: fix missing frames and export Inline by /rawcoverfiles

dashboard/app/api.go, dashboard/app/repro_test.go, dashboard/dashapi/dashapi.go, syz-manager/hub.go, syz-manager/manager.go
See commit descriptions.
In short, this PR adds new functionality:
* If `pkg/repro` returned a differently titled crash, record a failed bug reproduction attempt on the original crash.
* If there have been neither successful nor failed bug reproduction attempts, instruct syz-managers to repeat bug reproduction using older crash logs.
=> dashboard: reproducer management improvements

pkg/csource/csource.go, pkg/csource/csource_test.go, prog/target.go, prog/types.go, sys/syz-sysgen/sysgen.go, sys/test/csource.txt, sys/test/csource.txt.const
This factorizes const arguments into the shortest flags OR bitmask possible so they are easy to read. E.g:
```
/*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul
```
--- 
This follows up on prior discussions at https://github.com/google/syzkaller/pull/3947#pullrequestreview-1472130493
I'm not quite sure what to do of `ParseDescriptions` to be honest... I extracted calls to this function int the `Write` callers so they have more control over the syscall descriptions directory but it's still implemented in `csource.go`. Any guidance on how to make this nicer is very welcome! :)
=> pkg/csource: annotate syscall() args with their pretty-printed values

pkg/cover/backend/backend.go, pkg/cover/backend/dwarf.go, pkg/cover/backend/dwarf_test.go, pkg/cover/backend/elf.go, pkg/cover/report.go, pkg/mgrconfig/config.go
Source files for Pixel devices are split between the common AOSP kernel
(path/to/kernel/aosp) and the device-specific drivers residing in a
separate dir (path/to/kernel/private/google-modules for Android 14
and path/to/kernel/gs/google-modules for older Android versions).
See https://source.android.com/docs/setup/build/building-pixel-kernels
for details.
Android build system may reference these dirs in various ways, for which
syzkaller cannot always understand where it should look for the source.
The newly introduced split_build flags handles the problem by adding a
list of "delimiters" used when normalizing the kernel source paths.
If the path contains any of such delimiters ("/aosp/", "/gs/" or
"/private/"), then everything preceding the last delimiter in the path
is replaced with the …
=> introduce the split_build flag

syz-manager/hub.go, syz-manager/manager.go
From dashboard we receive logs, from syz-hub - ready reproducers. They must be treated differently.
If we failed to find a repro from the log, report a failure back to the dashboard. If we succeeded, prepend the options.
=> syz-manager: differentiate between repros from hub and from dashboard

vm/vm.go, vm/vm_test.go
In this mode, all syz-fuzzers will be on the same network and will start competing with each other for binding to the same port.
For now, we don't have the need to use pprof in the host fuzzer mode, so let's just disable it.
=> syz-manager: don't set up pprof endpoints for host fuzzing

dashboard/app/api.go, dashboard/app/app_test.go, dashboard/app/config.go, dashboard/app/entities.go, dashboard/app/jobs.go, dashboard/app/mail_fix_candidate.txt, dashboard/app/main.go, dashboard/app/tree_test.go, dashboard/dashapi/dashapi.go
Poll missing backport commits and, once a missing backport is found to
be present in the fuzzed trees, don't display it on the web dashboard
and send an email with the suggestion to close the bug.
Closes https://github.com/google/syzkaller/issues/4425.
=> dashboard: retest missing backports

syz-ci/manager.go, syz-manager/manager.go
Currently it's hard to understand individual syz-manager decisions during repro processing.
=> syz-manager: add more logging for repro reporting 

executor/common_linux.h, pkg/csource/generated.go
```
The fd may be closed by an async close() call, it's not a reason to report a failure.
Reported-by: Andrei Vagin <avagin@google.com>
```
Cc @avagin
=> executor: don't fail in syz_socket_connect_nvme_tcp()

prog/analysis.go, prog/any.go, syz-manager/hub.go, syz-manager/manager.go, syz-manager/rpc.go
In case of non-squashed programs we can leverage our descriptions in a much better way than just blind mutations of binary blobs.
=> syz-manager: prefer non-ANY progs in corpus minimization

.gitignore, dashboard/app/.gcloudignore
gcloud beta app deploy in GOMOD uploads 1.7G of data.
There is a way to see what files were recently uploaded. Let's get working solution first and review how can we reduce 1.7G to the current 30M.
To see what files were uploaded:
$ version=$(gcloud app --project=syzkaller versions list --sort-by '~version'
--format='value(version.id)' --hide-no-traffic --limit=1)
$ gcloud app --project=syzkaller versions describe --service=default "$version"
Origin: https://www.googlecloudcommunity.com/gc/Developer-Tools/Viewing-code-currently-deployed-in-App-Engine/m-p/605823
=> .gcloudignore: enable blacklist

pkg/cover/html.go, pkg/cover/report.go, pkg/cover/report_test.go, syz-manager/html.go, tools/syz-cover/syz-cover.go
Debugging coverage point validation warnings may require looking at specific addresses, which are not printed anywhere. Add a URL parameter that can be passed to prepareFileMap() to print a more meaningful error message.
=> pkg/cover, syz-manager: introduce the /cover?debug=1 parameter

syz-manager/manager.go
The log is apparently too big, which results in numerous code 413 errors.
Let's not include the repro log for some time before #4495 is fixed.
=> syz-manager: pause log reporting for successful repros

dashboard/config/linux/bits/base.yml, dashboard/config/linux/upstream-kmsan-base.config, dashboard/config/linux/upstream-kmsan.config
KMSAN is currently reporting boot-time false positives in debugging code called from stackdepot.c (see https://github.com/google/syzkaller/issues/4504)
Disable CONFIG_DEBUG_LIST under KMSAN until the fix lands.
=> dashboard/config: temporarily disable CONFIG_DEBUG_LIST for KMSAN

pkg/report/linux.go, pkg/report/testdata/linux/report/711
This library method is used in multiple places throughout the kernel.
Sample bug: https://syzkaller.appspot.com/bug?extid=dfab1425afcdae5ac970
=> pkg/report: ignore ida_free

pkg/cover/backend/dwarf.go, pkg/cover/backend/elf.go, pkg/cover/backend/elf_test.go, pkg/cover/backend/mach-o.go
Certain ARM64 builds continued reporting errors about coverage points not matching __sanitizer_cov_trace_pc calls. It turned out such coverage originated from calls to ____sanitizer_cov_trace_pc_veneer functions that are inserted by the linker to extend the range of BL instructions (limited by +/-128M).
Add support for __funcname_veneer functions to ELF to make sure this coverage is correctly attributed.
=> pkg/cover/backend: support veneers on ARM64

dashboard/app/README.md
1. We use modules now.
2. gcloud app deploy supports app_engine_apis flag.
3. "gcloud beta app deploy" believes project root is syzkaller/ and doesn't work.
=> dashboard/app/README.md: update gcloud howto

CONTRIBUTORS, vm/qemu/qemu.go
`os.Stat()` may return `(nil, err)` if it fails to open a file.
So, the code below wrongly validates `st` as it will be always `nil` if `err != nil`, causing nil pointer dereference in `st.Size()`.
```go
if st, err := os.Stat(inst.image); err != nil && st.Size() == 0 {
```
To fix this, this patch allows st.Size() only if `err == nil`.
=> vm/qemu.go: fix nil-ptr-deref in ctor

pkg/ipc/ipc.go
This change was taken out of https://github.com/google/syzkaller/pull/4509
***
We used to optimize the memory usage by making the slices of individual CallInfo structs point to the shared memory buffer between syz-fuzzer and executor.
However, this puts very strict expectations on all pkg/ipc users and complicates the decoupling of the fuzzing logic from individual proc loops.
Let's try to live without this optimization. When compared with the cost of a single syz-executor execution, the cost of array copying is very very small anyway.
=> pkg/ipc: copy signal and coverage

pkg/report/report.go, pkg/report/report_test.go, syz-manager/manager.go
Until we have figured out a way to solve #4495, let's just truncate repro logs before sending them over the dashboard API.
=> syz-manager: truncate repro logs before reporting

prog/resources_test.go
They used to depend on the side effects of BuildChoiceTable().
=> prog: fix TestCreateResource tests

pkg/cover/backend/modules.go, pkg/host/machine_info.go, pkg/host/machine_info_linux.go, tools/syz-cover/syz-cover.go
The address from /proc/modules is not necessarily the address of .text, e.g., can be the address of .plt.
If available, fix up the module address using the address from /sys/module/<module-name>/sections/.text
This patch was originally uploaded to
https://github.com/google/syzkaller/pull/4025.
Since then, it was reworked to store the addresses obtained from /proc/modules (aka `ProcAddr`) and /sys/module (aka `Addr`) independently.
=> pkg/host: get module .text address from /sys/module

pkg/cover/backend/dwarf.go, pkg/cover/backend/elf.go, pkg/cover/backend/modules.go
Since commit 971a0f14c5cf6 ("pkg/host: get module .text address from /sys/module") getModuleOffset() is not used by anyone, so it should be safe to delete it.
=> pkg/cover: delete getModuleOffset()

.github/workflows/ci.yml
It is to avoid "tput: No value for $TERM and no -T specified" in logs.
=> ci.yml: let's dumb the TERM

.github/workflows/ci.yml, Makefile, dashboard/app/util_test.go
There are 2 reasons:
1. They take 82/346 seconds. TOP2 candidate takes 38 seconds.
2. They pollute output adding 14k log lines.
$ cat race_logs.txt | grep github.com/google/syzkaller | grep -v files | grep ok | awk '{print $3, $4}' |  rev | cut -c2- | rev | awk '{print $2, $1}' | sort -rn
82.796 github.com/google/syzkaller/dashboard/app
38.479 github.com/google/syzkaller/pkg/host
28.317 github.com/google/syzkaller/pkg/runtest
17.904 github.com/google/syzkaller/prog
16.030 github.com/google/syzkaller/pkg/db
15.192 github.com/google/syzkaller/pkg/ipc
11.147 github.com/google/syzkaller/pkg/compiler
9.869 github.com/google/syzkaller/vm
8.882 github.com/google/syzkaller/pkg/cover/backend
7.515 github.com/google/syzkaller/pkg/ast
6.898 github.com/google/syzkaller/pkg/cover
6.778 …
=> run dashboard race tests independently

.github/workflows/ci.yml
Old path works for ./tools/syz-env container and doesn't work for the new configuration.
=> .github/workflows/ci.yml: fix cache paths

pkg/ast/testdata/all.txt, pkg/compiler/check.go, pkg/compiler/testdata/errors2.txt
Commit ed571339c6ff ("pkg/compiler: support if[expr] attributes") added support for conditional fields in structs and unions. Conditions however cannot refer to flags, as in the following example:
struct {
f0 flags[some_flags, int32]
f1 int32                     (if[value[f0] & FLAG1])
} [packed]
It will fail to compile with:
flags does not refer to an integer
This commit adds support for that syntax.
=> compiler: support using int flags in field conditions

pkg/vcs/git.go, pkg/vcs/git_test.go
The approach we used works perfectly for all commits, but they must be referenced by the full 40 character hash. In almost all cases, users would prefer to use the shorter one.
If the commit hash is not 40 characters long, fetch the whole git tree.
The only unsupported scenario is fetching a commit that is referenced by custom refs/* by its short hash. It's unlikely there's anything we can do here.
=> pkg/vcs: support fetches by a short git hash

dashboard/app/jobs.go, dashboard/app/jobs_test.go
In our reports, we sometimes supply short alias names for the repositories. It was confusing for our users why they could not use that same short name in patch testing requests.
Closes #2265.
=> dashboard: allow repo aliases in patch testing requests

.github/arc_config/values.yaml
We use machines with 32 CPU and 32 RAM.
Adding this options we prevent 2 runner PODs scheduling to the same node.
=> .github/workflows/ci.yml: require min 31 core per test job

.github/workflows/ci.yml
codecov [uploader believes](https://github.com/codecov/uploader/blob/8ebf576d1180832f5b66fc66f3271b3df998b157/src/ci_providers/provider_githubactions.ts#L11) GITHUB_ACTIONS env signal about github actions environment.
At least for the kubernetes mode actions runner controller this assumption is not correct.
Let's help codecov to understand who is who.
=> .github/workflows/ci.yml: workaround codecov limitation to detect environment

prog/clone.go, prog/encoding.go, prog/expr.go, prog/expr_test.go, prog/minimization.go, prog/mutation.go, prog/prog.go, prog/rand.go, prog/test/fuzz_test.go, prog/types.go, prog/validation.go, sys/linux/init_iptables.go, sys/linux/init_vusb.go, sys/test/expressions.txt
```
The replaced union field may contain resource references that must also be cleaned up.
The bug was triggered via methods that patch conditional fields, so let's add stress tests for the conditional fields + resources combination.
Reported-by: Paul Chaignon <paul.chaignon@gmail.com>
```
=> prog: assorted fixes for conditional fields

pkg/build/cuttlefish.go
Supporting configs from syz-kconf has increased complexity in reproducing builds, and not caused any quantifiable increase in fuzzing efficacy or crashes.
Reverting the Cuttlefish build to use upstream build commands to increase ease in reproduction.
=> build/cuttlefish: revert input config support

pkg/fuzzer/job.go, prog/hints.go, prog/hints_test.go, prog/rand_test.go, tools/syz-execprog/execprog.go, tools/syz-mutate/mutate.go
We don't need to try out all possible mutations. It can be very slow for
large programs, so let's limit the number of hint mutations to 100.
=> prog: speed up TestDeterminism() 

docs/linux/external_fuzzing_usbip.md
The asterisks are useless in the markdown title starting with #.
Fix this by removing them.
=> docs/linux: remove asterisks in the markdown title

CONTRIBUTORS, pkg/bisect/bisect.go, pkg/vcs/linux.go
When using the bisect script, we noticed that some bisection just failed as the config minimization internally failed and the bisect script then just gave up. However, we can actually continue bisection with the original config and still find reasonable bisection results. The needed change for that behavior is small and simple.
=> make bisection more robust in case of config minimization failures

vm/bhyve/bhyve.go, vm/cuttlefish/cuttlefish.go, vm/gce/gce.go, vm/isolated/isolated.go, vm/qemu/qemu.go, vm/vmimpl/util.go, vm/vmm/vmm.go, vm/vmware/vmware.go
Most of the VM types tightly manage the target they SSH into and can safely assume that system wide SSH configuration would mess with the SSH flags provided by syzkaller. However, in the "isolate" VM type, one can connect to a host that is not at all managed by syzkaller. In this case, it can be useful to leverage system wide SSH config, maybe provided by a corporate environment.
This adds an option to the isolated config to skip some of the SSH and SCP flags that would drop system wide config.
=> vm/isolated: allow the use of system-wide SSH config

pkg/cover/backend/backend.go, pkg/cover/backend/dwarf.go, pkg/cover/html.go, pkg/cover/report.go, pkg/cover/report_test.go, syz-manager/http.go
This data flow generates information only about the visited files.
We need more to calculate coverage numbers. I'll extend this dataflow in the following PRs.
This data is enough to start the data aggregation experiments or detect regressions.
=>  pkg/cover: export the frames data as jsonl

pkg/fuzzer/fuzzer.go, pkg/fuzzer/job.go
We are already trying to filter out any flaky coverage at that stage. Any new signal that we got by re-running the same program can be automatically treated as flaky as well.
=> pkg/fuzzer: ignore new max signal during triage

pkg/cover/backend/backend.go, pkg/cover/backend/dwarf.go, pkg/cover/html.go, pkg/cover/report.go
First request with lazy symbolization - 19s.
Time to get updated numbers (after 5 seconds) - 17s.
Lazy symbolized data - 361k lines, 61M.
First request with full symbolization - 49s.
Time to get fresh data (after 5 seconds)  - 5.5s.
Fully symbolized data - 3491k lines, 611M.
/cover uses 40G RAM every time it is called.
/cover?jsonl=1 uses 40G RAM only the first time. /cover takes 3 seconds and consumes 0 RAM if called after.
=> pkg/cover: add full symbolization for /cover?jsonl=1

prog/clone.go, prog/rand.go
In practice, we need to try out many different corpus programs before we may find a matching resource. It's very inefficient to Clone() each of them.
This change gives a +76% speed improvement in the BenchmarkMutate() test.
```
│ upstream      │              optimized                  │
│    sec/op     │    sec/op     vs base                   │
Mutate-36     443.1µ ± 8%   103.1µ ± 31%  -76.73% (p=0.000 n=15+25)
│ upstream      │              optimized                  │
│    B/op       │    B/op     vs base                     │
Mutate-36    836.0Ki ± 1%   188.8Ki ± 0%  -77.42% (p=0.000 n=15+25)
│ upstream      │              optimized                  │
│  allocs/op    │      allocs/op     vs base              │
Mutate-36     2.643k ± 1%       1.778k ± 0%     -32.73% (n=15+25)
```
=> prog: optimize resourceCentric()

.golangci.yml, pkg/cover/html.go, pkg/cover/manager_to_ci.go, pkg/cover/manager_to_ci_test.go, pkg/cover/report_test.go, syz-ci/manager.go, syz-ci/syz-ci.go
The goal is to put coverage details into DB.
Available options:
1. To put them directly. It will require the DB usage code.
2. To use GCP template pipelines. GCS based or Pub/Sub based pipeline.
GCS based pipeline looks the easiest because we already have GCS integration code.
=> syz-ci: stream coverage from manager to gcs

syz-ci/manager.go
dashboard_client maps 1:1 to the namespace
upstream is the only exception with 2 clients
=> syz-ci/manager.go: save jsonl to namespace folder

pkg/vcs/vcs_test.go
There's unfortunately no consistency in how mail.ParseAddress reacts to parentheses in display names.
Versions before 1.22 used to keep them, 1.22+ cut them out.
For syzbot operation the difference is not very significant, but it makes our tests too version dependent. Let's just omit parentheses from the test cases.
=> pkg/vcs: remove parentheses from email tests

pkg/corpus/corpus.go, pkg/cover/canonicalizer.go, pkg/cover/canonicalizer_test.go, pkg/fuzzer/cover.go, pkg/fuzzer/fuzzer.go, pkg/fuzzer/fuzzer_test.go, pkg/fuzzer/job.go, pkg/fuzzer/prio_queue.go, pkg/fuzzer/prio_queue_test.go, pkg/fuzzer/stats.go, pkg/rpctype/rpctype.go, pkg/signal/signal.go, pkg/signal/signal_test.go, syz-fuzzer/fuzzer.go, syz-fuzzer/fuzzer_test.go, syz-fuzzer/proc.go, syz-manager/http.go, syz-manager/hub.go, syz-manager/manager.go, syz-manager/rpc.go, syz-manager/stats.go
The version seems to be working locally, but there are still a lot of experiments and improvements to be done.
While it's still under development, I don't see sense in splitting it into smaller commits. I will later probably split out some of the changes that don't break their dependencies in an incompatible way.
Parent issue: #1541
***
Instead of doing fuzzing in parallel in running VM, make all decisions in the host syz-manager process.
Instantiate and keep a fuzzer.Fuzzer object in syz-manager and update the RPC between syz-manager and syz-fuzzer to exchange exact programs to execute and their resulting signal and coverage.
To optimize the networking traffic, exchange mostly only the difference between the known max signal and the detected signal.
=> all: move fuzzer to the host

tools/create-openbsd-gce-ci.sh
Reliance on -fsanitize-coverage=trace-pc makes clang look for full ubsan libraries. The only one currently available on OpenBSD is ubsan_minimal. We temporarily use it in place of ubsan_standalone. The ubsan_standalone_cxx library seems currently not necessary and so an empty file works in its stead.
This is a temporary measure until I figure out the best course of action for making fsanitize-coverage=trace-pc work out of the box on OpenBSD.
This should help with one of the issues we just discovered having replaced the base OS image we use to run syzkaller on OpenBSD.
=> tools/create-openbsd: substitute ubsan_minimal for fuzzer_test

syz-fuzzer/fuzzer.go
In case of a reproducible syz-executor failure, we could end up with a nil ipc.ProgInfo object. Don't dereference it.
=> syz-fuzzer: avoid a nil ptr dereference

pkg/cover/manager_to_ci_test.go, pkg/cover/report_test.go
The sampleCoverJSON was defined in a Linux-only test file.
Cc @blackgnezdo
=> pkg/cover: make tests build for non-Linux targets

syz-manager/manager.go, syz-manager/rpc.go
If a VM was e.g. intentionally restarted, there's no need to discard all pending requests.
Remember them and then redistribute to other VMs.
=> syz-manager: resend inputs from non-crashed VMs

docs/internals.md
After #4579, `syz-fuzzer` no longer performs the actual fuzzing.
=> docs: update the details on the syzkaller architecture

pkg/osutil/osutil.go, pkg/osutil/osutil_test.go, syz-fuzzer/fuzzer.go, tools/syz-linter/linter.go
time.Now/Since may reject to use monotonic time if the fuzzer
messes with system time badly enough. Enforce use of monotonic time.
=> syz-fuzzer: use of monotonic time for latency measurement

pkg/report/linux.go, pkg/symbolizer/cache.go, pkg/symbolizer/cache_test.go
When the same crash happens all over again,
we repeatedly symbolize the same PCs.
This is slow and blocks VM loop in the manager.
Cache PCs we already symbolize, we are likely
to symbolize them again.
=> pkg/symbolizer: add Cache type

executor/common_linux.h, pkg/csource/generated.go
Don't treat ENOENT from socket call as fatal.
Fuzzer manages to make all socket calls for a particular
protocol fail using NLBL_MGMT_C_REMOVE netlink function.
=> executor: ignore ENOENT for socket calls

syz-ci/manager.go
It currently uses "dashboard_client" from ci config.
=> syz-ci/manager.go: use dashboard_client from manager config

pkg/corpus/corpus.go, pkg/fuzzer/fuzzer.go, pkg/fuzzer/job.go, pkg/instance/instance.go, pkg/rpctype/rpc.go, prog/prog.go, syz-fuzzer/fuzzer.go, syz-hub/hub.go, syz-manager/hub.go, syz-manager/manager.go, syz-manager/rpc.go, syz-runner/runner.go, syz-verifier/rpcserver.go, tools/syz-hubtool/hubtool.go, tools/syz-runtest/runtest.go, vm/adb/adb.go, vm/bhyve/bhyve.go, vm/cuttlefish/cuttlefish.go, vm/gce/gce.go, vm/gvisor/gvisor.go, vm/isolated/isolated.go, vm/kvm/kvm.go, vm/proxyapp/init.go, vm/qemu/qemu.go, vm/starnix/starnix.go, vm/vm.go, vm/vm_test.go, vm/vmimpl/vmimpl.go, vm/vmm/vmm.go, vm/vmware/vmware.go
Currently we throw away saturated calls only after triage/minimization.
Triage/minimization is unnecessary for saturated calls,
we already know we will throw them away later.
Don't send saturated calls for triage/minimization.
=> pkg/fuzzer: don't triage saturated calls

executor/executor_linux.h
Because the executor may place other mappings next to the buffer used by kcov, occasional out-of-bound writes to them may corrupt the coverage, creating garbage PCs (see https://github.com/google/syzkaller/issues/4531).
To prevent those, map two extra pages for the kcov buffer, and protect them, so that OOB writes cause a segfault.
Fixes https://github.com/google/syzkaller/issues/4532
=> executor: add guard pages around the kcov mapping

pkg/corpus/corpus.go, pkg/corpus/minimize.go
The following two operations were in conflict:
1) Overwriting of corpus.ProgramsList in Minimize().
2) ProgramsList.ChooseProgram() that used its own mutex.
Instead of overwriting the object, let's create a new one.
=> pkg/corpus: avoid a race in Corpus.Minimize()

pkg/fuzzer/fuzzer_test.go, pkg/fuzzer/job.go, pkg/fuzzer/job_test.go
Demand that at least 3 out of 5 runs share common signal. Exit early if it's not feasible.
It should to some degree address the problem described in #4639.
=> pkg/fuzzer: make deflake() more flexible

executor/common_ext_test.go, pkg/fuzzer/fuzzer_test.go, pkg/ipc/ipc_test.go, sys/targets/targets.go
OpenBSD's missing syscall function yet TestOS requires it.
=> sys/targets: avoid building TestOS on OpenBSD

docs/translations/zh_CN/usage.md
Finish the translation of docs/usage.md. Our current policy is to keep the English link of untranslated documents.
Note that, all the relative paths of documents need relocation since these documents may not be translated.
=> docs/translations: add zh_CN translation of usage.md

pkg/rpctype/rpctype.go, syz-fuzzer/fuzzer.go, syz-manager/http.go, syz-manager/hub.go, syz-manager/manager.go, syz-manager/rpc.go, tools/syz-runtest/runtest.go
Currently we store whole CheckResult in the manager and send
it back to fuzzers. It is somewhat large for both storing
in memory and sending each time to fuzzers.
We already clear DisabledCalls in CheckResult before storing it
to save space. But we also don't need to store/send EnabledSyscalls.
Currently we use CheckResult.GlobFiles in the fuzzer to update
prog package, but we don't need to do it. That's a leftover from
"fuzzer in the VM" times. We don't generate programs in the fuzzer
anymore.
The only bit we really need it CheckResult.Features, so store/send
just them.
=> syz-manager: don't store whole CheckResult

docs/translations/zh_CN/program_syntax.md
The translation of program_syntax.md is done. There is no relative link in the document, no worry about relocation.
=> docs/translations: add the translation of program_syntax.md

pkg/fuzzer/job.go, pkg/fuzzer/job_test.go, pkg/signal/signal.go, pkg/signal/signal_test.go
We don't want to reach just any stable signal, we know the specific new signal that we target. The previous approach might have reduced the efficiency of the new deflake() approach.
=> pkg/fuzzer: deflake against new signal

pkg/symbolizer/symbolizer.go, sys/targets/targets.go, tools/docker/syzbot/Dockerfile
Use llvm-addr2line instead of addr2line if it's available.
llvm-addr2line seems to be way faster than llvm-addr2line
and consumes less memory on syzbot's vmlinux.
Also move the detection logic to sys/targets since that's
where we generally do this type of logic. This also allows
to reuse addr2line binary in other packages if needed.
Update #4461
=> pkg/symbolizer: use llvm-addr2line

pkg/cover/html.go, pkg/cover/report.go
prepareFileMap does more work than we need and leads to incorrect hit counts.
prepareFileMap produces hit counts per source line (for source reports),
but jsonl exports data based on coverage callbacks, not source lines.
So if we have 2 callbacks on the same line, we will double count them
(both will have hit count 2). If we calculate total percent later
based on that data, it will be wrong.
Use simpler calculation based on PCs.
=> pkg/cover: fix jsonl hit count calculation

syz-ci/manager.go, syz-manager/cover.go, syz-manager/http.go
Flush manager coverage report generator after requesting JSONL report.
We won't use coverage reports after this point, but it consumes gigs of RAM.
=> syz-ci: flush coverage report generator

pkg/cover/backend/dwarf.go, pkg/symbolizer/cache.go, pkg/symbolizer/symbolizer.go, pkg/symbolizer/symbolizer_test.go
Intern/deduplicate file/func strings created during symbolization.
There are lots and lots of duplicates.
In my local run syz-manager heap size jumps from 1.9G to 4.0G
are requesting /cover?jsonl=1 without this change, and from
1.9G to 2.9G with this change.
=> pkg/symbolizer: intern file/func strings

pkg/report/linux.go, pkg/report/testdata/linux/report/712
In some cases, we may only collect a part of the kernel output. There are no other "mand mount option" warnings in the kernel, so let's match by a shorter regexp.
=> pkg/report: make "mand mount option" regexps more robust

pkg/cover/html.go, pkg/cover/report.go, syz-manager/http.go, tools/syz-cover/syz-cover.go
When coverage points returned by kcov do not have corresponding coverage callbacks, this may indicate a problem with irrelevant signal being used for fuzzing. Therefore, by default syz-manager reports errors and does not show the coverage report in this case.
However, these errors can be annoying when onboarding new platforms, so the new `ignore_mismatching_coverage` flag is introduced to disable them. We still do not recommend to use it widely (e.g. on syzkaller.appspot.com)
=> pkg/cover, pkg/mgrconfig: introduce the ignore_mismatching_coverage flag

executor/common_linux.h, pkg/csource/generated.go
Starting from v6.9, we can no longer reuse a loop device while some filesystem is mounted on it. It conflicts with the MNT_DETACH approach we were previously using.
Let's umount synchronously instead, but also with a MNT_FORCE flag to abort potentially long graceful cleanup operations. We don't need them for the filesystems mounted only for fuzzing purposes.
=> executor: cleanup mounts with MNT_FORCE

pkg/cover/report_test.go
The TestReportGenerator/linux-riscv64/good-pie-relocs is broken due to some misinteroperability between gcc riscv cross-compiler and llvm-addr2line.
Run the test only with clang.
=> pkg/cover: fix riscv tests

vm/qemu/qemu.go
We're seeing a lot of `Image format was not specified for '%PATH' and probing guessed raw.` errors.
=> vm/qemu: use the new options format for NetBSD

pkg/build/netbsd.go
We used to do that before, but somehow we now pass the -enable-kvm flag.
=> pkg/build: run NetBSD in qemu emulation

prog/prio.go, prog/prio_test.go
Two changes:
1) Instead of multiplying static and dynamic prios, add them 1:1.
2) For dynamic priorities, limit the effect of too frequent call
combinations by taking a sqrt() of the value.
On syz-testbed experiments, the updated algorithm triggers 5-10% more different crash types.
As before, there is no big theory behind the approach :)
=> prog: update the choice table aglorithm

pkg/fuzzer/job.go
We used to send the non-modified program for execution.
=> pkg/fuzzer: fix fault injection

prog/prio.go
We don't use Enabled() anywhere.
=> prog: cleanup ChoiceTable

syz-fuzzer/fuzzer.go, syz-fuzzer/proc.go, syz-manager/manager.go, syz-manager/stats.go, tools/syz-execprog/execprog.go
- syz-manager: set firstConnect later
- syz-manager: show suppressed crashes on metrics graphs
- syz-fuzzer: don't sleep after transient executor errors
=> dvyukov manager misc

dashboard/app/getjson_test.go, dashboard/app/public_json_api.go
There's little sense to make users query that information in separate queries when we already have it available.
=> dashboard: include fix commits into terminal page JSONs

vm/starnix/starnix.go
2 updates necessitated by recent starnix changes:
- push the syz-executor binary to /tmp rather than /data
- mark the syz-executor binary as executable after pushing to the VM
=> Updates to starnix VM startup process

executor/executor.cc, pkg/csource/csource.go, prog/decodeexec.go, prog/encoding_test.go, prog/encodingexec.go, prog/encodingexec_test.go, prog/test/fuzz.go, sys/test/test.txt
- prog: use leb128 for exec encoding
- prog: don't pad data in exec encoding
- prog: more compact exec encoding for addresses
- prog: profile what consumes space in exec encoding
=> prog: optimize exec format encoding

pkg/ipc/ipc.go, pkg/ipc/ipcconfig/ipcconfig.go, syz-fuzzer/proc.go
1. Move the flag to Config (logically belongs there).
2. Create rate limter lazily (it's not needed most of the time).
This will help to stop passing *prog.Prog to Exec method.
=> pkg/ipc: refactor rate limiting

pkg/fuzzer/fuzzer.go, pkg/fuzzer/job.go, pkg/rpctype/rpctype.go, pkg/signal/signal.go, syz-fuzzer/fuzzer.go, syz-fuzzer/fuzzer_test.go, syz-manager/rpc.go
This fixes 2 issues:
1. We still want to get new coverage for syscalls during minimization.
We run lots of new programs, and some of them can give new coverage.
2. The signal filter should apply only to the target syscall.
Other syscalls probably can't even reach any of that code.
So add SignalFilterCall field and combine new and filtered signal
for that call. Other calls just collect new coverage as usual.
=> pkg/fuzzer: fix signal filtering during minimization

executor/common_linux.h, pkg/csource/generated.go
- executor: ignore socketpair error in syz_usbip_server_init
- executor: ignore EBADF when reading tun
=> executor fixes

vm/qemu/qemu.go
It seems to bring more problems than it solves.
=> vm/qemu: don't use UseNewQemuImageOptions for NetBSD

executor/executor.cc, pkg/csource/csource.go, pkg/ipc/ipc.go, pkg/rpctype/rpc.go, pkg/rpctype/rpctype.go, pkg/runtest/run.go, prog/decodeexec.go, prog/encoding_test.go, prog/encodingexec.go, prog/encodingexec_test.go, prog/target.go, prog/test/fuzz.go, prog/test_util.go, syz-fuzzer/fuzzer.go, syz-fuzzer/proc.go, syz-fuzzer/testing.go, syz-manager/manager.go, syz-manager/rpc.go, syz-manager/stats.go, tools/syz-execprog/execprog.go, tools/syz-imagegen/imagegen.go
- prog: don't require preallocated buffer for exec encoding
- syz-manager, syz-fuzzer: send RPC notifications about executing programs
- pkg/ipc: pass only exec encoding to Exec
- syz-manager, syz-fuzzer: send exec encoded programs to fuzzer
=> Send exec encoded programs to the fuzzer

vm/vm_test.go
Currently the inject-error test injects "BUG: foo\n"
and expects VM to fail with this error.
However, the command immidiatly exists, so it may exist
before the output is injected. In that case the test fails with:
=== NAME  TestMonitorExecution/inject-error
vm_test.go:431: got no report
Make the command execute for a second so that output
is always injected.
=> vm: fix logical race in a test

tools/docker/old-env/Dockerfile
Go 1.22 is already released.
We try to support up 2 latest Go releases,
so we can switch to 1.21 for old-env.
Go 1.21 has a number of useful things like
new slices/maps/cmp/slog packages,
min/max builtin functions, PGO builds.
=> tools/docker: update old-env to Go 1.21

pkg/ifuzz/arm64/pseudo.go
This should fix compile-time errors with GOARCH=386
=> pkg/ifuzz/arm64: explicitly use uint32 for immediates

Makefile
Using env to pass env don't seem to work as demonstrated by #4717.
It looks like it's broken since 62114d6064c8.
=> Makefile: fix cross-arch CI builds

dashboard/app/templates.html
Currently we print somewhat verbose "💬 0 [3d18h]" when there are
no discussions, the date repeats the reporting date.
It' makes it hard to visually see when there are conversations
and when there are none. Print nothing when there are no discussions.
=> dashboard/app: don't print discussion info where there are none

syz-manager/rpc.go
We have seen a number of syz-manager crashes on syzbot, which have very likely been caused by a race between shutdownInstance() and Check().
=> syz-manager: tolerate Check() calls from unknown runners

docs/internals.md
syz-fuzzer no longer generates programs.
=> docs: remove outdated architecture description

syz-fuzzer/fuzzer.go
Currently KCSAN instances fail with:
2024/04/30 16:07:00 SYZFATAL: failed to set KCSAN filterlist: failed to start
[ setup_kcsan_filter ...]: exec: no command
=> syz-fuzzer: set executor binary

pkg/compiler/compiler_test.go, pkg/compiler/gen.go, pkg/compiler/types.go, prog/any.go, prog/any_test.go
Netbsd syzbot instance crashes trying to squash a pointer.
Pointers must not be squashed. This happens because of
recursive ucontext_t type that contains a pointer to itself.
When we assign SquashableElem recursive struct types may not be fully
generated yet, and ForeachArgType won't observe all types.
Assign SquashableElem after all types are fully generated.
=> prog: fix panic during squashing

pkg/instance/instance.go, pkg/rpctype/rpctype.go, pkg/runtest/run.go, pkg/runtest/run_test.go, syz-fuzzer/fuzzer.go, syz-fuzzer/proc.go, syz-fuzzer/testing.go, syz-manager/manager.go, syz-manager/rpc.go, tools/syz-runtest/empty.go, tools/syz-runtest/runtest.go
syz-runtest effectively implemented the same execute program/return result
mechanism we use now for normal fuzzing.
So extend the general mechanism to allow collecting output/errors,
repeating program, and executing a precompiled binary as a test.
And switch syz-runtest to the general mechanism.
This removes another chunk of code from syz-fuzzer.
=> tools/syz-runtest: switch to the generic program execution 

tools/create-image.sh
With changes in this pull request, the `create-image.sh` tool:
1) Supports creating old EoL Debian images
2) Allows working with multiple images at the same time
Thanks!
=> Improvements in `tools/create-image.sh`

pkg/report/linux.go, pkg/report/testdata/linux/report/713
This is not the place of the actual bug.
We end up collecting too many different reports in one place: https://syzkaller.appspot.com/bug?extid=daa1128e28d3c3961cb2
=> pkg/report: ignore __phys_addr

pkg/host/machine_info.go, pkg/rpctype/rpctype.go, pkg/vminfo/linux_test.go, pkg/vminfo/syscalls.go, pkg/vminfo/vminfo.go, pkg/vminfo/vminfo_test.go, syz-manager/rpc.go, tools/syz-runtest/runtest.go
Switch to flatrpc.FileInfoT instead.
In preparation for pkg/host removal and to avoid
circular dependencies in future changes.
=> pkg/host: remove FileInfo

pkg/instance/instance.go, pkg/rpctype/rpc.go, syz-fuzzer/fuzzer.go, syz-fuzzer/testing.go, syz-hub/hub.go, syz-manager/hub.go, syz-manager/manager.go, syz-manager/rpc.go, syz-runner/runner.go, syz-verifier/rpcserver.go, tools/syz-hubtool/hubtool.go, tools/syz-runtest/runtest.go, vm/adb/adb.go, vm/bhyve/bhyve.go, vm/cuttlefish/cuttlefish.go, vm/gce/gce.go, vm/gvisor/gvisor.go, vm/isolated/isolated.go, vm/proxyapp/init.go, vm/qemu/qemu.go, vm/starnix/starnix.go, vm/vm.go, vm/vm_test.go, vm/vmimpl/vmimpl.go, vm/vmm/vmm.go, vm/vmware/vmware.go
Remove things that are only needed for target VM communication:
conditional compression, timeout scaling, traffic stats.
To minimize diffs when we switch target VM communication to flatrpc.
=> pkg/rpctype: prepare for not using for target communication

pkg/flatrpc/conn_test.go, pkg/flatrpc/flatrpc.fbs, pkg/flatrpc/flatrpc.go, pkg/flatrpc/flatrpc.h, pkg/flatrpc/helpers.go, pkg/host/machine_info.go, pkg/rpctype/rpctype.go, pkg/vminfo/linux_test.go, pkg/vminfo/syscalls.go, pkg/vminfo/vminfo.go, pkg/vminfo/vminfo_test.go, syz-manager/rpc.go, tools/syz-runtest/runtest.go
Remove T suffix from object API types.
It seems that we will use these types thoughout the code,
and the suffix looks alien in Go code.
So it's better to remove it before we started using
these names more widely.
Also add few extensions we will need to move feature
checking to the host.
=> pkg/flatrpc: refactor names

prog/clone.go, prog/encoding.go, prog/encoding_test.go, prog/mutation.go, prog/prog.go, prog/rand.go, prog/test/fuzz.go, prog/validation.go, sys/trusty/sys.txt
Allow to serialize/deserialize DataMmapProg
and fix validation in debug mode.
Fixes #4750
=> prog: fix validation of DataMmapProg

pkg/vminfo/linux_syscalls.go, pkg/vminfo/linux_test.go, pkg/vminfo/vminfo_test.go
Properly dedup syscall tests.
This reduces number of test programs for linux from 4349 to 641.
=> pkg/vminfo: deduplicate syscall test programs

.github/workflows/ci.yml
Every time we do force-push, the currently running workflows can be cancelled.
=> ci.yml: cancel old workflows

.github/workflows/ci.yml
Helps to fix #4793 
We have 2 coverage submits from Build and Dashboard jobs.
In one of the test submits, the first was successful and second fails.
It is not clear why it failed. Let's try to collect more details.
=> ci.yml: verbose codecov reports

pkg/corpus/minimize.go, pkg/corpus/prio.go
There's still a risk of a race between the pointer overwriting and accesses to the embedded object.
Let's use an internal replace() method instead.
Sample race:
```
WARNING: DATA RACE
Write at 0x00c0014b0668 by goroutine 5727:
github.com/google/syzkaller/pkg/corpus.(*Corpus).Minimize()
/syzkaller/gopath/src/github.com/google/syzkaller/pkg/corpus/minimize.go:37 +0x44e
main.(*Manager).minimizeCorpusLocked()
/syzkaller/gopath/src/github.com/google/syzkaller/syz-manager/manager.go:1246 +0x150
main.(*Manager).corpusMinimization()
/syzkaller/gopath/src/github.com/google/syzkaller/syz-manager/manager.go:1393 +0x96
main.(*Manager).machineChecked.func4()
/syzkaller/gopath/src/github.com/google/syzkaller/syz-manager/manager.go:1380 +0x33
Previous read at 0x00c0014b0668 by goroutine 113982: …
```
=> pkg/corpus: don't overwrite ProgsList

tools/docker/syzbot/Dockerfile
It is required to fix https://syzkaller.appspot.com/bug?extid=b74023cb6794d3bd2452.
=> tools/docker/syzbot: update bazel to 7.1.2

pkg/fuzzer/job.go, prog/hints.go, prog/hints_test.go
Do two exec hints to only leave stable comparison argument pairs.
In local experiments, it allows to reduce their count by 30-40% (on average).
=> pkg/fuzzer: deflake comparisons

pkg/fuzzer/fuzzer.go, pkg/fuzzer/queue/prio_queue.go, pkg/fuzzer/queue/prio_queue_test.go, pkg/fuzzer/queue/queue.go, pkg/fuzzer/queue/queue_test.go
We don't need the full priority queue functionality anymore. For our purposes it's enough to only enforce the order between the elements of different sub-queues.
=> pkg/fuzzer/queue: simplify the priority queue

syz-manager/rpc.go
If syz-fuzzer has not been able to execute the request, set the proper result status.
Assign fallback signal only if signal was requested and if the execution was successful.
=> syz-manager: handle failed requests

executor/common.h, pkg/csource/common.go, pkg/csource/csource.go, pkg/csource/options.go, pkg/csource/options_test.go, pkg/repro/repro.go, pkg/repro/repro_test.go, tools/syz-prog2c/prog2c.go
If C reproducers keep on printing "executing program" lines, it will be easier to re-use them during the repro and patch testing.
=> pkg/repro: don't clear the Repro flag

syz-fuzzer/fuzzer.go, syz-fuzzer/fuzzer_test.go, syz-fuzzer/proc.go, syz-manager/manager.go, syz-manager/rpc.go, syz-manager/stats.go
syz-manager,  syz-fuzzer: switch communication to flatrpc
Switch to flatrpc connection between manager and fuzzer.
With flatrpc we have a goroutine per connection instead of async RPC,
which makes things a bit simpler. Now don't reordered messages
(in particular start executing and finish executing for programs),
race on the program during printing is no longer possible
since we finish handlign start executing request before we even
receive finish executing.
We also don't need to lookup Runner for every RPC since it's
now local to the handling goroutine.
We also don't need to protect requests map since only single
goroutine accesses it.
We also send new programs to the fuzzer as soon as we receive
start executing message, which provides better buffering.
We also don't batch new requests …
=> syz-manager,  syz-fuzzer: switch communication to flatrpc

executor/test_linux.h
it seems to be redundant and moreover it lets us compile on musl which does not provide this system header
=> executor: Remove including <error.h> in test_linux.h

syz-ci/manager.go, syz-ci/syz-ci.go
Currently they can collide with the main instance and fail.
Use random ports for test instances.
=> syz-ci: use random ports for test instances

pkg/instance/execprog.go, tools/syz-crush/crush.go
The suppression of command executions errors must have been making pkg/repro blind to the "lost connection" bugs.
Cc @FlorentRevest
=> pkg/instance: don't ignore connection errors

syz-ci/manager.go
For GCE-based fuzzing, we need to bind to a real networking interface to accept connections from the VMs.
=> syz-ci: fix RPC connections to test syz-managers

pkg/csource/csource_test.go, pkg/fuzzer/job.go, pkg/repro/repro.go, pkg/repro/repro_test.go, prog/encoding_test.go, prog/expr_test.go, prog/minimization.go, prog/minimization_test.go, prog/prog_test.go, prog/rand_test.go
When we combine the progs found during prog bisection, there's a chance
that we may exceed the prog.MaxCalls limit. In that case, we get a
SYZFATAL error and proceed as if it were the target crash. That's
absolutely wrong.
Let's first minimize each single program before concatenating them, that
should work for almost all cases.
=> pkg/repro: avoid hitting the prog.MaxCalls limit

docs/syscall_descriptions_syntax.md, executor/executor.cc, prog/types.go, sys/linux/net_80211.txt, sys/linux/usbip.txt, sys/linux/vusb.txt
Update the descriptions to mark calls that cause remote coverage collection.
Remote some hacky code from the executor.
=> prog: introduce a remote_cover call attribute

pkg/build/build.go, pkg/cover/backend/backend.go, pkg/cover/backend/dwarf.go, pkg/cover/backend/gvisor.go, pkg/cover/backend/pc.go, pkg/cover/report_test.go, pkg/mgrconfig/load.go, pkg/report/report.go, pkg/vcs/linux.go, sys/targets/targets.go, syz-manager/cover.go, syz-manager/covfilter.go, syz-manager/covfilter_test.go, syz-manager/http.go, syz-manager/rpc.go, tools/syz-execprog/execprog.go, vm/gvisor/gvisor.go, vm/starnix/starnix.go, vm/vm_test.go
Now that PCs are 64-bit we don't need RestorePC callback.
Now we can just use PreviousInstructionPC, which does not require
creation of ReportGenerator.
=> pkg/cover/backend: remove RestorePC

executor/cov_filter.h, executor/test.h, syz-manager/covfilter.go, syz-manager/covfilter_test.go
Manager was switched to 64-bit PCs, but executor still expected
4-byte PC start in the header.
Fix it and switch size to uint64 for simplicity as well.
=> executor: fix coverfilter header size

syz-manager/rpc.go
Fuzzer memory may be corrupted, but it may contain a bug.
Don't crash on bad replies.
=> syz-manager: harden against bad fuzzer replies

syz-manager/http.go
There is no VM loop an answer reproRequest, so don't wait for it.
=> syz-manager: fix web interface in VM-less mode

executor/common.h, executor/common_bsd.h, executor/common_linux.h, executor/executor.cc, executor/executor_linux.h
Return failure reason from setup functions rather than crash.
This will provide better error messages, but also allow setup
w/o creating subprocesses which will be needed when we combine
fuzzer and executor.
Also close all resources created during setup.
This is also useful for in-process setup, but also should improve
chances of reproducing a bug with C reproducer. Currently leaked
file descriptors may disturb repro execution (e.g. it may act
on a wrong fd).
=> executor: rework feature setup

executor/executor.cc, executor/executor_linux.h
Fix 2 bugs:
1. We remove low 12 bits of every PC on amd64 b/c use_cover_edges return true.
This results in extremly low signal (gvisor PC are dense integers).
2. We hash prev/next PC on arm64 which does not make sense
since gvisor coverage is not a trace. This results in falsely large signal.
=> executor: fix gvisor signal

sys/targets/targets.go
Arm64 gcc on Debian rejects to build a program that includes <algorithm>.
Use C program for C compiler, and C++ program for C++ compiler.
=> sys/targets: build C++ program with C++ compiler

pkg/fuzzer/job.go, pkg/fuzzer/stats.go
Let exec smash describe purely the mutation part of the smash job. Introduce a separate stat for fault injection executions.
=> pkg/fuzzer: separate fault injection stats

tools/syz-execprog/execprog.go
ProgInfo.Extra may be nil if no extra coverage present.
=> tools/syz-execprog: fix nil deref

pkg/build/linux_generated.go, tools/create-gce-image.sh, tools/create-image.sh
The name server configuration filename in the script is incorrect. Instead `/etc/resolve.conf`, it should be `/etc/resolv.conf`. Otherwise, it may lead to nameserver configuration issues.
=> tools: correct resolv.conf filename for  nameserver configuration

tools/docker/syzbot/Dockerfile, tools/docker/syzbot/run-syz-command.sh
It enables us to use CloudRun.
The goal is to run syzkaller tools as a gcp job.
I've created gcr.io/syzkaller/syzbot-cloudrun for the testing purposes.
And it is the tool I need to periodically trigger covermerge.
=> tools/docker/syzbot: add run-syz-command.sh

executor/common.h, executor/common_linux.h, executor/executor_bsd.h, executor/executor_linux.h
- **executor: don't call close_fds twice**
- **executor: use close_range if available**
- **executor: optimize waiting for child processes exit**
=> few spot optimizations for executor

executor/executor.cc
To receive data, executor relies on changes propagating to its view of the shared memory buffer. This is only guaranteed with `MAP_SHARED`, whereas behavior is "unspecified" for `MAP_PRIVATE` (but happened to work on most implementations).
This came up as an issue when running under Starnix, which currently does not propagate changes in the `MAP_PRIVATE` case. This will likely change, but it seems that `MAP_SHARED` is the desired semantics in any case.
=> executor: map input buffer as shared

pkg/cover/backend/dwarf.go, pkg/symbolizer/cache.go
1. symbolize takes much time especially if there are hundreds of modules and many pcs.
2. concurrent writing to slice without protection will result in race condition, see https://blog.sgkandale.com/appending-slice-from-multiple-goroutines-86bc1c821e9e.
The PR is to fix these two issues:
1. by symbolize each module in different goroutine.
2. protect concurrent writing to slice using channel.
=> all: parallelize symbolize 

docs/syzbot_assets.md
In case of ARM64 bugs, we need to use a somewhat different set of qemu arguments to run the kernel from syzbot assets locally.
=> docs/syzbot_assets.md: provide a sample qemu command for arm64

pkg/email/parser.go
This is not needed for the actual operation.
=> pkg/email: remove the debugging code

syz-manager/http.go
In the summary page of the http server, the GitRevisionBase is truncated to 8 characters and displayed in the UI. However, when building syzkaller through other build systems, this value is not properly set and remains "unknown".
Unfortunately, "unknown" has only 7 letters, which causes the code that truncates to 8 letters to panic, and the UI page can't be shown.
To fix this without doing any more invasive changes to the logic behind how GitRevisionBase is set, we will simply check if it has more than 8 characters, and truncate it only if it does. Otherwise we will display it in full.
=> syz-manager: Check GitRevisionBase length

pkg/stats/sample/pvalue.go, pkg/stats/sample/sample.go, pkg/stats/sample/sample_test.go, tools/syz-testbed/stats.go, tools/syz-testbed/table.go, tools/syz-testbed/table_test.go
This will reduce the number of dependencies needed for the main syzkaller tools.
Cc @Mandragorian
=> pkg/stats: split out pkg/stats/sample

docs/syscall_descriptions_syntax.md
Remove a redundant square bracket in section "Expression syntax".
=> docs/syscall_descriptions_syntax.md: remove a redundant square bracket

pkg/instance/instance.go
We currently panic if the syz reproducer was not provided, but it's actually a valid situation - it happens if we perform patch testing for build/boot/test errors.
Closes #4907.
=> pkg/instance: don't require a syz reproducer

sys/targets/targets.go, vm/starnix/starnix.go
Changes:
1. Don't require adb to communicate with the starnix instance; instead, use ssh/scp.
2. After https://github.com/google/syzkaller/pull/4883, starnix can handle the standard linux fuzzing workflow. Instead of running in host fuzzer mode, push syz-fuzzer to the VM and use shared memory to communicate with syz-executor. This is much faster and eliminates the need for special timeouts for starnix.
3. Improve the log output when syz-manager is run with `-debug`, sending both syzkaller logs and the now-relatively-quiet kernel logs to stdout.
Caveats (numbers correspond to changes above):
2. Once every ~10-100 restarts, syz-manager fails to start with message "mismatching target/executor arches" (probably due to truncated RPC message reads). With `-debug` there are frequent "control …
=> starnix: syz-fuzzer runs on VM and talks to syz-manager over ssh

executor/executor_linux.h
The address ranges in is_kernel_data/pc are only true for normal Linux.
=> executor: fix is_kernel_data/pc for gVisor

Makefile
Temporary hack to allow updating old syz-ci when syz-fuzzer is removed.
=> syz-ci: prepare for removal of syz-fuzzer binary

executor/executor_runner.h, syz-manager/manager.go
It is returned by `vm/gvisor`.
=> syz-manager: support stdin as port forwarding result

dashboard/app/api.go, dashboard/app/entities_datastore.go, dashboard/app/index.yaml, dashboard/app/main.go, dashboard/app/main_test.go, dashboard/app/manager.html, dashboard/app/repro_test.go, dashboard/app/util_test.go, pkg/html/pages/style.css, syz-manager/manager.go
As it is problematic to set up automatic bidirectional sharing of reproducer files between namespaces, let's support the ability to manually request a reproduction attempt on a specific syz-manager instance. That should help in the time being.
=> dashboard: support manual reproduction requests

executor/common_linux.h
My gcc-10 in testing vm compainls during reproducer [0] build with following error:
rep.c: In function ‘remove_dir’:
rep.c:662:3: error: a label can only be part of a statement and a declaration is not a statement
662 |   const int umount_flags = MNT_FORCE | UMOUNT_NOFOLLOW;
|   ^~~~~
Label followed by declaration is C23 extension, so only new compilers support it.
Fix it by moving declaration above `retry` label and put unused attribute to suppress possible warning.
[0] https://syzkaller.appspot.com/bug?extid=dcc068159182a4c31ca3 …
=> executor/linux: fix compilation error with old compilers

executor/common.h, executor/common_test.h, executor/executor.cc, executor/style_test.go
We include a number of C++ headers in the runnner.
On FreeBSD some of them mention malloc, and our defines break the build.
Use the style test to check only our files for these things.
=> executor: prohibit malloc/calloc via linter

executor/conn.h
Otherwise, it fails with "SYZFAIL: failed to parse manager port".
=> executor: check whether the address is stdin before validation a port

executor/conn.h, executor/executor_runner.h
- **executor: use mcontext_t only on linux**
- **executor: include missing header**
=> dvyukov executor bsd fixes

dashboard/app/templates.html
Print OK only for non-failed and non-crashed jobs. Print links to independent assets independently.
=> dashboard: refactor job status links

executor/subprocess.h
Somehow it's very slow in syzbot arm64 image.
This speeds up pkg/runtest tests a hundred of times.
=> executor: disable lsan for exec subprocesses

pkg/rpcserver/rpcserver.go, pkg/rpcserver/runner.go, pkg/runtest/run_test.go, pkg/vminfo/features.go, pkg/vminfo/vminfo.go
Split out most of the Runner functionality into a separate file.
This should make it easier to reason about what rpcserver.go does and it also makes further pkg/rpcserver refactoring simpler.
=> pkg/rpcserver: split rpcserver.go

executor/executor.cc, executor/executor_runner.h, executor/executor_test.h, executor/subprocess.h, pkg/rpcserver/local.go, pkg/runtest/executor_test.go, pkg/runtest/run_test.go, pkg/vminfo/features.go, pkg/vminfo/vminfo.go
- **executor: fix max signal/cover filter mapping into subprocesses**
- **executor: don't trace PCs as comparisons**
- **executor: always return some coverage for test OS**
- **pkg/runtest: add tests for max signal and cover filter**
=> dvyukov coverfilter tests

pkg/cover/backend/dwarf.go
For modules, init_module and cleanup_module have the same sym.Start 0xffffffc014d310d0 even they are symbols for different sections.
Even we can keep symbols only in .text sections, there are still some symbols having the same Start.
Looking forward a better way, but currently to get constant behavior in buildSymbols, keep only one symbol incase there are other symbols having the same Start.
=> pkg/cover: remove symbols having the same Start Address

executor/executor_runner.h, pkg/report/linux.go, pkg/report/testdata/linux/report/716, pkg/report/testdata/linux/report/717, tools/syz-symbolize/symbolize.go
SIGBUS means OOM on Linux.
Most of the crashes that happen during fuzzing are SIGBUS,
so separate them from SIGSEGV and suppress.
=> pkg/report: suppress executor SIGBUS

executor/common_test.h, executor/executor.cc, executor/executor_bsd.h, executor/executor_darwin.h, executor/executor_linux.h, executor/executor_runner.h, executor/executor_test.h, executor/nocover.h, pkg/flatrpc/flatrpc.fbs, pkg/flatrpc/flatrpc.go, pkg/flatrpc/flatrpc.h, pkg/rpcserver/local.go, pkg/rpcserver/rpcserver.go, pkg/rpcserver/runner.go, pkg/runtest/executor_test.go, pkg/runtest/run_test.go, sys/targets/targets.go, sys/test/exec.txt
We see some errors of the form:
SYZFAIL: coverage filter is full
pc=0x80007000c0008 regions=[0xffffffffbfffffff 0x243fffffff 0x143fffffff 0xc3fffffff] alloc=156
Executor shouldn't send non kernel addresses in signal,
but somehow it does. It can happen if the VM memory is corrupted,
or if the test program does something very nasty (e.g. discovers
the output region and writes to it).
It's not possible to reliably filter signal in the tested VM.
Move all of the filtering logic to the host.
Fixes #4942
=> pkg/rpcserver: move kernel test/data range checks from executor

tools/syz-bq.sh
1. Replace uuidgen by cat /proc/sys/kernel/random/uuid.
2. Our gcloud version doesn't have storage command yet (alpha only is available). Use gsutil instead.
=> tools/syz-bq.sh: make it syz-env compatible

pkg/cover/backend/backend.go, pkg/cover/backend/dwarf.go, pkg/cover/backend/elf.go, pkg/cover/backend/modules.go, pkg/cover/report.go, pkg/cover/report_test.go, pkg/rpcserver/rpcserver.go, pkg/vminfo/linux.go
The current implementation doesn't work well when CONFIG_RANDOMIZE_BASE enabled.
Taken some arm64 devices for example:
kaslr_offset is diff at bits 12-40, and kernel modules are loaded at 2GB space,
so we have `ffffffd342e10000 T _stext` where uppper 32bit is ffffffd3. However,
if we check modules range, the 1st module is loaded at 0xffffffd2eeb2a000,
while the last module is loaded at 0xffffffd2f42c4000.
We can see the upper 32bits are diff for core kernel and modules.
If we use current 32bits for covered PC, we will get wrong module address
recovered, which uses pcBase from core kernel + lower 32bits offset.
So we need to move to 64bit cover and signal.
Besides, there are some other fixes and improvement in the PR to align with the 64bits support:
- Fix wrong module size which should be …
=> support CONFIG_RANDOMIZE_BASE=y

executor/common_linux.h
Commit 3160a12dd1047 ("executor: linux: chroot into tmpfs with sandbox=none") broke some Android instances, which fail to mount tmpfs. Disable it for the time being.
Tracking bug: https://github.com/google/syzkaller/issues/4972
=> executor: linux: bump fs.mount-max to 100000

pkg/mgrconfig/config.go, syz-manager/manager.go
This mode allows to run local manager that only "helps" main instances
by uncovering more coverage and extracting useful reproducers.
Otherwise it spends too much time reproducing all bugs that already
have reproducers.
=> syz-manager: allow manager to only consult dashboard if it needs reproducers

executor/common_linux.h
mount() in gVisor returns EFAULT if source is NULL. It is a gVisor issue and we will fix it. Let's explicitly sets a string source for the proc mount to unblock gVisor jobs. The source string will additionally be useful for troubleshooting mount-related problems in the future, because it is shown in /prod/pid/mountinfo.
=> executor: set `source` for the proc mount

dashboard/app/config.go, dashboard/app/handler.go, dashboard/app/main.go, dashboard/app/templates.html
Is also needed to #4979 .
2 unused options will be needed there.
=> dashboard/app: make coverage menu and page optional

tools/syz-bq.sh
It works good with empty workdirs.
If workdir has multiple remotes, git checkout is confused what version of "branch" to checkout.
=> tools/syz-bq.sh: assume the dir is already a multirepo

pkg/rpcserver/local.go, pkg/rpcserver/rpcserver.go, pkg/rpcserver/runner.go, pkg/runtest/run.go, pkg/runtest/run_test.go, pkg/vminfo/linux_test.go, pkg/vminfo/vminfo.go, pkg/vminfo/vminfo_test.go, syz-manager/manager.go
These changes should hopefully convert the timeouts we're seeing in #4954 into more actionable errors.
=> pkg/{runtest, rpcserver, vminfo}: ensure graceful exit

vm/qemu/qmp.go
Sometimes qemu just returns an "Error: ..." string in reply
instead of returning an error. Handle these cases.
Also log all qmp commands in debug mode.
=> vm/qemu: better handle qmp errors

Makefile
All syz-ci instances must have updated by this time, so we no longer need this noisy hack.
=> Makefile: remove dummy syz-fuzzer

tools/create-openbsd-gce-ci.sh
As syz-bot became much more aggressive about resource usage lately it started running over the limits and is getting blocked. Give it all the rope it wants. There's nothing else on the VM anyway.
Used the vmd class as it is given the most memory in login.conf.
=> tools/create-openbsd: bump up the limits for syz-bit

dashboard/dashapi/dashapi.go, dashboard/dashapi/dashapi_test.go, pkg/mgrconfig/config.go, syz-manager/manager.go
Some proxies have requirements on the user-agent used. If the default user-agent that the go `http` lib uses is not satisfying them, there should be a way to customize that header.
So we add a `DashboardUserAgent` config option, and if it is set we use it in the request constructor.
=> Dashapi useragent

executor/conn.h
This is a trivial change. A more interesting question is why the error is reported on openbsd:
https://syzkaller.appspot.com/bug?extid=7115badc143affd20158
=> executor: fix diagnostic message typo

pkg/vminfo/features.go
We're seeing ci failures:
```
2024/07/08 16:29:56 [FATAL] check failed: execution of simple program fails: test program execution failed
```
Let's make it more clear why it might have failed.
=> pkg/vminfo: add more details to an execution error

executor/common_openbsd.h
Unlike linux the BSDs used to check the result of setsid.
This suddenly became a problem a couple of weeks ago. It's hard to figure out why because there was a number of problems in the area preventing the test from working:
```
gmake executor execprog && \
./bin/openbsd_amd64/syz-execprog -stress -executor ./bin/openbsd_amd64/syz-executor
```
At least with this change the test above successfully executes some coverage and exits cleanly.
=> executor: only report unknown setsid errors

executor/executor_runner.h
OpenBSD seems to be more prone to returning `EAGAIN` from read than Linux. So [this problem happens fairly often](https://syzkaller.appspot.com/bug?extid=5a40af22a61b0bd8bbb5):
```
SYZFAIL: proc resp pipe read failed
n=-1 (errno 35: Resource temporarily unavailable)
```
=> executor: use a loop to deal with EAGAIN

pkg/corpus/corpus.go, pkg/db/db.go, pkg/db/db_test.go, syz-manager/http.go, syz-manager/hub.go, syz-manager/manager.go
- **syz-manager: don't keep corpus in memory**
- **pkg/corpus: don't keep serialized programs in memory**
- **syz-manager: don't minimize corpus during triage**
=> reduce syz-manager memory consumption

dashboard/app/access.go, dashboard/app/access_test.go
PR #4837 added displaying repro logs to syzbot but didn't make the logs publicly-accessible. Fix that.
=> dashboard: make repro logs public

vm/qemu/qmp.go
If qmp is used all the time for snapshotting,
it produces tons of uniniteresting logs at level 1 (manager web UI).
=> vm/qemu: don't log qmp on level 1

pkg/repro/repro.go, pkg/repro/repro_test.go, pkg/repro/strace.go, pkg/rpcserver/rpcserver.go, pkg/rpcserver/runner.go, syz-manager/http.go, syz-manager/hub.go, syz-manager/manager.go, syz-manager/repro.go, syz-manager/repro_test.go, syz-manager/stats.go, tools/syz-repro/repro.go, vm/adb/adb.go, vm/bhyve/bhyve.go, vm/cuttlefish/cuttlefish.go, vm/dispatcher/pool.go, vm/dispatcher/pool_test.go, vm/gce/gce.go, vm/gvisor/gvisor.go, vm/isolated/isolated.go, vm/proxyapp/proxyappclient.go, vm/qemu/qemu.go, vm/starnix/starnix.go, vm/vm.go, vm/vm_test.go, vm/vmimpl/vmimpl.go, vm/vmm/vmm.go, vm/vmware/vmware.go
* Split off the instance pool support functionality into a package.
* Don't waste as many VMs for bug reproduction as we did before -- 1.33 instead of 3.  
* Move the instance list and status functionality from `rpcserver` to `instance.Pool`.
=> all: switch to a generic instance pool functionality

syz-manager/hub.go, syz-manager/repro.go
Only request them if there's nothing else to reproduce.
=> syz-manager: deprioritize hub reproducers

pkg/flatrpc/conn.go, pkg/rpcserver/rpcserver.go, pkg/rpcserver/runner.go, pkg/runtest/run_test.go
Context: #4954.
In some cases, the executor seems to be mysteriously silent when we were awaiting a reply.
During pkg/runtest tests, give it 1 minute to prepare a reply, then try to request the current state and abort the connection.
=> pkg/rpcserver: debug executor stalls

dashboard/app/access_test.go, dashboard/app/app_test.go, dashboard/app/util_test.go
The test has recently become broken, but we didn't notice it in our presubmit testing.
Fix the problem (ReproLog being set to 0).
Use subtests to be able to identify the exact failing test case.
Run TestAccess in `-short` mode, but limit it to ensuring that non-public URLs are not accessible publicly. The short test now takes 60 seconds compared to 104 seconds without `-short`.
=> dashboard: fix TestAccess

pkg/runtest/executor_test.go, pkg/runtest/run_test.go
On 32 core machines, we spin up 32 executor procs per each subtest. In many cases, we don't need that many.
=> pkg/runtest: reduce the number of executors

syz-manager/repro.go
We should expect popCrash() to return nil.
=> syz-manager: add a missing nil check

syz-manager/repro.go
If we're reproducing a bug with a crash title A and there are several more crashes A in the reproduction queue, we still need to reserve VMs for just one bug reproduction.
=> syz-manager: optimize the numer of reserved VMs

pkg/vminfo/linux.go
/proc/sentry-meminfo is read in checker.MachineInfo which can be called when serv.checkDone is set.
=> pkg/meminfo: move /proc/sentry-meminfo to the required files list

pkg/rpcserver/local.go, pkg/rpcserver/rpcserver.go, pkg/rpcserver/runner.go
For local rpcserver runs, we do not reboot the executor in case of errors. Moreover, if the error did not lead to the executor process exit, we may never detect that something went wrong.
Return an error channel from CreateInstance() to be able to act on connection loop errors.
Explicitly register the instance during local executions and exit from RunLocal() in case of connection problems.
=> pkg/rpcserver: exit on connection loop abortion

docs/contributing.md
Fix a typo in the section of "Using syz-env": expacted to expected.
=> docs/contributing.md: fix a typo

pkg/runtest/run_test.go
s390x doesn't support 32bit TestOS.
=> Another s390x unit test fix

pkg/fuzzer/job.go
During deflake(), we look at the unions of the signal from multiple iterations. Let's do the same in minimize(), it would be more consistent.
=> pkg/fuzzer: use the signal union in minimize iterations

dashboard/app/templates/templates.html, pkg/html/pages/style.css
Dropdown is based on a hidden div.
Table has its own z-index ordering and internal divs can't be rendered outside of the table. At least I didn't find how to do it.
Wrapping table was removed because of this effect. As a side effect our menu responses to the window resizing now.
=> dashboard/app: coverage dropdown menu

syz-manager/hub.go, syz-manager/manager.go, syz-manager/repro.go, syz-manager/repro_test.go
There have been some mess and duplication around Crash/ReproResult data structures. As a result, we've been attempting to upload repro failure logs to the dashboard for bugs, which did not originate from the dashboard. It litters the syz-manager logs.
Refactor the code.
=> syz-manager: tidy ReproResult

dashboard/app/jobs_test.go, dashboard/app/templates/mail_test_result.txt
Kernel community asks to split it for tooling purposes:
https://lore.kernel.org/all/Zpb30HMt6jXtonhr@google.com/
=> dashboard/app: split Reported-and-tested-by tag

pkg/repro/repro.go, syz-manager/manager.go
It seems that this error may come up in absolutely valid and reasonable cases. Restore the special casing.
=> syz-manager: still ignore log parse problems

executor/common_bsd.h
See commit bc144f9a58782daa2399d417b56aad80e82a219e.  The justification applies to other BSDs as well, so apply the same workaround.
=> executor: avoid setsid() errors

executor/conn.h
It should fix errors like this one:
SYZFAIL: failed to resolve manager addr
addr=localhost h_errno=2
(errno 11: Resource temporarily unavailable
=> executor: manually replace localhost with equivalent ipv4/6 address

docs/translations/zh_CN/syscall_descriptions_syntax.md
Finish the translation of docs/syscall_descriptions_syntax.md, which has also been proofread by HCTT translation group.
=> docs/translations: add the translation of syscall_descriptions_syntax.md

pkg/cover/templates/cover.html
When working with standalone coverage reports, it can be sometimes useful to see the total count of covered basic blocks. Show it together with the percentage and the total number of BBs in the kernel (for the sake of uniformity)
=> pkg/cover: show the total count in the coverage report

tools/syz-env
=> Revert "tools/syz-env: allow commands with double quote in parameters"

syz-manager/manager.go
IPv6 addresses contain `:` symbols. So we can't just try to split a string at the first `:` to get the host and the port it specifies. Instead use the standard library `SplitHostPort` method which handles that case for us.
=> syz-manager: properly parse host:port

pkg/cover/heatmap.go, pkg/cover/heatmap_test.go, pkg/spanner/coveragedb/coverage.go, tools/syz-covermerger/db.go, tools/syz-covermerger/init_db.sh
There are 2 reasons to do it:
1. It will speed up and simplify #5066 .
2. Coverage per subsystem requests may be generated directly by db.
=> store subsystems for every file in spanner

executor/executor.cc, pkg/flatrpc/flatrpc.fbs, pkg/flatrpc/flatrpc.go, pkg/flatrpc/flatrpc.h, pkg/fuzzer/fuzzer.go, pkg/fuzzer/job.go, pkg/rpcserver/runner.go, pkg/runtest/run_test.go, prog/hints.go, prog/hints_test.go, prog/rand_test.go, tools/syz-execprog/execprog.go, tools/syz-mutate/mutate.go
We are getting too many generated candidates, the fuzzer may not keep up
with them at all (hints jobs keep growing infinitely). If a hint indeed came
from the input w/o transformation, then we should guess it on the first
attempt (or at least after few attempts). If it did not come from the input,
or came with a non-trivial transformation, then any number of attempts won't
help. So limit the total number of attempts (until the next restart).
=> prog: restricts hints to at most 10 attempts per single kernel PC

dashboard/app/api.go, dashboard/app/repro_test.go, dashboard/dashapi/dashapi.go, syz-manager/manager.go, syz-manager/repro.go, syz-manager/repro_test.go
Share the kind of the dashboard-originated reproduction requests and prioritize them in syz-manager accordingly.
=> {dashboard, syz-manager}: prioritize manual repro requests

dashboard/app/graphs.go, dashboard/app/main.go, dashboard/app/templates/templates.html, pkg/cover/heatmap.go, tools/syz-cover/syz-cover.go
This one integrates the subsystems coverage.
=> add coverage->sybsystems_coverage menu

executor/common_test.h, executor/executor.cc, executor/executor_test.h, pkg/runtest/run_test.go, sys/test/exec.txt
We never reset remote coverage, so if there is one block,
we will write it after every call and multiple times at the end.
It can lead to "too many calls in output" and just writes quadratic
amount of coverage/signal.
Reset remote coverage after writing.
=> executor: fix writing of remote coverage

executor/common_linux.h
Running the vusb_ath9k runtest (with [1] and [2] applied) produces ~100k of extra coverage, which is somewhat close to the current 256k limit. A more complicated program might produce more extra coverage and overflow the coverage buffer.
Increase kExtraCoverSize to 1024k.
As the extra coverage buffer is maintained per-executor and not per-thread, the total increase of the coverage mapping is ~9%, which is not too bad.
[1] https://lore.kernel.org/all/eaf54b8634970b73552dcd38bf9be6ef55238c10.1718092070.git.dvyukov@google.com/
[2] https://lore.kernel.org/all/20240722223726.194658-1-andrey.konovalov@linux.dev/T/#u
=> executor: increase kExtraCoverSize to 1024k

pkg/runtest/run.go, syz-manager/manager.go
- **syz-manager: fix deadlock in run-tests mode**
- **pkg/runtest: fix nil deref on test failures**
=> dvyukov fix run tests

pkg/runtest/run.go, pkg/runtest/run_test.go, syz-manager/manager.go
Run method usually runs in a separate goroutine concurrently with request consumer
(Next calls), so at least executor needs to be initialized before Run.
Otherwise we can get episodic nil derefs in Next method.
=> pkg/runtest: fix a race during startup

pkg/rpcserver/rpcserver.go, pkg/runtest/run_test.go, pkg/vminfo/linux.go, pkg/vminfo/vminfo.go
Starnix doesn't implement `/proc/kallsyms` (at least not yet), and there is already a short-circuit for gVisor in `parseModules`. This change pipes the VM type through to the machine info checker so that it can handle these cases separately from other linux VMs.
=> pkg/vminfo: don't parse modules for gvisor or starnix

syz-manager/manager.go, syz-manager/stats.go, vm/dispatcher/pool.go
This should be calculated in dispatcher.Pool that actually does boot VMs.
=> vm/dispatcher: move boot duration calculation to vm

Makefile, tools/syz-declextract/.clang-format, tools/syz-declextract/README.md, tools/syz-declextract/syz-declextract.cpp
tools/syz-declextract parse Linux Headers to extract metadata about syscalls
Clang tool that uses AST matchers to extract relevant metadata about Linux system calls. The tool is to be extended later to support more interfaces, collect more relevant metadata and to automatically generate syzkaller descriptions
=> tools/syz-declextract parse Linux Headers to extract metadata about syscalls

tools/check-copyright.sh, tools/syz-declextract/.clang-format, tools/syz-declextract/README.md, tools/syz-declextract/run.go, tools/syz-declextract/syz-declextract.cpp
Run multiple instances of syz-declextract only on files specifed by a compilation database.
=> tools/syz-declextract: run syz-declextract on files specified by a compilation database

executor/executor.cc, executor/executor_runner.h, pkg/flatrpc/conn_test.go, pkg/flatrpc/flatrpc.fbs, pkg/flatrpc/flatrpc.go, pkg/flatrpc/flatrpc.h, pkg/flatrpc/helpers.go, pkg/fuzzer/fuzzer.go, pkg/fuzzer/job.go, pkg/fuzzer/queue/distributor.go, pkg/fuzzer/queue/distributor_test.go, pkg/fuzzer/queue/queue.go, pkg/rpcserver/local.go, pkg/rpcserver/rpcserver.go, pkg/rpcserver/runner.go, syz-manager/manager.go
- **prog: reduce amount of hint replacements**
- **pkg/fuzzer: optimize smash jobs**
- **pkg/fuzzer: remove signal rotation**
- **pkg/fuzzer: try to triage on different VMs**
- **pkg/fuzzer: tune corpus triage**
- **pkg/fuzzer: issue minimize attempts in parallel**
- **executor: restart procs more deterministically**
- **pkg/fuzzer: deflake hints 3 times instead of 2**
=> fuzzer jobs optimizations

pkg/cover/backend/dwarf.go, pkg/cover/backend/elf.go, pkg/cover/backend/modules.go
we use offset to symbolize pc for module,
while use absolute pc for core kernel.
Fix by removing base address from module only.
=> pkg/cover: fix pc for core kernel

CONTRIBUTORS, sys/linux/filesystem.txt
Added the inlinecrypt mount flag for ext4, f2fs.
=> sys/linux/filesystems: add the inlinecrypt mount flag

pkg/corpus/minimize.go
Occasionally, deflake() and minimize() fail and we end up with huge programs in the syzkaller corpus. Huge programs in the corpus, in turn, lead to slower corpus triage and slower exec/sec overall, since many of the executed programs are based on the ones from the corpus.
A slightly bigger corpus with on average shorter and more focused programs sounds like a more desirable outcome.
Give preference to smaller programs during minimization. It should hopefully improve the situation over time.
=> pkg/corpus: prefer smaller programs during minimization

sys/syz-extract/extract.go, tools/syz-linter/linter.go, tools/syz-linter/testdata/src/github.com/google/syzkaller/pkg/tool/tool.go, tools/syz-linter/testdata/src/lintertest/lintertest.go
Check tool.Failf messages for the common style as well.
=> tools/syz-linter: check tool.Failf messages

syz-manager/snapshot.go
1) Include output in queue.Result only if it was requested.
2) Always return the output to the caller -- we use it for crash
detection.
=> syz-manager: fix snapshotRun() return values

syz-manager/snapshot.go
We increment StatExecs in both snapshotVM and snapshotRun,
which leads to 2x overcounting. Remove one increment.
=> syz-manager: don't overcount executed programs in snapshot mode

sys/linux/filesystem.txt
=> sys/linux/filesystem: add mount options for bpf

sys/linux/filesystem.txt
Added mount options for some filesystems
=> sys/linux/filesystem: add mount flags for some filesystems

executor/executor.cc
It's not necessary to set process name in snapshot mode
since we execute only 1 program each time.
=> executor: set process name before taking snapshot

pkg/mgrconfig/load.go, syz-manager/manager.go, syz-manager/snapshot.go, vm/dispatcher/pool.go, vm/dispatcher/pool_test.go
For now, let's just reuse the already existing reproduction mechanism by plugging in snapshot-based VMs into `dispatcher.Pool`.
=> syz-manager: support bug reproduction in snapshot mode

pkg/instance/instance.go
We should not be setting FuzzingVMs to a value below the overall VM count.
Closes #5175.
=> pkg/instance: adjust FuzzingVMs in OverrideVMCount()

syz-manager/manager.go
The current fuzzing algorithm in syzkaller may preserve the poorly
minimized corpus programs forever - they trigger a lot of coverage and
will very likely survive all syzkaller restarts.
As a result, more than 18% of the current syzbot corpus programs are
larger than 25 calls, which is an unreasonably big figure.
Introduce a way to prevent the domination of the bigprograms in the
corpus.
Every corpus retriage, pick up to 50 seeds among the 10% largest corpus
programs and re-minimize them. Hopefully, this should reduce the
magnitude of the problem.
=> syz-manager: re-minimize a subset of corpus programs

pkg/cover/file.go, pkg/covermerger/covermerger.go, pkg/covermerger/deleted_file_merger.go, pkg/covermerger/file_line_merger.go, tools/syz-cover/syz-cover.go
To test use ```go run ./tools/syz-cover -for-file virt/kvm/kvm_main.c -from 2024-08-10 -to 2024-08-10```.
Knowing the source of the "strange" signals I'll be able to debug what went wrong calling "github.com/sergi/go-diff/diffmatchpatch".
We can alternatively merge this PR by parts starting with #5184 .
=> tools/syz-cover: explain file coverage source

syz-manager/hub.go, syz-manager/manager.go
Let it be equal to 25 calls for now.
Don't reminimize corpus programs that have fewer calls.
Always reminimize hub programs that no less calls.
=> syz-manager: define a reminimization threshold

docs/adding_new_os_support.md
Fix a typo in `docs/adding_new_os_support.md`: qemo.go to qemu.go
=> docs/adding_new_os_support.md: fix a typo

pkg/covermerger/bq_csv_reader.go
Current statement doesn't work for table names like "something-71".
The namespace was backticked here before the code migration to golang.
=> pkg/covermerger: allow to use namespaces with dash

pkg/bisect/bisect.go, pkg/build/build.go, pkg/build/freebsd.go, pkg/build/linux.go, pkg/build/netbsd.go, pkg/build/openbsd.go, pkg/instance/instance.go, sys/syz-extract/linux.go, syz-ci/jobs.go, syz-ci/manager.go, syz-ci/syz-ci.go
On syz-ci instances that fuzz on qemu VMs, we already have a substantial CPU load. If there happens a background kernel build, which gets parallelized to all (=a lot of) CPUs, it affects the execution speed of all fuzzing VMs. As all prog timeouts remain the same, we may well see the temporary fuzzing efficiency reduction.
Let's control the number of cores dedicated to the kernel build process on such VMs.
=> pkg/build, syz-ci: control the `make -j N` value

pkg/cover/templates/cover.html
Html item is not a block element by default.
It allows sub-elements to overflow next line.
This change still allow element to go next line, but the overall file tree layout will not be affected.
=> pkg/cover: fix layout

pkg/covermerger/lines_matcher.go
It hopefully fixes https://github.com/google/syzkaller/issues/4815.
The default 1 second timeout is not what we want.
To reproduce the problem, set timeout to 10 ms.
=> pkg/covermerger: never give up diffing the files

pkg/covermerger/provider_monorepo.go
Closes #5213.
Some commits may be detached upstream.
Specifying the commits we increase the cloning probability.
To test it run:
```
go run ./tools/syz-covermerger/ -workdir ../workdir-cover-aggregation/ -repo git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git  -branch master -commit 3d5f968a177d468cd13568ef901c5be84d83d32b -namespace upstream -duration 7
-date-to 2024-08-23 -file-path-prefix drivers/clk/actions
```
=> pkg/covermerger: clone commits not branches

pkg/cover/heatmap.go, pkg/cover/heatmap_test.go, pkg/cover/templates/heatmap.html
Hover mouse onto the percent value to see details.
It enables hover details for both, command line tool and dashboard.
To test:
$ go run ./tools/syz-cover -heatmap upstream -from 2024-08-23 -to 2024-08-23
$ google-chrome upstream.html
=> pkg/covermerger: add debug tooltips

tools/syz-bq.sh
=> tools/syz-bq: session was moved to syz-covermerger

tools/syz-covermerger/syz_covermerger.go
There is no need to print this data if we submit result to dashapi.
It currently pollutes the logs.
=> tools/syz-covermerger: don't print merge result for dashapi client

tools/syz-bq.sh
tools/syz-covermerger uses CheckoutCommit() now.
CheckoutCommit calls "git fetch --tags origin commit".
The tags are not available in this case.
=> tools/syz-bq: make sure branch information is available locally

pkg/covermerger/provider_monorepo.go, pkg/vcs/fuchsia.go, pkg/vcs/git.go, pkg/vcs/vcs.go
We currently checkout commits only.
It results in git origins w/o branch information.
Adding the branch names we simplify the repo reuse.
It also checks for the commit presence in local repo.
The alternative to CommitExists() function was a ListCommitHashes().
ListCommitHashes() takes apx. 5 seconds which is too slow.
=> pkg/covermerger: optimize checkouts

Makefile, docs/contributing.md, tools/docker/env/Dockerfile
When act -j build in local host, it reports:
exec failed: unable to start container process: exec: "node": executable file
not found in $PATH: unknown
=> tools/docker: add missing node in syz-env

pkg/fuzzer/fuzzer.go, pkg/fuzzer/job.go, pkg/fuzzer/job_test.go, syz-manager/http.go
Instead of printing the full program, enable per-job logs.
=> pkg/fuzzer: make job logging more flexible

executor/conn.h
Occasionally a SIGCHLD would cause EINTR to be returned by pselect(), and then the runner would become hung by attempting to read a socket that was not in fact ready.
=> executor: retry pselect() when interrupted

pkg/report/linux.go, pkg/report/testdata/linux/report/721
Bugs are unlikely to be in the rhashtable code itself.
Example: https://syzkaller.appspot.com/bug?extid=128aaac913636290e5a9
=> pkg/report: ignore rhashtable_lookup frames

pkg/report/linux.go, pkg/report/linux_test.go
Call trace can have line like below printed by %pSb:
func_name+0x254/0x5f0 [module_name b31b29679ab712c360bddd861f655ab24898b4db]
=> pkg/report: support module format with stacktrace_build_id

pkg/manager/repro.go, pkg/manager/repro_test.go
It was processed incorrectly in the repro loop - we should have skipped that crash and looked for another one, but we actually ignored its return value.
=> pkg/manager: properly handle NeedRepro() == false

docs/linux/kernel_configs.md
After Linux 5.12, the `CONFIG_DEBUG_INFO` is replaced by `CONFIG_DEBUG_INFO_{NONE, DWARF4, DWARF5, DWARF_TOOLCHAIN_DEFAULT}`.
If a user simply adds `CONFIG_DEBUG_INFO=y` to the configuration and run `make olddefconfig`, the configuration will fallback to `CONFID_DEBUG_INFO_NONE`, causing syzkaller's failure in obtaining coverage.
This patch solves this by adding the *safe* configuration `CONFIG_DEBUG_INFO_DWARF_TOOLCHAIN_DEFAULT`, so the kernel will be compiled based on what the user has.
This …
=> docs/linux: update debug info kernel config

tools/syz-cover/syz-cover.go
This adds the force flag to syz-cover, and makes syz-cover aware of the debug flag.
I'm only uncertain about the wording on the description for the new force flag.
It also doesn't line up exactly with the error message below, but I think it's a relatively intuitive thing to try.
`x out of y PCs returned by kcov do not have matching coverage callbacks. Check the discoverModules() code. Use ?force=1 to disable this message.`
Closes #5265
=> tools/syz-cover: capture debug flag and add force flag

executor/common_kvm_arm64_syzos.h, sys/linux/dev_kvm.txt, sys/linux/test/syz_kvm_setup_cpu_arm64-memwrite
The new API call will be used to write values to guest memory specified by base+offset.
Writing to e.g. MMIO registers for VGIC (or any other MMIO ranges) may result in new coverage.
=> executor: sys/linux: arm64: implement SYZOS_API_MEMWRITE

dashboard/app/app.yaml
go122 is the latest supported. Let's update.
https://cloud.google.com/appengine/docs/standard/lifecycle/support-schedule#go
=> dashboard/app: use go122

dashboard/app/graphs.go, pkg/cover/heatmap.go, pkg/coveragedb/time_period.go, pkg/coveragedb/time_period_test.go, tools/syz-cover/syz-cover.go
Current coverage is a week long data merge for every day.
The goal is to show a monthly data by default and make daily data available for &period=day requests.
This commit makes the first two steps:
1. Make the day a day long, not a week long aggregation.
2. Enable the month long merges available for &period=month.
=> dashboard/app: use day long aggregations not week long

sys/linux/dev_kvm.txt
According to
https://elixir.bootlin.com/linux/v6.10.9/source/include/uapi/linux/kvm.h, the third member of `struct kvm_coalesced_mmio_zone` is a union of `__u32 pad` and `__u32 pio`, where `pio` can be 0 or 1, depending on whether the user wants to use KVM_MMIO_BUS or KVM_PIO_BUS (see also https://elixir.bootlin.com/linux/v6.10.9/source/virt/kvm/coalesced_mmio.c#L137)
=> sys/linux/dev_kvm.txt: fix the description of kvm_coalesced_mmio_zone

dashboard/app/cron.yaml
It fixes the "INVALID_ARGUMENT: Cron jobs only support Groc format for schedule." error.
=> dashboard/app: fix cron schedule

dashboard/app/api.go, dashboard/app/api_test.go
Per: https://github.com/google/syzkaller/issues/4992#issuecomment-2334090331
>If there are non-revoked reproducers, we will always prefer them to the revoked ones. And we do update the priority once we have revoked a reproducer. But if the only reproducer was revoked, we still give that crash a higher priority than other crashes, which never had a reproducer attached.
>
>If "repro revoked" should have the same priority as "no repro", then we just need to update Crash.UpdateReportingPriority.
Fixes: https://github.com/google/syzkaller/issues/4992.
=> dashboard/app: priority of revoked & no repro

dashboard/app/main.go
This PR changes the default period for coverage details pages to 1 month.
Nothing changes for the total page. The parameter in URI is needed as a reminder.
=> set default periods for coverage pages

pkg/rpcserver/rpcserver.go, pkg/rpcserver/runner.go, syz-manager/manager.go
It does sometimes happen that the kernel is crashed so fast that syz-manager is not notified that the syz-executor has started running the faulty input.
In cases when the exact program is known from Comm, let's make sure it's always present in the log of the last executed programs.
=> pkg/rpsever, syz-manager: always include the program from Comm

pkg/cover/file.go
If no coverage for file is available, we panic(nil deref).
New code doesn't panic.
=> pkg/cover: assume no coverage exists

dashboard/config/linux/bits/arm64.yml, dashboard/config/linux/upstream-arm64-full-base.config, dashboard/config/linux/upstream-arm64-full.config, dashboard/config/linux/upstream-arm64-kasan-base.config, dashboard/config/linux/upstream-arm64-kasan.config, dashboard/config/linux/upstream-arm64-kasan_sw-kcov-base.config, dashboard/config/linux/upstream-arm64-kasan_sw-kcov.config, dashboard/config/linux/upstream-arm64-mte-base.config, dashboard/config/linux/upstream-arm64-mte.config
It seems to have caused boot problems on ci-upstream-gce-arm64 (see #5303).
Reported-by: Sabyrzhan Tasbolatov <snovitoll@gmail.com>
=> dashboard/config: restore CMDLINE_FROM_BOOTLOADER on arm64

dashboard/app/entities_datastore.go
For many managers, 500 are not enough to even cover the last year.
Cc: @pchaigno
=> dashboard: display up to 1000 last builds

pkg/build/android.go, pkg/build/cuttlefish.go
Copy Cuttlefish module objects to be used
in coverage report generation.
=> pkg/build/cuttlefish: copy module objects

syz-manager/hub.go
These no longer make any sense since we only send programs after the corpus triage.
=> syz-manager: remove syz-hub prog add statistics

dashboard/app/graphs.go, dashboard/app/main.go, pkg/cover/file.go, pkg/coveragedb/time_period.go, pkg/coveragedb/time_period_test.go, pkg/covermerger/provider_web.go, pkg/validator/validator.go, tools/syz-cover/syz-cover.go, tools/syz-covermerger/syz_covermerger.go
It directly uses the coverage signals from BigQuery.
There is no need to wait for the coverage_batch cron jobs.
Looks good for debugging.
Limitations:
1. It is slow on large periods. I know how to speed up but want to stabilize the UI first.
2. It is expensive because of the direct BQ requests. Limited to admin mostly because of it.
3. It merges only the commits reachable on github because of the gitweb throttling.
After the UI stabilization I'll save all the required artifacts to spanner and make this page publicly available.
To merge all the commits, not the github reachable only, http git caching instance is needed.
To test:
/upstream/graph/coverage/file?dateto=2024-08-31&period=day&commit=20371ba120635d9ab7fc7670497105af8f33eb08&filepath=virt/kvm/kvm_main.c
=> dashboard/app: add file coverage page

pkg/bisect/bisect.go, pkg/bisect/bisect_test.go, pkg/build/build.go, pkg/build/build_test.go, pkg/osutil/osutil.go, syz-ci/jobs.go, syz-ci/manager.go
Handle SIGKILL (exit code = 137) on osutil.Run() during Linux kernel image
building and return build.InfraError without reporting.
Fixes: https://github.com/google/syzkaller/issues/5317
=> pkg/build: handle OOM-killed build error

pkg/report/report.go, pkg/report/testdata/linux/report/706
Sometimes it may happen that we only get part of the string. Let's suppress the report both for the specific error message and for ALSA in general.
=> pkg/report: better suppress ALSA-caused go runtime error

syz-ci/manager.go
If we failed to build/test the current tip of the tree, it seems that we still stay on that commit, which may lead to problems in fix commit collection, coverage report generation and in determining the right people to Cc.
Always reset to the last successfully built kernel commit before restarting a syz-manager instance.
Closes #5333.
=> syz-ci: reset to the build commit at restart

pkg/instance/execprog.go, pkg/instance/instance.go, pkg/instance/instance_test.go
Reduce the number of arguments by using a csource.Options value directly.
=> pkg/instance: refactor ExecprogCmd

tools/create-buildroot-image.sh
It will enable Buildroot image usage also for the kenrels that don't enable CONFIG_DEVTMPFS_MOUNT.
On the kernels with `CONFIG_DEVTMPFS_MOUNT` enabled, the kernel prints `mount: mounting devtmpfs on /dev failed: Device or resource busy` to the serial output, but otherwise everything works fine.
=> tools: mount devtmpfs in Buildroot images explicitly

docs/linux/setup.md
go.mod has been bumped with go 1.22.1 version recently. So let's update the documentation as well.
https://github.com/google/syzkaller/blob/master/docs/linux/setup.md#go-and-syzkaller
=> doc: update go version in syzkaller setup

pkg/covermerger/bq_csv_reader.go, pkg/validator/validator.go, pkg/validator/validator_test.go
The consistency make the code more predictable.
We want all the values to be non-empty (commit, kernelPath, etc.).
If "empty" is an option - use validator.AnyOk(validator.EmptyStr(target), otherCheck(target)).
=> pkg/validator: target value is not empty by default

syz-ci/jobs.go
We currently observe episodic "job: reproducer consistency is empty" error messages, but there's little one can do with them.
Make them more actionable.
=> syz-ci: include more details in job error logs

dashboard/app/coverage_batch.go
Sometimes 6 hours are not enough to make the quarter long aggregation.
Typically 5 hours 30 minutes are enough.
=> dashboard/app: set coverage batching timeout to 12 hours

dashboard/app/access.go, dashboard/app/app_test.go, dashboard/app/config.go, docs/setup_syzbot.md
In some situations, it could be useful to share access to the dashboard to multiple authentication domains. The current GlobalConfig format doesn't really allow it so this deprecates the existing field and add a new slice of allowed authentication domains.
=> dashboard: allow multiple allowed authentication domains

tools/docker/syzbot/Dockerfile
Some builds require these tools and update-alternatives lets us use these tools without hardcoding the LLVM version suffix.
=> tools/docker/syzbot: add llvm-strip and llvm-readelf alternatives

pkg/build/build.go, pkg/build/freebsd.go, pkg/build/netbsd.go
It was reported in https://groups.google.com/g/syzkaller/c/GV3JjN6RrPk that linux kernel clean tasks call make with "-j0" this is because the clean function wasn't replicating the build function's default number of CPUs.
While I was at it, I also rationalised a couple of OS-specific implementations of the clean function that were extracting the number of CPUs themselves.
=> Fix kernel clean tasks

pkg/manager/seeds.go
Some seeds are arch-dependent, so it's to be expected that we do not take them.
Ideally we should have been parsing the conditions in pkg/manager as well, but for now it does not seem to be worth the refactoring effort.
=> pkg/manager: lower the broken seed error message

tools/syz-declextract/run.go
I've got this error when trying to run the tool:
arch/x86/tools/relocs_64.c: In file included from arch/x86/tools/relocs_64.c:2:
In file included from arch/x86/tools/relocs.h:5:
/usr/include/stdio.h:33:10: fatal error: 'stddef.h' file not found
The arch/x86/tools/relocs_64.c is part of some host tool
that was compiled with gcc. And probably my clang installation
is somehow broken and can't compile normal user-space C programs.
Skip files that were not compiled with clang.
We don't need to analyze them (host tools),
and it also solves my clang problem.
=> tools/syz-declextract: don't analyze host files

dashboard/app/batch_reproexport.go
1. Silent git clone to not write "Cloning syzkaller..." into stderr.
2. Download in 10 threads to speed up testing.
3. Use gcloud token to bypass throttling.
4. CI=1 to stop writing warnings into stderr.
=> dashboard/app: tune repro export

tools/docker/syzbot/Dockerfile
ARM64 instances may require running QEMU, so add it to the container.
=> tools/docker: add QEMU packages to ARM64 docker container

pkg/report/linux.go, pkg/report/testdata/linux/report/725, pkg/report/testdata/linux/report/726, pkg/report/testdata/linux/report/727, pkg/report/testdata/linux/report/89
Take a frame from the stack trace that is included in the bug report.
=> pkg/report: improve Bad page state parsing

CONTRIBUTORS, tools/syz-build/build.go
While `Ccache` is a field in `build.Params`, a user of `syz-build` does not have the option to set it via the CLI. This PR exposes a CLI flag for `ccache` and passes it to `build.Params`.
=> tools/syz-build: expose ccache as cli flag

dashboard/app/access.go, dashboard/app/access_test.go, dashboard/app/app_test.go, dashboard/app/config.go, dashboard/app/handler.go
1. This PR unit test the accessLevel function internals and
2. Introduces the authorized AccessPublic requests
We need AccessPublic authorization primarily to stop throttling our own service accounts.
=> dashboard/app: introduce authorized access to public resources

dashboard/app/batch_reproexport.go
https://www.googleapis.com/auth/userinfo.email scope is needed to include email info the token.
The token is later generated by "gcloud auth print-access-token".
=> dashboard/app: specify reproexport serviceAccount scopes

dashboard/app/config.go, dashboard/app/graphs.go, pkg/covermerger/provider_web.go
We don't want to scale the github repo usage.
Let's eventually switch to the internal service.
=> dashboard/app: make WebGitURIProvider configurable

Makefile, pkg/corpus/corpus.go, pkg/corpus/corpus_test.go, pkg/corpus/minimize.go, pkg/corpus/prio.go, pkg/corpus/prio_test.go, pkg/fuzzer/fuzzer.go, pkg/fuzzer/job.go, pkg/fuzzer/queue/queue.go, pkg/fuzzer/queue/stats.go, pkg/manager/covfilter.go, pkg/manager/crash.go, pkg/manager/crash_test.go, pkg/manager/diff.go, pkg/manager/http.go, pkg/manager/report_generator.go, pkg/mgrconfig/config.go, pkg/mgrconfig/load.go, pkg/repro/repro.go, pkg/rpcserver/local.go, pkg/rpcserver/rpcserver.go, pkg/rpcserver/rpcserver_test.go, pkg/vcs/git.go, pkg/vcs/git_test.go, prog/meta.go, syz-manager/manager.go, syz-manager/snapshot.go, tools/syz-diff/diff.go, tools/syz-diff/patch.go
This is the prototype version of the patch series fuzzing functionality based on the syzkaller fuzzing engine.
The tool takes two syzkaller configs -- one for the base kernel, one for the patched kernel. The patch itself can optionally be also provided.
syz-diff will consider a bug patched-only if:
1) It happened while fuzzing the patched kernel.
2) It was never observed on the base kernel.
3) The tool found a repro on the patched kernel.
4) The repro did not crash the base kernel.
=> tools: add a syz-diff tool

pkg/email/parser.go, pkg/email/parser_test.go
It changed recently and it broke our email discussion link extraction.
Closes #5431.
=> dashboard: adapt to the new Googe Groups footer

.golangci.yml, pkg/cover/backend/dwarf.go
Fix linter reported issue with "err != nil" is always true and add "this check suggests that the pointer can be nil" to the exclusion rules as the false-positives due to non-standard/standard package's Fatalf() exiting.
```
$ make lint
bin/golangci-lint run  ./...
pkg/cover/backend/dwarf.go:180:8: SA4023: this comparison is always true
if err != nil {
^
sys/fuchsia/fidlgen/main.go:24:5: SA5011(related information): this check suggests that the pointer can be nil
if target == nil {
tools/syz-declextract/run.go:95:6: SA5011(related information): this check suggests that the pointer can be nil
if parse == nil {
^
tools/syz-declextract/run.go:234:5: SA5011(related information): this check suggests that the pointer can be nil
if netlinkUnionParsed == nil {
^
prog/encodingexec_test.go:60:6: …
```
=> lint: fix lint issues

pkg/mgrconfig/load.go
If we have converted one way of configuration into another, we should reset the old one.
Otherwise after the processing in syz-ci both will be set and the instance no longer starts due to
"you cannot use both cov_filter and focus_areas".
=> pkg/mgrconfig: properly convert cover_filter

pkg/report/linux.go, pkg/report/testdata/linux/report/728
These are just warnings to the system administrator. Ignore them during fuzzing.
=> pkg/report: ignore warnings printed by __ext4_msg

sys/linux/socket_bluetooth.txt
Replace socket_$bt_{bnep, cmtp, hidp, rfcomm} to syz_init_net_socket.
Fixes: https://github.com/google/syzkaller/issues/4729
=> sys/linux: use syz_init_net_socket for bluetooth

pkg/build/build.go, pkg/build/starnix.go, pkg/vcs/fuchsia.go, pkg/vcs/vcs.go, vm/starnix/starnix.go
After this, syz-ci can build Starnix and run syz-manager with a manager config with `"type": "starnix"`.
=> pkg/build: add build command for starnix

dashboard/api/client.go, dashboard/app/handler.go, dashboard/app/templates/error.html
2024/10/26 00:08:09 alert: error: api request "https://syzkaller.appspot.com/text?json=1&tag=ReproC&x=11003952980000" failed: 500 (%!w(<nil>))
1. We have a 500 error w/o explanation. Let's dump some body here to better understand root-cause.
2. It is hard to filter AppEngine errors. Let's use "appengine error: " prefix.
3. Let's return traceID in body to simplify the errors analysis.
=> dashboard/api: better error description

dashboard/app/batch_reproexport.go, tools/syz-reprolist/reprolist.go
1. Don't print per-file log by tool.
2. Disable tar verbosity.
3. Make gsutil quiet.
=> dashboard/app: generate fewer logs exporting reproducers

.github/dependabot.yml
https://github.com/dependabot/dependabot-core/issues/7542#issuecomment-1664438228
Dependabot can't create the PRs for some reason. The logs don't explain why.
It may be the root cause.
=> dependabot.yml: remove dash from the names

tools/syz-reproducers.sh
It downloads the repro archive and build all files:
...
Downloaded 4487 reproducers.
Successfully built 4487 programs.
It mimics what was done by @dvyukov on https://github.com/dvyukov/syzkaller-repros/blob/master/build.sh .
=> tools/syz-reproducers.sh: download and build tool

.github/dependabot.yml
For some reason dependabot doesn't create PRs for group updates.
We have a tracking issue for it #5466 .
Let's disable grouping for now.
=> dependabot.yml: revert changes, don't use groups

.github/dependabot.yml
Merging the dependency update we trigger rebase and retest for other PRs.
Reducing the amount of PRs we reduce ARC pressure.
=> dependabot.yml: limit to max 5 PRs

.github/dependabot.yml
Mockery and golangci-lint updates typically require more efforts.
I don't see any value in mockery updates now.
=> dependabot.yml: let's ignore mockery

.github/dependabot.yml
For some reason dependabot stopped to create PRs again.
I think it happened after this change. Let's check this assumption.
=> dependabot.yml: remove mockery from ignore list

pkg/coveragedb/spanner.go, tools/syz-covermerger/init_db.sh, tools/syz-covermerger/syz_covermerger.go
Instrumented lines + hit count gives more information than instrumented + covered lines.
Expected storage cost is at the same level.
=> pkg/coveragedb: store hitcount instead of coveredlines

dashboard/app/graphs.go, pkg/cover/file.go, pkg/cover/heatmap.go, pkg/coveragedb/spanner.go, tools/syz-cover/syz-cover.go
We currently merge bigquery data for every lines coverage request.
Let's read cached lines coverage data from spanner instead.
It allows to get only 1 file version from git and skip the data merge step.
P.S. Line coverage data is available for the last month only (will require coverage table drop to update other columns).
=> dashboard/app: read lines coverage from spanner

pkg/validator/validator.go, pkg/validator/validator_test.go
The main problem - kernel file path may contain "-". Let's allow it.
Side problems:
1. Two -- are better to be blocked. It may be used as an SQL comment.
2. Some regexp engines consider "-" as a range. Let's move it to the end.
=> pkg/validator: fix regexp mistake

dashboard/app/batch_coverage.go
Stderr output is interpreted as an error.
Let's stop printing "Cloning into 'syzkaller'..." to stderr.
=> dashboard/app: silence git clone in batch_coverage

pkg/html/pages/stats.go, pkg/html/pages/stats.html, pkg/html/pages/stats_test.go, pkg/html/pages/style.css, pkg/manager/html/common.html, pkg/manager/html/corpus.html, pkg/manager/html/crash.html, pkg/manager/html/fallback_cover.html, pkg/manager/html/job_list.html, pkg/manager/html/main.html, pkg/manager/html/prio.html, pkg/manager/html/raw_cover.html, pkg/manager/html/syscalls.html, pkg/manager/html/text.html, pkg/manager/html/vms.html, pkg/manager/http.go, pkg/manager/http_test.go, syz-manager/manager.go, vm/dispatcher/pool.go, vm/dispatcher/pool_test.go
- **pkg/manager: add common page header type**
- **pkg/manager: add common HTML page header**
- **syz-manager: add pause function**
- **pkg/manager: wrap stats page with the common header**
=> syz-manager: add common HTML header to every page

dashboard/app/static/coverage.js, pkg/cover/templates/heatmap.html
Chrome  devtools allow to edit js code directly in browser.
But it doesn't allow to edit the JS code on HTML page.
This change will speed up further development.
=> dashboard/app: move coverage page js code to static file

pkg/instance/execprog.go, pkg/instance/instance.go, pkg/repro/repro.go, pkg/repro/repro_test.go, pkg/repro/strace.go, syz-manager/manager.go, tools/syz-diff/diff.go, tools/syz-repro/repro.go
Refactor pkg/repro to accept a context.Context object. This will make it look more similar to other package interfaces and will eventually let us abort currently running repro jobs without having to shut down the whole application.
Simplify the code by factoring out the parameters common both to RunSyzRepro() and RunCRepro().
=> pkg/repro: accept a cancellable context

executor/executor_runner.h, pkg/rpcserver/runner.go
After 9fc8fe026baa ("executor: better handling for hanged test processes"), syz-executor's responses may reference procids outside of the [0;procs] range.
If procids are no longer dense on the syz-executor side, we cannot rely on this check in pkg/rpcserver:
```
if avoid == (uint64(1)<<runner.procs)-1 {
avoid = 0
}
```
=> executor: use any executor if the avoid mask included all of them

pkg/report/linux.go, pkg/report/testdata/linux/report/730
It's a helper used by many different filesystems. Let's be more specific.
https://syzkaller.appspot.com/bug?extid=651ca866e5e2b4b5095b
=> pkg/report: ignore the drop_nlink frame

executor/executor.cc, executor/executor_linux.h, executor/snapshot.h, pkg/flatrpc/flatrpc.fbs, pkg/flatrpc/flatrpc.go, pkg/flatrpc/flatrpc.h, pkg/fuzzer/fuzzer.go, pkg/fuzzer/stats.go, pkg/manager/html/syscalls.html, pkg/manager/http.go, prog/prog.go
If the overflows happen often, it's bad.
Add visibility into this.
=> pkg/manager: show number of times coverage for each call has overflowed

vm/adb/adb.go, vm/bhyve/bhyve.go, vm/gce/gce.go, vm/gvisor/gvisor.go, vm/isolated/isolated.go, vm/qemu/qemu.go, vm/vm.go, vm/vmm/vmm.go, vm/vmware/vmware.go
Move the VM count restriction logic info vm package.
This avoids lots of duplication, makes it supported
for VM types that failed to do this, and allows
to unify more VM count logic in future.
=> vm: dedup VM count restriction in debug mode

pkg/vminfo/linux.go, pkg/vminfo/netbsd.go, pkg/vminfo/openbsd.go, pkg/vminfo/vminfo.go
Use default nop implementation for most openbsd/netbsd methods.
Move linux-specific vm type checks to linux code.
Remove indirection for CheckFiles as we have for RequiredFiles.
=> pkg/vminfo: refactor few things

executor/executor.cc, pkg/runtest/run_test.go
Currently we write coverage backwards.
This is visible e.g. when running syz-execprog -coverfile.
Write it in the right order.
=> executor: don't revert coverage order

pkg/ifaceprobe/ifaceprobe.go, syz-manager/manager.go
Package ifaceprobe implements dynamic component of automatic kernel interface extraction.
Currently it discovers all /{dev,sys,proc} files, and collects coverage for open/read/write/mmap/ioctl
syscalls on these files. Later this allows to build file path <-> file_operations mapping.
=> pkg/ifaceprobe: add package

tools/docker/env/Dockerfile, tools/docker/syzbot/Dockerfile
As part of #5518, I'm adding fsck logs as annotation to the mounted file system assets. For this, I need a variety of fsck-like commands in the ci environment as well as eventually in the production environment.
=> tools/docker: add various fsck-like commands to the environment

docs/contributing.md, tools/syz-env
Useful for testing local Dockerfile changes that have not been pushed yet.
In extension of commit 326f9c5a1cae ("tools/syz-env: export https_proxy to docker in case behind proxy"), cover further HTTP proxy environment variables and the Docker build process.
=> tools/syz-env: add local build option and consider HTTP proxy environment variables

executor/test.h
=> executor: remove a tempnam() call from test.h

pkg/bisect/bisect.go, pkg/bisect/bisect_test.go, pkg/report/crash/types.go, vm/vm.go, vm/vm_test.go
These have been the cause of too many invalid bisection results recently.
This is the first step towards the more universal approach of https://github.com/google/syzkaller/issues/5414.
=> pkg/bisect: ignore irrelevant lost connection crashes 

syz-ci/manager.go, syz-ci/syz-ci.go
syz-ci calls several `Dashboard` methods, and the case of a nil `Dashboard` pointer receiver was not handled. This change allows syz-ci to operate with a nil dashboard. (In terms of the [syzbot setup docs](https://github.com/google/syzkaller/blob/master/docs/setup_syzbot.md), we wanted to deploy a test instance of syz-ci without deploying a dashboard.)
=> syz-ci: run syz-ci without a dashboard

vm/qemu/qemu.go
The new qemu versions began to fail with the settings we previously used. It's probably not worth extensive debugging, so let's just do what qemu suggests.
```
qemu-system-arm: Invalid CPU model: max
The only valid type is: cortex-a15
```
=> vm: use -cpu cortex-a15 for qemu/arm32

pkg/vcs/fuchsia.go
This is a temporary workaround for managing a fuchsia checkout:
- Mark the repo as "precious" so that checkout operations don't delete GN args and other build configuration state. In a follow-up, this will be replaced by a fuchsia-specific `repair` method using `fx clean`.
- Checkout operations apply only to fuchsia.git, which has a chance of creating inconsistencies between versions of fuchsia and its dependencies. The main poll workflow (using `jiri`) is not affected by this problem, but bisection workflows may fail. This will be fixed in a follow-up by checking out branches and commits from fuchsia's global integration repo.
=> pkg/vcs: implement remaining Repo methods for fuchsia

pkg/vcs/linux_patches.go
It unblocks the bisection for the period of Jan 2021-Mar 2021.
=> pkg/vcs: backport "Fix broken irq restoration in kvm_wait" for bisect

pkg/vminfo/linux.go
_etext symbol points to the _next_ section, so it has type of the next section.
It can be at least T, D, or R in some cases:
https://groups.google.com/g/syzkaller/c/LSx6YIK_Eeo
=> pkg/vminfo: fix up _etext symbol parsing

pkg/report/linux.go, pkg/report/testdata/linux/report/733
These frames are not very informative.
See https://syzkaller.appspot.com/bug?extid=72d3b151aacf9fa74455
=> pkg/report: skip get_taint and put_device

pkg/runtest/executor_test.go, tools/docker/env/Dockerfile
When running on Github CI, turn every failure to start a cross-arch binary (e.g. due to missing qemu-user) into a fatal error.
=> pkg/runtest: make cross-arch failures fatal on CI

executor/snapshot.h
We missed that step for snapshot mode.
=> executor: setup sysctl/cgroups in snapshot mode

pkg/build/starnix.go
This is a fixup to https://github.com/google/syzkaller/pull/5543: the `--dir` argument to `fx` in the `fx set` step should be a path relative to the kernel dir, not an absolute path.
=> pkg/build: use relative path for fx set directory arg

pkg/vcs/fuchsia.go
Shall we merge this for now and revert when no longer needed?
=> pkg/vcs: work around bug in jiri prebuilt_versions hook

pkg/report/linux.go, pkg/report/testdata/linux/report/734
Currently we mis-parse all of them, and attribute the bug to HWASAN.
=> pkg/report: fix parsing of HWASAN reports

dashboard/dashapi/dashapi.go, pkg/cover/heatmap.go, pkg/coveragedb/spanner.go, pkg/covermerger/bq_csv_reader.go, pkg/covermerger/covermerger.go, pkg/covermerger/covermerger_test.go, tools/syz-covermerger/init_db.sh, tools/syz-covermerger/syz_covermerger.go
This PR starts to collect the per-manager data.
It eventually enables us to see the per-manager and manager unique coverage.
Manager unique coverage will require additional processing on the AE side but we'll be able to see unique coverage from any combination of the namespace managers.
=> pkg/covermerger: aggregate data per-manager

tools/syz-covermerger/init_db.sh
`select count(distinct session) from files` works as fast with multicolumn index as before.
=> pkg/coveragedb: add (session, manager) index to files

syz-ci/manager.go, syz-ci/managercmd.go
ManagerCmd transparently restarts the instance in case of crashes, so we should better be cleaning up the bench file within its loop, rather than in manager.go.
=> syz-ci: rename bench file on all syz-manager restarts

dashboard/dashapi/dashapi.go
It may help to compress huge coverage json w/o OOM.
=> dashboard/dashapi: change json encoding to stream

dashboard/app/api.go, dashboard/app/reporting_external.go
Let's ignore gz.Close() error because we may not read all data.
gz.Close() returns error if the checksum of the data read != gz checksum.
=> dashboard/app: deserialize data directly from gz reader

pkg/cover/file.go, pkg/covermerger/covermerger.go, pkg/covermerger/covermerger_test.go, pkg/covermerger/file_line_merger.go, tools/syz-covermerger/syz_covermerger.go
We need coverage details for all usage scenarios.
It makes sense to remove this option.
=> pkg/covermerger: always store details

executor/subprocess.h, pkg/instance/execprog.go, pkg/mgrconfig/config.go, pkg/mgrconfig/load.go, sys/targets/targets.go
In some build environments (notably Yocto), syzkaller host and target binaries end up in separate packages for each built architecture, which are then shipped with the respective image/SDK.
Add the `Execprog`/`ExecutorBinOnTarget` and `StraceBinOnTarget` options to the manager config, which when set expects the respective binaries to be shipped with the target image and does not attempt to copy them from the host.
=> all: add support for binaries shipped with target

pkg/clangtool/clangtool.go, pkg/declextract/declextract.go, pkg/declextract/entity.go, pkg/declextract/serialization.go, pkg/declextract/typing.go, pkg/testutil/testutil.go, sys/linux/auto.txt, tools/syz-declextract/clangtool/declextract.cpp, tools/syz-declextract/clangtool/json.h, tools/syz-declextract/clangtool/output.h, tools/syz-declextract/declextract.go, tools/syz-declextract/declextract_test.go, tools/syz-declextract/testdata/functions.c, tools/syz-declextract/testdata/functions.c.info, tools/syz-declextract/testdata/functions.c.json, tools/syz-declextract/testdata/functions.c.txt, tools/syz-declextract/testdata/types.c, tools/syz-declextract/testdata/types.c.json
Use data flow analysis to infer syscall argument, return value,
and struct field types.
See the comment in pkg/declextract/typing.go for more details.
=> tools/syz-declextract: infer argument/field types

dashboard/app/main.go
This fixes a runtime panic when generating links to fsck logs.
=> dashboard/app: provide a text filename to fsck logs

prog/rotation_test.go
Now that we added automatically generated syscalls to the Linux corpus, we added a lot of work to the TestRotationCoverage test. We can make it faster by skipping all automatically generated syscalls.
=> prog: make TestRotationCoverage faster

pkg/cover/file.go, pkg/covermerger/covermerger.go, pkg/covermerger/covermerger_test.go
The problem is the deadlock happening on GCS storage error.
GCS client establishes the connection when it has enough data to write. It is approximately 16M.
The error happens on io.Writer access in the middle of the merge.
This error terminates errgroup goroutine. Other goroutines remain blocked.
This commit propagates termination signal to other goroutines.
=> pkg/covermerger: propagate context cancellation

dashboard/app/api_test.go
It tests the Dashboard.CreateUploadURL.
It internally calls "create_upload_url" method of the dashboard "/api" interface.
This dashboard API requires GlobalConfig.UploadBucket option to specify the bucket.
Dashboard generates the $bucket/$uuid.upload URL and returns it to the client.
=> test coverage upload dashapi

dashboard/app/api.go
All API handlers expect input stream to be ungzipped. This wrapper shouldn't be the exception.
=> dashboard/app: gcsPayloadHandler ungzips the gcs content

pkg/coveragedb/coveragedb.go
Current tests check the amount of data transfered to the mock.
But they didn't check the data correctness.
Because of this bug every batch have the same coverage which is nonsense.
=> pkg/coveragedb: fix data unpacking bug

pkg/coveragedb/init_db.sh
Current schema makes session+filepath a primary key (it is unique).
Manager as a part of primary key makes session+filepath+manager a unique combination.
New schema allows us to store information from different managers.
=> pkg/coveragedb: fix schema in order to support multiple managers

dashboard/app/graphs.go, pkg/cover/heatmap.go
It allows to see per-manager coverage aggregations with `&manager=your_candidate`.
https://syzkaller.appspot.com/upstream/graph/coverage_heatmap?period=month&manager=your_candidate
=> dashboard/app: show manager coverage

pkg/email/lore/read.go, pkg/vcs/fuchsia.go, pkg/vcs/git.go, pkg/vcs/git_test.go, pkg/vcs/vcs.go
Support filtering by the commit date.
It was part of #5620.
=> pkg/vcs: extend ListCommitHashes

pkg/vcs/fuchsia.go, pkg/vcs/git.go, pkg/vcs/git_repo_test.go, pkg/vcs/git_test.go, pkg/vcs/git_test_util.go, pkg/vcs/linux.go, pkg/vcs/linux_patches.go, pkg/vcs/testos.go, pkg/vcs/vcs.go
One more part of #5620 (see the discussion there as well).
***
It will let other parts of the code to use only the git-specific functionality.
=> pkg/vcs: export GitWrapper

dashboard/app/graphs.go, dashboard/app/static/coverage.js, pkg/cover/heatmap.go, pkg/cover/templates/heatmap.html
It allows to control known parameters:
1. Period (months or days).
2. Target subsystem.
3. Target manager.
And adds the disabled "Only unique" checkbox.
=> dashboard/app: add targeting controls to the coverage page

executor/common_kvm_arm64_syzos.h
Make sure operands passed to 64-bit MOV, MSR and MRS instructions are actually 64-bit.
This fixes compiler warnings in certain build configurations.
=> executor: arm64: fix compiler warnings on inline assembly

.github/workflows/oss-fuzz.yml
=> .github/workflows: use upload-artifacts v4 in oss-fuzz workflow

.golangci.yml
In order to remove warning:
The linter \"gomnd\" is deprecated (step 2) and deactivated. It should be removed from the list of disabled linters. https://golangci-lint.run/product/roadmap/#linter-deprecation-cycle
=> .golangci.yml: remove deprecated gomnd

pkg/email/lore/parse.go, pkg/email/lore/parse_test.go, pkg/email/lore/read.go, tools/syz-lore/query_lkml.go
Another part of #5620.
***
Refactor the code to make it more reusable.
Add a method to extract specifically the list of new patch series.
=> pkg/email/lore: extract patch series

vm/vmimpl/vmimpl.go
If localhost is not configured on a system, UnusedTCPPort will loop forever without producing any errors. By checking EADDRINUSE and ENOACC and then skipping only in these cases, we'd avoid at least the mentioned deadlock.
On top of this, this change should catch other errors without locking, like other DNS errors and so on.
=> vm: fix deadlock in UnusedTCPPort

pkg/image/fsck.go
My dev environment skips the osutil_linux sandbox because it doesn't have a "syzkaller" user and group. The CI environment also skips the sandbox because it sets the "CI" environment variable.
Therefore, nothing caught that, when run in the syzbot docker container, (which has a "syzkaller" user) the sandbox actually starts to be used and breaks fsck commands.
Syz-manager, which is run as root, writes the image to /tmp/1234.img with permissions 0600 and then tries to run fsck under the "syzkaller" user which doesn't have read permissions on the file, so fsck fails:
fsck.ext4 -n exited with status code 8
e2fsck 1.47.0 (5-Feb-2023)
fsck.ext4: Permission denied while trying to open /tmp/1234.img
You must have r/o access to the filesystem or be root
Changing the owner of the file to the …
=> fsck: fix permissions of the temp fs image when a sandbox is used

Makefile, sys/targets/targets.go
See [this line in the Yocto recipe](https://git.openembedded.org/meta-openembedded/tree/meta-oe/recipes-test/syzkaller/syzkaller_git.bb#n57) on why we need [Makefile: rename CFLAGS to CXXFLAGS and add LDFLAGS](https://github.com/google/syzkaller/commit/692168c54dcc33576aa8a89d0ebbce65c53bf341). [sys/targets: allow users to override hardcoded cross-compilers](https://github.com/google/syzkaller/commit/09e73637366462a14da0dfabc1eec4e672543f3c) and [sys/targets: remove hardcoded CFlags for ARM](https://github.com/google/syzkaller/pull/5627/commits/9c029f8f5fc7d129c76750b79fb2ca7585aeab76) are based upon a [Yocto recipe patch](https://git.openembedded.org/meta-openembedded/tree/meta-oe/recipes-test/syzkaller/syzkaller/0001-sys-targets-targets.go-allow-users-to-override-hardc.patch). Note that …
=> Yocto build compatibility

pkg/manager/http.go, pkg/mgrconfig/load.go, syz-ci/manager.go, syz-ci/syz-ci.go, syz-manager/manager.go, tools/syz-diff/diff.go
We don't really need an HTTP server when running syz-manager during kernel image testing and when running syz-diff automatically.
Don't require the config to be set and don't start the HTTP server in this case.
=> all: support empty HTTP config

tools/docker/README.md, tools/docker/env/Dockerfile
* Use sub-containers to parallelize/cache some build steps.
* Add a Spanner emulator binary -- it will be used in #5620
=> tools/docker: assorted updates for syz-env

sys/linux/test/arm64-syz_kvm_setup_syzos_vm-wfi, sys/linux/test/arm64-syz_kvm_setup_syzos_vm-wfit
Add sys/linux/test/arm64-syz_kvm_setup_syzos_vm-wfi and sys/linux/test/arm64-syz_kvm_setup_syzos_vm-wfit, two seeds that exercise the WFxT path in KVM.
=> sys/linux/test: add seeds that exercise WFI[T]

sys/linux/test/arm64-syz_kvm_setup_syzos_vm-enable-pmu-msr-emul-0, sys/linux/test/arm64-syz_kvm_setup_syzos_vm-enable-pmu-msr-emul-1, sys/linux/test/arm64-syz_kvm_setup_syzos_vm-enable-pmu-msr-emul-2, sys/linux/test/arm64-syz_kvm_setup_syzos_vm-msr-emul-0, sys/linux/test/arm64-syz_kvm_setup_syzos_vm-msr-emul-1, sys/linux/test/arm64-syz_kvm_setup_syzos_vm-msr-emul-2, sys/linux/test/arm64-syz_kvm_setup_syzos_vm-msr-emul-3, sys/linux/test/arm64-syz_kvm_setup_syzos_vm-msr-emul-4
When using QEMU full emulation mode, the majority of the system registers (as defined in sys/linux/dev_kvm.txt:kvm_regs_arm64_sys) are not accessible (i.e. only 77/592 trigger kvm_handle_sys_reg()). This series of tests perform MSR accesses to the accessible registers.
=> sys/linux/test: Add tests for ARM QEMU emulation

syz-manager/manager.go
We currently read an fs image twice from an io.Reader, once to upload it to the dashboard and once to write it to disk for fsck. The first io.Reader read exhausts the stream and therefore leaves an empty image to write to disk. All fsck commands fail with
fsck.ext4 -n exited with status code 8
e2fsck 1.47.0 (5-Feb-2023)
fsck.ext4: Attempt to read block from filesystem resulted in short
read while trying to open /tmp/1234.img
Could this be a zero-length partition?
This basically duplicates the io.Reader using a Tee. I considered refactoring the asset upload and fsck APIs to use a buffer instead of a reader but this leads to a rather far fetching refactoring. Duplicating streams here seemed to be a more self-contained change.
=> syz-manager: fix empty fs images being run through fsck

tools/docker/env/Dockerfile
Prevent Go from downloading all external dependencies each time syz-env is called. It will become a problem once vendor/ is deleted.
=> tools/docker/syz-env: persist GOMODCACHE

.github/CODEOWNERS, executor/_include/flatbuffers/README.md, tools/check-copyright.sh, tools/check-language.sh, tools/check-shebang.sh, tools/check-whitespace.sh
The one remaining mention is this:
https://github.com/google/syzkaller/blob/af620dc7f40ce8ec58b546376a779eff1b64cddb/executor/_include/flatbuffers/README.md?plain=1#L1-L7
Is that still relevant?
=> all: remove more mentions of the vendor folder

pkg/rpcserver/local.go, pkg/rpcserver/rpcserver.go, pkg/vminfo/linux_test.go, pkg/vminfo/vminfo.go, pkg/vminfo/vminfo_test.go
The context is assumed to be passed into the function doing the actual processing. Refactor vminfo to follow this approach.
This will help refactor pkg/rpcserver later.
=> pkg/vminfo: remove Context from the constructor

executor/common.h, executor/common_linux.h
* Linux executor now mounts /syz-inputs folder to sandbox, so user can pass their own files for fuzzing with globs. Folder is mounted as RO, so this shouldn't make sandoxing less effective. (See https://groups.google.com/g/syzkaller/c/U-DISFjKLzg for specific usecase)
* Timeouts for globs are disabled. They can be quite slow (with default settings, in my tests, globs started timing out on thousands of files), and right now, if glob resolution timeouts, nothing happens. If you are running debug, you can see the timeout error, but in any case, it is ignored and fuzzer runs with less inputs then user expected without any notification. I think that it is reasonable to wait for those longer then default program timeout.
=> executor: better support for globs

syz-cluster/controller/processor.go
If we don't consider the possibility, we risk getting a nil pointer dereference in the case it's closed:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2d648de]
goroutine 1103 [running]:
github.com/google/syzkaller/syz-cluster/controller.(*SeriesProcessor).seriesRunner(0xc000d96f80, {0x37681e0, 0xc000e37c70}, 0xc000e3d5c0)
/__w/syzkaller/syzkaller/gopath/src/github.com/google/syzkaller/syz-cluster/controller/processor.go:126 +0x21e
github.com/google/syzkaller/syz-cluster/controller.(*SeriesProcessor).Loop.func1()
=> syz-cluster/controller: handle a channel closure

pkg/flatrpc/conn.go, pkg/flatrpc/conn_test.go, pkg/manager/diff.go, pkg/manager/seeds.go, pkg/rpcserver/local.go, pkg/rpcserver/mocks/Manager.go, pkg/rpcserver/rpcserver.go, pkg/rpcserver/rpcserver_test.go, pkg/rpcserver/runner.go, syz-manager/manager.go
These calls prevent graceful error handling in the caller code. We should just return `error` and let individual tools decide what to do.
=> pkg: avoid log.Fatal calls

dashboard/app/api.go, pkg/coveragedb/coveragedb.go, pkg/coveragedb/coveragedb_mock_test.go, pkg/coveragedb/init_db.sh, pkg/covermerger/covermerger.go, pkg/covermerger/covermerger_test.go
Unblocks #5591 .
Instead of the target file function name this version is using the most popular source function name.
It will generate wrong function names if the function was renamed.
The better way is to parse the actual file.
=> pkg/coveragedb: store information about the covered functions

pkg/manager/diff.go, tools/syz-diff/diff.go
Make the method more flexible.
Rename the variables to better reflect what is being done.
=> pkg/manager: accept multiple patches in PatchFocusAreas

pkg/build/android.go, pkg/cover/backend/modules.go, tools/syz-declextract/declextract.go, tools/syz-testbed/targets.go
filepath.Walk calls os.Lstat for every file or directory to retrieve os.FileInfo. 
filepath.WalkDir avoids unnecessary system calls since it provides a fs.DirEntry, which includes file type information without requiring a stat call.
This improves performance by reducing redundant system calls.
=> all: replace Walk with WalkDir to reduce os.Lstat calls

pkg/fuzzer/queue/queue.go, pkg/rpcserver/runner.go, syz-manager/snapshot.go
Whenever the status is set, also include the reason. It should help easier debug execution and machine check time problems.
=> all: clarify the error in case of ExecFailure

pkg/fuzzer/fuzzer_test.go, pkg/rpcserver/local.go
It should hopefully let us debug #5674.
(Currently we actually don't return the error in that case, but it will change once #5700 is merged).
=> pkg/fuzzer: collect executor debug logs in tests

.github/workflows/ci.yml
**Summary**
Aux requires more dependencies than other jobs. It also doesn't fail as often as others.
Because of these two points aux will be the cache updating job.
Other jobs use `actions/cache/restore` and are the cache readers.
Old and gvisor are the special cases that are not `gcr.io/syzkaller/env` based and require additional GOMODCACHE param.
**TODO**
**Notes**
400MB cache restore costs 15s.
Cache update costs 1 minute.
It is too expensive to update the cache every build.
The proposal is to update the cache daily. The alternative is to update cache on go.mod change.
=> ci.yml: fix caching error

dashboard/app/coverage_test.go, dashboard/app/main.go, dashboard/app/templates/templates.html, pkg/cover/heatmap.go, pkg/cover/heatmap_test.go
Current links look too complex. I'd like to change naming before we introduce coverage json API.
=> dashboard/app: move coverage to /coverage link

tools/docker/syzbot/Dockerfile
Linux-next now offers a choice between using `CONFIG_GENDWARFKSYMS` and `CONFIG_GENKSYMS`. See:
* Docs: https://www.kernel.org/doc/html/next/kbuild/gendwarfksyms.html
* Series: https://patchwork.kernel.org/project/linux-kbuild/list/?series=922143
It broke our builds: https://syzkaller.appspot.com/bug?extid=62ba359e1dfec1473c57
We could either enforce `CONFIG_GENKSYMS=y` and keep things as they used to be or we could add a libdw-dev dependency to the container and be more flexible.
`CONFIG_GENDWARFKSYMS` offers a slight advantage in that it will be better if/when we start fuzzing Rust code in the kernel.
=> tools/docker: add libdw-dev to the syzbot container

pkg/fuzzer/fuzzer_test.go, pkg/fuzzer/queue/queue.go, pkg/rpcserver/local.go, pkg/rpcserver/rpcserver.go, pkg/rpcserver/rpcserver_test.go, pkg/runtest/run_test.go, pkg/vminfo/syscalls.go, pkg/vminfo/vminfo.go, tools/syz-execprog/execprog.go
It should address the current spike in ` SYZFATAL: image testing failed w/o kernel bug`
=> pkg/rpcserver, pkg/vminfo: fix Context cancellation processing bugs

dashboard/app/app.yaml
It is available in preview since Nov. 19 2024.
Tested the AppEngine manually. Looks good.
=> dashboard/app/app.yaml: go122 -> go123

executor/executor.cc, executor/executor_bsd.h, executor/executor_linux.h, executor/executor_test.h
MAP_FIXED_NOREPLACE allows to fail early if we happened to overlap with an existing memory mapping. It should help detects bugs like #5674 at an earlier stage, before it led to memory corruptions.
MAP_FIXED_NOREPLACE is supported from Linux 4.17, which is okay for all syzkaller use cases on syzbot.
There's no such option for some of the supported OSes, so set it depending on the configuration we're building for.
=> executor: favor MAP_FIXED_NOREPLACE over MAP_FIXED

sys/targets/targets.go
The current default value sometimes intersects with the addresses used by malloc, which causes executor memory corruptions.
Closes #5674.
=> sys/targets: change the default DataOffset value

dashboard/app/api.go, dashboard/app/handler.go, dashboard/app/handler_test.go
See #5731 for details.
Closes #5731
=> dashboard/app: always gzip intermediate handler results

dashboard/app/coverage.go, dashboard/app/public_json_api.go, pkg/cover/heatmap.go, pkg/cover/heatmap_test.go, pkg/coveragedb/coveragedb.go, pkg/coveragedb/coveragedb_test.go, pkg/coveragedb/functions.go
Covers min #5591 requirements.
Json size is 66MB. Gzipped version 4,5MB.
AppEngine can stream only the gzipped version because of its response size limitations.
Repo and commit are streamed last because it is a bit easier.
The response time is 10-15s for the `upstream` namespace.
It returns the previous (not current) month coverage.
The data is available at `/upstream/graph/coverage_heatmap?json=1`.
Landing the #5716 we'll be able to serve it from `/coverage?json=1`.
[coverage.json.gz](https://github.com/user-attachments/files/18618386/coverage.json.gz)
=> dashboard/app: export coverage json

tools/docker/env/Dockerfile, tools/docker/old-env/Dockerfile, tools/docker/syzbot/Dockerfile
"go mod go@1.23" updates go.mod to the latest 1.23.*.
Syz-ci containers are auto updating the go version now. It is cheap.
The only concern is the github actions ability to cache the new toolchain. We'll know it tomorrow.
=> tools/docker: golang toolchain is autoupdated since 1.21

sys/targets/targets.go
It turned out that the currently used value hit the high shadow area on arm64 machines.
Closes #5762.
=> sys/targets: increase DataOffset for 64bit builds

.golangci.yml, pkg/corpus/corpus_test.go, pkg/cover/cover.go, pkg/fuzzer/queue/queue.go, pkg/ifuzz/powerpc/powerpc.go, pkg/signal/signal.go, prog/expr.go, prog/prog.go, prog/types.go, tools/syz-testbed/html.go, tools/syz-testbed/stats.go, tools/syz-testbed/targets.go, tools/syz-testbed/testbed.go
The plan was to make a few trivial fixes, but something went wrong...
=> .golangci.yml: enable recvcheck

vm/adb/adb.go, vm/vmimpl/console.go
=> vm: support console_cmd to run cmd to collect console log

executor/executor.cc
Some environments don't define MAP_FIXED_NOREPLACE.
=> executor: fix MAP_FIXED_NOREPLACE dependency

pkg/report/linux.go, pkg/report/testdata/linux/report/736, pkg/report/testdata/linux/report/737
This will untangle the crashes of
https://syzkaller.appspot.com/bug?extid=bf36934adc7979488192
=> pkg/report: ignore some timer-related frames

vm/qemu/qemu.go
The chance of port collision is very low, but still not 0. There's no reason to report an error on the first ocurrence of the problem, let it first retry 100 times.
The PR should prevent syzbot from reporting bugs like this: https://syzkaller.appspot.com/bug?extid=724178e778bd3fd15e91
=> vm/qemu: retry on Address already in use errors

pkg/coveragedb/coveragedb.go
Happy path testing rely on iter.Stop() call to be done before we close errCh.
Closes #5775 .
=> pkg/coveragedb: fix tests flakiness

dashboard/app/config.go, dashboard/app/coverage.go, pkg/covermerger/provider_web.go
Gerrit servers return base64 encoded file content. To get the raw data, &format=TEXT request param is needed.
This PR closes #5592.
=> dashboard/app: support gerrit servers as a webgit source

pkg/vcs/linux_patches.go
The commit should fix the bisections for the period of 2-3 months of 2021.
See e.g. this failed bisection:
https://syzkaller.appspot.com/x/bisect.txt?x=124a9200580000
=> pkg/vcs: add one more Linux backport

pkg/rpcserver/rpcserver.go
Dump the whole flatrpc.ConnectRequest to the logs, so that we can better understand the cause of #5805
=> pkg/rpcserver: improve the mismatching arches error message

syz-cluster/series-tracker/main.go, syz-cluster/series-tracker/main_test.go
Extract Cc addresses for the processed patch series.
=> syz-cluster/series-tracker: collect Cc addresses

executor/executor_runner.h, pkg/flatrpc/conn_test.go, pkg/flatrpc/flatrpc.fbs, pkg/flatrpc/flatrpc.go, pkg/flatrpc/flatrpc.h, pkg/flatrpc/helpers.go, pkg/rpcserver/rpcserver.go, pkg/rpcserver/rpcserver_test.go
As we figured out in #5805, syz-manager treats random incoming RPC connections as trusted, and will crash if a non-executor client sends an invalid packet to it.
To address this issue, we introduce another stage of handshake, which includes a cookie exchange:
- upon connection, the executor sends a ConnectHelloRequest containing its ID assigned to it at startup;
- the manager responds with a ConnectHelloResponse containing a random 64-bit cookie;
- the executor calculates a hash of that cookie and includes it into its ConnectRequest together with the other information;
- before checking the validity of ConnectRequest, the manager ensures client sanity (passed ID didn't change, hashed cookie has the expected value)
We deliberately pick a random cookie instead of a magic number: if the …
=> pkg/rpcserver: pkg/flatrpc: executor: add handshake stage 0

executor/common_bsd.h
The error handling for the setsid() call in sandbox_common() requires it.  Without it, some csource builds fail.
=> executor: pull in errno.h on BSD systems

sys/targets/targets.go
After some time, my FreeBSD fuzzing runs start to hit frequent "coverage filter is full" SYZFAILs, caused by garbage PC values.  Some assertions in kcov convinced me that PC values exported by the kernel are in the expected range, so it appears that the executor is corrupting them somehow.  In particular, we leave the first page of each kcov mapping writeable since the interface to clear the trace buffer involves overwriting the first quadword.
Sanitize kernel PC values so that we don't fill up the coverage filter with bogus values.
=> sys/targets: add a kernel address range for FreeBSD/amd64 kernels

dashboard/app/public_json_api.go, dashboard/app/public_json_api_test.go, pkg/cover/backend/backend.go, pkg/cover/backend/dwarf.go, pkg/cover/backend/gvisor.go, pkg/cover/html.go, pkg/cover/report.go, pkg/cover/report_test.go, pkg/manager/http.go
#5668 for the wider context
**The exported jsonl lines len statistics**
Average: 155514
Max: 1220378
Min: 556
25th percentile: 18392
50th percentile: 58633
75th percentile: 166546
200KB is the average json line.
Every jsonl line has the program and information about all the visited frames.
=> pkg/manager: export programs with coverage

docs/syscall_descriptions_syntax.md
I was reading syscall_descriptions_syntax.md and I found a typo (probably a bug) in the file.
=> Modification of syscall_descriptions_syntax.md file

sys/targets/targets.go
It seems that, on ARM64, in many cases we just can't use many enough bits of the address space. Let's use the old value for now.
It's also problematic (see #5770), but it's lesser of the two evils.
=> sys/targets: use a different DataOffset value for ARM64

syz-cluster/overlays/gke/kustomization.yaml
It's NoSchedule, not NO_SCHEDULE.
=> syz-cluster: fix incorrect Node toleration values

dashboard/app/reporting.go, dashboard/app/reporting_test.go, dashboard/app/templates/mail_bug.txt, dashboard/dashapi/dashapi.go
Context: #5829.
Let's not pretend that the revoked reproducer never existed and still report it. It will avoid unexpected side-effects for the higher-level logic.
There may be better ways to resolve the bug, but let's first just get it fixed to prevent syzbot from spamming the mailing lists.
Add a test to verify the new behavior.
=> dashboard: include revoked reproducers in reports

pkg/cover/html.go, pkg/cover/manager_to_ci.go, syz-ci/manager.go, syz-ci/syz-ci.go
See #5668 for the wider context.
#5798 needs to be landed first
=> syz-ci: upload programs coverage from managers to gcs

pkg/cover/html.go, pkg/cover/report_test.go, pkg/mgrconfig/config.go
Some sub paths may not be covered due to hardware configuration, or lack of interest. This patch allows them to be excluded from the stats. This can be convenient if the excluded paths are deep in the hierarchy:
```
{
"name": "sound",
"path": [
"techpack/audio",
"-techpack/audio/asoc/aaa/bbb"
"-techpack/audio/asoc/aaa/ccc"
]
}
```
=> pkg/cover: allow paths to be excluded from stats

docs/linux/setup.md
Update the go version in docs/linux/setup.md from go1.22.1 to go1.23.6 to ensure consistency with go.mod.
=> docs/linux: update go version

pkg/gcs/gcs.go, syz-ci/manager.go, syz-ci/syz-ci.go
PublishGCS param now controls the CoverProgramsPath targets too.
Previously it controlled only CoverUploadPath and CorpusUploadPath.
Context: gcs://syzkaller bucket doesn't allow to configure permissions per-folder.
The alternatives are - to create one more bucket for all the programs coverage export to change syzkaller code and configure ACL the same was we're doing it for other artefacts.
=> syz-ci/manager.go: make CoverProgramsPath target public

sys/targets/targets.go
Use 0x200000000000 to be within the address range used by Starnix.
Cc https://github.com/google/syzkaller/issues/5770
=> sys/targets: use a smaller default DataOffset

sys/targets/targets.go
It is incorrect to consider VMArch here - if we are running a 32 bit app on a 64 bit kernel, the 64 bit arch is not of interest here.
Also, VMArch is not set for every Target, what led to problems when running arm64 fuzzing on an arm64 host.
=> sys/targets: determine DataOffset by Arch

pkg/gcs/gcs.go, pkg/gcs/mocks/Client.go, syz-ci/manager.go, syz-ci/manager_test.go
Each fuzzing session costs 2G-13G of detailed coverage data now. It looks too much.
The data is highly redundant (jsonl) thus compression should help.
P. S. The better option is to dedup this data in some DB but it will take much more efforts.
Cloud Spanner allows to import gzipped JSONL data just in case we'll decide to use these programs for web UX.
TODO:
=> syz-ci: gzip programs coverage on GCS

executor/common_kvm_amd64.h, executor/common_kvm_arm64.h, executor/kvm.h, executor/kvm_amd64.S
* Fixes a bug when setting up a 64-bit guest by making the bit manipulation macros produce unsigned long long: To create a VCPU that has paging enabled, one needs to set the CR0.PE and CR0.PG bits in CR0. The latter is problematic when setting up a 64-bit guest since if the macro is not using 1ULL, it sign extends the output (in 64-bit mode the control registers are extended to 64-bits with some of the CR0[32:63] bits reserved). This results in either failing the KVM_SET_SREGS ioctl (in newer kernel versions) or just failing the KVM_RUN ioctl with EXIT_REASON_INVALID_STATE.
* Moved some macro definitions to the generic kvm header to consolidate them with the already existing ones. Prefixed them with X86_ to avoid confusion. These will then be used by the x86-64 version of SYZOS. …
=> executor/kvm: bug fix and minor refactor in KVM

.mockery.yaml, Makefile, pkg/coveragedb/coveragedb_mock_test.go, pkg/coveragedb/mocks/ReadOnlyTransaction.go, pkg/coveragedb/mocks/Row.go, pkg/coveragedb/mocks/RowIterator.go, pkg/coveragedb/mocks/SpannerClient.go, pkg/covermerger/mocks/FileVersProvider.go, pkg/covermerger/provider_monorepo.go, pkg/gcs/gcs.go, pkg/gcs/mocks/Client.go, pkg/rpcserver/mocks/Manager.go, pkg/rpcserver/rpcserver.go, tools/mockery.sh, vm/proxyapp/mocks/ProxyAppInterface.go, vm/proxyapp/mocks/subProcessCmd.go, vm/proxyapp/proxyappclient_mocks_test.go
Changes
1. //go:generate is not recommended. Removed.
2. Mockery `packages` is the new default way to configure it. Added config with `packages` (see yaml file).
3. Fixes ~3 warnings.
=> migrate to mockery config

syz-ci/manager.go, syz-ci/manager_test.go
Currently every jsonl file name is unique.
To download data, customer needs the file name and it requires bucket list access rights.
With static file names customers are able to download data using static links.
=> syz-ci/manager: upload programs coverage to the same file

dashboard/app/batch_main.go
Coverage merging often costs more than 1 hour.
=> dashboard/app: use more cores for coverage merging

pkg/covermerger/file_line_merger.go
```
panic: runtime error: index out of range [-1]
goroutine 1952 [running]:
github.com/google/syzkaller/pkg/covermerger.(*LineToLineMatcher).SameLinePos(...)
... 
```
It is a side effect of #5850.
Some records have only information about the function covered.
Let's skip them.
~2% of the records in BigQuery don't have information about line. (checked data for yesterday)
=> pkg/covermerger: skip record without target line

dashboard/app/entities_spanner.go
Some time ago we added the per-manager statistics.
Histogram was broken since that moment.
Closes #5867.
=> dashboard/app: fix histogram numbers

tools/create-openbsd-gce-ci.sh
Tested locally:
```
quirks-7.103 signed on 2025-03-30T21:24:36Z
ldconfig: /var/run/ld.so.hints: No such file or directory
The following new rcscripts were installed: /etc/rc.d/gitdaemon
See rcctl(8) for details.
New and changed readme(s):
/usr/local/share/doc/pkg-readmes/git
/usr/local/share/doc/pkg-readmes/llvm-16
bash-5.2.37         GNU Bourne Again Shell
gcc-8.4.0p26        GNU compiler collection: core C compiler
git-2.49.0          distributed version control system
gmake-4.4.1         GNU make
go-1.24.1           Go programming language
llvm-16.0.6p32      modular, fast C/C++/ObjC compiler, static analyzer and tools
nano-8.3            simple editor, inspired by Pico
wget-1.25.0         retrieve files from the web via HTTP, HTTPS and FTP
pkg_add OK
CONGRATULATIONS! Your OpenBSD …
```
=> tools: use lvvm-16 for OpenBSD bot as 13 is not available in 7.7

dashboard/app/batch_main.go
We changes the machine type to c3-highmem-8 in #5874 .
But forgot to double the CPU resources.
=> dashboard/app: double the requested CPU

syz-cluster/controller/processor.go, syz-cluster/controller/processor_test.go
If the Loop() was restarted in between the moment we marked the session as started in the DB and the moment we actually started the workflow, there was no way back to the normal operation.
That was the reason of the sporadic TestProcessor failures we've seen in the presubmit tests.
Handle this case in the code by just continuing the non-finished calls.
Closes #5776.
=> syz-cluster: better handle SeriesProcessor restarts

pkg/fuzzer/job.go
The Clone() we do at the beginning of the handleCall() function is unnecessary and may even confuse the people wo read and modify the code (see #5878).
For all the jobs we start below, we anyway do another Clone() of the program. The corpus also does not assume that the programs in it will be modified elsewhere.
=> pkg/fuzzer: remove an unnecessary clone

syz-manager/manager.go
When running in debug mode, mgr.vmPool.Count()-mgr.cfg.FuzzingVMs can become negative even for a valid config since we reduce number of VMs to 1.
NewReproLoop panics when VM count argument is negative since it passes it to make chan.
Cap number of repro VMs at 0.
=> syz-manager: fix panic in debug mode

tools/syz-covermerger/syz_covermerger.go
Empty flagToGCS means nil WriteCloser.
=> tools/syz-covermerger: fix nil deref

syz-manager/manager.go
Check coverage early.
Otherwise we do machine check w/o coverage, but then it's enabled by ifaceprobe package for all programs anyway.
=> syz-manager: check that coverage is enabled in ifaceprobe mode

tools/syz-declextract/clangtool/declextract.cpp, tools/syz-declextract/testdata/include/types.h, tools/syz-declextract/testdata/types.c, tools/syz-declextract/testdata/types.c.json, tools/syz-declextract/testdata/types.c.txt
Remove __attribute__ on types.
Some kernels now use it on some syscall args as shown in the test.
The __attribute__ may contain quotes and break json.
=> tools/syz-declextract: support attributes on types

.github/workflows/ci.yml
Every workflow job is executed on the fresh GCE instance.
4 machines are used to check every PR.
Every PR starts its own machines. 5 parallel tests means 20 machines.
The autoscaling was perfect during testing.
We need 1 minute to get the machines and 1 minute to run syz-env docker.
Every job real execution time is what you see on Github + 2 minutes.
=> ci.yml: use self hosted x86 runners

dashboard/app/batch_main.go
Quarter long aggregations are killed.
OpsAgent may help to understand why.
=> dashboard/app: install opsagent to batch processors

sys/linux/dev_nbd.txt, sys/linux/dev_nbd.txt.const, sys/linux/socket_netlink_generic_80211.txt
Definitions for attribute `NBD_ATTR_SOCKETS`, `NL80211_ATTR_BSS_SELECT`, `NL80211_ATTR_PEER_MEASUREMENTS`, and `NL80211_ATTR_SCHED_SCAN_MATCH` have some errors.
For example, the current definition of `NBD_ATTR_SOCKETS` is like
```c
NBD_ATTR_SOCKETS  nlnest[NBD_ATTR_SOCKETS, array[nlattr[NBD_SOCK_FD, sock_nbd_client]]]
```
However, according to the actual parsing code:
```c
nla_for_each_nested(attr, info->attrs[NBD_ATTR_SOCKETS],
rem) {
struct nlattr *socks[NBD_SOCK_MAX+1];
if (nla_type(attr) != NBD_SOCK_ITEM) {
pr_err("socks must be embedded in a SOCK_ITEM attr\n");
ret = -EINVAL;
goto out;
}
ret = nla_parse_nested_deprecated(socks, NBD_SOCK_MAX,
attr,
nbd_sock_policy,
info->extack);
```
The attribute `NBD_ATTR_SOCKETS` actually encloses stream of `NBD_SOCK_ITEM`
attribute first, then to …
=> sys/linux: fix error defined attributes

tools/syz-declextract/clangtool/declextract.cpp
The signature oif `getBitWidthValue` changed in https://github.com/llvm/llvm-project/commit/81fc3add1e627c23b7270fe2739cdacc09063e54
=> tools/syz-declextract/clangtool: fix getBitWidthValue for LLVM>=21

dashboard/app/public_json_api.go, dashboard/app/public_json_api_test.go, pkg/cover/html.go, pkg/cover/report_test.go
- pkg/cover: reorder types for natural reading order
- dashboard/app: export info about uncovered blocks as well
=> dashboard/app: export info about uncovered blocks as well

tools/syz-benchcmp/benchcmp.go
The -out option is used by syz-testbed, which only needs the output.
=> tools/syz-benchcmp: don't start browser if -out is set

dashboard/app/coverage.go
Moves #5661 forward.
It allows to see records older than 12 periods.
And it allows to specify the target for coverage regression analysis.
=> dashboard/app: allow user defined dateto for coverage

pkg/manager/diff.go, pkg/osutil/tar.go, pkg/osutil/tar_test.go, syz-cluster/dashboard/handler.go, syz-cluster/dashboard/templates/series.html, syz-cluster/pkg/api/client.go, syz-cluster/pkg/api/http.go, syz-cluster/pkg/controller/api.go, syz-cluster/pkg/controller/api_test.go, syz-cluster/pkg/db/entities.go, syz-cluster/pkg/db/migrations/1_initialize.up.sql, syz-cluster/pkg/service/sessiontest.go, syz-cluster/workflow/fuzz-step/main.go, tools/syz-diff/diff.go
Compress the diff fuzzing artifacts (crash logs, various reproducers found during the process, etc) that are mentioned in the fuzzer's log and share the archive via the web dashboard. It will help debug the false positives.
=> syz-cluster: share .tar.gz of diff fuzzing artifacts

syz-cluster/dashboard/handler.go, syz-cluster/dashboard/templates/series.html, syz-cluster/pkg/api/api.go, syz-cluster/pkg/db/entities.go, syz-cluster/pkg/db/migrations/1_initialize.up.sql, syz-cluster/pkg/service/session.go, syz-cluster/pkg/triage/commit.go, syz-cluster/pkg/triage/commit_test.go, syz-cluster/pkg/triage/tree.go, syz-cluster/workflow/triage-step/main.go
* Be more explicit about the exact reason for skipping a series.
* Ignore the series that do not modify any `.h` or `.c` files.
=> syz-cluster: improve series triage

syz-manager/manager.go
These are perfectly normal since we are stopping all the functionality.
=> syz-manager: ignore context.Canceled error on shutdown

syz-cluster/controller/processor.go, syz-cluster/controller/processor_test.go, syz-cluster/pkg/db/report_repo_test.go, syz-cluster/pkg/db/session_test_repo.go, syz-cluster/pkg/db/session_test_repo_test.go, syz-cluster/pkg/db/util_test.go, syz-cluster/pkg/service/sessiontest.go
If the workflow step crashed or timed out, we used to have Running
status for such steps even though the session itself may be long
finished.
In order to prevent this inconsistency, on finishing each session go
through all remaining running steps and update their status to Error.
=> syz-cluster: clean up running steps of finished workflows 

pkg/manager/repro.go, pkg/manager/repro_test.go
When the context is cancelled, no one may be polling the pingQueue, yet we write to it synchronously.
Wrap it in a select{} statement and add a test to ensure that the loop reacts properly to the context cancellation.
=> pkg/manager: prevent deadlock on ReproLoop cancellation

pkg/mgrconfig/load.go, tools/syz-testbuild/testbuild.go
1. Properly set up a manager config.
2. Use clang/ld.lld by default.
3. Set the right boot partition for qemu VMs.
=> tools: repair syz-testbuild

pkg/cover/heatmap.go, pkg/cover/templates/heatmap.html
=> pkg/cover: use space for alignment, not underscore

pkg/manager/repro.go, pkg/manager/repro_test.go
As pingQueue holds maximum 1 element, it's not a very good indicator of
whether there are more elements in the reproduction queue. If the first
few crashes happen to be no longer needed (which is quite likely when
reproduction loop is started long after we have begun to collect the
crashes), the loop becomes reactive - new reproductions will be started
only once new bugs are submitted to the queue.
Fix it by polling the queue until it returns nil. Add a test that
exposes the previously existing bug.
=> pkg/manager: better handle the reproduction queue

pkg/manager/diff.go, pkg/repro/repro.go, pkg/repro/strace.go, vm/dispatcher/pool.go, vm/dispatcher/pool_test.go
Make the pool.Run() function take a context.Context to be able to abort the callback passed to it or abort its scheduling if it's not yet running.
Otherwise, if the callback is not yet started and the pool's Loop is aborted, we risk waiting for pool.Run() forever. It prevents the normal shutdown of repro.Run() and, consequently, the DiffFuzzer functionality.
=> vm/dispatcher: make pool.Run cancellable

dashboard/app/access.go, dashboard/app/access_test.go
To make them accessible for non-admins, we need explicit checks in access.go.
Extend TestAccess to cover fsck logs.
Cc @FlorentRevest
=> dashboard: add missing access check for fsck logs

go.mod, go.sum, tools/docker/env/Dockerfile
It requires appengine dependency update to match golang versions.
gcloud-appengine-python patching is needed to fix #4785.
=> tools/docker/env: update gcloud to 519

sys/targets/targets.go
ARM32 suffers from the same problem as ARM64 - the data offset may be beyond the addressable memory range.
Cc #5986.
Cc #5770.
=> sys/targets: use a custom data offset for arm32

pkg/gcs/gcs.go
After https://github.com/googleapis/google-cloud-go/pull/11519, the cloud storage library wraps the errors which we used to check directly. This has led to multiple asset upload errors.
***
We need this PR ASAP to fix asset storage, but then it would be nice to think how we could have caught such an incompatibility.  In `syz-cluster`, I was using https://github.com/fsouza/fake-gcs-server in the dev environment, probably we could add it to our `env` container and write some tests for `pkg/gcs` against the emulated server?
=> pkg/gcs: check errors with errors.Is

dashboard/app/api.go, dashboard/app/coverage.go, dashboard/app/coverage_test.go, dashboard/app/handler.go, dashboard/app/public_json_api.go, dashboard/app/public_json_api_test.go, dashboard/app/reporting_email.go, dashboard/app/reporting_test.go, dashboard/app/util_test.go
getSpannerClient returns prod client as a default.
=> dashboard/app: allow to set spanner context only from tests

vm/qemu/qemu.go
We want to keep on using `vexpress-v2p-ca15-tc1.dtb`, so let's keep on using `-machine vexpress-a15`.
=> Revert "vm/qemu: use -machine virt and -cpu max for arm32"

pkg/vminfo/linux_syscalls.go
"executor/kvm: add x86-64 SYZOS fuzzer" accidentally disabled pseudo-syscalls that manipulate SYZOS VMs, by adding an empty case to a switch statement.
Merge the two cases together to fix the problem.
=> pkg/vminfo: re-enable SYZOS for arm64

docs/bisect.md
It looks like `compiler_type` entry is mandatory to avoid this error:
unsupported bisect compiler:
It can be `gcc` or `clang`.
(Note that I had to install `grub-pc-bin` and apply the following extra patch because apparently, `create-gce-image.sh` is called and `nbd` doesn't seem to work on Ubuntu 25.04, but even after that, `syz-bisect` couldn't reproduce the issue on the current kernel, I need to investigate why)
```diff
diff --git a/pkg/build/linux_generated.go b/pkg/build/linux_generated.go
index a084684d3..c7cb0b87c 100644
--- a/pkg/build/linux_generated.go
+++ b/pkg/build/linux_generated.go
@@ -33,7 +33,7 @@ fi
BLOCK_DEVICE="loop"
if [ "$(uname -a | grep Ubuntu)" != "" ]; then
-       BLOCK_DEVICE="nbd"
+       : # BLOCK_DEVICE="nbd"
fi
sudo umount disk.mnt || true
diff --git …
```
=> doc: bisect: add `compiler_type` entry

docs/translations/zh_CN/db.md
Finish the translation of docs/db.md, which has been proofread by HCTT translation team.
Update to commit 36c961ad9dc0 ("tools/syz-db: add more usage info for syz-db").
=> docs/translations: add the translation of db.md

docs/translations/zh_CN/adding_new_os_support.md
Finish the translation of docs/adding_new_os_support.md, which has been proofread by HCTT translation team.
Update to commit db5852f9fc90 ("docs/adding_new_os_support.md: fix a typo").
=> docs/translations: add the translation of adding_new_os_support.md

pkg/cover/backend/dwarf.go
Rust compilation units are different from C in that a single compilation unit includes multiple source files, but we still need to tell which PC range belong to which source file.
Infer that information from the LineEntry structures.
Cc #6000.
=> pkg/cover/backend: extract PC ranges from Rust DWARF

tools/syz-symbolize/symbolize.go
=> tools/syz-symbolize: use -config to support module symbolize

tools/create-ec2-rootfs.sh
The current EC2/AL2023 root file system only works for systems using the Intel e1000 driver. Extend the configuration to cover all potential network interfaces in order to allow fuzzing with other network interfaces (such as virtio-net).
=> tools: widen network DHCP configuration for EC2 Root FS

pkg/build/netbsd.go, pkg/instance/execprog.go, pkg/manager/diff.go, syz-manager/manager.go, syz-manager/snapshot.go, vm/adb/adb.go, vm/bhyve/bhyve.go, vm/cuttlefish/cuttlefish.go, vm/gce/gce.go, vm/gvisor/gvisor.go, vm/isolated/isolated.go, vm/proxyapp/proxyappclient.go, vm/proxyapp/proxyappclient_test.go, vm/qemu/qemu.go, vm/starnix/starnix.go, vm/vm.go, vm/vm_test.go, vm/vmimpl/vmimpl.go, vm/vmm/vmm.go, vm/vmware/vmware.go
There are a few reasons for these changes:
1. vm.Run behavior is the same for the termination event and timeout event. Implementation duplicates logic.
2. Termination events  sometimes are channels and sometimes are contexts. It requires double conversion.
This change allows to use context as a single termination signal source.
=> vm: func Run accepts context

executor/common_kvm_amd64_syzos.h, sys/linux/dev_kvm_amd64.txt, sys/linux/test/amd64-syz_kvm_setup_syzos_vm-cpuid
This commit adds support for CPUID instructions on AMD64. It also adds a relevant test.
=> executor/kvm: add SYZOS support for CPUID

sys/linux/dev_block.txt, sys/linux/filesystem.txt
/dev/rnullb{} is the Rust implementation of the null block driver.
=> sys/linux: add rnullb descriptions

pkg/subsystem/linux/rules.go, pkg/subsystem/linux/subsystems.go, pkg/subsystem/linux/subsystems_test.go, pkg/subsystem/lists/linux.go
There was a mistake in the Linux subsystem generation rules that led to
the exclusion of exfat-related syz_mount_image calls from the resulting
subsystem descriptions.
Verify the rules before applying them. Fix other problems found by the
check.
=> pkg/subsystem: fix dangling entries in the rules list

prog/hints_test.go
In the test mode that sets debug=true, MutateWithHints is essentially quadratic to the prog(call) size due to numerous validation checks.
Skip calls that are too large in order to prevent test hangs.
Closes #5637.
=> prog: skip large calls in TestHintsRandom

syz-cluster/README.md, syz-cluster/db-mgmt/migrate-job.yaml
Make k8s generate unique names for migrate jobs to facilitate their run by CI/CD pipelines. Also set job expiration time.
=> syz-cluster: use unique names for migrate jobs

syz-cluster/db-mgmt/migrate-job.yaml, syz-cluster/pkg/db/spanner.go
Don't restart the job if it returned a non-zero exit code. Don't treat the ErrNoChange error as a failure.
=> syz-cluster: fix db-mgmt job problems

tools/check_translation_update.py
Check if the translations in `docs/translations/LANG/FILES` are update with `docs/FILES` with detailed outputs.
Translations should be committed with "Update to commit HASH (TITLE)".
=> tools/check_translation_update.py: check if the translations are up to date

syz-ci/jobs.go, syz-ci/manager.go, syz-ci/manager_test.go, syz-ci/syz-ci.go
1. Use context for the goroutines termination.
2. uploadCoverJSONLToGCS reached 8 params, refactor.
=> syz-ci: use context for termination

pkg/report/linux.go, pkg/report/testdata/linux/report/745, pkg/report/testdata/linux/report/746
Even though __alloc_frozen_pages_noprof has the WARN_ON, the actual problem lies in how malloc was called down the stacktrace. This leads to several different bugs being merged into one:
https://syzkaller.appspot.com/bug?extid=03fb58296859d8dbab4d
Ingore the __alloc_frozen_pages_noprof frame when selecting the bug title.
=> pkg/report: ignore the __alloc_frozen_pages_noprof frame

pkg/report/linux.go, pkg/report/report.go, pkg/report/testdata/linux/report/748, pkg/report/testdata/linux/report/749
We need to look for the error type after the "rust_kernel: panicked" line.
Ignore some common irrelevant frames.
=> pkg/report: improve Rust report parsing

syz-cluster/email-reporter/deployment.yaml, syz-cluster/overlays/minikube/service-accounts.yaml
This will allow us to granularly configure its access to GCP's Secret Manager. Also, it doesn't need Spanner access like controller or web-dashboard.
=> syz-cluster: use a separate service account for email reporter

CONTRIBUTORS, pkg/cover/backend/dwarf.go
The `attrName` is often an absolute path for out-of-tree modules. This commit avoids redundant path concatenation when `attrName` is already absolute, enabling developers to view coverage correctly in the web UI.
=> pkg/cover: fix handling of compile unit name

prog/expr.go, prog/expr_test.go, prog/types.go, prog/validation.go
We used to assume that the default value was the last, yet when it was not specified in the serialized program, the first union option whose condition is satisfied was chosen. Let's be consistent and use the last value in both cases.
Also, remember that there's a case when there's no valid default value - this happens when pkg/compiler wraps a conditional field into a union with two conditional fields. Explicitly check for this case and assume that, whatever value is set, is the correct default because in this particular case the conditions of the two union options must be exclusive.
Fixes #6105.
=> prog: use consistent default values for conditional unions

dashboard/app/main.go
GKE streams all stdout as severity=ERROR messages, which makes it too noisy to be useful on the Admin page of syzbot.
=> dashboard: don't display GKE errors on the admin page

pkg/report/crash/types.go, pkg/report/darwin.go, pkg/report/freebsd.go, pkg/report/fuchsia.go, pkg/report/gvisor.go, pkg/report/linux.go, pkg/report/netbsd.go, pkg/report/openbsd.go, pkg/report/report.go, pkg/report/report_test.go, pkg/report/testdata/linux/report/590, pkg/report/testdata/linux/report/591, pkg/report/testdata/linux/report/592, pkg/report/testdata/linux/report/593, pkg/report/testdata/linux/report/594, pkg/report/testdata/linux/report/595, pkg/report/testdata/linux/report/596, pkg/report/testdata/linux/report/597, pkg/report/testdata/linux/report/598, pkg/report/testdata/linux/report/599, pkg/report/title_to_type.go, pkg/report/title_to_type_test.go
Bug title uniquely identifies the bug class.
This refactoring allows to add bug subclasses that may be used by:
1. Manager.
2. Dashboard.
3. Non-Linux OSes.
We're doing it in scope #6072.
=> pkg/report: factor out type definitions

pkg/instance/instance.go
Since #6123, the ability to run syz reproducers with Sandbox="" is also relevant for pkg/repro.
Instead of patching the value at Env.Test(), do it right before the syz-execprog's invocation.
Closes #6137.
=> pkg/instance: patch empty Sandbox for all syz-execprog calls

pkg/manager/diff.go
In syz-manager, we symbolize reports right before saving them. Follow a similar approach for diff fuzzing as well and symbolize only the reports which were confirmed to only affect the patched kernel.
=> pkg/manager: symbolize diff fuzzing reports

tools/check-commits.sh
Some dependencies updates fail because of the len(descr_line)>120.
#6130 is the example
=> tools: allow dependabot to commit long descriptions

sys/linux/test/landlock_fs_ioctl, sys/linux/test/landlock_ptrace
When testing with the test mode (see #6164), I found that some Landlock tests are not correct.
This PR improves them as much as possible and document why it may not be possible.
Filtered output of `syz-manager` with `-mode run-tests --tests landlock_ -debug`:
```
landlock_fs_accesses none             : OK
landlock_fs_accesses none/cover       : OK
landlock_fs_accesses none/cover C     : OK
landlock_fs_accesses none/cover C/repeat C: OK
landlock_fs_accesses none/cover C/repeat C/thr: OK
landlock_fs_accesses none/cover C/repeat C/thr/cover: OK
landlock_fs_accesses none/cover C/repeat C/thr/cover C: OK
landlock_fs_accesses none/cover C/repeat C/thr/cover C/repeat C: OK
landlock_fs_forbidden none            : OK
landlock_fs_forbidden none/cover      : OK
landlock_fs_forbidden none/cover C …
```
=> Fix errno for Landlock

pkg/report/README.md, pkg/report/crash/types.go, pkg/report/impact_score.go, pkg/report/testdata/linux/report/112, pkg/report/testdata/linux/report/174, pkg/report/testdata/linux/report/18, pkg/report/testdata/linux/report/20, pkg/report/testdata/linux/report/21, pkg/report/testdata/linux/report/247, pkg/report/testdata/linux/report/256, pkg/report/testdata/linux/report/371, pkg/report/testdata/linux/report/480, pkg/report/testdata/linux/report/481, pkg/report/testdata/linux/report/567, pkg/report/testdata/linux/report/676, pkg/report/testdata/linux/report/677, pkg/report/testdata/linux/report/693, pkg/report/title_to_type.go
Null ptr derefs deserve lower priority than all other KASAN bugs because of the lower exploitation probability.
Some of the null ptr derefs are detected as a "general protection faults". Let's keep them as is and let them go to DoS category (for now).
=> pkg/report: introduce null ptr crash types

dashboard/app/email_test.go, dashboard/app/reporting_email.go, pkg/email/lore/parse_test.go, pkg/email/parser.go, pkg/email/parser_test.go, syz-cluster/email-reporter/handler.go, syz-cluster/email-reporter/handler_test.go, syz-cluster/email-reporter/stream.go, syz-cluster/email-reporter/stream_test.go
Let's make sure we always recognize our patch fuzzing findings emails as our own to avoid reacting to them. At the same time, we should still react to the emails forwarded by the web dashboard.
=> syz-cluster, dashboard: assorted email sending improvements

syz-cluster/workflow/configs/net/base.cfg
This prevents bind() and connect() from being disabled. See #6171.
=> syz-cluster: add nci syscalls to the net config

executor/common_test.h
It used to fail because we cannot mmap 0 bytes.
Closes #6148.
=> executor: handle zero length in syz_compare_zlib

pkg/report/title_to_type.go
Replace "keep-sorter" with "keep-sorted" to fix the following warning:
2025-07-14T10:01:57Z WRN This instruction doesn't have matching
'keep-sorted end' line. keep-sorted will not attempt to sort anything until this is addressed.
file=./pkg/report/title_to_type.go line=231
=> pkg/report: typo fix

syz-cluster/pkg/emailclient/dashapi_sender.go
When sending via dashapi, we used to only include the raw email address. Include the bot's name there as well.
=> syz-cluster: include bot's name into the sender email

.golangci.yml, Makefile
There are no configuration changes. Only the ordering.
=> golangci.yml: keep linters sorted

syz-cluster/email-reporter/handler.go, syz-cluster/pkg/api/api.go, syz-cluster/pkg/controller/testutil.go, syz-cluster/pkg/report/template.txt, syz-cluster/pkg/report/testdata/1.in.json, syz-cluster/pkg/report/testdata/2.in.json, syz-cluster/pkg/reporter/api_test.go
Currently, the list was both within the Series object and within the SessionReport object that also encloses Series. And, since only was was actually filled, we were unable to actually Cc the people from the series.
Keep only the Cc list in the Series object and adjust the tests.
=> syz-cluster: keep only one Cc list in SessionReport

docs/syscall_descriptions.md
Commit d34313c changed the sourcedir variable in the syz-extract command but did not adjust the text beneath it.
=> Fix sourcedir variable name

pkg/report/linux.go, pkg/report/testdata/linux/guilty/66
If these happen to be in the stack frames, in almost all cases it will be due to a bug in the calling code.
See the discussion in #5784.
=> pkg/report: exclude crc implementations from guilty files

syz-cluster/email-reporter/main.go
Our pkg/vcs logic attempts to first delete a target folder, which is impossible for the mount point of a k8s disk.
Instead of checking out into the mounted disk directly, use a subfolder on it.
=> syz-cluster: checkout the archive into a subfolder

syz-cluster/email-reporter/handler.go, syz-cluster/email-reporter/handler_test.go, syz-cluster/overlays/gke/prod/global-config.yaml, syz-cluster/pkg/app/config.go, syz-cluster/pkg/emailclient/sender.go
Cc syzkaller-bugs@googlegroups.com in all upstreamed syzbot ci findings.
=> syz-cluster: configure a Cc list for reported bugs

syz-cluster/dashboard/templates/series.html, syz-cluster/pkg/api/api.go, syz-cluster/pkg/api/client.go, syz-cluster/pkg/controller/api.go, syz-cluster/pkg/service/session.go, syz-cluster/pkg/triage/tree.go, syz-cluster/pkg/triage/tree_test.go, syz-cluster/pkg/workflow/template.yaml, syz-cluster/workflow/triage-step/main.go
* Always upload and display triage logs.
* Instead of selecting one base tree and sticking to it, generate an ordered list of trees to try out. Then, pick the first one where the patch series can be applied without issues.
=> syz-cluster: minor triage improvements

syz-cluster/workflow/fuzz-step/workflow-template.yaml
The fuzzing step only takes inputs and communicates via API. This will reduce the number of `Error: open /mainctrfs/output/result.json: no such file or directory` errors in our logs.
=> syz-cluster/wokflow/fuzz-step: don't mount /output

pkg/coveragedb/README.md, pkg/coveragedb/bq-schema.json
#6177 is the better way to remove this extra complexity than trying to automate these steps.
=> pkg/coveragedb: document how to create the BQ table and data transfer

pkg/manager/diff.go, pkg/manager/diff_test.go
The rules were too generic - there are plenty of functions that have "stall" as substring, yet they do not relate to rcu stall bugs.
Improve the rules list and add a unit test.
=> pkg/manager: improve patched crash skip rules

syz-cluster/overlays/gke/prod/global-config.yaml, syz-cluster/pkg/api/api.go, syz-cluster/pkg/api/client.go, syz-cluster/pkg/controller/api.go, syz-cluster/pkg/triage/fuzz_config.go, syz-cluster/pkg/triage/fuzz_config_test.go, syz-cluster/pkg/triage/tree.go, syz-cluster/pkg/triage/tree_test.go, syz-cluster/workflow/configs/kvm/base.cfg, syz-cluster/workflow/configs/kvm/patched.cfg, syz-cluster/workflow/triage-step/main.go
Not always are fuzzing targets well represented by their own kernel
trees, so let's select a kernel tree and a fuzzing config separately.
Drop explicit priorities and instead just sort the lists of trees and
configs.
***
Add a config to fuzz kvm patches.
Listen on the kvm mailing list.
=> syz-cluster: refactor triage + add a kvm fuzz config

pkg/gce/gce.go
The old method internals:
```golang
// New creates a new Service. It uses the provided http.Client for requests.
//
// Deprecated: please use NewService instead.
// To provide a custom HTTP client, use option.WithHTTPClient.
// If you are using google.golang.org/api/googleapis/transport.APIKey, use option.WithAPIKey with NewService instead.
func New(client *http.Client) (*Service, error) {
if client == nil {
return nil, errors.New("client is nil")
}
return NewService(context.TODO(), option.WithHTTPClient(client))
}
```
This change should not touch the logic.
=> pkg/gce.go: replace deprecated method

executor/executor.cc, sys/targets/targets.go
Reverts google/syzkaller#6251
***
The change apparently breaks syzkaller's normal operation. We should figure out why it still passed tests, but for now let's just revert.
=> Revert "executor: change input/output area mapping rules"

dashboard/app/api.go, dashboard/app/coverage.go, dashboard/app/cron.yaml, dashboard/app/main.go, pkg/coveragedb/coveragedb.go, pkg/coveragedb/coveragedb_mock_test.go, pkg/covermerger/covermerger_test.go
#6070 explains the problem of data propagation.
1. Add /cron/update_coverdb_subsystems.
2. Stop updating subsystems from coverage receiver API.
Closes #6070
=> pkg/coveragedb: update file to subsystem info periodically

pkg/manager/html/crash.html, pkg/manager/html/main.html, pkg/manager/http.go
On the syz-manager's html dashboard, dispay the number of repro attempts per each bug. It will help distinguish the bugs where reproduction was attempted and failed from those that have never been reproduced yet.
=> pkg/manager: display repro attempts

syz-cluster/pkg/triage/git.go, syz-cluster/workflow/build-step/main.go, syz-cluster/workflow/rebuild-kernels-cron.yaml
The functionality that checks if latest base kernel revisions are not build-broken (we use this information to determine to which base commit to apply a series) has gotten broken itself. This PR includes a number of fixes that bring it back.
=> syz-cluster: assorted fixes for regular kernel rebuilds

pkg/gcpsecret/secret.go, syz-cluster/pkg/emailclient/smtp_sender.go, syz-cluster/tools/send-test-email/Dockerfile
It simplifies the dependency tree and fixes a build error for the send-test-email container.
=> pkg: move gcpsecret to a separate package

syz-cluster/dashboard/templates/series.html
Otherwise we sometimes display broken data.
=> syz-cluster/dashboard: html escape modal content

syz-cluster/dashboard/handler.go, syz-cluster/dashboard/templates/base.html, syz-cluster/dashboard/templates/graphs.html, syz-cluster/pkg/db/stats_repo.go, syz-cluster/pkg/db/stats_repo_test.go
Add a web dashboard page with the main statistics concerning patch series fuzzing.
Improve the navigation bar on top of the page.
=> syz-cluster: display statistics

syz-cluster/overlays/gke/common/kustomization.yaml
Selecting it by a label instead of an exact vm pool name makes it possible to implement a blue/greed node pool update strategy (since pool names would be different in this case).
=> syz-cluster: select nested vm pool by label

syz-cluster/dashboard/templates/graphs.html
They look more natural without it.
=> syz-cluster/dashboard: don't smooth stats graphs

pkg/report/gvisor.go
Following
https://github.com/google/gvisor/commit/b47d21ef21a6f59b8f574eebf83c7936880c1c0d syzkaller should look for this message type.
=> pkg/report: add "BUG on" oops entry for gVisor

pkg/rpcserver/rpcserver.go
To be useful, the stat should have a different name depending on the VM pool name.
=> pkg/rpcserver: add suffix to executor restarts

syz-cluster/dashboard/templates/graphs.html, syz-cluster/pkg/api/api.go, syz-cluster/pkg/db/migrations/5_session_test_skipped.down.sql, syz-cluster/pkg/db/migrations/5_session_test_skipped.up.sql, syz-cluster/pkg/db/stats_repo.go, syz-cluster/workflow/fuzz-step/main.go, syz-cluster/workflow/fuzz-step/main_test.go
If all symbol hashes between the base and the pathed kernel match, there's no reason to spend time fuzzing the series.
Add a 'skipped' status to the enum of possible session test results and set it from the fuzz-step. Display it in the status distribution.
=> syz-cluster: skip fuzzing if binaries are the same

pkg/instance/instance.go, pkg/instance/instance_test.go
We used the wrong name for the optional argument.
=> pkg/instance: fix sandbox_arg passing

syz-cluster/workflow/fuzz-step/main.go, syz-cluster/workflow/fuzz-step/main_test.go
And improve the tests for the method.
=> syz-cluster: fix hash comparison bugs

executor/executor_runner.h
Moved this commit from https://github.com/google/syzkaller/pull/6260 since it's useful by itself.
***
This will reduce code duplication and simplify adding new fields.
=> executor: move proc opts to a separate struct

pkg/fuzzer/queue/queue.go, pkg/fuzzer/queue/queue_test.go
Copy everything that might be important during execution on other kernels/VM pools. Add a test to verify it.
The functionality is actively used to clone requests in the diff fuzzer.
=> pkg/fuzzer/queue: copy more field in Tee

pkg/manager/html/corpus.html, pkg/manager/html/crash.html, pkg/manager/html/fallback_cover.html, pkg/manager/html/job_list.html, pkg/manager/html/main.html, pkg/manager/html/prio.html, pkg/manager/html/raw_cover.html, pkg/manager/html/syscalls.html, pkg/manager/html/vms.html
We need to modify the table so that you can sort it using the values ​​of Report and Repro Attempt Count by creating a separate column for Repro Attempt Count.
Also, the thead and tbody HTML tags are missing throughout the syz-manager HTML, causing a minor issue where the background color of the header section matches the background color of the first line of the body. Therefore, you need to add the missing HTML tags.
=> pkg/manager: add column and missing html tags

syz-cluster/dashboard/templates/graphs.html
Add more detailed graph descriptions.
Move "Click and drag to zoom into a time range" tips below the graphs.
=> syz-cluster: explain graphs on the stats page

pkg/build/build.go, tools/docker/syzbot/Dockerfile
The needed Bazel version to build gVisor got bumped. However, instead of doing the same bump in two places whenever this happens, we can simply use bazelisk in syzkaller to determine which bazel version to use automatically.
=> tools/docker: install bazelisk instead of bazel

syz-cluster/workflow/build-step/main.go
Fix the following error:
```
runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x70 pc=0x16e3c5e]
at main.reportResults ( /syz-cluster/workflow/build-step/main.go:146 )
at main.main ( /syz-cluster/workflow/build-step/main.go:84 )
```
=> syz-cluster: fix a possible nil ptr deref

vm/starnix/starnix.go
Instead of:
ffx --target <target> target get-ssh-address
Use:
ffx --target <target> target list --format addresses
=> vm/starnix: switch to new ffx command for vm ssh address

syz-cluster/pkg/api/api.go
Some series don't apply to torvalds, see e.g.
https://ci.syzbot.org/series/f429573e-7862-4f1e-97dd-3215a235b1d3
=> syz-cluster: add kvm/next tree

pkg/build/linux.go, syz-cluster/workflow/build-step/main.go, syz-cluster/workflow/fuzz-step/main.go, syz-cluster/workflow/fuzz-step/main_test.go
When determining whether a patch series is worth fuzzing, consider not only the hashes of .text symbols, but also the hashes of the global (static and non-static) variables.
As before, calculate the hashes during build and process them at the beginning of the fuzz step.
=> syz-cluster: consider global/static variable values

syz-cluster/pkg/api/api.go
There are a number of patch series that don't apply to torvalds, but do apply to linux-next.
Since we don't fetch all maintainer trees, use linux-next as the last resort.
=> syz-cluster: fetch linux-next

syz-cluster/workflow/fuzz-step/main.go
If the archive turned out to be too large, just print an error message and don't return an error from the status update function.
=> syz-cluster/workflow/fuzz-step: nuance archive upload errors

docs/kfuzztest.md
```
Update kfuzztest.md to reflect some recent changes. In particular:
- Point to the newest kernel pull request (PR v2) instead of the outdated RFC v1 patch series.
- Change example description, as commit 0ac7291ca introduced a new input parameter for syz_kfuzztest_run.
```
I just linked this doc in a [patch series comment](https://lore.kernel.org/all/CANgxf6xOJgP6254S8EgSdiivrfE-aJDEQbDdXzWi7K4BCTdrXg@mail.gmail.com/) but then realized that it was slightly outdated.
=> docs: update kfuzztest.md

pkg/bisect/bisect.go, pkg/build/freebsd.go, pkg/build/netbsd.go, pkg/cover/report_test.go, pkg/instance/execprog.go, pkg/instance/instance.go, pkg/osutil/osutil.go, syz-ci/manager.go, syz-ci/updater.go, syz-cluster/workflow/build-step/main.go, tools/syz-testbuild/testbuild.go, vm/adb/adb.go, vm/bhyve/bhyve.go, vm/cuttlefish/cuttlefish.go, vm/dispatcher/pool.go, vm/dispatcher/pool_test.go, vm/gce/gce.go, vm/gvisor/gvisor.go, vm/isolated/isolated.go, vm/proxyapp/proxyappclient.go, vm/proxyapp/proxyappclient_test.go, vm/qemu/qemu.go, vm/starnix/starnix.go, vm/vm.go, vm/vm_test.go, vm/vmimpl/util.go, vm/vmimpl/vmimpl.go, vm/vmm/vmm.go, vm/vmware/vmware.go
Enable external abortion of the instance creation process. This is
especially useful for the qemu case where we retry the creation/boot up
to 1000 times, which can take significant time (e.g. it timeouts
syz-cluster pods on unstable kernels).
The context can be further propagated to WaitForSSH, but that requires
another quite significant vm/ refactoring.
***
In almost all cases these mean some boot time crash.
It also doesn't make much sense to continue string matching since the
boot output may contain the matched strings in benign contexts.
***
This sequence also asks for another change - we abuse `osutil.VerboseError` in too many different contexts and in a way that contradicts current Go error wrapping APIs. In this particular case it prevents an adequate ssh timeout error detection …
=> vm: react to context cancellation and better handle errors in VM creation

Makefile, pkg/kfuzztest-manager/manager.go, pkg/kfuzztest/description_generation_test.go, syz-kfuzztest/main.go
Address kFuzzTest errors that appear on e.g. OpenBSD: https://syzkaller.appspot.com/text?tag=CrashLog&x=109bd534580000
=> kfuzztest: various build/test fixes
